### ISSUE TITLE
Add Configured mode for AutoFakeItEasy

### ISSUE THREAD

**Issue by blairconrad** [AutoFixture/AutoFixture#1000]
In https://github.com/AutoFixture/AutoFixture/pull/998#issuecomment-373170972, @zvirja suggests

> Given that we already merged the other approach, there is a gap - faked delegates do not return auto-values. If you wish, I'd like to ask you to implement the Configured mode for the FakeItEasy integration - it would be really awesome to have it. I love how it's done in the NSubstitute and would recommend that as a sample:
> 
> * automatically generate value as a method result/properties/fields. Return the same result for the same args;
> * auto generate the ref and out parameters;
> * the same for delegates;
> * fully support the open generic methods;

**Comment by blairconrad** [comment]
I'm happy to work on this.

**Comment by zvirja** [comment]
Would be awesome!

**Comment by blairconrad** [comment]
@zvirja, sorry for radio silence. I was off on vacation, then catching up after vacation and whatnot. I've started work on this.

**Comment by zvirja** [comment]
@blairconrad No worries at all :blush:
