### ISSUE TITLE
null guard issue?

### ISSUE THREAD

**Issue by cocogorilla** [AutoFixture/AutoFixture#1008]
I have a test in one of my suites... its an ice breaker that just verifies autofixture components downloaded and interacting with my dev studio correctly.  Interestingly, it started failing with my last autofixture update.  I'll put the test below and report the error I'm seeing... it has always passed previously to my knowledge.

Should I just remove the test, point it to some other type or possibly this is unintended behavior that should be fixed?  Thanks!

`        [Theory, Gen]`
`        public void IdiomaticFixturesAreFunctional([Frozen] IFixture fixture, GuardClauseAssertion assertion)`
`        {`
`            var tocheck = typeof(Fixture);`
`            assertion.Verify(tocheck.GetConstructors());`
`        }`

AutoFixture.Idioms.GuardClauseException: An attempt was made to assign the value null to the parameter "engineParts" of the method ".ctor", and no Guard Clause prevented this. Are you missing a Guard Clause? 
Method Signature: Void .ctor(AutoFixture.DefaultRelays)
Parameter Type: AutoFixture.DefaultRelays, AutoFixture, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b24654c590009d4f

etc...

**Comment by zvirja** [comment]
Good catch :smiley: Indeed, the guard clause is missing and therefore the assertion fails. Looks expected. If you wish, you could fire a PR and improve that.

Let me know if I misunderstood the question :wink:
