### ISSUE TITLE
Access to fixture created by AutoData attribute.

### ISSUE THREAD

**Issue by malylemire1** [AutoFixture/AutoFixture#1026]
Hi, 
For now i only can access the fixture like this.
```
[Theory, AutoData]
public void Dummy(string dummy)
{
    MethodBase method = MethodBase.GetCurrentMethod();
    IFixture fixture = method.GetCustomAttribute<AutoDataAttribute>().Fixture;


    Assert.Equal(dummy, dummy);
}
```
And I get the 'AutoDataAttribute.Fixture' is obsolete warning.

Is there a better way to access the fixture created in the AutoData attribute. I would like to mix parameter and manual creation and injection. 
Thanks

**Comment by malylemire1** [comment]
Yes, it's really a better way.

Can you put this in the AutoData wiki?
I have search everywhere to find how to do this.
Did not think the IOC got the IFixture registered.

Thanks a lot!

**Comment by Kralizek** [comment]
Why are you trying to register for the fixture with the IoC? In my experience it is never needed

**Comment by malylemire1** [comment]
Mostly to minimize test method parameters for complex recurring interfaces setup.

```
[Theory, AutoMoqData]
public void Dummy(IFixture fixture, ComplexClassWith30Interfaces needed, TestClass sut)
{
    //This will add interfaces setupsfor needed.
    SetupInterfaces(fixture, needed);
   //We can now use needed injected in sut.
}
```

**Comment by zvirja** [comment]
> Mostly to minimize test method parameters for complex recurring interfaces setup.

Agree, I have the similar usage in tests. The only difference is that I prefer to prefix those auxiliary repeating methods with `When()`, so test looks like following:

```c#
public void Test([Frozen] IProvider provider, ISut sut, IFixture fixture)
{
    // arrange
    WhenProviderReturnsOnlyInitializedEntities(provider, fixture);
    .....
}
```

But basically idea is still the same 😉

**Comment by zvirja** [comment]
Closing this one as no more actions are required.

> Can you put this in the AutoData wiki?

@malylemire1 I'm going to create a doc site somewhere in future. However, feel free to add this sample to [our wiki](https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet) 😅
