### ISSUE TITLE
Treat delegates as substitutes with NSubstitute

### ISSUE THREAD

**Issue by gtbuchanan** [AutoFixture/AutoFixture#1027]
NSubstitute supports [substituting delegates](http://nsubstitute.github.io/help/creating-a-substitute/#substituting_for_delegates). However, delegates are not resolved as substitutes when using a fixture with the NSubstitute customization. Therefore, I can't run any NSubstitute assertions on them.

```
[Test]
public void ActionIsSubstitute()
{
    var fixture = new Fixture().Customize(new AutoNSubstituteCustomization());

    var action = fixture.Create<Action>();

    Assert.That(action.DidNotReceive, Throws.Nothing);
}
```

Fails with:

> Expected: No Exception to be thrown
> But was:  <NSubstitute.Exceptions.NotASubstituteException: NSubstitute extension methods like .Received() can only be called on objects created using Substitute.For<T>() and related methods.

Similar to #984.

**Comment by gtbuchanan** [comment]
I just realized the property `GenerateDelegates` already exists on `AutoNSubstituteCustomization`. Setting that to `true` resolved my issue. My apologies. I'm new to AutoFixture and couldn't find any documentation on this. Should have checked after I saw how it was resolved for the other issue.

**Comment by zvirja** [comment]
Yep, you're completely right in your finding :blush:

One day we'll create a nice doc site and you'll be able to find this information there :sweat_smile:

**Comment by Kralizek** [comment]
| One day we'll create a nice doc site and you'll be able to find this information there 😅

Me at the standup meeting at work!
