### ISSUE TITLE
Generating System.Uris with a configurable number of path segments

### ISSUE THREAD

**Issue by andersborum** [AutoFixture/AutoFixture#1036]
I need the option of generating System.Uris with a configurable number of path segments. As far as I'm informed, the UriGenerator currently only generates Uris in the form of protocol://host (and I'm after protocol://host/segment where number of segments = n).

Unless I missed something, it's not currently supported and I would like to contribute the feature a pull request.

[Referring to UriGenerator](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/UriGenerator.cs)

**Comment by zvirja** [comment]
Thanks for registering the issue 👍 

Honestly, I'm a bit in doubt whether we should change the default behavior of the core. The default set of builders is not supposed to cover all the needs and is suitable for the _common_ cases only. When the default behavior is not suitable for clients, they are expected to customize the fixture. In your case, you can create the customized version (e.g. `CustomUriGenerator`) and inject it to the fixture:
```c#
fixture.Customizations.Add(new CustomUriGenerator());
```

In any case, let's clarify your particular needs before making the final decision. Do you need to change the default number of segments globally, or it's somehow local (e.g. you need `Uri`s with variable number of segments in the same test)? Why the default Uri format doesn't work for you?

Thanks.

**Comment by andersborum** [comment]
Thanks for the feedback. I guess the best approach is to keep the library as common as possible and then customize as suggested; however, what actually is considered common varies greatly. I guess the System.Uri type is sufficiently complex such that the scale tips in favor of customization.

Should be fairly easy to write a generator that uses CreateMany<T> to create path segments.

**Comment by zvirja** [comment]
> I guess the best approach is to keep the library as common as possible and then customize as suggested; however, what actually is considered common varies greatly.

Well, the current strategy is to create values than pass most obvious expectations, so code which doesn't cares about the values "scrupulously" will not complain. OTOH if some code has more advanced expectations, we are fine to not satisfy them - it's exactly what customization API is designed for 😉

>  guess the System.Uri type is sufficiently complex

Exactly. And the variety of the possible forms is too large to predict all the possible expectations. That's why my vote is to keep the codebase as is in a favor of ad-hoc adjustments in clients' projects.

@moodmosaic Could you please also share your opinion as well?

**Comment by moodmosaic** [comment]
Perhaps, you can do what you describe by [supplying a custom scheme name](http://blog.nikosbaxevanis.com/2012/04/19/uri-support-in-autofixture/)? If not, could you provide some sample/pseudo code before putting effort on a proper pull request?

**Comment by zvirja** [comment]
Closing this one due to inactivity. Please re-open if further assistance is required.

**Comment by andersborum** [comment]
Got derailed .. and managed to return to the thread as I'm facing a similar requirement in another project. As previously suggested, I've implemented a specimen builder that generates a Uri with a configurable number of path segments.

It was debated if the stock `UriGenerator` could be refactored to cater for a wider set of use cases, and while it's a possible route, I'd personally argue that it's better to leave the default generators as simple as possible and costumize on a per project basis (the `Uri` class for instance has many aspects).

Considerations as follows:

- Resolve the `segments` argument using the internal specimen builder
- Expose the internal specimen builder as a constructor argument

Here's the source code:

```
/// <summary>
/// Creates new <see cref="Uri"/> instances.
/// </summary>
public class CompositeUriGenerator : ISpecimenBuilder
{
    private readonly ISpecimenBuilder builder = new UriGenerator();
    private readonly int segments;

    /// <summary>
    /// </summary>
    /// <param name="segments">Requested number of <see cref="Uri"/> segments.</param>
    public CompositeUriGenerator(int segments = 3)
    {
        if (segments <= 0) { throw new ArgumentOutOfRangeException(nameof(segments)); }

        this.segments = segments;
    }

    /// <summary>
    /// Creates a new specimen based on a request.
    /// </summary>
    /// <param name="request">The request that describes what to create.</param>
    /// <param name="context">A context that can be used to create other specimens.</param>
    /// <returns>
    /// The requested specimen if possible; otherwise a <see cref="NoSpecimen"/> instance.
    /// </returns>
    public object Create(object request, ISpecimenContext context)
    {
        if (context == null) throw new ArgumentNullException(nameof(context));

        if (typeof(Uri).Equals(request) == false) { return new NoSpecimen(); }

        var baseUri = this.builder.Create(request, context) as Uri;

        if (baseUri == null) { return new NoSpecimen(); }

        var path = string.Join("/",
            Enumerable
                .Range(0, this.segments)
                .Select(p => context.Resolve(typeof(string)) as string));

        return new UriBuilder(baseUri) { Path = path }.Uri;
    }
}
```
