### ISSUE TITLE
GuardClauseAssertion incorrectly warns about deferred execution when return type is string

### ISSUE THREAD

**Issue by snerks** [AutoFixture/AutoFixture#1042]
See also: #277 

# Steps to reproduce #
Assume this SUT:

```cs
public class MyClass
{
    public string GetString(string input)
    {
        return "Test";
    }
}
```
Write this test:
```cs
[Fact]
public void Demo()
{
    new GuardClauseAssertion(new Fixture()).Verify(typeof(MyClass));
}
```

# Expected result #
The test should fail, with the following warning:

`An attempt was made to assign the value null to the parameter "input" of the method "GetString", and no Guard Clause prevented this. Are you missing a Guard Clause?`

# Actual result #
The test fails with this warning:

`An exception of type 'AutoFixture.Idioms.GuardClauseException' occurred in AutoFixture.Idioms.dll but was not handled in user code: 'A Guard Clause test was performed on a method that may contain a deferred iterator block, but the test failed. See the inner exception for more details. However, because of the deferred nature of the iterator block, this test failure may look like a false positive. Perhaps you already have a Guard Clause in place, but in conjunction with the 'yield' keyword (if you're using C#); if this is the case, the Guard Clause is dormant, and will first be triggered when a client starts looping over the iterator. This doesn't adhere to the Fail Fast principle, so should be addressed.
See e.g. http://codeblog.jonskeet.uk/2008/03/02/c-4-idea-iterator-blocks-and-parameter-checking/ for more details.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 AutoFixture.Idioms.GuardClauseException : An attempt was made to assign the value null to the parameter "input" of the method "GetString", and no Guard Clause prevented this. Are you missing a Guard Clause?
Method Signature: System.String GetString(System.String)
Parameter Type: System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
Declaring Type: xunitaf01.UnitTest.MyClass, xunitaf01.UnitTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Reflected Type: xunitaf01.UnitTest.MyClass, xunitaf01.UnitTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

**Comment by zvirja** [comment]
@snerks Thanks for the repro! I've tried to fix the issue via PR, so stay tuned 😉
