### ISSUE TITLE
Nunit3 VS Adapter won't run AutoFixture AutoMoqDataAttribute

### ISSUE THREAD

**Issue by xlecoustillier** [AutoFixture/AutoFixture#1046]
I created an [issue](https://github.com/nunit/nunit3-vs-adapter/issues/342) on [nunit3-vs-adapter](https://github.com/nunit/nunit3-vs-adapter) almost one year ago (sorry for letting this idle for so long).

It seems that NUnit VS Adapter won't run tests marked with AutoMoqDataAttribute seemingly because of the random data being injected in the parameters messing up with the test discovery.

Do you think that something can be done regarding this problem ?

I can dupicate the orginal question content here if needed.

Thanks :)

**Comment by zvirja** [comment]
Have you tested that with the latest version of AutoFixture? We have applied [a tweak](https://github.com/AutoFixture/AutoFixture/issues/862) in v4 to make it work fine. The idea is that now test name is stable as we replace dynamic parts with placeholders.

If it still doesn't work, please attach a test project and a full scenario, so we can investigate that further.

Thanks.

**Comment by xlecoustillier** [comment]
You're right, it works with the latest version.
I didn't test it in the latest version before because we are stuck on the v3.X (it's our fault, we unitentionnally use the bug fixed by the #781 ). I guess we'll have to handle this eventually.
Thanks for the quick reply :)

**Comment by zvirja** [comment]
If you use one of the latest v3, you can still enable the fix. See more detail [here](https://github.com/AutoFixture/AutoFixture/wiki/Known-Issues#test-name-strategies-for-nunit3).

As for the update blocker, as far as I remember  we agreed on the solution in #966, aren't you fine with that approach? It's a pity to hear that you cannot now update due to the improvement we did :(

**Comment by xlecoustillier** [comment]
Thanks, I'll take a look.
About the update blocker, I'm totally fine with the approach, we just didn't manage to make the changes yet (business priorities and stuff :( ).

BTW, thanks for all the work in this really nice tool framework! 🎉

**Comment by xlecoustillier** [comment]
I tested the [tweak](https://github.com/AutoFixture/AutoFixture/wiki/Known-Issues#test-name-strategies-for-nunit3) you mentioned, it works great 👍 
I can also close the [NUnit issue](https://github.com/nunit/nunit3-vs-adapter/issues/342) as well then.

Thanks again.

**Comment by zvirja** [comment]
Great to hear the fix works! :relaxed:

You're welcome, thanks for the warm words :wink:
