### ISSUE TITLE
LambdaExpressionGenerator does not fulfill requests for LambdaExpression

### ISSUE THREAD

**Issue by bordecal** [AutoFixture/AutoFixture#1049]
As currently implemented, `LambdaExpressionGenerator` only fulfills requests for subclasses of `LambdaExpression`, but not for `LambdaExpression` itself.  This leads to an object creation failure when attempting to use AutoFixture to create a `LambdaExpression` (or an instance of a class that takes a `LambdaExpression` as a constructor parameter).

In the absence of any specific typing information for the expression, it does not seem unreasonable to assume that the specific type does not matter.  In such a case, returning the simplest possible expression (i.e.: the one that is currently returned for `Expression<Action>`) would seem like an acceptable default when fulfilling a request for a `LambdaExpression` (as opposed to one of its subclasses).

**Comment by zvirja** [comment]
Hi @bordecal,

Thanks for raising the issue. Could please provide a real-world scenario when you want to take a non-typed expression as a parameter? What is the motivation behind that?

Just want to better understand why it might be needed.

Thanks.

**Comment by bordecal** [comment]
Normally, it shouldn't be necessary, but recent changes to the  `Expression<>` implementation classes in .NET Core are constraining me to take this approach.  The core scenario in my case involves a non-trivial implementation of sorting behaviour in a RESTful API (_i.e._: allowing callers to specify returned list sorting via a query string like `?sort=lastName,firstName,-dateOfBirth`.

Down at the "core" of this implementation, I need to invoke the `Queryable.OrderBy(...)` and `Queryable.OrderByDescending(...)` methods to cause the desired sorting be applied in the system database (via an ORM).  These methods take `Expression<Func<TSource,TKey>` parameters to specify the sorting keys. (BTW, I am aware that dynamic LINQ would be a candidate approach for this, but that option has already been rejected for reasons that aren't really relevant here.)

Since the target property types are not known at design time, `Expression<TSource, object>` would be the obvious choice for passing around the sorting specifications.  However, this would require that actual expressions resolved at runtime be castable to this type, and those runtime expressions are actually specific with respect to the function return type (_e.g._: the "lastName" sort would get mapped to an expression of type `Expression<Func<Person, string>>` that refers to `Person.LastName`).

Under expected framework behaviour, this still wouldn't cause a problem since `Expression<Func<Person, string>>` is castable to `Expression<Func<Person, object>>`.  However, .NET Core has started implementing `Expression<>` via a set of internal classes that reflect the number of parameters on the wrapped function.  For example, when one creates an lambda expression for a `Func<,>`, this will be implemented by `Expression1<TDelegate>`, which is a subclass of `Expression<TDelegate>`.  This creates a rather nasty little problem around choosing a type for carrying the sorting specification since:

- `Expression1<Func<TSource, string>>` cannot be cast to `Expression<Func<TSource, object>>` at runtime, which means that the latter cannot be used for the sorting specification type, and
- `Expression1<TDelegate>` has internal visibility in the `System.Linq.Expressions` assembly, which means that `Expression1<Func<TSource, object>>` can't be used either.

This framework change has pretty much backed me into a corner where the base `LambdaExpression` is the only type that I can use for exposing the sorting key in property and method parameter types.

FWIW, I'm already using a fixture customization that supplies the empty action for `LambaExpression` requests, so I'm not dependent on the requested change being implemented.  However, I'm guessing that the new .NET Core behaviour will likely cause similar problems for others, and use of the base `LambaExpression` might start to increase in frequency... :(

**Comment by zvirja** [comment]
@bordecal Thanks for the great and detailed explanation! Marking this as a potential feature then. Feel free to create a PR if you have free time and would like to contribute 😉 

P.S. Sorry for the belated reply 😖

**Comment by bordecal** [comment]
Done (and much less painful than dealing with `Expression1<>` 😉)

**Comment by zvirja** [comment]
Implemented via #1053
