### ISSUE TITLE
JSchema - generate stub object

### ISSUE THREAD

**Issue by bobbyangers** [AutoFixture/AutoFixture#1065]
Hi,

I have a JSchema that describe the expected structure for a Json object.

Is there a way, from that JSchema to generate a JObject that would implement the schema and the properties be seeded with specimen from AutoFixture, then be serialized and use as input data ?

**Comment by zvirja** [comment]
Hello,

Unfortunately, we don't have a built-in tool for that. You can write a customization for the fixture, however to suggest you a direction I should better understand your needs. Could you please describe the feature in more detail? Provide e.g. a sample of code and how you would like it to behave. The better you describe the goal, the precisely I could advice you a way 😊 

Thanks!

**Comment by zvirja** [comment]
The issue seemed to stalled. Closing it due to inactivity. Please re-open if further assistance needed.
