### ISSUE TITLE
XUnit - Moq - Auto-initialize service under test

### ISSUE THREAD

**Issue by Katya-g** [AutoFixture/AutoFixture#1066]
I created an attribute InlineAutoSUT to auto generate service under test and instantiate each service that it is using. It allows creating tests like this:
```c#
[Theory, InlineAutoSUT]
public void Test([CP] Mock<ISubService1> subServiceMock1, 
                [CP] string string1, 
                [CP] Mock<ISubService2> subServiceMock2,
                [SUT] Service service)
{
      subServiceMock1.Setup(_ => _.GetInteger()).Returns(13);
      subServiceMock2.Setup(_ => _.GetDouble()).Returns(66.99);

      var actualInteger = service.GetIntegerFromSubService1();
      var actualDouble = service.GetDoubleFromSubService2();

      actualInteger.Should().Be(13);
      actualDouble.Should().Be(66.99);
      service.GetString().Should().Be(string1);
}
```

where the service under test looks like this:
```c#
public class Service 
{
    private ISubService1 _subService1;
    private ISubService2 _subService2;
    private string _test;

    public Service(ISubService1 subService1, string test, ISubService2 subService2)
    {
        _subService1 = subService1;
        _subService2 = subService2;
        _test = test;
    }

    public int GetIntegerFromSubService1()
    {
        return _subService1.GetInteger();
    }

    public double GetDoubleFromSubService2()
    {
         return _subService2.GetDouble();
    }

    public string GetString()
    {
        return _test;
    }
}

public interface ISubService1
{
    int GetInteger();
}

public interface ISubService2
{
    double GetDouble();
}
```

There is a limitation. All constructor parameters of the SUT must be provided as parameters to the unit test in the order they appear in the constructor itself.

Is it worth creating a PR for this? If so, what additional changes would you recommend?

**Comment by Katya-g** [comment]
InlineAutoSUT is very similar to InlineAuto attribute. I've made changes to GetData method. When creating specimen, if it a parameter with SUT attribute, it institutes it with the parameters (that have CP attribute) form unit tests. Here is the code for InlineAutoSUT:
`public class InlineAutoSUT : DataAttribute
{
    private readonly Fixture _fixture;

    public InlineAutoSUT()
    {
        _fixture = new Fixture();
    }

    public override IEnumerable<object[]> GetData(MethodInfo methodUnderTest)
    {
        if (methodUnderTest == null)
        {
            throw new ArgumentNullException(nameof(methodUnderTest));
        }

        var specimens = new List<object>();
        var constructorParameterSpecimen = new List<object>();
        foreach (var parameterInfo in methodUnderTest.GetParameters())
        {
            CustomizeFixture(parameterInfo);
            if (IsServiceUnderTest(parameterInfo))
            {
                var serviceUnderTest = CreateServiceUnderTest(constructorParameterSpecimen, parameterInfo);
                specimens.Add(serviceUnderTest);
                continue;
            }

            var specimen = Resolve(parameterInfo);
            if (IsConstructorParameter(parameterInfo))
            {
                constructorParameters.Add(specimen);
            }

            specimens.Add(specimen);
        }

        return new[] { specimens.ToArray() };
    }

    private static object CreateServiceUnderTest(IEnumerable<object> constructorParameterSpecimen,
                                                 ParameterInfo parameterInfo)
    {
        var parameters = GetConstructorParameters(constructorParameterSpecimen);
        var constructors = parameterInfo.ParameterType.GetConstructors();
        if (!constructors.Any())
        {
            throw new ValidationException("Service under test does not have constructor with parameters. You can remove [SUT] from that parameter.");
        }

        foreach (var constructorInfo in constructors)
        {
            if (constructorInfo.GetParameters().Length != parameters.Count)
            {
                continue;
            }

            return constructorInfo.Invoke(parameters.ToArray());
        }

        throw new ValidationException("Number of parameters in the constructor does not match the number of provided parameters. Make sure that only constructor parameters have [CP] attribute.");
    }

    private static List<object> GetConstructorParameters(IEnumerable<object> constructorParameterSpecimen)
    {
        var parameters = new List<object>();
        foreach (var specimen in constructorParameterSpecimen)
        {
            if (specimen is Mock mock)
            {
                parameters.Add(mock.Object);
                continue;
            }

            parameters.Add(specimen);
        }

        return parameters;
    }

    private static bool IsServiceUnderTest(ParameterInfo parameterInfo)
    {
        return parameterInfo.GetCustomAttribute(typeof(SUTAttribute)) != null;
    }

    private static bool IsConstructorParameter(ParameterInfo parameterInfo)
    {
        return parameterInfo.GetCustomAttribute(typeof(CPAttribute)) != null;
    }

    private void CustomizeFixture(ParameterInfo p)
    {
        var customizeAttributes = p.GetCustomAttributes()
            .OfType<IParameterCustomizationSource>()
            .OrderBy(x => x, new CustomizeAttributeComparer());

        foreach (var ca in customizeAttributes)
        {
            var c = ca.GetCustomization(p);
#pragma warning disable 618
            _fixture.Customize(c);
#pragma warning restore 618
        }
    }

    private object Resolve(ParameterInfo p)
    {
#pragma warning disable 618
        var context = new SpecimenContext(_fixture);
#pragma warning restore 618
        return context.Resolve(p);
    }
}`

As for CP and SUT attributes, they are just a way to tag a parameter:
`[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = true)]
public class CPAttribute : Attribute
{
}

[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
public class SUTAttribute : Attribute
{
}`

**Comment by zvirja** [comment]
@Katya-g Sorry for the belated reply - was seriously busy with my primary job 😖 

As far as I got, you need the `Frozen` attribute. Its main purpose is to resolve and freeze the value, so you can work with value in the test scope and also the same value is passed to the constructor. The argument order does matter and you need to resolve the dependency first.

Here is the sample:

```c#
public interface ISubService1
{
    int GetValue();
}

public interface ISubService2
{
    int GetValue();
}

public class Service
{
    private ISubService1 Sub1 { get; }
    private ISubService2 Sub2 { get; }

    public Service(ISubService1 sub1, ISubService2 sub2)
    {
        Sub1 = sub1;
        Sub2 = sub2;
    }

    public int GetSourceValue() => Sub1.GetValue();
}

[Theory, AutoMoqDataAttribute]
public void ShouldReturnCorrectValue([Frozen] Mock<ISubService1> subService1, Service sut)
{
    subService1.Setup(x => x.GetValue()).Returns(42);

    var result = sut.GetSourceValue();
    
    Assert.Equal(42, result);
}

public class AutoMoqDataAttribute: AutoDataAttribute
{
    public AutoMoqDataAttribute(): base(() => new Fixture().Customize(new AutoMoqCustomization()))
    {
    }
}
```

With this approach you need to specify only the values you really need to access in the test. All the other members might be omitted. Also the order doesn't matter. It's a common pattern in the tests, as it's very resistant to any refactorings you make in the code (e.g. add extra constructor parameter).

Also notice, that there is an alternative design approach. Mark Seemann usually says, that [it's completely fine to expose what you compose](http://blog.ploeh.dk/2013/04/04/structural-inspection/) and it doesn't break the encapsulation. This way the `Service` dependencies should be stored in public read-only properties, so you can access the dependencies like `service.Sub1`.

Let me know whether it answered your question! Thanks.

**Comment by Katya-g** [comment]
oh that's exactly what I was looking for. thank you
