### ISSUE TITLE
TemplateMethodQuery usage

### ISSUE THREAD

**Issue by xlecoustillier** [AutoFixture/AutoFixture#1068]
Hi,

Reading the documentation regarding the TemplateMethodQuery, I read this:

> Selects public static methods that has the same parameters of another method, ignoring optional parameters and return type

But let's say I have something like this:

```c#
public class Test
{
    public class Wrapper<T>
    {
        public T X { get; }

        public Wrapper(T x) { X = x; }
    }
    public class Dummy
    {
        private Dummy(int i) { }

        public static Wrapper<Dummy> Create(int i) => new Wrapper<Dummy>(new Dummy(i));
    }

    public class WrapperFactoryMethodQuery : IMethodQuery
    {
        public IEnumerable<IMethod> SelectMethods(Type type)
        {
            if (type == null) throw new ArgumentNullException(nameof(type));

            return from mi in type.GetTypeInfo().GetMethods(BindingFlags.Static | BindingFlags.Public)
                    let methodType = mi.ReturnType
                    where !string.Equals(mi.Name, "op_Implicit", StringComparison.Ordinal) &&
                            !string.Equals(mi.Name, "op_Explicit", StringComparison.Ordinal)
                    where methodType.IsGenericType &&
                            methodType.GetGenericTypeDefinition() == typeof(Wrapper<>).GetGenericTypeDefinition() &&
                            methodType.GetGenericArguments()[0] == type
                    let parameters = mi.GetParameters()
                    where mi.GetParameters().All(p => p.ParameterType != type)
                    orderby parameters.Length descending
                    select new StaticMethod(mi) as IMethod;
        }
    }

    [Fact]
    public void test()
    {
        var fixture = new Fixture();
        fixture.Customizations.Add(new MethodInvoker(new WrapperFactoryMethodQuery()));

        var dummy = fixture.Create<Dummy>();
    }
}
```

Obviously, the object creation fails because there is no way of casting a Wrapper<Dummy> into a Dummy object.

What I fail to understand there is not that the cast fails, but that it's specified in the documentation that the return type is ignored. Shouldn't it be checked for a hierarchy between created type and returned type, or an [im|ex]plicit conversion between them ?

Is there a way around this without redefining casting operators, like implementing a specific MethodInvoker for instance ?

More generally, is there a place somewhere where I could find some sample usages of the TemplateMethodQuery class ?

Thanks a lot!

**Comment by zvirja** [comment]
Hi again and once again sorry for the delayed reply 😖

Likely the `TemplateMethodQuery` type caused some confusion to you, as currently we have really poor documentation (well, we don't have it at all 😅) It was created to solve a bit different type of problem. Suppose you have the following type:

```c#
public class Dummy
{
    private Dummy(int i)
    {
    }
    
    public static Dummy CreateUsingNumbers(int num1, int num2) => new Dummy(num1 + num2);
    public static Dummy CreateUsingString(string numStr) => new Dummy(int.Parse(numStr));
}
```

And you would like to provide AutoFixture with a hint which factory method you would like to use. For this purpose you might define a template method (method with a same signature as the target method) and register it via the `TemplateMethodQuery`:

```c#
[Fact]
public void test()
{
    var fixture = new Fixture();
    
    fixture.Customizations.Add(
        new MethodInvoker(new TemplateMethodQuery(typeof(Test).GetMethod(nameof(CreateUsingNumbers)))));
    // Or this one for slightly better performance
    // fixture.Customizations.Add(new FilteringSpecimenBuilder(
    //    new MethodInvoker(new TemplateMethodQuery(typeof(Test).GetMethod(nameof(CreateUsingNumbers)))),
    //    new ExactTypeSpecification(typeof(Dummy))));

    var dummy = fixture.Create<Dummy>();
}

public static Dummy CreateUsingNumbers(int num1, int num2) => default;
```

The method query purpose is to find a suitable factory method. It doesn't handle casting somehow, so if it happens that result is not convertible to a target type - here you get an exception.

As far as I remember, AutoFixture doesn't contain a mechanism to covert the resolved result to the expected result. Usually, we rely on the factory discovery subsystem and if it reports a way to activate an object, we expect the result of convertible type. When you are customizing AutoFixture, you should follow the same principle.

In your particular case the solution might really straightforward:
```c#
public class Wrapper<T>
{
    public T X { get; }

    public Wrapper(T x)
    {
        X = x;
    }
}

public class Dummy
{
    private Dummy(int i)
    {
    }

    public static Wrapper<Dummy> Create(int i) => new Wrapper<Dummy>(new Dummy(i));
}

[Fact]
public void ExamplePermanentCustomization()
{
    var fixture = new Fixture();
    
    fixture.Register((int number) => Dummy.Create(number).X);

    var sut = fixture.Create<Dummy>();
}

[Fact]
public void ExampleOneTimeCreation()
{
    var fixture = new Fixture();

    var sut = fixture.Get((int number) => Dummy.Create(number).X);
}
```

Hope it helps 😉 Let me know if I got the problem you are trying to solve. If not - please clarify it more specifically.

**Comment by xlecoustillier** [comment]
I suspected something was wrong in the way i was using TemplateMethodQuery.
And it seems like I missed the fact that we can register functions for data creations 😅 
This works like a charm 👍 
Thanks!
