### ISSUE TITLE
AutoData throws an exception

### ISSUE THREAD

**Issue by Kosntantin** [AutoFixture/AutoFixture#1074]
I am trying to write some test using the XUnit,AutoFixture and Moq combination. However, when I use the AutoData property the test canno run because of an 
![image](https://user-images.githubusercontent.com/42246943/47609526-9eb19380-da40-11e8-8a97-ec7149989e6e.png)

Something somewhere gets mixed up with resharper I suppose, but I have no idea how to resolve it. Any suggestions?

**Comment by zvirja** [comment]
@Kosntantin It should work correctly with R#. Could you please provide list of the packages you install? Also, if possible, attach a demo project demonstrating the issue - will be much easier to spot the problem place.

Thanks.

**Comment by Kosntantin** [comment]
Hi Alex,
I created a sample project. It throws the same error. You can see the packages there as well.
https://github.com/Kosntantin/TmpUnitTestProject

**Comment by zvirja** [comment]
I've just tested it on my local env and it works fine:
![image](https://user-images.githubusercontent.com/1074182/47622343-b9e9d500-db0c-11e8-8fa0-b40e4adb7a5d.png)

I used VS 2017 (15.8.1) and R# 2018.2.3.
Also tested with Rider 20182.3 (which uses R# test engine) - works fine as well.

Could you please test for one more time? If the issue still happens, could you please clarify particularities of your environment? When exactly the issue starts to happen (after which package)? If you use the latest version of R#, please try also reseting the settings.

**Comment by Kosntantin** [comment]
I have the same version of VS and R#. I reset R# settings and cleared the cache, but no change. If I run a single test I get the error, if I run all of them the test runs correctly. I am not sure what do you mean by environment, but as I said I have the same versions of VS and R# as you and Windows10. I have never tried to make tests on this machine so I it is the first time I see this problem. The problem starts when I add the AutoData property. If I remove it it dissappears.
I run the test from one of the two icons on the left.
![image](https://user-images.githubusercontent.com/42246943/47635726-5edcd000-db56-11e8-8adf-e3eaa978b570.png)

**Comment by zvirja** [comment]
@Kosntantin I've just played with the scenario for one more time and was able to reproduce it. That's a R# issue and I've reported it to them: [https://youtrack.jetbrains.com/issue/RSRP-472052](https://youtrack.jetbrains.com/issue/RSRP-472052)

Feel free to subscribe to it there to be notified about the fix 😉 

Thanks for reporting it! 👍

**Comment by zvirja** [comment]
@Kosntantin The issue will be fixed in the next R#/Rider version. You might test [latest EAP](https://www.jetbrains.com/resharper/eap/) and issue doesn't happen there anymore.

Closing this one as nothing can be done from our side.
