### ISSUE TITLE
AutoNSubstitute dependency issue when trying to use NSubstitute v3.1.0

### ISSUE THREAD

**Issue by robsonj** [AutoFixture/AutoFixture#1076]
Hi There,

Trying to move to NSubstitute v3.1.0, but this is resulting in the following error...

```
System.IO.FileLoadException : Could not load file or assembly 'NSubstitute, Version=2.0.3.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at AutoFixture.AutoNSubstitute.AutoNSubstituteCustomization.Customize(IFixture fixture)
   at AutoFixture.Fixture.Customize(ICustomization customization)
```

Is the answer here to add binding redirects everywhere? Or to update the AutoNSubstitute dependency on NSubstitute to be v3.1.0 ?

**Comment by zvirja** [comment]
Yep, binding redirection for win 😊 `AutoNSubstitute` dependencies update is not an option at all, as soon `NSubstitute` might release next major version (they will do it, actually) and we'll again get version mismatch 😉
