### ISSUE TITLE
Control enumerable size by attribute when using AutoNSubstituteCustomization

### ISSUE THREAD

**Issue by MrLuje** [AutoFixture/AutoFixture#1077]
Hi,
Using Theory & AutoNSubstituteCustomization, is there any way to control the size of a generated enumerable using an attribute ? (like WithSize in example below)

I want to achieve something like this :
```csharp
[Theory, AutoNSubstituteData]
public void CheckNames(
    [WithSize(5)] List<string> names
)
{
    Check.That(names).HasSize(5);
}
```

I know a workaround would be to use IFixture and CreateMany with expected length but I was wondering about the attribute way

**Comment by zvirja** [comment]
Hi @MrLuje,

AutoFixture supports some of the [DataAnnotation attributes](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations?view=netframework-4.7.2), so you might use that:

 ```c#
        [Theory, AutoData]
        public void CreateAmount([MinLength(42), MaxLength(42)] int[] names)
        {
            var namesList = names.ToList();
            Assert.Equal(42, namesList.Count);
        }
```

Notice, `Min/MaxLength` [support](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.maxlengthattribute?) string and array types only, so if you need list - simply convert input via `ToList()` extension method.

**Comment by MrLuje** [comment]
Perfect, totally missed that !
Thanks
