### ISSUE TITLE
Best way to request an empty collection?

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#1104]
What's the best way to get an empty collection, say List<string>?

I fixed it by adding a customisation with using factory and manually invoking the constructor, but it feels less than optimal.

**Comment by zvirja** [comment]
Hi @Kralizek,

The best idea which comes from top of my head is to use API like `fixture.CreateMany<string>(0).ToArray()`. If that doesn't work, please be more specific in your question and add a sample😉

**Comment by Kralizek** [comment]
Hey @zvirja sorry for the late reply.

The problem I have is accepting an instance of  class accepting a collection of any type in its constructor. For several reasons, that collection must be empty.

**Comment by zvirja** [comment]
So here we basically have two options:
- if that collection is very unique to the whole object graph, just inject empty collection to the fixture: `fixture.Inject(new VerySpecificClass[0])`
- register custom callback to activate your type and pass empty collection to the constructor: `fixture.Register((IOtherDependendency otherDep) => new Sut(otherDep, new VerySpecificClass[0]))`.

I'd say that the last option looks more preferable to me.
