### ISSUE TITLE
[Autodata+Moq] Freezing both the mock and mock.Object

### ISSUE THREAD

**Issue by isberg** [AutoFixture/AutoFixture#1112]
It would be nice to mark a test with AutoData and then have AutoFixture create your SUT and your choosen mock and then freeze both the mock and the mock.Object.

One way would be a FrozenMoq attribute on a parameter to the test method.

I have not managed to do this out of the box, but I have a draft for a solution as an answer to issue #1102.

This is a suggestion for an improvement and I would be happy for some feedback, both for the idea and my drafted solution.

**Comment by zvirja** [comment]
@isberg Thanks for raising the issue!

Could you please clarify whether the feature is still required if you [follow the approach](https://github.com/AutoFixture/AutoFixture/issues/1102#issuecomment-487422170) advised by @Kralizek? It should eliminate the need of `FrozenMoq` attribute.

Thanks.

**Comment by isberg** [comment]
@zvirja I am fine with closing this issue/question. The suggestion from @Kralizek helps alot. Considering there is no AutoMoqData attribute included, it does make sense to have no other moq related attributes built in.

Thanks!
