### ISSUE TITLE
Make AutoMoqDataAttribute work with XBehave

### ISSUE THREAD

**Issue by ftaran** [AutoFixture/AutoFixture#1113]
Hello,

I am trying to use an AutoMoqDataAttribute with my XBehave scenarios but it seems that when I do this I use the benefit of having different step information showing up on the Resharper or MsTest windows.

![Capture](https://user-images.githubusercontent.com/7329422/57209752-ae063080-6fd1-11e9-81f2-cf0004591779.PNG)

usually to provide data to your tests in Xbehave you use an Example attribute but I want to be able to provide already setup test data using autofixture.

I can see someone has had a similar issue [here](https://github.com/xbehave/xbehave.net/issues/285) and they have created this [gist](https://gist.github.com/iamkoch/81cecac9a3c5519a36801e01c8ab4968), but I am not sure how this will help or how it is supposed to be wired up to auto fixture.

here is my code:

```
[Scenario]
        [AutoMoqData]
        public void CorrelationId_WhenCorrelationIdIsPassedIn(
            string result,
            string correlationId,
            [Frozen(Matching.DirectBaseType)] DefaultHttpContext httpContext,
            [Frozen] Mock<IHttpContextAccessor> httpContextAccessorMock,
            CorrelationIdProvider sut)
        {
            $"Given a correlation id header value of {correlationId} has been passed in"
                .x(() =>
                {
                    httpContext.Request.Headers["x-Correlation-ID"] = correlationId;
                    httpContextAccessorMock.Setup(x => x.HttpContext).Returns(httpContext);
                });

            "When the correlation id is retrieved"
                .x(() => result = sut.CorrelationId);

            "Then the correlation id is not empty"
                .x(() => result.Should().NotBeEmpty());

            $"And the correlation id matches {correlationId}"
                .x(() => result.Should().Be(result));
        }
``` 
```
 public class AutoMoqDataAttribute : AutoDataAttribute
    {
        public AutoMoqDataAttribute() :
            base(() => new Fixture().Customize(new AutoMoqCustomization()))
        {
        }
    }
```

**Comment by zvirja** [comment]
@ftaran Hi, thanks for firing the issue.

Unfortunately, I'm not familiar with XBehave, so it's a bit hard for me to grasp what exactly the question is about. Could you please describe that more from the AutoFixture library perspective?

Also notice, that it might worth asking XBehave about that, as to me it sounds like you are looking for a way to customize XBehave... But I might be wrong on that 😊

**Comment by zvirja** [comment]
Just noticed [you raised question on SO](https://stackoverflow.com/questions/56017749/how-to-replace-example-from-xbehave-with-autofixtures-automoqdataattribute). That's right thing to do! Closing this issue in favor of the SO question and please feel free to re-open it if any specific help is required.
