### ISSUE TITLE
Fix typo in WritablePropertyAssertion Class remarks

### ISSUE THREAD

**Issue by venotp** [AutoFixture/AutoFixture#1114]
[AutoFixture/Src/Idioms/WritablePropertyAssertion.cs](https://github.com/AutoFixture/AutoFixture/blob/master/Src/Idioms/WritablePropertyAssertion.cs)
line 15 :
`/// one should always write a unit test that verifies that the value read from the proeprty is`

Change "proeprty" to "property"

Thanks !

**Comment by zvirja** [comment]
Thanks! Fixed that.
