### ISSUE TITLE
Make creation of Fixture in AutoData attribute a virtual method not a Func in the constructor

### ISSUE THREAD

**Issue by Ergamon** [AutoFixture/AutoFixture#1125]
Current design does not allow inherited attributes to use properties.
so e.g. if I want to have an attribute like this:
```c#
  public class MyAutoDataAttribute : AutoDataAttribute
  {
    public int RepeatCount { get; set; }
  }
```
So how do I set the RepeatCount? As the property is part of the instance it cannot be used in a constructor.
So either I can make it a constructor argument like this:
```c#
    public MyAutoDataAttribute(int repeatCount = 3)
         : base(() => new Fixture() { RepeatCount = repeatCount })
    {
    }
```
but this is against attribute design guidelines where parameters in constructors are mandatory values an attribute needs and properties are optional values.
So my other option is more or less a hack:
```c#
public override IEnumerable<object[]> GetData(MethodInfo testMethod)
    {
      this.Fixture.RepeatCount = RepeatCount;

      return base.GetData(testMethod);
    }
```

but this feels very ugly ;)
A virtual CreateFixture compared with the Func<IFixture> constructor argument would have the benefit of having access to all instance members.
What do you think?

**Comment by zvirja** [comment]
Hi! Thanks for raising the issue - very interesting concern.

I could advise you more elegant solution:

```c#
[DataDiscoverer("AutoFixture.Xunit2.NoPreDiscoveryDataDiscoverer", "AutoFixture.Xunit2")]
public class MyAutoDataAttribute : DataAttribute
{
    public int RepeatCount { get; set; }

    public override IEnumerable<object[]> GetData(MethodInfo testMethod) =>
        new CustomizedAutoData(RepeatCount).GetData(testMethod);

    private class CustomizedAutoData : AutoDataAttribute
    {
        public CustomizedAutoData(int repeatCount) :
            base(() => new Fixture { RepeatCount = repeatCount })
        {
        }
    }
}
```

I don't like making the `CreateFixture` a virtual method, as I don't want to restrict when the fixture is actually created. Otherwise, if later I want to create the fixture instance immediately in the constructor, [I will be not allowed to call the `CreateFixture` as it's a virtual method](https://stackoverflow.com/questions/119506/virtual-member-call-in-a-constructor).

I don't think that scenario you describe is that common, so the suggested workaround should be fine. Is it? :wink:

**Comment by Ergamon** [comment]
I am not religious on things like this. If you can show me a way then it is fine for me. Of course the virtual method has other disadvantages. Like everything has pros and cons.

I came up with ideas like this to make the fixture creation a little bit more declarative. I wonder why I am the only person with such desires ;)

I would probably never came up with this idea but your code works for this scenario like a charm!

I have only one small problem left with this. There is the "companion attribute" for inline data. Currently looking like this:

```
  public class MyInlineAutoDataAttribute : CompositeDataAttribute
  {
    public MyInlineAutoDataAttribute(params object[] values)
      : base(new InlineDataAttribute(values), new MyAutoDataAttribute())
    {
    }
  }
```
If I change my attribute code to the one you showed above it still works, but of course I dont have access to the RepeatCount property.
Just to be sure is the solution to this basically doing the same again?

```
  [DataDiscoverer("AutoFixture.Xunit2.NoPreDiscoveryDataDiscoverer", "AutoFixture.Xunit2")]
  [AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
  public class MyInlineAutoDataAttribute : DataAttribute
  {
    private readonly object[] values;

    public MyInlineAutoDataAttribute(params object[] values)
    {
      this.values = values;
    }

    public int RepeatCount { get; set; }

    public override IEnumerable<object[]> GetData(MethodInfo testMethod)
    {
      var inlineData = new InlineDataAttribute(values);
      var autoData = new CustomizedAutoData(RepeatCount);
      var compositeData = new CompositeDataAttribute(inlineData, autoData);

      return compositeData.GetData(testMethod);
    }
  }
```
(Of course the private class CustomizedAutoData has to be moved to internal to be accessable from both attributes, but this is just a minor detail)

Thx for your help and more than quick reply.

**Comment by zvirja** [comment]
Sorry for changing the direction a bit, but I want to advise you something completely different. Here is the way how I normally use AutoFixture in my projects:
https://gist.github.com/zvirja/9366f23e28dd88e637d32bb52c025542

It's more flexible and allows you to not lock your data attribute to the specific customizations. Instead, you have a generic way to customize fixture my means of `CustomizeFixture` attribute. This way I apply test specific customization which are never repeated in other tests.

If it's fine for you - feel free to grab and use it 😉 

> Just to be sure is the solution to this basically doing the same again?

Yes, something like that should work. while yeah, it's pretty clumsy 😟

**Comment by Ergamon** [comment]
Sorry for the late reply, I was out for the last few days ;)

Thx for the example. Actually this was my main problem. I use AutoFixture / Xunit / NSubstitute now for a while, but for some specific tests I need these types of customizations. But if you generate the parameters of the test method by AutoFixture it is too late to work with the fixture in the test code.

So my attempt was to extend my implementation of the AutoDataAttribute with some kind of paramatrization. 

I experimented a little with your sample and modified it to be used a little easier (of course this is very dependent on personal opinion :))

I like the idea of not making the AutoDataAttribute class too complicated and use some kind of "companion"-attribute, but having the CustomizeFixtureAttribute using another type created by Activator.CreateInstance basically brings me back to the same problem as before. Now the Customization cannot have parameters.
So I changed the code a little making this class abstract and implement ICustomization. It feels a little bit more in line with the other attributes as well (at least for me).

So the test classes now have private attribute classes in my version and I can now design them with any number of constructor parameters or properties.

Works like a charm. Thx for your great support. You made an already great AutoFixture fan even happier.

**Comment by zvirja** [comment]
> I like the idea of not making the AutoDataAttribute class too complicated and use some kind of "companion"-attribute, but having the CustomizeFixtureAttribute using another type created by Activator.CreateInstance basically brings me back to the same problem as before. Now the Customization cannot have parameters.

Well, my idea was that you will not need parameters when you have local customizations, as you can always create something like `FiveItemsInSequenceCustomization`, which is very specific and applies in the individual cases only.

And again, you can always consider usage of other APIs to create sequences of custom length.

Anyway, glad my answer helped and you have found a way for yourself 😉
