### ISSUE TITLE
Inconsistent Build behaviour

### ISSUE THREAD

**Issue by pavlos-pavlopoulos-cko** [AutoFixture/AutoFixture#1127]
I have two uses of Build that should behave the same way, semantically. 

Version 1:
```
        public class Class1
        {
            public string Id { get; set; }
            public IEnumerable<int> Values { get; set; }
        }

        public class Class2
        {
            public Class1 Class1 { get; set; }
        }

        public Class2 CreateClass2(Class1 inst = null)
        {
            var classBuilder = _fixture.Build<Class2>();

            if (inst != null)
            {
                classBuilder.With(p => p.Class1, inst);
            }

            return classBuilder.Create();

        }
```

Version 2:
```
        public Class2 CreateClass2(Class1 inst = null)
        {
            return _fixture.Build<Class2>()
                .With(p => p.Class1, inst ?? _fixture.Create<Class1>())
                .Create();
        }
```

When version 2 is called with a non-null instance of Class1, the generated instance of Class2 does indeed hold the given instance of Class1. When version 1 is called the same way, a random isntance of Class1 is generated even though the if block is executed.

Is that expected behaviour? At first glance the two implementations should be equivalent.

**Comment by zvirja** [comment]
Hi,

I suspect that the reason for this behavior is that `With` method is a part of immutable API. It does not mutate the existing object, but return you a new object with applied customization. In the first example you are discarding result of the `With()` method invocation, so in fact your `classBuilder` is never customized.

Could you try re-writing code like below and check whether it helps?

```c#
...
if (inst != null)
{
    classBuilder = classBuilder.With(p => p.Class1, inst);
}
...
```

**Comment by pavlos-pavlopoulos-cko** [comment]
Yup, that works! Thanks. Was treating this as a more classic builder so was very surprised it didn't work.

Closing this.
