### ISSUE TITLE
Arg.Is not matching when instance is generated with .NET Core 2.2, AutoFixture, xUnit2 and AutoNSubstituteData attribute.

### ISSUE THREAD

**Issue by JoanComasFdz** [AutoFixture/AutoFixture#1133]
Hi,

I have a .NET Core 2.2 xUnit 2.4.1 project with AutoFixture 4.11 and NSubstitute 4.2.1.

I have the following example production code to test this issue:
```c#
    public class Data
    {
        public int Age { get; set; }
    }

    public interface IDoer2
    {
        int Do2(Data d);
    }

    public class Doer1
    {
        private readonly IDoer2 _doer2;

        public Doer1(IDoer2 doer2)
        {
            _doer2 = doer2;
        }

        public int Do1(string dataJson)
        {
            var data = JsonConvert.DeserializeObject<Data>(dataJson);

            var result = _doer2.Do2(data);

            return result + 1;
        }
    }
```

For the tests, I have the following attribute:
```c#
    public class AutoNSubstituteDataAttribute : AutoDataAttribute
    {
        public AutoNSubstituteDataAttribute()
            : base(() => new Fixture().Customize(new AutoNSubstituteCustomization()))
        {
        }
    }
```

If I use `Substitute.For<>()` to create my mocks, it all works as expected:
```c#
        [Fact]
        public void TestArgsWithExplicityDeclaringData()
        {
            var data = Substitute.For<Data>();
            var json = JsonConvert.SerializeObject(data);
            var doer2 = Substitute.For<IDoer2>();
            doer2.Do2(Arg.Is<Data>(d => d.Age == data.Age)).Returns(2);
            var sut = new Doer1(doer2);

            var res2 = sut.Do1(json);

            Assert.Equal(3, res2);
        }
```

But when I use the attribute to auto generate the items that I need, argument matching seems to not be working. Example:

```c#
        [Theory, AutoNSubstituteData]
        public void TestArgs1WithAutoData(
            Data data,
            IDoer2 doer2,
            Doer1 sut)
        {
            var json = JsonConvert.SerializeObject(data);
            doer2.Do2(Arg.Is<Data>(d => d.Age == data.Age)).Returns(2);

            var res = sut.Do1(json);

            Assert.Equal(3, res);
        }
```
The assert fails because actual value of `res` is 1.

Why does `Arg.Is<>()` not work with auto generated data? Am I missing some configuration here? 

Thanks,
Joan

**Comment by zvirja** [comment]
Hi @JoanComasFdz,

Thanks for the nicely formatted question - I appreciate it!

The reason of this behavior is that the `IDoer2` instance injected to the `sut` and the instance provided to you via theory parameters is not the same instance. By default AutoFixture creates new instance each time you request object - no matter whether it's a class, or an interface substitute.

The simplest and the most correct way to solve the issue would be to use the `Frozen` attribute which comes with the xUnit integration library.

```c#
[Theory, Issue1133.AutoNSubstituteDataAttribute]
public void TestArgs1WithAutoData(
    Data data,
    [Frozen] IDoer2 doer2,
    Doer1 sut)
{
```

Now the instance injected to the test and to the `sut` dependency will be the same. Notice that order matters, so if you re-order `doer2` activation after `sut`, it will not work.

It's a general pattern you follow with AutoFixture - you "freeze" all the dependencies you are interested in before activating SUT and below configure them to verify the actual scenario.

Happy testing 🚀

**Comment by JoanComasFdz** [comment]
Hi @zvirja ,

Yes, that was the issue, thanks a lot!

**Comment by aivascu** [comment]
Closing this issue since it seems to be resolved. 
Feel free to reopen if necessary.
