### ISSUE TITLE
AutoNSubstitute Fails to load assembly for NSubstitute 4.2.1

### ISSUE THREAD

**Issue by JGCreator** [AutoFixture/AutoFixture#1135]
While the following image shows that the version of the dependency should be `>= 2.0.3 && < 5.0.0` this is not supporting my direct reference to 4.2.1.

![image](https://user-images.githubusercontent.com/5280734/63968193-ba246b00-ca64-11e9-8477-ce43ee5b40e8.png)

```
        private ICmdOptions _options;
        private IAzureRepository _azureRepository;
        private Fixture _fixture;
        private ReleaseReportBuilder _sutBuilder;

        [SetUp]
        public void Setup()
        {
            _fixture = new Fixture();
            _fixture.Behaviors.Add(new OmitOnRecursionBehavior());
            _fixture.Customize((new PropertyTypeExclusion<IdentityRef>()).ToCustomization());
            _fixture.Customize(new AutoNSubstituteCustomization());

            _options = _fixture.Freeze<ICmdOptions>();
            _azureRepository = _fixture.Freeze<IAzureRepository>();
            _sutBuilder = _fixture.Create<ReleaseReportBuilder>();
        }
```

![image](https://user-images.githubusercontent.com/5280734/63968434-4cc50a00-ca65-11e9-8b20-2965844bbaa1.png)

**Comment by zvirja** [comment]
Hi @JGCreator 

Sorry for the belated reply - you must have solved the issue yourself already 🤔

But just in case, the right answer is assembly binding redirections you need to configure in your project ;-) After that it should work like a charm.
