### ISSUE TITLE
Customizing a specific type with a custom ISpecimenBuilder only customizes the entire fixture

### ISSUE THREAD

**Issue by JGCreator** [AutoFixture/AutoFixture#1136]
I have a [question open on StackOverflow](https://stackoverflow.com/questions/57700154/register-custom-ispecimenbuilder-only-to-a-particular-type/57704999#57704999) that details this issue.

I want to customize a type S to omit any specimen building for properties within the context of that type S that are of another type T.

For this I have created a custom `ISpecimenBuilder` as thus:

```c#
        /// <summary>
        /// A class implementing <see cref="ISpecimenBuilder"/> to allow the exclusion of properties initialized by <see cref="AutoFixture"/> based on their type.
        /// </summary>
        /// <typeparam name="T">The type upon which to base the exclusion.</typeparam>
        /// <inheritdoc />
        public class PropertyTypeExclusion<T> : ISpecimenBuilder
        {
            public object Create(object request, ISpecimenContext context)
            {
                var propertyInfo = request as PropertyInfo;

                if (propertyInfo?.PropertyType == typeof(T))
                {
                    return new OmitSpecimen();
                }

                return new NoSpecimen();
            }
        }
```

But using it thus:

`_fixture.Customize<Release>(c => new PropertyTypeExclusion<IdentityRef>());`

registers the customization for any type created with the fixture having properties of type `IdentityRef` such that:

```
public class Build
{
    public IdentityRef IdRef { get; set; }
}
```
does not get the `IdRef` property populated when 
```
_fixture.Customize<Release>(c => new PropertyTypeExclusion<IdentityRef>());
_fixture.Create<Build>();
```

**Comment by zvirja** [comment]
Updated the original question with another way of solving the issue ;-)
