### ISSUE TITLE
Add custom configuration support (e.g., RecognizePostfixes) for mapping from Dictionary<string, object> and ExpandoObject

### ISSUE THREAD

**Issue by NeoXtreem** [AutoFixture/AutoFixture#1151]
Take a scenario where a `Dictionary<string, object>` (or `ExpandoObject`) is to be mapped to a class `Bar` where the source keys (or property names) have postfixes which are configured in AutoMapper using `RecognizePostfixes`:

    var mapper = new Mapper(new MapperConfiguration(cfg =>
    {
        cfg.RecognizePostfixes("Postfix");
    }));
    
    var foo = new Dictionary<string, object> {{"XPostfix", 1}, {"YPostfix", 2}};
    var bar = mapper.Map<Bar>(foo);

`Bar` is defined as:

    class Bar
    {
        public int X;
        public int Y;
    }

Currently, the properties are not mapped unless the source keys and destination property names match. AutoMapper supports both `Dictionary<string, object>` and `ExpandoObject` (as per [here](http://docs.automapper.org/en/stable/Dynamic-and-ExpandoObject-Mapping.html)), but seemingly without support for configuration options such as `RecognizePostfixes`.

Could configuration support be added for `Dictionary<string, object>` and `ExpandoObject` just as with regular types?

**Comment by NeoXtreem** [comment]
@ploeh @moodmosaic Apologies, I accidentally created this issue on this project when it should have been created under AutoMapper (I've recreated the issue [there](https://github.com/AutoMapper/AutoMapper/issues/3262)). Please could you delete this issue (not just close it, but delete completely so it's removed from my profile history)? Thanks!

**Comment by moodmosaic** [comment]
@NeoXtreem 
>accidentally created this issue on this project when it should have been created under AutoMapper

No problem, that's OK :+1: I'll just close it and then [it's up to @zvirja to decide](https://github.com/AutoFixture/AutoFixture/issues/703) if it should be hard-deleted. Deleting or rewriting things related to a project's history (issues, git logs, etcetera) isn't my cup of tea. :nerd_face:

**Comment by NeoXtreem** [comment]
@moodmosaic Yes, I recall that @ploeh took a step back from AutoFixture. Yes, if @zvirja could then just delete this issue as it has nothing to do with AutoFixture at all, that would be great.

**Comment by NeoXtreem** [comment]
@zvirja Are you able to delete this then?
