### ISSUE TITLE
Using MockHttp with AutoFixture AutoData

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#1152]
Hi,

I'm trying to use [MockHttp](https://github.com/richardszalay/mockhttp) with AutoFixture's AutoData attribute.

To test the library, I've created a [test repo](https://github.com/Kralizek/MockHttpTests) that contains only two tests:

```csharp
public class Tests
{
    [Test, CustomAutoData]
    public async Task Basic_test(Uri testUri, string result)
    {
        var handler = new MockHttpMessageHandler();

        var sut = new TestService(handler.ToHttpClient());            

        handler.When(HttpMethod.Get, testUri.ToString()).Respond(HttpStatusCode.OK, new StringContent(result));

        var actual = await sut.GetString(testUri);

        Assert.That(actual, Is.EqualTo(result));
    }

    [Test, CustomAutoData]
    public async Task Test_with_custom_autodata([Frozen] MockHttpMessageHandler handler, TestService sut, Uri testUri, string result)
    {
        handler.When(HttpMethod.Get, testUri.ToString()).Respond(HttpStatusCode.OK, new StringContent(result));

        var actual = await sut.GetString(testUri);

        Assert.That(actual, Is.EqualTo(result));
    }
}

public static IFixture CreateFixture()
{
    var fixture = new Fixture();

    fixture.Customize<HttpClient>(o => o.FromFactory((MockHttpMessageHandler handler) => handler.ToHttpClient()));

    return fixture;
}
```

This setup is not working as the second test fails due to a CancellationToken being on "ThrowIfCancellationRequested".

Changing the customizations as follow makes the second test working. Unfortunately this is not optimal because it makes the setup too dependent on the SUT constructor.

```csharp
public static IFixture CreateFixture()
{
    var fixture = new Fixture();

    //fixture.Customize<HttpClient>(o => o.FromFactory((MockHttpMessageHandler handler) => handler.ToHttpClient()));

    fixture.Customize<TestService>(o => o.FromFactory((MockHttpMessageHandler handler) =>
    {
        var http = handler.ToHttpClient();

        return new TestService(http);
    }));

    return fixture;
}
```

This issue is mostly about a clarification about the "chain".

I was expecting:
1. TestService (default setup) to require a HttpClient
2. HttpClient use the provided customization based on `FromFactory` that requires a MockHttpMessageHandler
3. MockHttpMessageHandler to be newed up using the default setup

Thanks for your help!

I opened an issue on MockHttp here: https://github.com/richardszalay/mockhttp/issues/73

**Comment by aivascu** [comment]
@Kralizek don't know if you still need help with this but it seems that you need a custom specimen builder.
I've made a small [gist](https://gist.github.com/aivascu/97a9459726bc650c8c1a4b0d6ec44ce9) for you.
Basically you add that specimen builder and then instead of using the factory you customize your Fixture like this:
```csharp
fixture.Customizations.Add(new HttpClientSpecimenBuilder());
```

**Comment by Kralizek** [comment]
Thanks for your help! I'll check it later this week :)

**Comment by Kralizek** [comment]
@aivascu do you mind if I put your specimen into a NuGet package?

**Comment by aivascu** [comment]
@Kralizek not at all, as long as the package is open source and you credit my contribution.
