### ISSUE TITLE
Upgrade the minimum NSubstitute version

### ISSUE THREAD

**Issue by SeanFarrow** [AutoFixture/AutoFixture#1158]
has upgrading the minimum NSubstitute version to v4 for version 5.0 been considered?

It strikes me that we are two clear versions behind, and I wondered what hte rationale for this is?

I'm happy to do the upgrade if it is desired?

**Comment by aivascu** [comment]
@SeanFarrow my guess is the primary reason is that there are not enough active maintainers (see #1167).
Could you elaborate what would be the benefits of this upgrade?
Is there something that could be optimized in AutoFixture, with this upgrade?

**Comment by SeanFarrow** [comment]
Hi,

Firstly, what I would say is the currently referenced package is nearly 3 years out of date.

Secondly, there is a really odd issue whereby after setting up tests with after setting up AutoFixture with the AutoNSubstituteCustomization, you are not able to use features of NSubstitute to, for example, set the return value ofa method on an interface mocked by AutoFixture.

**Comment by aivascu** [comment]
@SeanFarrow this does indeed sound like an issue. 
I have to admit I have not used `AutoFixture.AutoNSubstitute` in any projects recently.

I tried to replicate the issue you describe (see below) but the tests pass fine.
Perhaps if you could share a minimum reproducible test? 
It could help narrow down the issue.

### Test
```csharp
public class NSubReturnValueTests
{
    [Fact]
    public void ShouldFailWhenAutoFixtureSetupWithNSubCustomization1()
    {
        var fixture = new Fixture().Customize(new AutoNSubstituteCustomization());
        var contract = fixture.Freeze<IMyContract>();
        var consumer = fixture.Create<MyConsumer>();
        var expected = fixture.Create<string>();

        contract.DoSomething().Returns(expected);

        var actual = consumer.Do();

        actual.Should().Be(expected);
    }
}

public interface IMyContract
{
    string DoSomething();
}

public class MyConsumer
{
    private readonly IMyContract dependency;

    public MyConsumer(IMyContract dependency)
    {
        this.dependency = dependency;
    }

    public string Do()
    {
        return this.dependency.DoSomething();
    }
}
```

### Packages:
```xml
<PackageReference Include="AutoFixture" Version="4.11.0" />
<PackageReference Include="AutoFixture.AutoNSubstitute" Version="4.11.0" />
<PackageReference Include="AutoFixture.Xunit2" Version="4.11.0" />
<PackageReference Include="FluentAssertions" Version="5.10.3" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.0-preview-20200318-01" />
<PackageReference Include="NSubstitute" Version="4.2.1" />
<PackageReference Include="xunit" Version="2.4.1" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
```

**Comment by SeanFarrow** [comment]
Andre,

The interesting thing about this test is it’s nearly identical to what I’m using, however, rather than doing Fixture.Freeze<IMyContract>(), I’m doing fixture.Create<IMyContract>().
This is what seems to cause the issue.
Do freeze and create call the same code internally?
Thanks,
Sean.

**Comment by aivascu** [comment]
@SeanFarrow the short answer is yes, they go through the same pipeline (chain of responsibility) of object creation.

**Comment by aivascu** [comment]
@SeanFarrow if you want to know more about freezing mocks see this [post](https://blog.ploeh.dk/2010/03/27/Freezingmocks/), on Mark's blog. It's a bit outdated but it will help you get the ropes, if you have not used it before.
There's also a [AutoFixture course](https://app.pluralsight.com/library/courses/autofixture-dotnet-unit-test-get-started/table-of-contents), on pluralsight, made by Jason Roberts. 
Might help you cover the gaps.

**Comment by aivascu** [comment]
@SeanFarrow are there any other concerns about the minimum NSubstitute version?

I'm thinking, a bump for the minimum version can be motivated if AutoFixture can benefit from it, or if there are any breaking changes that affect the AutoFixture behavior.

You can always install the latest version of NSub, alongside the AutoFixture.AutoNSubstitute package and benefit from the most up to date features.

Anyway can this issue be closed?

**Comment by aivascu** [comment]
Closing the issue due to inactivity.
