### ISSUE TITLE
Is there a way to Freeze only once?

### ISSUE THREAD

**Issue by JoanComasFdz** [AutoFixture/AutoFixture#1163]
I am in an scenario like this:

```
[Theory, AutoNSubstituteData]
public void Method_Setup_Result(
[SomeCustomization] Car car1, 
Garage garage1,

)
{
    Assert.Equal(car1, garage.Cars.ElementAt(0))
    Assert.NotEqual(car1, garage.Cars.ElementAt(1))
    Assert.NotEqual(car1, garage.Cars.ElementAt(2))
}
```

Is there a way to create an attribute and or a relay to do this?

I would like to be able to use an attribute like FreezeOnce like:
```
[Theory, AutoNSubstituteData]
public void Method_Setup_Result(
[FreezeOnce, SomeCustomization] Car car1, 
Garage garage1,
)
{
    Assert.Equal(car1, garage.Cars.ElementAt(0))
    Assert.NotEqual(car1, garage.Cars.ElementAt(1))
    Assert.NotEqual(car1, garage.Cars.ElementAt(2))
}
```

I have found this SO questions but the API has changed since then:

- https://stackoverflow.com/questions/18161127/cant-grasp-the-difference-between-freeze-inject-register
- https://stackoverflow.com/questions/34069682/autofixture-can-you-unfreeze-a-data-type/34073751?noredirect=1#comment106061718_34073751

**Comment by Tarig0** [comment]
could you give a more substantial example for the freeze once scenario?

**Comment by aivascu** [comment]
@JoanComasFdz moving discussion to #1214
