### ISSUE TITLE
Customizations are ignored

### ISSUE THREAD

**Issue by KarolStosikPowel** [AutoFixture/AutoFixture#1165]
I've recently updated from AutoFixture 3.50.2 to 4.11.0

After update, `Customize<>()` is not used when creating object with `Build()` 

One more thing, probably related. When there are multiple customizations on the same object, only the last is valid, and previous are ignored. (The quick fix is to chain them inside one block, but this should not be the final solution.)

See the reproductions for both issues:

```
using AutoFixture;
using Xunit;

namespace CustomizationDoesntWork
{
    public class ProofTest
    {
        public class Example
        {
            public string Name { get; set; }
            public string City { get; set; }
        }

        [Fact]
        public void ShouldUseCustomizationWhenBuilding()
        {
            var fixture = new Fixture();

            fixture.Customize<Example>(e => e.Without(p => p.Name));

            var exampleByCreate = fixture.Create<Example>();
            Assert.Null(exampleByCreate.Name); // ok

            var exampleByBuild = fixture.Build<Example>().With(e => e.City, "something").Create();
            Assert.Null(exampleByBuild.Name); // fails!
        }

        [Fact]
        public void ShouldRememberAllCustomizations()
        {
            var fixture = new Fixture();

            fixture.Customize<Example>(e => e.With(p => p.Name, "John"));
            fixture.Customize<Example>(e => e.With(p => p.City, "New York"));

            var exampleByCreate = fixture.Create<Example>();
            Assert.Equal("John", exampleByCreate.Name); // fails!
        }
    }
}
```

**Comment by elonmallin** [comment]
I can't get this working in any version. `Customize` is only applied when you do `Create`. `Build` is ignored and just gets whatever default things `AutoFixture` does. Seems like this example on some site says that it should be possible to do what you describe in the bug as well: https://docs.educationsmediagroup.com/unit-testing-csharp/autofixture/type-customization but I haven't seen any official docs for it.

This bug is over a year old though and this seems like a pretty standard use case? Is there any update on this?

**Comment by ecampidoglio** [comment]
@KarolStosikPowel The behavior you're seeing is _by design_.

The documentation for the `Build<T>` method [says](https://github.com/AutoFixture/AutoFixture/blob/c56d708b1ef3d03be313848c11d5a52855b54e09/Src/AutoFixture/IFixture.cs#L82-L85):

> Note that the Build method chain is best understood as a one-off Customization. It bypasses all Customizations on the `Fixture` instance. Instead, it allows fine-grained control when building a specific specimen. However, in most cases, adding a convention-based `ICustomization` is a better, more flexible option.

In other words, `Customize` and `Build` are two _mutually exclusive_ ways to customize the creation of a type.

**Comment by ecampidoglio** [comment]
@elonmallin It seems the folks at @emgdev should update their documentation regarding the [type customization](https://github.com/emgdev/unit-testing-csharp/blob/master/docs/autofixture/type-customization.md#type-customization). The test in their second example will always fail.

**Comment by aivascu** [comment]
@Kralizek can you check the documentation reference above? ☝️

**Comment by Kralizek** [comment]
@simgu FYI :)

**Comment by elonmallin** [comment]
Thanks @ecampidoglio =)

Somehow I found these two misleading things pointing in the same direction before the docs xP

Anywho, my use case wouldn't be solved even if this worked, I'd also need a callback on `Create`, similar to https://github.com/AutoFixture/AutoFixture/issues/988.

Then building test data for EF Core InMemory testing would be quite nice:
```
// Setup
var fixture = new Fixture();

fixture.Customize<Person>(b => b
    .With(p => p.Id, () => UniqueId())
    .OnCreate((person) => {
        _efCoreInMemoryTestContext.Persons.Add(person);
        _efCoreInMemoryTestContext.SaveChanges();
    })
);
```
```
// Test
// Arrange
var person = fixture.Build<Person>()
    .With(p => p.UpdatedDate, DateTime.Now.AddDays(-8))
    .Create(); // Person has a generated id, is saved to the InMemory DB and is ready to use in EF Core InMemory testing.

// Act
// Get persons updated more than a week ago

// Assert
// Result matches person
```

**Comment by Kralizek** [comment]
@aivascu I don't work for @emgdev anymore but I suppose the new CTO (@simgu) will assign the edit to someone else.

Anyway I have cloned and republished the guide on my own company's account:

Repo: https://github.com/insight-architectures/unit-testing-csharp/
Published version: https://docs.insightarchitectures.com/unit-testing-csharp/
