### ISSUE TITLE
Best way to override Delegate creation while keeping all other customizations

### ISSUE THREAD

**Issue by Ergamon** [AutoFixture/AutoFixture#1174]
We often use factory methods (Func<T>) in classes.
This works well in conjunction with AutoFixture.
The only problem I have is that the generated code always returns the same value.

Let´s take a sample class:
```
public class Sample 
{
  private readonly Func<IFoo> _createFoo;

  public Sample(Func<IFoo> createFoo)
  {
    _createFoo = createFoo;
  }
}
```

So if I would have to write the code AutoFixture does automatically it would look like this:

```
var fixture = CreateFixture();
var foo = fixture.Create<IFoo>();
var sample = new Sample(() => foo);
```

I am of course simplifying what AutoFixture does, but the result is that I will always get the same instance whenever I call the factory method.
Can someone please direct me into customizing this behavior so that the result is like this:
```
var fixture = CreateFixture();
var sample = new Sample(() => fixture.Create<IFoo>());
```

**Comment by Ergamon** [comment]
I spend now some time analyzing the source code.
From my understanding the problem I have is in DelegateGenerator, more specifically in DelegateGenerator.CreateMethodSpecimenBody
```
        private static Expression CreateMethodSpecimenBody(MethodInfo request, ISpecimenContext context)
        {
            var returnType = request.ReturnType;
            Expression body;

            if (returnType == typeof(void))
            {
                body = Expression.Empty();
            }
            else
            {
                var returnValue = context.Resolve(returnType);
                body = Expression.Convert(Expression.Constant(returnValue), returnType);
            }

            return body;
        }
```
There is visible that the returnValue is only created once.
I would suggest to change this to:
```
        private static Expression CreateMethodSpecimenBody(MethodInfo request, ISpecimenContext context)
        {
            var returnType = request.ReturnType;
            Expression body;

            if (returnType == typeof(void))
            {
                body = Expression.Empty();
            }
            else
            {
               var argumentExpression = Expression.Constant(returnType);
               Expression<Func<object, object>> resolveExpression = o => context.Resolve(o);
               var invokeExpression = Expression.Invoke(resolveExpression, argumentExpression);

               body = Expression.Convert(invokeExpression, returnType);
            }

            return body;
        }
```
With the current maintainer situation, probably my hopes that this will be changed are probably quite low?

**Comment by Kralizek** [comment]
I am not sure I understood your problem but generally I delegate the generation of fake delegates to Moq via the AutoMoq integration.

https://github.com/Nybus-project/Nybus/blob/9f2c7d2268787a5a9c7a8a232c303f9d50637871/tests/TestUtils/AutoMoqDataAttribute.cs#L17-L23

Here I use the piece of configuration above in a custom implementation of the `AutoDataAttribute` that you find in the glue libraries like `AutoFixture.NUnit3` (the one I used).

https://github.com/emgdev/templates/blob/b1cb90a17add09170434e92e1f0a324d1b168a8b/content/UnitTestProject/UnitTest1.cs#L9-L15

**Comment by ecampidoglio** [comment]
@Ergamon Your assessment is correct; you'll always get the same return value from a given delegate specimen. In other words, given this:

```csharp
var someFunc = fixture.Create<Func<int>>();
var anotherFunc = fixture.Create<Func<int>>();
```

You'll always get the same number from calling `someFunc()`, but you'll get a *different* number from `anotherFunc()`.

The change you're suggesting would be a *breaking change*, since it alters the current behavior. However, you can always write your own delegate builder and tell AutoFixture to use that instead of the built-in one:

```csharp
fixture.Customizations.Insert(0, new DelegateWithUniqueReturnValueBuilder());
```

**Comment by Ergamon** [comment]
@Kralizek for the sake of simplicity I used plain AutoFixture. Normally I use AutoNSubstitute. But it does not matter what framework you use as the "problem" is in the base library.
Perhaps you can understand it better, if I show it in your style:
```
  public interface IFoo
  {
    string Name { get; }
  }

  public class Sample
  {
    private readonly Func<IFoo> _getFoo;

    public Sample(Func<IFoo> getFoo)
    {
      _getFoo = getFoo;
    }

    public string GetText()
    {
      var foo = _getFoo();

      return foo.Name;
    }
  }

  public class Tests
  {
    [Theory]
    [AutoMoqData]
    private void DelegateTest(Sample sample)
    {
      var text1 = sample.GetText();
      var text2 = sample.GetText();

      text1.Should().NotBe(text2);
    }
  }
```
This test fails, as every call to the Func<IFoo> will always give you the same Moq instance.

**Comment by Ergamon** [comment]
> 
> 
> @Ergamon Your assessment is correct; you'll always get the same return value from a given delegate specimen. In other words, given this:
> 
> ```cs
> var someFunc = fixture.Create<Func<int>>();
> var anotherFunc = fixture.Create<Func<int>>();
> ```
> 
> You'll always get the same number from calling `someFunc()`, but you'll get a _different_ number from `anotherFunc()`.
> 
> The change you're suggesting would be a _breaking change_, since it alters the current behavior. However, you can always write your own delegate builder and tell AutoFixture to use that instead of the built-in one:
> 
> ```cs
> fixture.Customizations.Insert(0, new DelegateWithUniqueReturnValueBuilder());
> ```

You are probably right. This would be a change, even if it feels more like a bug to me. 
As I maintain our company test library for me and my coworkers. I had this topic now a few times, cause noone so far expected to get always the same result.

**Comment by ecampidoglio** [comment]
@Ergamon To give a bit of historical context, the `DelegateGenerator` was one of the early specimen builder in AutoFixture, dating all the way back to 2011 (6b574dd).
If I were to implement it today, I would definitely return a new specimen with each call to the delegate, since that's [what you've come to expect](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) in AutoFixture, as you pointed out.

I'm going to close this issue, since a workaround has been identified. Feel free to reopen, if you'd like to discuss this further.

**Comment by Kralizek** [comment]
Should we tag this issue so that if a new major version was to come, we could take the chance to introduce this breaking change?

**Comment by Ergamon** [comment]
Yes I would love to see this changed in the future, but as said, there might be someone out there relying on this behavior.
