### ISSUE TITLE
Creating multiple regular expression requests in rapid succession yields same result (.NET framework)

### ISSUE THREAD

**Issue by MagnusMikkelsen** [AutoFixture/AutoFixture#1183]
The test below (usually) fails in .NET framework fails in .NET framework, but not in core.

The underlying reason for this is that Xeger is used in autofixture without injecting an object of type Random, and Xeger uses `new Random()` - without injecting a seed.

The test passes, in .NET Core, because `new Random()` internally generates a unique seed.
However, as you probably know, in framework, it uses tick count as seed.

I haven't created a pr, because I didn't know where to do it to - does it make sense to create a pr with a failing test to master?

And I don't know if it should be fixed here in AF, or a pr should be created in the Fare repo.

What do you think? I'd like to fix this - but I'm not sure how to proceed...

```
        [Theory]
        [InlineData(@"^[A-Z]{27}$")]
        public void CreateTwoWithRegularExpressionRequestReturnsDifferentResults(string pattern)
        {
            // Arrange
            var sut = new RegularExpressionGenerator();
            
            var request = new RegularExpressionRequest(pattern);
            var dummyContext = new DelegatingSpecimenContext();
            // Act
            var result1 = sut.Create(request, dummyContext);
            var result2 = sut.Create(request, dummyContext);
            
            // Assert
            Assert.NotEqual(result1, result2);
        }
```

**Comment by moodmosaic** [comment]
Thank you for reporting this. It looks like the issue can be fixed in Fare, as per https://github.com/moodmosaic/Fare/issues/26.

**Comment by MagnusMikkelsen** [comment]
👍

**Comment by moodmosaic** [comment]
Using a [singleton-scoped](https://blog.ploeh.dk/2014/06/03/compile-time-lifetime-matching/) (e.g. `private readonly` or perhaps `private static readonly`) `Random` instance supplied in https://github.com/AutoFixture/AutoFixture/blob/d3e14a818b933d948ea82464b197a5aeb152f070/Src/AutoFixture/RegularExpressionGenerator.cs#L40

as per [this `Xeger` constructor overload](https://github.com/moodmosaic/Fare/blob/703c5e24b9b4e352663f0b4acf8ab832c75cffbc/Src/Fare/Xeger.cs#L42
) should fix the issue.

**Comment by MagnusMikkelsen** [comment]
> Using a [singleton-scoped](https://blog.ploeh.dk/2014/06/03/compile-time-lifetime-matching/) (e.g. `private readonly` or perhaps `private static readonly`) `Random` instance...
> ... should fix the issue.

I think that's what I'm trying to do in #1187 ?
https://github.com/AutoFixture/AutoFixture/blob/02f6b7c69a0d1ceb595d2d550e64558320f4c75f/Src/AutoFixture/RegularExpressionGenerator.cs#L52
