### ISSUE TITLE
Drop .NET Core 1.1 support

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#1195]
Somehow, building AutoFixture on a machine without .NET Core SDK 1.1 installed fails.

Unfortunately I cannot reproduce right now as I installed the needed SDK on my machine while testing some code I was working on.

Considering the .NET Core SDK 1.1 is out-of-life, is it possible to remove this requirement?

I have been looking both the FAKE file and the build.cmd one but I couldn't find any explicit reference to the SDK version.

**Comment by zvirja** [comment]
@aivascu I believe we should drop .NET Core 1.1 support in v5. @aivascu WDYT?

**Comment by aivascu** [comment]
@zvirja yes, I this should go into v5, possibly together with other deprecations

**Comment by Kralizek** [comment]
Please consider that the original issue was with the build system, not only with the supported runtimes.

**Comment by Kralizek** [comment]
Also, I would add to v5 the explicit support to the net5 target framework.

**Comment by aivascu** [comment]
@Kralizek I think it's worth adding it to our backlog, since that's the first issue that's going to be opened once .NET 5 releases, anyway. 🙂 
I'll create an issue for it.

**Comment by jzabroski** [comment]
It shouldn't reference .netcoreapp1.1, it should reference netstandard1.1

Source: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by aivascu** [comment]
@jzabroski you're correct, and currently this is the case for all library projects.
I think @Kralizek  was referring to the unit test projects, that are referencing `netcoreapp1.1` as the runtime target framework, since `netstandard` doesn't have it's own runtime. 

The plan is to drop the `netcoreapp1.1`, in the next version and add target framework support for `net5.0`. 
This will be the priority, once we remove the blockers for `v5`.

**Comment by Kralizek** [comment]
IIRC the problem wasn't even in the test projects but in the build script.

**Comment by aivascu** [comment]
@Kralizek I see. Well that should be fixed in the following days for `v5`, since we're replacing the build script entirely.

**Comment by aivascu** [comment]
Support for .NET Core 1.x and .NET Standard 1.x has been dropped in v5
