### ISSUE TITLE
How to create a pass-through behavior

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#1197]
I'm studying the internals of AutoFixture and right now I'm focusing on behaviors (i.e. `ISpecimenBuilderTransformation`).

I'm trying to create a simple pass-through behavior as a starting point but apparently it's not a simple as returning the incoming request.

```csharp
public class PassThroughBehavior : ISpecimenBuilderTransformation
{
	public ISpecimenBuilderNode Transform(ISpecimenBuilder builder)
	{
		return builder; // this will not work!
	}
}
```

The compiler will raise the following error for the snippet above:
> CS0266 Cannot implicitly convert type 'AutoFixture.Kernel.ISpecimenBuilder' to 'AutoFixture.Kernel.ISpecimenBuilderNode'. An explicit conversion exists (are you missing a cast?)

What's the best course of action?

**Comment by zvirja** [comment]
@Kralizek Just wrap it in `CompositeSpecimenBuilder`:

```c#
public class PassThroughBehavior : ISpecimenBuilderTransformation
{
	public ISpecimenBuilderNode Transform(ISpecimenBuilder builder)
	{
		return new CompositeSpecimenBuilder(builder);
	}
}
```

The returned builder should be able to invoke potentially multiple children, that's why we use `CompositeSpecimenBuilder` here.

**Comment by Kralizek** [comment]
Thanks @zvirja :)
