### ISSUE TITLE
Add .NET 5 support

### ISSUE THREAD

**Issue by aivascu** [AutoFixture/AutoFixture#1201]
Add .NET 5 support for the AutoFixture libraries (once .NET 5 releases)

**Comment by emilwall** [comment]
Will it be possible to use the Build API (.Build().With().Create()) with [Init only setters](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#init-only-setters)? AutoFixture has become less convenient to use for my team since we started using readonly properties in our models so I'm hoping for this. :)

**Comment by aivascu** [comment]
@emilwall that is a good question. I'll let you know that it is absolutely possible this feature will be implemented.
In fact we even have a PR for it already. Believe it or not it was opened back in 2018, and I'm not even joking #1075.
So it's not a question of **if** it would be possible but rather **should** it be possible to use init-only (private) setters, with AutoFixture.
Anyway, given the recent changes in C#, I think we'll have review the original decision on that PR, and see in what form will the init-only setters be supported in AutoFixture.

**Comment by emilwall** [comment]
@aivascu I'm happy to hear that! I think there is an important difference between using the build API with init only setters compared to private setters, in that the init only setters are actually not internal to the class, so this should be more in line with the original creators of the AutoFixture libraries.

Ideally, I think it should be implemented in the existing .With method, not by adding .WithInit or anything like that (I saw in the PR you linked that it adds .WithPrivate). In the end it is of course up to whoever implements this to decide.

**Comment by aivascu** [comment]
@emilwall yeah, not particularly happy with the `.WithPrivate()` choice either. Let's open up a new thread in the [Ideas](https://github.com/AutoFixture/AutoFixture/discussions/categories/ideas) section and continue the discussion there.

**Comment by emilwall** [comment]
@aivascu Ah, I hadn't seen that section! I found a [related thread](https://github.com/AutoFixture/AutoFixture/discussions/1212) that I think is suitable to hijack.

**Comment by MihaMarkic** [comment]
I guess scratch .NET 5 and go for .NET 6 instead.

**Comment by C0DK** [comment]
I'm having issues using the idioms in general in .net 6 and didn't know you don't officially support it yet. :) 

Currently, I get a `Cannot set initonly static field 'specimenBuilder' after type 'ValueType2c3b74b73b9241f083926de1431cc7c9' is initialized.` when utilizing guard clauses on a method that takes a record as input.  (Similar to https://github.com/replaysMike/AnyClone/issues/11)

**Comment by MatiSanchez** [comment]
Hi @aivascu!! 

Any ETA in the release of V5??

**Comment by aivascu** [comment]
@MatiSanchez unfortunately I can't give a solid estimate of v5 being released. It all depends on how much free time I get.
I have been in heavy crunch, for the last couple months, and lately I barely have time to reply to questions on SO.
I'm hoping to get to v5 RC in mid May, if all goes as planned at my workplace. Beyond that I can't really say.

**Comment by aivascu** [comment]
@ecampidoglio I don't mind targeting .NET 6 for v5 however there is an issue with the AppVeyor pipelines. The virtual machine that supports .NET 6 does not support the earlier .NET Core and afair .NET Framework versions which we use to test our support for .NET Standard and .NET Framework. This is one of the main reasons I moved the vnext pipeline to use GitHub Workflows.

Theoretically we could allow the master pipeline to fail for the vnext branch but my perfectionist brain likes everything passing at all times 🙂. Copying the vnext build script into master is also an option but it would be hell to sync the master and the vnext branches afterwards.

I was planning to release v5 and then almost immediately start working on v6 which would drop support for .NET 6 and deprecate more stuff. Obviously this plan didn't go so well as for the last few months I didn't have almost any free time.

Anyway let's discuss which option is the most viable and go with it.

PS: Sorry for late reply. 🙁

**Comment by Kralizek** [comment]
> I was planning to release v5 and then almost immediately start working on v6 which would drop support for .NET 6 and deprecate more stuff. Obviously this plan didn't go so well as for the last few months I didn't have almost any free time.

I guess you mean dropping support for .NET 5?

**Comment by aivascu** [comment]
yes exactly 🙂

**Comment by Danielovich** [comment]
Let's talk about how to approach this, because it seems like a rather larger task.

1. The target frameworks differ somewhat throughout the solution and I am wondering if it's even possible to add another target framework (.net 6) to the list of existing (.net 4.5/4.7/.netstandard etc). I doubt it, but I am not sure ?

2. It seems like a "manual class library porting job" where one creates a new class library targeting .net 6 for each existing library and from there copies code to the new library. Thoughts ?

3. Dependency updates - I haven't looked at the dependencis per se but if any I assume these will also needed updating towards .net 6.

4. Why not target .net 7 while we are at it ?

Any thoughts ?

**Comment by aivascu** [comment]
@Danielovich there are currently some roadblocks regarding the pipeline, support for older frameworks, moving some parts of the repo somewhere else (RhinoMock, xUnit 1, etc), and a big one - my availability.

1. Yes in the current context of the existing vnext branch, it is absolutely possible to maintain support for both older and newest versions of .NET
2. No nothing like that. Just adding another .NET works fine. I tried it with .NET 6 but couldn't jump this many versions at one time due to the pipeline and the outdated code analysis rules.
3. Dependencies will be managed just like they currently are, using target framework conditions.
4. This is a complex question. To put it simply, there would be people that are still on .NET 5,6 or even .NET Framework that wouldn't be able to use the latest fixes/features if I just target .NET 7. That, and some changes that will be required in the internal implementation, CI pipeline.

The high level plan I am working towards is the following:
- Version 5
  - Drop support for .NET Standard 1, .NET Core 1 and 2
  - Migrate to .NET 5 and add related features (`IAsyncEnumerable`, etc)
  - Upgrade CI pipeline (drop AppVeyor switch to GitHub Actions)
  - Upgrade .NET Framework to v4.6.1 (the latest version that does not support .NET Standard and the latest supported by old NuGet versions)
  - Remove Obsolete code
  - Fix InlineDataAttribute and MemberDataAttribute (xUnit 2, NUnit 3)
  - Drop and move to separate repos integrations for xUnit1, RhinoMocks, etc.
  - Drop MyGet feed and move preview versions to NuGet
 - Version 6
   - Drop .NET 5
   - Add .NET 6 and add related features using pragmas (DateOnly, etc)
   - Remove .NET Framework dependencies (leave only .NET Standard 2.0)
   - Add nullable guards (probably after initial v6 release)
 - Version 7
    - Add .NET 7 support (required properties, generic math, etc)

I'm considering just releasing a v5 just with the upgraded references and without the planned features/fixes. The fixes and some features have taken me a lot of time and I'm still not sure about the implementation.

**Comment by aivascu** [comment]
Closing this as most of the .NET 5.0 features have already been implemented.
