### ISSUE TITLE
AutoFixture.AutoFakeItEasy - Latest FakeItEasy Support

### ISSUE THREAD

**Issue by napalm684** [AutoFixture/AutoFixture#1208]
It appears that the latest AutoFixture.AutoFakeItEasy is not able to work with the latest FakeItEasy version. Are there plans to support the latest FakeItEasy?

`warning NU1608: Detected package version outside of dependency constraint: AutoFixture.AutoFakeItEasy 4.14.0 requires FakeItEasy (>= 4.9.0 && < 6.0.0) but version FakeItEasy 6.2.1 was resolved.`

**Comment by aivascu** [comment]
@napalm684 thank you for raising this! 
This major version release has gone under the radar for us it seems.

I just tried to run the tests against FakeItEasy 6 and it seems there are some breaking changes.
Hopefully we'll have a new release soon with support for v6.
