### ISSUE TITLE
Domain names

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#1220]
I have at least three _AutoFixture_-related domain names:

- autofixture.com
- autofixture.net
- autofixture.org

These lapse in about six months. Since I'm no longer involved with AutoFixture and I don't use these domain names for anything, I don't intend to keep them.

I don't think that they are being used for anything at the moment, but they could be set up to point to an AutoFixture landing page.

I'll gladly transfer them to the AutoFixture project.

This most likely involves setting up some entity that will be the 'owner' of these domain names. The way this is usually handled is by having an open-source foundation that takes care of such things on behalf of the project. For AutoFixture, I'd consider it natural to contact the .NET Foundation, but any foundation could serve that purpose.

Let me know, within the next six months, if you'd like me to transfer these domain names. If I don't hear anything, I'll get rid of them.

**Comment by aivascu** [comment]
@ploeh thank you, Mark. It is generous of you to offer these domain names.

I'd like to mention there's also `autofixture.io` which I registered some time ago, hoping to move the documentation/landing page to Azure or some other hosting service. I'll gladly transfer it was well to the AutoFixture project.

I think the .NET Foundation is a good fit considering the size and the role of the project in the community. 
Looking at the [eligibility criteria](https://dotnetfoundation.org/projects/net-foundation-project-committee#eligibility-criteria) of the .NET Foundation, there are some minor things that we'll need to adjust in order for the application process to go as smooth as possible.

@zvirja @moodmosaic @adamchester @ecampidoglio do you have any opinions on this topic?

**Comment by ecampidoglio** [comment]
I, too, think it's time for AutoFixture to join the .NET Foundation. I created [an issue](https://github.com/AutoFixture/AutoFixture/issues/1221) to track the work required to get the project 100% compliant, should we decide to move forward.

**Comment by moodmosaic** [comment]
I agree with what @ecampidoglio wrote about the .NET Foundation. About the domain names, perhaps just one is good enough.

**Comment by ploeh** [comment]
In order to buy time I last year decided to renew the above domain names for another year. They will, however, lapse in 2022.

It costs me money to renew the domain names, but I was happy to do this one time in order to buy you enough time to set all of this up. I do think, however, that 1½ years was time enough, so I don't plan on renewing the domain names again. You should still have about half a year to get this in order.

**Comment by aivascu** [comment]
@ploeh Thank you, for keeping the domain names, all this time. The ".NET Foundation" seem to be taking their time with the onboarding. So far I have not been contacted, about any further steps, by anyone on their side. If it's fine with you, I can take the domain names and pay for them, until the onboarding is completed.

**Comment by ploeh** [comment]
Sure. Do you have any idea how to make the transfer? I've never transferred a domain name before...

**Comment by Kralizek** [comment]
@aivascu if you do the steps necessary for setting up a sponsoring button here on GitHub, I'd gladly donate to help with paying for the domains.

**Comment by aivascu** [comment]
@ploeh I've not done this either. The registrar that I'm using seems to have a streamlined process for this, but I'll need to investigate the topic before we attempt it. In any case, we'll need some coordination while performing the transfer. I suggest moving the discussion to email where we can discuss details. You can contact me at [andrew.ivascu@gmail.com](mailto:andrew.ivascu@gmail.com).

**Comment by aivascu** [comment]
@Kralizek thank you for the offer. Because I live in a third-world country, I don't have access to any of the popular crowd-funding platforms including GitHub's. :disappointed: I'll look for options but I'm not sure if I'll be able to receive any donations.

**Comment by aivascu** [comment]
The domain names have been transferred over to myself for now. We'll discuss with the .NET Foundation representatives if they'll be able to help us with the domain registration and the hosting.

@ploeh thank you for the contribution to the AutoFixture project.
