### ISSUE TITLE
Join the .NET Foundation

### ISSUE THREAD

**Issue by ecampidoglio** [AutoFixture/AutoFixture#1221]
In light of #1220, I think it's time for the AutoFixture project to join the [.NET Foundation](https://dotnetfoundation.org/).

The project already conforms to most of the [eligibility criteria](https://dotnetfoundation.org/projects/net-foundation-project-committee#eligibility-criteria), so it shouldn't take that much work to get us all the way there. From what I can gather, here's the list of requirements that are still outstanding:

### Code

- [x] The project uses [Source Link](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink).
- [x] The project uses either embedded PDBs or publish symbol packages to NuGet (if applicable).

### Quality

- [x] The project has a published Security Policy.

### Community

- [x] The project has a home page which provides high level information about its status and purpose<sup>1</sup>.

---

1. We technically do have [a website](https://autofixture.github.io/#), but it needs work.

**Comment by ecampidoglio** [comment]
@AutoFixture/core Is everyone OK with joining the .NET Foundation? If yes, I'll be happy to get the process going.

**Comment by ecampidoglio** [comment]
@zvirja Are you OK with AutoFixture joining the .NET Foundation?

**Comment by zvirja** [comment]
Thanks for asking, I'm OK

**Comment by ecampidoglio** [comment]
@AutoFixture/core As part of the [onboarding process](https://github.com/dotnet-foundation/projects/blob/master/new-projects.md), I need to submit the names and email addresses of the [project's members](https://github.com/dotnet-foundation/projects/blob/master/new-projects.md#signing-the-cla). Please, let me know whether you'd like to be included and, if so, your email address. You can email me at enrico@megakemp.com. Thanks!

**Comment by aivascu** [comment]
@ecampidoglio are there any updates on joining the .NET Foundation?

**Comment by ecampidoglio** [comment]
@aivascu There are a couple of things to work out. I've sent you an email.

**Comment by ecampidoglio** [comment]
I've submitted AutoFixture to the .NET Foundation. You can track the onboarding process at dotnet-foundation/projects#178

**Comment by harleydk** [comment]
> I've submitted AutoFixture to the .NET Foundation. You can track the onboarding process at [dotnet-foundation/projects#178](https://github.com/dotnet-foundation/projects/issues/178)

It seems the foundation has closed their onboarding process, wherefore this issue can likely be marked as closed.
