### ISSUE TITLE
AutoFixture.ObjectCreationExceptionWithPath When ILogger<T> is needed

### ISSUE THREAD

**Issue by r3dr4gon** [AutoFixture/AutoFixture#1238]
Might not be the right place for it as it is not a bug per se, but when using [Theory, AutoData] attributes, it is not clear how to handle this error (the error info only give info on how to fix it without the attributes, i.e. in a simple case).

This is my case:
![image](https://user-images.githubusercontent.com/14729972/109853586-54ff9600-7c56-11eb-9882-376b78902883.png)

sutController needs serviceMock and ILogger<T> in order to build (ctor).
However, it seems he does not know how to build ILogger (though as it is a pretty common thing, I would have expected it to just be mocked I guess).
Anyway, the error I get is:
```
    AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance from Microsoft.Extensions.Logging.ILogger`1[PatientIndicatorResultController] because it's an interface. There's no single, most appropriate way to create an object implementing the interface, but you can help AutoFixture figure it out.
    
    If you have a concrete class implementing the interface, you can map the interface to that class:
    
    fixture.Customizations.Add(
        new TypeRelay(
            typeof(Microsoft.Extensions.Logging.ILogger`1[PatientIndicatorResultController]),
            typeof(YourConcreteImplementation)));
    
    Alternatively, you can turn AutoFixture into an Auto-Mocking Container using your favourite dynamic mocking library, such as Moq, FakeItEasy, NSubstitute, and others. As an example, to use Moq, you can customize AutoFixture like this:
    
    fixture.Customize(new AutoMoqCustomization());
    
    See http://blog.ploeh.dk/2010/08/19/AutoFixtureasanauto-mockingcontainer for more details.
```

this being said, as I use the attributes, I have no access to the fixture var.
Is there any way to go around it? or should I just drop the attributes?

**Comment by Kralizek** [comment]
I suggest you create your custom implementation of AutoData and add automoq to it

**Comment by aivascu** [comment]
@r3dr4gon in order for AutoFixture to know how to properly inject the mock into your SUT, you need to add the appropriate customization, via the AutoData attribute.
There is a detailed walkthrough on how do that in the [Quick-start article](https://autofixture.github.io/docs/quick-start/#).

**Comment by r3dr4gon** [comment]
Hey @aivascu thanks for the reference, I actually saw this but did not see that it created another error which was solved by using [greedy].

Thanks for the help
