### ISSUE TITLE
AutoFixture.AutoNSubstitute: System.InvalidCastException when mocking a class with type parameters

### ISSUE THREAD

**Issue by crhistianramirez** [AutoFixture/AutoFixture#1241]
There is a class in a library I'm using that looks like this:

```csharp
public class Order<TContact> : Order where TContact : Contact
{
    // ...other properties
    public TContact Contact { get; set; }
}
```

This allows a user of that library to define an order with their own `Contact `  class that may have additional properties so long as it extends the base `Contact ` model. For example:

```csharp

public class MyOrder: Order<MyContact>
{}

public class MyContact Contact
{
    public string MyProperty { get; set; }
}

var order = new MyOrder();
var myProperty = order.Contacts.MyProperty; // sweet!
```

However if I try to use auto mocking to get an instance of `MyOrder` I get 
> System.InvalidCastException : Unable to cast object of type 'Library.Models.Contact' to type 'MyApp.Models.MyContact'.

Is there anything I can do so that automocking works as expected and retrieves a member of type MyContact?

**Comment by aivascu** [comment]
Hello @crhistianramirez ,

So far the information you've provided is a bit vague.
Could you provide a minimum reproducible example, with a list of packages you're using (including  versions)?

Also please use the [Q&A Discussions](https://github.com/AutoFixture/AutoFixture/discussions/categories/q-a) section for questions.

Moving question to discussions.
