### ISSUE TITLE
Unable to create nested records

### ISSUE THREAD

**Issue by jamesfoster** [AutoFixture/AutoFixture#1244]
Version: 4.15.0
Runtime: .NET Core 3.1
Language: C# 9.0

Hi,

I've noticed an issue using AutoFixture to create a nested structure of records. The following test fails:

```csharp
        public record ParentRecord(string Name, NestedRecord NestedRecord);
        public record NestedRecord(string Description);

        [Fact]
        public void AutoFixture_can_create_nested_records()
        {
            var fixture = new Fixture();

            fixture.Create<ParentRecord>();
        }
```

The exception is:

```
AutoFixture.ObjectCreationExceptionWithPath: AutoFixture was unable to create an instance from 
ConsoleApp1+ParentRecord because creation unexpectedly failed with exception. Please refer to the 
inner exception to investigate the root cause of the failure.

Request path:
	ConsoleApp1+ParentRecord

Inner exception messages:
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	  System.InvalidProgramException: Common Language Runtime detected an invalid program.


   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in /_/src/AutoFixture/Kernel/TerminatingWithPathSpecimenBuilder.cs:line 81
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in /_/src/AutoFixture/BehaviorRoot.cs:line 73
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in /_/src/AutoFixture/Kernel/RecursionGuard.cs:line 176
   [... truncated]
```

I'd be interested to know if there's a way to workaround this issue.

**Comment by Ergamon** [comment]
There must be something missing. I copied your code and the test is green. No exception thrown.

What I did:
1. Made a new .NET Core 3.1 class library
2. Added LangVersion latest to csproj to get C# 9 support
3. Added IsExternalInit class to the project for record support
4. Added NuGet packages AutoFixture,xunit,xunit.runner.visualstudio and Microsoft.NET.Test.Sdk
5. Changed Class1 by adding your code
6. Ran test => green

**Comment by jamesfoster** [comment]
Interesting. I will try to reproduce this from scratch and get back to you. FYI it is fine creating a `record` which doesn't have nested record properties.

The fact that the error indicates `Common Language Runtime detected an invalid program.` seems to suggest it maybe emitting invalid byte code?
