### ISSUE TITLE
Documentation is broken (all pages except Creation)

### ISSUE THREAD

**Issue by MoonCoder14** [AutoFixture/AutoFixture#1272]
All pages under https://autofixture.github.io/docs, except https://autofixture.github.io/docs/fixture-creation/ are empty (at least in Chrome and Edge).

For example: https://autofixture.github.io/docs/fixture-customization-overview/

**Comment by aivascu** [comment]
@MoonCoder14 thank you raising this. Simply put articles you mentioned are not written yet.
Though not yet officially announced, we are working on a new website that will also feature auto generated API reference for both AutoFixture and SemanticComparison.
Articles on AutoFixture basics, like aninymous values, customizations and some glue library features will be published across the next couple weeks.
I will make sure to cross publish articles as they become available. 
The preview version of the new site is located at [AutoFixture.io](https://autofixure.io).

**Comment by MoonCoder14** [comment]
Ok thanks for the info!

Op za 29 mei 2021 12:54 schreef Andrei Ivascu ***@***.***>:
