### ISSUE TITLE
does generated GUID include empty guid?

### ISSUE THREAD

**Issue by satuday** [AutoFixture/AutoFixture#1278]
Hi does generated GUID from autofixture include empty guid(00000000-0000-0000-0000-000000000000)?

**Comment by aivascu** [comment]
@satuday the `GuidGenerator` uses `Guid.NewGuid()`  (see [implementation](https://github.com/AutoFixture/AutoFixture/blob/730b47884975d0c1256209073a719a9fe510d8a9/Src/AutoFixture/GuidGenerator.cs#L17)) which is [guaranteed](https://docs.microsoft.com/en-us/dotnet/api/system.guid.newguid?view=net-5.0#remarks) to never return an empty `Guid`.
