### ISSUE TITLE
✨ Add support for `IAsyncEnumerable<>`

### ISSUE THREAD

**Issue by aivascu** [AutoFixture/AutoFixture#1325]
### Description

Add support for `IAsyncEnumerable<>`, for target framework netstandard2.1 or greater.

### Example

N/A

### Tasks

- [x] Confirmed feature idea with maintainers in support forums

### More Information

Feature discussed in #1233 and #1322

Thanks!

**Comment by Kralizek** [comment]
@aivascu I will rebase #1326 onto v5 once this is merged.

**Comment by aivascu** [comment]
Implemented in #1323
