### ISSUE TITLE
🐛 Property value not set

### ISSUE THREAD

**Issue by satishviswanathan** [AutoFixture/AutoFixture#1332]
### Describe the Bug
In my domain model I have a virtual property with protected set. I'm using the fixture to create an object of my domain model and it seems like the properties with protected set are not being set with values.

### Scenario

```cs
public class Employee
{
    public virtual string FirstName { get; set; }
    public virtual string LastName { get ; protected set ;  }
}

var emp = fixture.Create<Employee>();
```

### Expected Behavior

Both properties should be have the values set.

**Comment by aivascu** [comment]
@satishviswanathan this is exactly why the bug report template has a tasks section, and why **you shouldn't remove it**.
![image](https://user-images.githubusercontent.com/7030530/155393866-b91b07bf-45fb-4cc0-9186-b192194837b4.png)

This is how the object creation is supposed to work. AutoFixture does **not** work with non-public accessors.
You can either customize it to be created as a mock or delegate the creation to a test double that implements a public setter for that property.

Next time post a question in the support forums or on SO.
