### ISSUE TITLE
Support for yourself my dude✨ 

### ISSUE THREAD

**Issue by JVenereal** [AutoFixture/AutoFixture#1342]
### Description
Take a vaction. Your framework is fucking phenomenal

**Comment by aivascu** [comment]
@JVenereal thank you very much for the kind words!

I assume this is in response to my earlier comment on crunching at work. I did indeed need a vacation, as I was getting frustrated and angry, even in my replies to AutoFixture questions and bug reports, which I now regret. I thank @Kralizek for calling me out on those.

I did actually have a small vacation last week, to recover and spend time with my family. Also I set things up at my workplace to normalize my work schedule. I don't expect the result to be immediate, but I should get more free time in the coming weeks and as a result more time to spend on AutoFixture.
