### ISSUE TITLE
Support for IReadOnlySet✨ 

### ISSUE THREAD

**Issue by oniony** [AutoFixture/AutoFixture#1343]
### Description

Most of the `IReadOnlyXXX` standard library types are supported out-of-the-box, but `System.Collections.Generic.IReadOnlySet` is not. Would it be possible to please add this?

### Tasks

- [ ] Add support for `System.Collections.Generic.IReadOnlySet`.
- [ ] Add test-case coverage

### More Information

See [this similar, earlier, request  for `IReadOnlyList` support](https://github.com/AutoFixture/AutoFixture/issues/924).

Thanks!

**Comment by Kralizek** [comment]
@oniony do you want to try implement this? It's literally 1 line of code and 2/3 tests

**Comment by oniony** [comment]
I'm working away from home in a company that won't allow me to push to GitHub. I might be able to take a look when I'm back home in a few days.

**Comment by Romfos2** [comment]
@Kralizek could you please provide some example? I'm interested in System.Collections.Immutable support

**Comment by Kralizek** [comment]
@Romfos2 @oniony you can look at this PR https://github.com/AutoFixture/AutoFixture/pull/941

**Comment by oniony** [comment]
Had a quick look at implementing this but it turns out [`IReadOnlySet`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlyset-1?view=net-6.0) was introduced in .NET 5, so cannot be supported by AutoFixture at this time.

**Comment by Kralizek** [comment]
@oniony if you base your PR off the V5 branch, you can then use the compiler preprocessor to enable this behaviour.

Anyway, better tag @aivascu :)

**Comment by aivascu** [comment]
Yep not much else to say. It'll have to go in the v5 version or later as it's not supported by any of the currently supported .NET versions, and it'll have to be guarded by preprocessor directives as none of the BCL libraries implement it.
I will not be working on this at the moment, as there are other higher priority features/bugs, however if someone would raise a PR on this, I'd gladly consider it for merging.

**Comment by Kralizek** [comment]
For whoever will work on this PR, use the `NET5_0_OR_GREATER` compiler variable

**Comment by aivascu** [comment]
@Kralizek leave some issues for the new contributors )

**Comment by aivascu** [comment]
Closed in #1346
