### ISSUE TITLE
🐛 AutoFixture AutoMoqCustomization not working when building unit test on devOps git Build pipeline

### ISSUE THREAD

**Issue by Skm5900** [AutoFixture/AutoFixture#1370]
Hi Team,
We have a project with unit test . In unit test we are using Moq functionality

protected IFixture _fixture;

_fixture=new Fixture().Customize(New AutoMoqCustomization())   this line is not building
 this is little bit legacy code and was building on local with ref of 
using Ploeh.AutoFixture
using Ploeh.AutoFixture.AutoMoq

but we found above dll are  obselete now so we added ref of 
using AutoFixture

but  its not working  to execute _fixture=new Fixture().Customize(New AutoMoqCustomization())   line of code 
Any suggestion.

**Comment by GeraldLx** [comment]
Can you provide a sample with the problem?

**Comment by Skm5900** [comment]
Hi, 
I was working further, and found in cs.proj file assembly information was not updated, not sure but it did not updated csproj fileautomatically when added the nuget for moq new version. So i manually updated the cs.proj file and its worked.

Thanks

**Comment by Skm5900** [comment]
Closing this thread with above solution.
