### ISSUE TITLE
🐛AutoMoq incompatible with Moq > 4.8.0

### ISSUE THREAD

**Issue by Xynratron** [AutoFixture/AutoFixture#1386]
### Describe the Bug
With Version 4.8.0 of Moq, AutoFixture reports errors in object creation. Version 4.7.145 and lower work as expected. 

### Scenario
If you switch between the two Moq versions, we can reproduce the error:
```
 public class AutoFixtureMoqTest
    {
        public class MyCustomization : ICustomization
        {
            public void Customize(IFixture fixture)
            {
                fixture.Customize<Mock<IFace1>>(d => d.Do(m => m.Setup(o => o.GetData()).ReturnsUsingFixture(fixture)));
                fixture.Customize<Mock<IFace2>>(d => d.Do(m => m.Setup(o => o.GetData()).ReturnsUsingFixture(fixture)));
                fixture.Customize<Mock<IFace3>>(d => d.Do(m => m.Setup(o => o.GetData()).ReturnsUsingFixture(fixture)));
            }
        }

        public interface IFace1
        {
            string GetData();
        }
        public interface IFace2
        {
            string GetData();
        }
        public interface IFace3
        {
            string GetData();
        }

        public class TestSut
        {
            private readonly IFace1 _face1;
            private readonly IFace2 _face2;
            private readonly IFace3 _face3;

            public TestSut(IFace1 face1, IFace2 face2, IFace3 face3)
            {
                _face1 = face1;
                _face2 = face2;
                _face3 = face3;
            }
        }

        [Fact]
        public void TestWithoutAttribute()
        {
            var fixture = new Fixture();
            fixture.Customize(new MyCustomization());
            fixture.Customize(new AutoMoqCustomization());
            fixture.Create<TestSut>();
        }
    }
```

### Expected Behavior
Should work like in before.

### Tasks

- [ ] Updated all AutoFixture and related libraries
- [ ] Confirmed in support forums if behavior is expected

### More Information
I debug this at the moment, but I haven't found the root cause. Is there a built in mechanism to plot the creation graph? How do you debug errors like this?

The Mock get created successfully in ConstructorMethod.Invoke(IEnumerable<object> parameters) in both cases. 

Since my time is a bit limited, has any other this problem? I came across it, cause another library needs a higher Moq Version.

Thanks!

**Comment by Ergamon** [comment]
Sadly this is not really a bug, this is the way AutoFixture is designed. You were just lucky that your code works with older versions.

If I could change one thing in AutoFixture it is this. Everyone starting with AutoFixture assumes that customizations stack. And I wish this would be the case. But customizations start everytime from scratch.

So your problem is, that you use the Customize method of AutoFixture. By doing that, you overwrite the AutoMoqCustomization. So the part of 
```
fixture.Customize(new AutoMoqCustomization());
```
is completly irrelevant to your sample. You can delete it and nothing will change..

If you understand this, you also have to know that AutoFixture populates every writeable property.

So your problem can be shortened to:
```
public interface IFace
{
}

var fixture = new Fixture();
fixture.Customize<Mock<IFace>>(c => c);
var mocks = fixture.CreateMany<Mock<IFace>>(3);
```

You will notice that CreateMany with a value of 2 will work, but a value of 3 will fail.

The reason is that Mock<T> has a property of DefaultValue with an enum. Enums rotate in AutoFixture. So your code starts with the first value, then the second and so on.

So (among other things) the code does basically this:
```
var mock1 = new Mock<IFace>
{
  DefaultValue = DefaultValue.Mock,
};

var mock2 = new Mock<IFace>
{
  DefaultValue = DefaultValue.Empty,
};

var mock3 = new Mock<IFace>
{
  DefaultValue = DefaultValue.Custom,
};
```

And setting the DefaultValue to Custom makes Moq throw an exception.

In 4.7 and earlier Custom did not exist, therefore it works.

How could you get out of this?

Either ping DefaultValue
```
var fixture = new Fixture();
fixture.Customize<Mock<IFace>>(c => c);
fixture.Inject(DefaultValue.Mock);
var mocks = fixture.CreateMany<Mock<IFace>>(3);
```
or omit it in your customization:
```
var fixture = new Fixture();
fixture.Customize<Mock<IFace>>(c => c.Without(m => m.DefaultValue));
var mocks = fixture.CreateMany<Mock<IFace>>(3);
```

Personally I use NSubstitute so I have not to much insight of Moq, probably it is the best to ignore all properties:
```
var fixture = new Fixture();
fixture.Customize<Mock<IFace>>(c => c.OmitAutoProperties());
var mocks = fixture.CreateMany<Mock<IFace>>(3);
```

With any of the 3 changes your code should work. As written, personally I would go for #3.

**Comment by aivascu** [comment]
Hi @Xynratron,
As @Ergamon mentioned this is not a bug and the fact it worked with versions of Moq prior to v4.8 is purely accidental. The Customize method was not intended to be used to setup mocks.

From what I remember all the members of the `Mock` type required by AutoFixture are set explicitly so omitting all members should indeed work fine.

For now you can use the customization from below to customize the behavior for all `Mock` types. I'll need to investigate further whether it is safe/useful for it to be added to `AutoMoqCustomization`.

```cs
public class MockMemberOmitter : ICustomization
{
    public void Customize(IFixture fixture)
    {
        fixture.Customizations.Add(new Omitter(
            new OrRequestSpecification(
                new DeclaringTypeSpecification(typeof(Mock<>)),
                new DeclaringTypeSpecification(typeof(Mock)))));
    }
}

public class DeclaringTypeSpecification : IRequestSpecification
{
    public DeclaringTypeSpecification(Type declaringType)
    {
        this.DeclaringType = declaringType;
    }

    public Type DeclaringType { get; set; }

    public bool IsSatisfiedBy(object request)
    {
        return request is MemberInfo propertyInfo
            && propertyInfo.DeclaringType == this.DeclaringType;
    }
}
```

**Comment by Xynratron** [comment]
@aivascu @Ergamon you are incredible.

First, thanks for saving me time, I thought about the change of "DefaultValue" in moq, but I wanted to track that down and maybe provide a PR.
That is my fault, because of the low code frequency in AutoFixture I thought, it is maybe a problem no one cares any more about. Addinonally, there was a very old Question with "does not work" - and the answer was: "use Automoq" - Problem was in my opinion identical, 2 Mocks work, 3 not. Maybe I did not read and understood, that this are only the properties, AutoFixture tried to fill. And yes, in that case, you do not want the properties filled with some random behavior.

But: I had the time to debug some code and got insight into AutoFixture. I have to say, I miss some things, I would adjust code to be more "modern". To be Fair: not the creation of objects is the nice thing, to declare types as parameters in the test function an have complete objects (with data) is the benefit.
So, is this project a bit alive? Is it worth to refactor and create PR's?

nevertheless,  @Ergamon I understood the problem, @aivascu it was an eye opener (and a bit of shame for me ^^)

Thanks very much.

**Comment by Xynratron** [comment]
I forgot to ask: how you tracked this so fast? Knowledge of the framework and knowing "Ahh, as usual, that is a enum"?

**Comment by aivascu** [comment]
> I forgot to ask: how you tracked this so fast? Knowledge of the framework and knowing "Ahh, as usual, that is a enum"?

When you debug the test that you provided, inside the AutoMoq test project, the exception is caught inside `TerminatingWithPathSpecimenBuilder`. There you can see the line inside Moq where the exception was thrown.

![image](https://user-images.githubusercontent.com/7030530/224144648-c3b7a879-a7aa-4b44-8183-4a714fe63358.png)

> So, is this project a bit alive? Is it worth to refactor and create PR's?

Yes, it is alive though the code frequency lately was indeed low, for which I take responsibility. The project is in between major version at the moment, so community PRs will not likely be accepted, but soon the release pipeline should get unstuck and community PRs will be welcome.
