### ISSUE TITLE
🐛 Fixture.CreateMany sometimes creates a few bool fields all with false values

### ISSUE THREAD

**Issue by TrueGandalf** [AutoFixture/AutoFixture#1396]
So we create a few objects with Fixture.CreateMany(), filter them by bool field and other fields (that we change to success values always after we created that list with createMany), and we check the list by Assert.Empty(ourFilteredCollection).

In Visual Studio all works fine and I always see three objects each sequential object with an opposite boolean field to the previous. Like:
1 object someBoolField = true
2 object someBoolField = false
3 object someBoolField = true
so when we filter this list by someBoolField we always get a not empty list and the test works fine (I've checked it both manually and with run test until fail VS button).

But when the test is running in CICD during a merge, it fails sometimes.
I believe that the behavior of  Fixture.CreateMany() works differently there.
Is it possible? Did anyone experience it before?

**Comment by Kralizek** [comment]
Unless otherwise configured, AF alternates true and false values when generating boolean properties (it does something similar with enums too).

If that property needs to be either true or false, it's better if you explicitly configure it to be so.

**Comment by TrueGandalf** [comment]
Thanks, you are totally right about explicitly configuring a property. But if something works differently on your local pc and in the dev environment it is a but, am I right?

**Comment by aivascu** [comment]
Seems the question was answered. Closing the issue.
