### ISSUE TITLE
🐛 Unexpected ObjectCreationExceptionWithPath or if not a bug at least a confusing description

### ISSUE THREAD

**Issue by jafaber** [AutoFixture/AutoFixture#1411]
### Describe the Bug
ObjectCreationExceptionWithPath, which shows all the correct types and the correct range, but then suggests "it has no public constructor, is an abstract or non-public type", all of which are not true.

I tried adding various customizations, but nothing helped.

```csharp
exception of type 'AutoFixture.ObjectCreationExceptionWithPath' occurred in AutoFixture.dll
AutoFixture was unable to create an instance from RangedRequest (MemberType: Quantity, OperandType: System.Double Minimum: [Double] 0, Maximum: [Double] 1000), most likely because it has no public constructor, is an abstract or non-public type.

Request path:
	Blah
	  Quantity Limit
	    RangedRequest (MemberType: Quantity, OperandType: System.Double Minimum: [Double] 0, Maximum: [Double] 1000)
```

### Scenario

Simple console app:

```csharp
using AutoFixture;
using System.ComponentModel.DataAnnotations;

Fixture fixture = new();
var blah = fixture.Create<Blah>();

public class Blah
{
    [Range(0.0, 1000.0)]
    public Quantity Limit { get; set; }
}

public class Quantity
{
    private double _value;

    public Quantity(double x)
    {
        _value = x;
    }
}
```

### Expected Behavior
Maybe I'm misunderstanding, but I was expecting that adding a `[Range(0.0, 1000.0)]` attribute to my property would be automatically picked up by AutoFixture to generate a number within that range.

At the very least the exception description is confusing as none of the suggestions match my case.

**Comment by jafaber** [comment]
Thank you for the quick reply and apologies for calling it a bug.

I still think the exception message is a bit confusing though:

`(MemberType: Quantity, OperandType: System.Double Minimum: [Double] 0, Maximum: [Double] 1000), most likely because it has no public constructor, is an abstract or non-public type`

It mentions the correct type (Quantity) which actually does have a public constructor and is not an abstract type nor a non-public type.

Anyway, I'll give things some more thought to come up with an alternative for my situation.

**Comment by aivascu** [comment]
There is a different issue opened discussing the fact that AF throws when it encounters an unsupported type decorated with a data annotations attribute. That one will be fixed soon, but I cannot make it assume how to apply data annotations to custom types.
