### ISSUE TITLE
✨ Support for NUnit 4 

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#1418]
### Description
NUnit 4 has just been released. This issue is just to make sure that we are aware of it.

### Tasks

- [ ] Create NUnit 4 glue library

### More Information
https://docs.nunit.org/articles/nunit/release-notes/framework.html#nunit-400---november-26-2023

Thanks!

**Comment by aivascu** [comment]
Yeah.. I know. Never thought new versions of .NET and my favorite libraries would bring me such dread. 😅
xUnit 3 should be arriving soon as well.

**Comment by Kralizek** [comment]
sorry to hear mate. I scanned a bit the changelog and there shouldn't be any change affecting auto data.

**Comment by aivascu** [comment]
@Kralizek it only supports .NET 6 and .NET Framework 4.6.2 😶
![giphy](https://github.com/AutoFixture/AutoFixture/assets/7030530/84ed5bfc-8eb2-4e31-887f-a593a02e4fa7)

**Comment by Kralizek** [comment]
Yup, I read it too. Is that an issue?

**Comment by aivascu** [comment]
Don't think so, but that means it will have to be moved to v6.

**Comment by Rasmus715** [comment]
Bump!

**Comment by saan800** [comment]
+1
Not supporting nunit 4 is starting to become problematic for my company.

**Comment by BlackGad** [comment]
Same. Need NUnit 4 support :) If there are no issues with the 4 NUnit for the current version - you could just copy paste and add another dependencies

**Comment by aivascu** [comment]
The issue so far wasn't the compatibility of the code but the target frameworks supported by NUnit 4.
The .NET 6+ support for planned for the v6 release.
I'm considering at the moment adding all the newer .NETs 5-8 in the next release.
There will be a lot of preprocessor directives anyway, so I might as well bite the bullet.

**Comment by ArkadiuszHnat** [comment]
When do you plan releasing v6?

**Comment by ladenedge** [comment]
The current preview releases don't help, in case anyone is thinking of trying those.

![image](https://github.com/AutoFixture/AutoFixture/assets/2699775/a2740127-5647-4b8e-88c3-c3480d55fc5e)

Good luck with the new release!

**Comment by rcdailey** [comment]
@aivascu Doesn't seem to be working for me:

> [NU1608] Detected package version outside of dependency constraint: AutoFixture.NUnit3 5.0.0-preview0011 requires NUnit (>= 3.7.0 && < 4.0.0) but version NUnit 4.1.0 was resolved.

**Comment by saan800** [comment]
Could we reopen this issue, and only close it once its out of preview?
My company can't use preview packages, but I want to know when this is released to actual v5

**Comment by stevenaw** [comment]
@saan800 You should be able to subscribe for notifications of new releases from the home page of the repo by clicking `Watch` -> `Custom` -> `Releases` .

@aivascu I also wanted to chime in here to say thanks for all the effort here in this and related PRs to add more runtime targets and, of course, NUnit 4 support itself.

**Comment by aivascu** [comment]
@saan800 I'm using the issue states to check how close the project is to a milestone, in this case [v5](https://github.com/AutoFixture/AutoFixture/milestone/5).
As mentioned there are other ways to be notified of when a release is out. I doubt you'll miss the v5 release since your IDE will likely tell there's an update.

@stevenaw thank you, I appreciate that.

I've taken a few days off, to work on AutoFixture, next week. I appreciate that not everyone can use preview versions, so I'm trying to make time in order to complete this release.

**Comment by muratguneydev** [comment]
Hello @aivascu, is there any progress on the stable version? By the way, we really appreciate your time and effort on this.

**Comment by aivascu** [comment]
@muratguneydev yes, last month I've been able to set some time aside and the testing of the NUnit attributes rewrite is almost done, but I've been working OT since then, and didn't have time to finish it. I should have more time this month. I believe we should have a RC by end of June.

**Comment by sensslen** [comment]
> @muratguneydev yes, last month I've been able to set some time aside and the testing of the NUnit attributes rewrite is almost done, but I've been working OT since then, and didn't have time to finish it. I should have more time this month. I believe we should have a RC by end of June.

Again I'm wondering about the release date. Do you have an estimate?
