### ISSUE TITLE
✨ Accept `ISpecimentBuilder` as value generator for `With`

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#1421]
### Description
I have to work with a class with a string property whose valid value is limited to few option (a missed `enum`).

I can use `ElementsBuilder<string>` to do so but the configuration is a bit cumbersome.

It would be great if `With` accepted `ISpecimenBuilder` directly.

### Example

```csharp
fixture.Customize<SomeProduct>(o => o
    .With(p => p.OperatingSystem, (IFixture f) => f.Build<string>().FromFactory(new ElementsBuilder<string>(new[]{"ios", "windows", "mac"})).Create())
);
```

could be written as

```csharp

// IPostprocessComposer<T> With<TProperty, TInput>(Expression<Func<T, TProperty>> propertyPicker, ISpecimenBuilder valueFactory);
fixture.Customize<SomeProduct>(o => o
    .With(p => p.OperatingSystem, new ElementsBuilder<string>(new[]{"ios", "windows", "mac"}))
);
```

**Comment by aivascu** [comment]
Implemented in #1444. Available after AutoFixture v5.0.0-preview009
