### ISSUE TITLE
🐛 SourceLink doesn't work because of incorrect casing in GitHub URLs

### ISSUE THREAD

**Issue by kimsey0** [AutoFixture/AutoFixture#1450]
### Describe the Bug
AutoFixture implements SourceLink (#770), which allows stepping through the actual AutoFixture source code when debugging issues with the library in a consumer project. It does this by adding GitHub URLs for the source files into the debugging symbols (.pdb), which editors and other debugging tools then use to fetch and display the source code. However, there seems to be a problem with the setup that causes the URLs to reference an incorrectly cased `src` folder, instead of the correctly cased `Src` folder. GitHub URLs are case sensitive, so this means the sources won't load.

### Example
As an example, this is the SourceLink URL currently included for the Fixture class: https://raw.githubusercontent.com/AutoFixture/AutoFixture/fd842903f3da074080191e23f5dd3db6b7a58156/src/AutoFixture/Fixture.cs
And this is the correctly cased URL: https://raw.githubusercontent.com/AutoFixture/AutoFixture/fd842903f3da074080191e23f5dd3db6b7a58156/Src/AutoFixture/Fixture.cs

### Possible fixes
I'm unsure exactly what causes this problem. The build seems to run on a Windows agent, where paths are normally case insensitive, but other paths of the URL (for example the AutoFixture directory in the path above) are correct. I can see one lowercased reference to the `src` directory which is used when calling MSBuild, so maybe that's it?

https://github.com/AutoFixture/AutoFixture/blob/885fd4ad6b7ff10c73cfdfe07aec886300489cdd/Build.fsx#L37

### Verifying a fix
Once a fix has been deployed, it can be verified either through the Go to Implementation feature in an IDE like Visual Studio or Rider, or using [this SourceLink testing tool](https://github.com/ctaggart/SourceLink) like `sourcelink test -f "lib/netstandard2.0/AutoFixture.pdb" .\autofixture.4.18.1.nupkg`.

### Additional info
[Starting with .NET 8](https://github.com/dotnet/sourcelink/?tab=readme-ov-file#using-source-link-in-net-projects), SourceLink (including GitHub support) is included in the .NET SDK and enabled by default, so if you change to the Visual Studio 2022 AppVeyor image, it may be possible to remove all references to SourceLink from the code.

**Comment by aivascu** [comment]
@kimsey0 thank you for raising this, however this is unlikely to be fixed in the current major version, due to target framework limitations. I'll check if the Source Link works fine in the latest v5 preview build.
If it does then I'll close this issue as no new v4 releases are currently planned.

**Comment by kimsey0** [comment]
@aivascu, this isn't related to the target framework. I'm sorry if the _Additional info_ section was confusing. This can hopefully be fixed without any .NET SDK changes.

Can we try changing the casing of `sourcesDirPath` in the build script to see if that embeds the right SourceLink path.

**Comment by aivascu** [comment]
@kimsey0 I know. ) I meant that currently, the AppVeyor pipeline doesn't work at all because the VS 2019 image version dropped support for .NET Core 1, 2, and 3. These targets are used in v4, and I can not drop them in this major version.
The v5 branch uses a Nuke the build system.

**Comment by aivascu** [comment]
@kimsey0 I know. ) I meant that currently, the AppVeyor pipeline doesn't work at all because the VS 2019 image version dropped support for .NET Core 1, 2, and 3. These targets are used in v4, and I can not drop them in this major version.
The v5 branch uses a Nuke the build system. So, the Bulild.fsx doesn't even exist.

**Comment by kimsey0** [comment]
Ah! I understand now. This does seem to be fixed in the 5.0 preview packages. Thanks!
