### ISSUE TITLE
🚨 Vulnerability in packages System.Net.Http and System.Text.RegularExpressions

### ISSUE THREAD

**Issue by moslem-hadi** [AutoFixture/AutoFixture#1451]
Hello,
These packages used by AutoFixture.Xunit2, are venerable and deprecated:

- [System.Net.Http 4.3.0 ](https://www.nuget.org/packages/System.Net.Http/4.3.0)
- [System.Text.RegularExpressions 4.3.0 ](https://www.nuget.org/packages/System.Text.RegularExpressions/4.3.0)

Should upgrade to higher versions.

Thanks!

**Comment by Kralizek** [comment]
Hi, a short term fix is to explicitly pin the latest non-breaking release of each library.

```csproj
<ItemGroup>
  <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  <PackageReference Include="System.Net.Http" Version="4.3.4" />
</ItemGroup>
```

This should help mitigate the issue until the next version is released.

**Comment by bjowes** [comment]
I can also recommend installing the latest prerelease of AutoFixture, where the dependencies have been updated.

**Comment by aivascu** [comment]
duplicate of #1356
