### ISSUE TITLE
make AutoFixture static

### ISSUE THREAD

**Issue by Accc99** [AutoFixture/AutoFixture#160]
[This is an enhancement request]

It would be cool if we could write

Fixture.Create<Foo>();

instead of instantiating a Fixture
var fixture = new Fixture();
fixture.Create<Foo>();

In your presentation at NDC of autofixture, you said that you hate declaring variable in constructor of a test class in order to use it in every test method. You said it's clearer to see everything inside one method. I followed your idea because I think it's a good idea, but the problem is that I'm currently instantiating a new Fixture in each method and I'm not really fan, I would prefer to call Fixture.Create<Foo>();

What do you think ?

Yeah I know, I could use the declarative way, but I'm not a big fan, because I'll have to create a new class which implement ICustomize. Therefore, I will not see everything inside one test method. I'll have to navigate to the class to see how the data is setup'ed. And more, most of my methods have different way to setup the data, so I don't want to create one class which implements ICustomize for each one my test method.

**Comment by RyanLiu99** [comment]
I also like the idea to keep new Fixture() but also have additional static shortcut (to private static instance) in the library itself. It is trivial to write a wrapper or an extension method, but little bit troublesome to mange (e.g. namespace) and carry over from projects to projects.
Thanks,
