### ISSUE TITLE
Remove implicit 'assignable from' match from ConstructorInitializedMemberAssertion

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#207]
`ConstructorInitializedMemberAssertion` has a built-in implicit match for for constructors, where members are compared not on exact type, but on 'assignable from' comparison.

Since `ConstructorInitializedMemberAssertion` has been opened up for extensibility with custom comparers, this built-in implicit match should be removed. Removing it is a breaking change, so this will have to wait until AutoFixture 4.

More details here: https://github.com/AutoFixture/AutoFixture/pull/202#issuecomment-28645107

**Comment by zvirja** [comment]
Done for v4
