### ISSUE TITLE
AutoFixture.AutoFoq should use Foq's new Return Strategy

### ISSUE THREAD

**Issue by moodmosaic** [AutoFixture/AutoFixture#214]
Originally discussed and proposed by Ruben Bartelink (@bartelink) in [Foq project site discussions](https://foq.codeplex.com/discussions/470568).

Foq 1.4 and above (currently available using the latest Foq source code) accepts a Strategy for properties and methods that have not been explicitly setup:

```
Mock<AClient>(returnStrategy: SpecimenContext(fixture).Resolve)
```
The above can be automated with AutoFixture.AutoFoq and could also be the default behavior.

This would be a breaking change (new behavior and Foq package update), so should be done in AutoFixture 4.

**Comment by moodmosaic** [comment]
Foq's default behavior for mock objects that have not been explicitly setup, is to return `null` if the return type of a method is a reference type (e.g. a `string`):

```f#
type IInterface =
    abstract ReturnSomething : unit -> string

let fixture = Fixture().Customize(AutoFoqCustomization())

let sut = fixture.Create<IInterface>()
// No expectations have been setup - return null if
// the return type of a method is a reference type.

let actual = sut.ReturnSomething()
// -> actual: null
```
AutoFixture is an opinionated library, and one of the opinions it holds is that [nulls are invalid return values](http://stackoverflow.com/a/18170070/467754).

By the time AutoFixture.AutoFoq 3 was published, Foq was still in version 1.0 with no specific hooks to override this default behavior.

Since [we've updated Foq](https://github.com/AutoFixture/AutoFixture/pull/264), all the necessary hooks to override its default behavior are already [available](https://foq.codeplex.com/discussions/470568) to us. This means we'll be able to do the following, out of the box, once this issue is worked on:

```f#
type IInterface =
    abstract ReturnSomething : unit -> string

let fixture = Fixture().Customize(AutoFoqCustomization())

let sut = fixture.Create<IInterface>()
// No expectations have been setup - fallback to
// Foq's returnStrategy function.

let actual = sut.ReturnSomething()
// Foq uses a fresh new Fixture instance internally.
// -> actual: "f5cdf6b1-a473-410f-95f3-f427f7abb0c7"
```

---

Since this is happening in `v4`, I'd prefer to modify the existing `AutoFoqCustomization`. — Any thoughts?

**Comment by ploeh** [comment]
@moodmosaic Agreed; I'v removed the *4.0* milestone from this issue.

**Comment by moodmosaic** [comment]
@ploeh I think it'll be safer if I've done this in `v4

**Comment by ploeh** [comment]
Have we ever promised (in documentation or tests) anything about the return values of unconfigured test doubles?

**Comment by moodmosaic** [comment]
No, we haven't, but this requires an additional constructor parameter in `FoqMethodQuery`, plus an additional parameter in `FoqMethod.Create`, so it's essentially a breaking change since these types are public.

It can be safer if I open a Pull Request in `v4` branch, and we can decide from there whether we should move on to the `master` branch instead.

**Comment by ploeh** [comment]
Ah, OK, I'll add the *4.0* milestone back, then.

**Comment by moodmosaic** [comment]
:+1:

**Comment by ploeh** [comment]
With #464 I think we can close this issue now. Any objections?

**Comment by moodmosaic** [comment]
Nope, let's close this.
