### ISSUE TITLE
What is .WithAutoProperties() about?

### ISSUE THREAD

**Issue by vorou** [AutoFixture/AutoFixture#222]
Can't find any reference about the method.

Am I right thinking that these two lines are equivalent?

```
var x = new Fixture().Create<MyClass>();
var x = new Fixture().Build<MyClass>().WithAutoProperties().Create();
```

If yes, then what is the purpose of it?

**Comment by jzabroski** [comment]
> If you disable the assignment of writable properties through the `Fixture` instance:
> 
> ```
> var sut = new Fixture() { OmitAutoProperties = true };
> ```
> 
> you can selectively enable it using the `WithAutoProperties` method, by doing:
> 
> ```
> .Customize<MyClass>(x => x.WithAutoProperties());
> ```
> 
> and also, as you wrote in the code:
> 
> ```
> .Build<MyClass>().WithAutoProperties();
> ```



As discussed in #1270 , there is now a better way to omit auto properties than to do so globally.  The following is possible:

```
fixture.Customize<MyClass>(x => x.WithAutoProperties());
var ex1 = fixture.Build<MyClass>().OmitAutoProperties().Create();
var ex2 = fixture.Build<MyClass>().Create(); // will use value set by Customize call
var ex3 = fixture.Build<MyClass>().WithAutoProperties().Create(); // redundant due to last Customize call

fixture.Customize<MyClass>(x => x.OmitAutoProperties());
var ex4 = fixture.Build<MyClass>().WithAutoProperties().Create();
var ex5 = fixture.Build<MyClass>().Create(); // will use value set by Customize call
var ex6 = fixture.Build<MyClass>().OmitAutoProperties().Create(); // redundant due to last Customize call
```
