### ISSUE TITLE
CheetSheet - Replaced Default Algorithm is obsolete

### ISSUE THREAD

**Issue by mnau** [AutoFixture/AutoFixture#239]
The  Replaced Default Algorithm section in the CheetSheet doesn't work. It should be updated, most likely with http://blog.ploeh.dk/2010/10/19/Convention-basedCustomizationswithAutoFixture/

**Comment by ploeh** [comment]
Resolved: https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#replaced-default-algorithm
