### ISSUE TITLE
Creating a object tree where children reference parent for DDD design

### ISSUE THREAD

**Issue by kobbikobb** [AutoFixture/AutoFixture#242]
Hi there.

I wan't to be able to create a object tree where children reference parent.
For example a Car has Tires and a Tire references it's car.

So far I have been using OmitOnRecursionBehavior and assignin the reference manually, demo:

``` c#
var fixture = new Fixture();
fixture.Behaviors.Add(new OmitOnRecursionBehavior());
var car = fixture.Create<Car>();
foreach (var tire in car.Tires)
{
    tire.Car = car;
}
```

What I wanted to do:

``` c#
fixture.Customize<Car>(composer => composer
.With(car => car.Tires, fixture.Build<Tire>().With(tire => tire.Car, car)
.CreateMany().ToList()));
```

What I also wanted to do:

``` c#
private class CarCustomization : ICustomization
{
    public void Customize(IFixture fixture)
    {
        fixture.Behaviors.Add(new OmitOnRecursionBehavior());
        fixture.Customizations.Add(new CarBuilder());
    }
}

private class CarBuilder : ISpecimenBuilder
{
    public object Create(object request, ISpecimenContext context)
    {
        var t = request as Type;
        if (t != null && t == typeof(Car))
        {
            //Won't work, builder depends on it's self
            var car = context.Create<Car>();
            foreach (var tire in car.Tires)
            {
                tire.Car = car;
            }
        }

        return new NoSpecimen(request);
    }
}
```

Here are the Car/Tire classes:

``` c#
public class Car
{
    public string Name { get; set; }
    public string Description { get; set; }
    public int Doors { get; set; }
    public List<Tire> Tires { get; set; }
}

public class Tire
{
    public int Size { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Car Car { get; set; }
}
```

Can anyone help me solve this neatly?

**Comment by worldspawn** [comment]
I've noticed that is you have a .Customize call for the type being processed by the Filler that causes the filler to be ignored. eg `fixture.Customize<Car>(c => c.Without(x => x.Doors))`

I've tried to combine these like so:
```
var fixture = new Fixture();
            fixture.Customize<Tire>(c => c.Without(x => x.Car));
            ///fixture.Customize<Car>(c => c.Without(x => x.Doors));
            fixture.Customizations.Add(
                new FilteringSpecimenBuilder(
                    new Postprocessor(
                        SpecimenBuilderNodeFactory.CreateComposer<Car>().WithAutoProperties(!fixture.OmitAutoProperties)
                        .With(x=>x.Description, "Wee")
                        ,
                        new CarFiller()),
                    new CarSpecification()));
            
            
            var car = fixture.Create<Car>();

            Assert.Equal("Wee", car.Description);
            Assert.NotEmpty(car.Tires);
            Array.ForEach(car.Tires.ToArray(), x => Assert.NotNull(x.Car));
            Array.ForEach(car.Tires.ToArray(), x => Assert.True(x.Car == car));
```

So the Assert on the Description fails. Its being auto generated still, the customisations are ignored.

**Comment by worldspawn** [comment]
Heres a more genericised version:

```
private class CollectionBackReferenceFiller<T, TElement> : ISpecimenCommand
            where T : class
        {
            private readonly string _collectionProperty;
            private readonly Action<TElement, T> _backReferenceSetter;

            public CollectionBackReferenceFiller(string collectionProperty, Action<TElement, T> backReferenceSetter)
            {
                _collectionProperty = collectionProperty;
                _backReferenceSetter = backReferenceSetter;
            }

            public void Execute(object specimen, ISpecimenContext context)
            {
                if (specimen == null)
                    throw new ArgumentNullException("specimen");
                if (context == null)
                    throw new ArgumentNullException("context");

                var typedSpecimen = specimen as T;
                if (typedSpecimen == null)
                    throw new ArgumentException(
                        "The specimen must be an instance of " + typeof(T).Name,
                        "specimen");

                Array.ForEach(typedSpecimen.GetType().GetProperties(), x =>
                {
                    if (x.Name == _collectionProperty)
                    {
                        var elements =
                            ((IEnumerable<object>)context
                                .Resolve(new MultipleRequest(typeof(TElement))))
                                    .Cast<TElement>().ToArray();
                        Array.ForEach(elements, e => _backReferenceSetter(e, typedSpecimen));

                        x.SetValue(typedSpecimen, elements.ToList());
                    }
                });
            }
        }
        
        private class TypeSpecification<T> : IRequestSpecification
        {
            public bool IsSatisfiedBy(object request)
            {
                var requestType = request as Type;
                if (requestType == null)
                    return false;

                return typeof(T).IsAssignableFrom(requestType);
            }
        }
```

**Comment by jeremia** [comment]
Your generic solution was great!
I updated it to use Property Expressions for more type safe code and created a generic Customization. I ended up not using it, but I thought I would share it since I had already written it. :-)

Example. CashRegister has List with Receipts. Receipt has a back reference to CashRegister
```
public class CashRegister : EntityBase
{
	public List<Receipt> Receipts { get; set; }
}

public class Receipt : EntityBase
{
	public CashRegister CashRegister { get; set; }
}
```

Usage of Customization:
`new BackReferenceCustomization<CashRegister, Receipt>(cashRegister => cashRegister.Receipts, receipt => receipt.CashRegister)`

Customization:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using AutoFixture;
using AutoFixture.Kernel;

public class BackReferenceCustomization<TTypeWithList, TTypeWithBackReference> : ICustomization where TTypeWithList : class
{
	private readonly Expression<Func<TTypeWithList, List<TTypeWithBackReference>>> _collectionPropertyExpression;
	private readonly Expression<Func<TTypeWithBackReference, TTypeWithList>> _backReferencePropertyExpression;

	public BackReferenceCustomization(
		Expression<Func<TTypeWithList, List<TTypeWithBackReference>>> collectionPropertyExpression,
		Expression<Func<TTypeWithBackReference, TTypeWithList>> backReferencePropertyExpression)
	{
		_collectionPropertyExpression = collectionPropertyExpression;
		_backReferencePropertyExpression = backReferencePropertyExpression;
	}

	public void Customize(IFixture fixture)
	{
		fixture.Customize<TTypeWithBackReference>(c => c.Without(_backReferencePropertyExpression));
		fixture.Customizations.Add(
			new FilteringSpecimenBuilder(
				new Postprocessor(
					new MethodInvoker(new ModestConstructorQuery()),
					new CollectionBackReferenceFiller<TTypeWithList, TTypeWithBackReference>(_collectionPropertyExpression, _backReferencePropertyExpression)
				),
				new TypeSpecification<TTypeWithList>()
			)
		);
	}
}

public class CollectionBackReferenceFiller<TTypeWithList, TTypeWithBackReference> : ISpecimenCommand where TTypeWithList : class
{
	private readonly Expression<Func<TTypeWithList, List<TTypeWithBackReference>>> _collectionPropertyExpression;
	private readonly Expression<Func<TTypeWithBackReference, TTypeWithList>> _backReferencePropertyExpression;

	public CollectionBackReferenceFiller(Expression<Func<TTypeWithList, List<TTypeWithBackReference>>> collectionPropertyExpression, Expression<Func<TTypeWithBackReference, TTypeWithList>> backReferencePropertyExpression)
	{
		_collectionPropertyExpression = collectionPropertyExpression;
		_backReferencePropertyExpression = backReferencePropertyExpression;
	}

	public void Execute(object specimen, ISpecimenContext context)
	{
		if (specimen == null)
			throw new ArgumentNullException(nameof(specimen));
		if (context == null)
			throw new ArgumentNullException(nameof(context));

		if (!(specimen is TTypeWithList typedSpecimen))
			throw new ArgumentException(
				"The specimen must be an instance of " + typeof(TTypeWithList).Name,
				nameof(specimen));

		var elements =
			((IEnumerable<object>)context
				.Resolve(new MultipleRequest(typeof(TTypeWithBackReference))))
			.Cast<TTypeWithBackReference>().ToList();

		var collectionProperty = (PropertyInfo)((MemberExpression)_collectionPropertyExpression.Body).Member;
		collectionProperty.SetValue(typedSpecimen, elements);

		var backReferenceProperty = (PropertyInfo)((MemberExpression)_backReferencePropertyExpression.Body).Member;

		foreach (var element in elements)
		{
			backReferenceProperty.SetValue(element, typedSpecimen);
		}

		var otherProperties = typedSpecimen.GetType().GetProperties().Where(p => !p.Equals(collectionProperty) && p.SetMethod != null);
		foreach (var property in otherProperties)
		{
			property.SetValue(typedSpecimen, context.Resolve(property.PropertyType));
		}
	}
}

public class TypeSpecification<T> : IRequestSpecification
{
	public bool IsSatisfiedBy(object request)
	{
		var requestType = request as Type;
		if (requestType == null)
			return false;

		return typeof(T).IsAssignableFrom(requestType);
	}
}
```

**Comment by IvanAverin** [comment]
I have made improvement in @jeremia example  and make possible to perform additional customization for Type with back reference link.

Sorry @ploeh for disturbing in your project 

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using AutoFixture;
using AutoFixture.Dsl;
using AutoFixture.Kernel;

public class BackReferenceCustomization<TTypeWithList, TTypeWithBackReference> : ICustomization where TTypeWithList : class
{
	private readonly Expression<Func<TTypeWithList, IEnumerable<TTypeWithBackReference>>> _collectionPropertyExpression;
	private readonly Expression<Func<TTypeWithBackReference, TTypeWithList>> _backReferencePropertyExpression;

    private readonly Expression<Func<ICustomizationComposer<TTypeWithBackReference>, ISpecimenBuilder>>
        _additionalCustomizationExpression;

	public BackReferenceCustomization(
		Expression<Func<TTypeWithList, IEnumerable<TTypeWithBackReference>>> collectionPropertyExpression,
		Expression<Func<TTypeWithBackReference, TTypeWithList>> backReferencePropertyExpression,
        Expression<Func<ICustomizationComposer<TTypeWithBackReference>, ISpecimenBuilder>> customizationForTypeWithBackReference=null)
	{
		_collectionPropertyExpression = collectionPropertyExpression;
		_backReferencePropertyExpression = backReferencePropertyExpression;
        _additionalCustomizationExpression = customizationForTypeWithBackReference;
    }

	public void Customize(IFixture fixture)
    {
        if (_additionalCustomizationExpression != null)
        {
            Expression<Func<ICustomizationComposer<TTypeWithBackReference>, ISpecimenBuilder>> backReferenceExpression =
                (comp) => comp.Without(_backReferencePropertyExpression);
            var backReferenceCall = ((MethodCallExpression) backReferenceExpression.Body);
            var AllCustomization =
                Expression.Lambda<Func<ICustomizationComposer<TTypeWithBackReference>, ISpecimenBuilder>>(
                    Expression.Call(_additionalCustomizationExpression.Body, backReferenceCall.Method,
                        backReferenceCall.Arguments),
                    _additionalCustomizationExpression.Parameters);

            fixture.Customize<TTypeWithBackReference>(AllCustomization.Compile());
        }
        else
        {
            fixture.Customize<TTypeWithBackReference>(c => c.Without(_backReferencePropertyExpression));
        }

        fixture.Customizations.Add(
			new FilteringSpecimenBuilder(
				new Postprocessor(
					new MethodInvoker(new ModestConstructorQuery()),
					new CollectionBackReferenceFiller<TTypeWithList, TTypeWithBackReference>(_collectionPropertyExpression, _backReferencePropertyExpression)
				),
				new TypeSpecification<TTypeWithList>()
			)
		);
	}
}

public class CollectionBackReferenceFiller<TTypeWithList, TTypeWithBackReference> : ISpecimenCommand where TTypeWithList : class
{
	private readonly Expression<Func<TTypeWithList, IEnumerable<TTypeWithBackReference>>> _collectionPropertyExpression;
	private readonly Expression<Func<TTypeWithBackReference, TTypeWithList>> _backReferencePropertyExpression;

	public CollectionBackReferenceFiller(Expression<Func<TTypeWithList, IEnumerable<TTypeWithBackReference>>> collectionPropertyExpression, Expression<Func<TTypeWithBackReference, TTypeWithList>> backReferencePropertyExpression)
	{
		_collectionPropertyExpression = collectionPropertyExpression;
		_backReferencePropertyExpression = backReferencePropertyExpression;
	}

	public void Execute(object specimen, ISpecimenContext context)
	{
		if (specimen == null)
			throw new ArgumentNullException(nameof(specimen));
		if (context == null)
			throw new ArgumentNullException(nameof(context));

		if (!(specimen is TTypeWithList typedSpecimen))
			throw new ArgumentException(
				"The specimen must be an instance of " + typeof(TTypeWithList).Name,
				nameof(specimen));

		var elements =
			((IEnumerable<object>)context
				.Resolve(new MultipleRequest(typeof(TTypeWithBackReference))))
			.Cast<TTypeWithBackReference>().ToList();

		var collectionProperty = (PropertyInfo)((MemberExpression)_collectionPropertyExpression.Body).Member;
		collectionProperty.SetValue(typedSpecimen, elements);

		var backReferenceProperty = (PropertyInfo)((MemberExpression)_backReferencePropertyExpression.Body).Member;

		foreach (var element in elements)
		{
			backReferenceProperty.SetValue(element, typedSpecimen);
		}

		var otherProperties = typedSpecimen.GetType().GetProperties().Where(p => !p.Equals(collectionProperty) && p.SetMethod != null);
		foreach (var property in otherProperties)
		{
			property.SetValue(typedSpecimen, context.Resolve(property.PropertyType));
		}
	}
}

public class TypeSpecification<T> : IRequestSpecification
{
	public bool IsSatisfiedBy(object request)
	{
		var requestType = request as Type;
		if (requestType == null)
			return false;

		return typeof(T).IsAssignableFrom(requestType);
	}
}`

**Comment by IvanAverin** [comment]
I have made improvement in @jeremia example and make possible to perform additional customization for Type with back reference link.
Example of using:

new BackReferenceCustomization<Car, Tire>
                (l => l.Tires, r => r.Car, c => c.Without(p => p.Radius))

Sorry @ploeh for disturbing in your project


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using AutoFixture;
using AutoFixture.Dsl;
using AutoFixture.Kernel;

public class BackReferenceCustomization<TTypeWithList, TTypeWithBackReference> : ICustomization where TTypeWithList : class
{
	private readonly Expression<Func<TTypeWithList, IEnumerable<TTypeWithBackReference>>> _collectionPropertyExpression;
	private readonly Expression<Func<TTypeWithBackReference, TTypeWithList>> _backReferencePropertyExpression;

    private readonly Expression<Func<ICustomizationComposer<TTypeWithBackReference>, ISpecimenBuilder>>
        _additionalCustomizationExpression;

	public BackReferenceCustomization(
		Expression<Func<TTypeWithList, IEnumerable<TTypeWithBackReference>>> collectionPropertyExpression,
		Expression<Func<TTypeWithBackReference, TTypeWithList>> backReferencePropertyExpression,
        Expression<Func<ICustomizationComposer<TTypeWithBackReference>, ISpecimenBuilder>> customizationForTypeWithBackReference=null)
	{
		_collectionPropertyExpression = collectionPropertyExpression;
		_backReferencePropertyExpression = backReferencePropertyExpression;
        _additionalCustomizationExpression = customizationForTypeWithBackReference;
    }

	public void Customize(IFixture fixture)
    {
        if (_additionalCustomizationExpression != null)
        {
            Expression<Func<ICustomizationComposer<TTypeWithBackReference>, ISpecimenBuilder>> backReferenceExpression =
                (comp) => comp.Without(_backReferencePropertyExpression);
            var backReferenceCall = ((MethodCallExpression) backReferenceExpression.Body);
            var AllCustomization =
                Expression.Lambda<Func<ICustomizationComposer<TTypeWithBackReference>, ISpecimenBuilder>>(
                    Expression.Call(_additionalCustomizationExpression.Body, backReferenceCall.Method,
                        backReferenceCall.Arguments),
                    _additionalCustomizationExpression.Parameters);

            fixture.Customize<TTypeWithBackReference>(AllCustomization.Compile());
        }
        else
        {
            fixture.Customize<TTypeWithBackReference>(c => c.Without(_backReferencePropertyExpression));
        }

        fixture.Customizations.Add(
			new FilteringSpecimenBuilder(
				new Postprocessor(
					new MethodInvoker(new ModestConstructorQuery()),
					new CollectionBackReferenceFiller<TTypeWithList, TTypeWithBackReference>(_collectionPropertyExpression, _backReferencePropertyExpression)
				),
				new TypeSpecification<TTypeWithList>()
			)
		);
	}
}

public class CollectionBackReferenceFiller<TTypeWithList, TTypeWithBackReference> : ISpecimenCommand where TTypeWithList : class
{
	private readonly Expression<Func<TTypeWithList, IEnumerable<TTypeWithBackReference>>> _collectionPropertyExpression;
	private readonly Expression<Func<TTypeWithBackReference, TTypeWithList>> _backReferencePropertyExpression;

	public CollectionBackReferenceFiller(Expression<Func<TTypeWithList, IEnumerable<TTypeWithBackReference>>> collectionPropertyExpression, Expression<Func<TTypeWithBackReference, TTypeWithList>> backReferencePropertyExpression)
	{
		_collectionPropertyExpression = collectionPropertyExpression;
		_backReferencePropertyExpression = backReferencePropertyExpression;
	}

	public void Execute(object specimen, ISpecimenContext context)
	{
		if (specimen == null)
			throw new ArgumentNullException(nameof(specimen));
		if (context == null)
			throw new ArgumentNullException(nameof(context));

		if (!(specimen is TTypeWithList typedSpecimen))
			throw new ArgumentException(
				"The specimen must be an instance of " + typeof(TTypeWithList).Name,
				nameof(specimen));

		var elements =
			((IEnumerable<object>)context
				.Resolve(new MultipleRequest(typeof(TTypeWithBackReference))))
			.Cast<TTypeWithBackReference>().ToList();

		var collectionProperty = (PropertyInfo)((MemberExpression)_collectionPropertyExpression.Body).Member;
		collectionProperty.SetValue(typedSpecimen, elements);

		var backReferenceProperty = (PropertyInfo)((MemberExpression)_backReferencePropertyExpression.Body).Member;

		foreach (var element in elements)
		{
			backReferenceProperty.SetValue(element, typedSpecimen);
		}

		var otherProperties = typedSpecimen.GetType().GetProperties().Where(p => !p.Equals(collectionProperty) && p.SetMethod != null);
		foreach (var property in otherProperties)
		{
			property.SetValue(typedSpecimen, context.Resolve(property.PropertyType));
		}
	}
}

public class TypeSpecification<T> : IRequestSpecification
{
	public bool IsSatisfiedBy(object request)
	{
		var requestType = request as Type;
		if (requestType == null)
			return false;

		return typeof(T).IsAssignableFrom(requestType);
	}
}
