### ISSUE TITLE
Support for IReadOnlyCollection

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#257]
.NET 4.5 introduces the `IReadOnlyCollection<T>` interface. AutoFixture is currently built on .NET 4.0, so it would be a breaking change to update it to .NET 4.5. We've already had to reject [one pull request](https://github.com/AutoFixture/AutoFixture/pull/256) because of this.

We should _consider_ building **AutoFixture 4** on .NET 4.5. If we decide to do that, we should add support for `IReadOnlyCollection<T>`. If @clausndk keeps his fork around, we may even be able to reopen his PR and pull it at that time.

**Comment by abatishchev** [comment]
What is the release schedule for v4?

**Comment by ploeh** [comment]
There's no schedule as such, but I'm keeping an eye on what's happening with .NET Core. When .NET Core is released and stable, I could imagine that a lot of people would like to have AutoFixture available on that platform as well. That'll require breaking changes, but also seems like an appropriate occasion for releasing a new major version.

Issue #404 tracks the effort to make AutoFixture compatible with .NET Core, but it's not something anyone is actively working on, to my knowledge.

**Comment by abatishchev** [comment]
Thanks for headups!
I would personally prefer v4 to target .NET 4.6.1 instead and v5 to point .NET Core.
So projects targeting the latest full .NET would have AutoFixture with the latest full .NET features. And projects targeting Core would get it as soon as the platform matures and the porting onto it takes place.

**Comment by adamchester** [comment]
Just FYI and AFAICT, we would target [`netstandard1.X`](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) which is the set of APIs that would run on any platform that implements them.

**Comment by abatishchev** [comment]
hi, any update on this please? so far we have to always add custom type relay for it. would love to see it bundled by default.

**Comment by abatishchev** [comment]
Keeping in mind https://github.com/AutoFixture/AutoFixture/issues/703, I'd like to propose to ship a new minor version (v3.6) targeting .NET 4.6 and support Core in the next major version (v4.0).
