### ISSUE TITLE
Problem of AutoFixture current version with Moq current version 

### ISSUE THREAD

**Issue by binydev** [AutoFixture/AutoFixture#260]
when i build my application using Team Foundation MsBuild I face this problem. it work on my local computer I face this problem when it is on server. 

System.IO.FileLoadException: Could not load file or assembly 'Moq, Version=3.1.416.3, Culture=neutral, PublicKeyToken=69f491c39445e920' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    at Ploeh.AutoFixture.AutoMoq.MockPostprocessor.Create(Object request, ISpecimenContext context)

**Comment by Skm5900** [comment]
Hi Team,
Same issue facing here, unit test having reference to AutoFixture is not working for below line of code on devOps pipeLine build, on local it works fine. Please sugggest.

**Comment by aivascu** [comment]
@Skm5900 It might be that you are relying on the implicit version of `Moq` added by `AutoFixture.AutoMoq`.
The `Moq` version in our packages is intentionally kept at lower values to enable more compatibility.
You should install `Moq`package in your test projects and update it to the latest version.
