### ISSUE TITLE
Online documentation

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#266]
AutoFixture has rather decent documentation in the form of formal XML documentation comments in the source code, but unfortunately, few people discover it.

We should set up a site with on-line documentation, built from those XML comments, but we'd need an automated process for it. We should also consider how our rapid release cycle impacts the documentation; ideally, there should be a complete set of documentation files for each release - at least for every major and minor release.

Perhaps it would also be a good idea to ship the documentation with each NuGet package?

It's been quite a while since I last looked into the state of documentation generators for .NET, so I don't know what's good these days. Last time I looked, Sandcastle was the only viable alternative, and I found it quite difficult to work with.

We should keep in mind that we'd need to generate documentation from both C# and F# code bases.

**Comment by moodmosaic** [comment]
Unless we can *easily* put this in our current build automation pipeline (e.g. using [F# Formatting](http://fsprojects.github.io/FSharp.Formatting/literate.html), or similar), should we close this?
