### ISSUE TITLE
Add idiomatic assertions for GetHashCode, similar to the ones for Equals.

### ISSUE THREAD

**Issue by yreynhout** [AutoFixture/AutoFixture#292]
Next to Equals, I'd also like to be able to test GetHashCode in an idiomatic way. As it stands, I think, GetHashCodeSelfAssertion and GetHashCodeSuccessiveAssertion will suffice.

**Comment by moodmosaic** [comment]
@yreynhout, since this issue has been inactive since mid-2014, I'm not sure if it's ever going to be resolved.

**Comment by yreynhout** [comment]
Yeah, I'm not going to work on it, so if you want to close it down, that's fine by me. I've been using NodaTime's approach to generating my hashcodes and feel comfortable with that approach without AutoFixture trying to cover this niche.

**Comment by moodmosaic** [comment]
[Noda Time](http://nodatime.org/) becomes more and more interesting.

Alright, let's close this, as it might not be trivial to implement it in terms of `IIdiomaticAssertion`. (We can always re-open the issue, of course.)
