### ISSUE TITLE
OmitOnRecursionBehavior does not guard against recursionDepth < 1

### ISSUE THREAD

**Issue by dcastro** [AutoFixture/AutoFixture#337]
The following code throws an `InvalidCastException` for `recursionDepth` < 1.

```csharp
var fixture = new Fixture();
fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList()
    .ForEach(b => fixture.Behaviors.Remove(b));

fixture.Behaviors.Add(new OmitOnRecursionBehavior(recursionDepth));

fixture.Create<string>();
```

```
System.InvalidCastExceptionUnable to cast object of type 'Ploeh.AutoFixture.Kernel.OmitSpecimen' to type 'System.String'.
   at Ploeh.AutoFixture.SpecimenFactory.Create(ISpecimenContext context, T seed) in SpecimenFactory.cs: line 125
   at Ploeh.AutoFixture.SpecimenFactory.Create(ISpecimenContext context) in SpecimenFactory.cs: line 29
   at Ploeh.AutoFixture.SpecimenFactory.Create(ISpecimenBuilder builder) in SpecimenFactory.cs: line 73
   at Ploeh.AutoFixtureUnitTest.OmitOnRecursionBehaviorTest.FactMethodName() in OmitOnRecursionBehaviorTest.cs: line 90
```

It seems like `OmitOnRecursionBehavior` is not supposed to work for depth < 1, so a guard clause is needed somewhere. 

At first glance, it seems like the guard should go into the `OmitOnRecursionBehavior`'s constructor, but maybe this could be generalized for every `RecursionGuard` and be put into its constructor instead.

I can volunteer to make this change, but since I'm not very familiar with this part of the code, I'd like to know the owners/contributors' thoughts on this first.

**Comment by ploeh** [comment]
I wonder why creation of `string` even triggers any recursion behaviour... `string` has a dedicated `ISpecimenBuilder`.

**Comment by Pvlerick** [comment]
From what I understood, when `OmitOnRecursionBehavior` (or the default `ThrowingRecursionBehavior`) is added to the list of behaviors, their `Transform` function puts them first in the graph, which means that their respective Handlers returned get called first.

So in the example code above, execution doesn't reach the specimen builders.

Adding a guard in `RecursionGuard` would do the trick but then the exception would be thrown when `Transform` is called, contrarily to adding the guard clause in the constructor.

I'd be happy to pick this up either way, just let me know what is the preferred way and I'll send a PR.
