### ISSUE TITLE
FormatException from fixture.Create<System.Net.Mail.MailAddress>()

### ISSUE THREAD

**Issue by cbowdon** [AutoFixture/AutoFixture#339]
The following code fails with a FormatException:

```C#
new Fixture().Create<System.Net.Mail.MailAddress>()
```

Fairly obviously this is because the MailAddress constructor won't accept arbitrary strings. It's easy to work around with some customization. However, this feels like something that should just work, the same way that creating a System.Uri just works.

Looking at the AutoFixture source it looks like a fairly straightforward solution would be to add a MailAddressGenerator. Would that be acceptable? If so I will submit a PR.

**Comment by ecampidoglio** [comment]
Since MailAddress is part of the BCL I don't see why not. 👍

**Comment by ploeh** [comment]
Sounds reasonable.

However, I think it's important to ensure that the generated email addresses fall into a range that runs no risk of bothering people with real email addresses.

Although AutoFixture is intended to be used for unit testing, people use if for all sorts of funny purposes, so I wouldn't be surprised if, one day, someone would (accidentally) write a test suite that as a side effect attempts to actually send out emails.

One way to do that is to generate all addresses using [fictitious domain names](http://en.wikipedia.org/wiki/Example.com), e.g.

- 12a111d4-42d0-486e-b099-2be08789c923@example.com
- 3c38dd7d-3c42-4e59-9188-adbbcf879ae0@example.net
- a6be450b-3475-49c3-b550-eaabe338d0da@example.org

**Comment by cbowdon** [comment]
That makes sense, I will ensure it only generates addresses for fictitious domains.

**Comment by ploeh** [comment]
Resolved in d02f102301af95908e31dcb0e5c628abe48cbb8b.
