### ISSUE TITLE
How to extend ICustomizationComposer ?

### ISSUE THREAD

**Issue by Kuqd** [AutoFixture/AutoFixture#344]
Hello,

Good job with this framework it's awesome.

I'd like to have some help on this one however I'm trying to create custom composition behavior but the `Do` is always call right after the instance is created as you can see above.
I'm pretty sure there is nothing that would allow me to run an `Action` after all property have been anonymously created.

```c#
 public static IPostprocessComposer<GamePlatform> WithActiveStatus(this ICustomizationComposer<GamePlatform> composer,
            string countryCode)
        {
            List<GamePlatformStatus> statuses = composer.CreateMany<GamePlatformStatus>(3).ToList();
            GamePlatformStatus activeStatus = statuses.FirstOrDefault();
            if (activeStatus != null)
            {
                activeStatus.CountryCode = countryCode;
                activeStatus.Status = GamePlatformStatuses.Active;
            }
            return composer.Without(x=>x.Statuses).Do(platform =>
            {
                statuses.ForEach( s=>s.GamePlatformId = platform.Id);
                platform.Statuses = statuses;
            });
        }
```

The issue is that the ` statuses.ForEach( s=>s.GamePlatformId = platform.Id);` statement received always a default object not yet populated.

I really want to use the `Build` this way : 

`Fixture.Build<GamePlatform>().WithActiveStatus(_country).With(x=>x.Id,_spaceId).Create()`

it allows me for some testcase to create a complex object with a specific state, I don't want all object to have this specific state.

so how do I create this new `Do` that does the given `Action` after all processing is finished ? I'm trying to understand where to start to implement.

Thank you.

**Comment by ploeh** [comment]
> I really want to use the Build this way :

> `Fixture.Build<GamePlatform>().WithActiveStatus(_country).With(x=>x.Id,_spaceId).Create()`

What if you changed the extension method so that you'd be able to write the following instead?

```C#
Fixture.Build<GamePlatform>().With(x=>x.Id,_spaceId).Create().WithActiveStatus(_country)
```

It looks as though all the properties are mutable, so that'd be much easier.

---

As a side note, though, you [shouldn't provide settable collection properties](https://msdn.microsoft.com/en-us/library/dn169389.aspx).

**Comment by Kuqd** [comment]
Thanks for the answer,

You are right for the extension and it makes even more sense since it's really tie to my object type and not really extending your work.

Thanks again.
