### ISSUE TITLE
MailAddressGenerator should use context to resolve name

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#348]
As described in [this comment](https://github.com/AutoFixture/AutoFixture/pull/340/files#r23569387), `MailAddressGenerator` should delegate the creation of the name part of an email address to the `ISpecimenContext`.

There are two options for this:

- Ask the context for a `string`. This is the simplest solution, but could theoretically be problematic if the user has changed the string generation algorithm to create strings incompatible with the STMP address format.
- Ask the context for an instance of a hypothetical signal type like `EmailAddressNamePart`. We should look up the correct terminology for talking about the part of an email address that goes before the @ sign. If we take this route, we'd need to add this `EmailAddressNamePart` type, and make sure that AutoFixture can resolve it. This is similar to the implementation of how AutoFixture creates URLs.

**Comment by ploeh** [comment]
The implementation of this feature would be an enhancement of #340.

**Comment by dlongest** [comment]
Per RFC 3696, which I believe is controlling on the issue, the part before the @ is the `local-part`.  The RFC defines an email address as `local-part@domain`.  http://tools.ietf.org/pdf/rfc3696.pdf   RFC 5322 also mentions it.  So I submit `EmailAddressLocalPart` as the proper term in place of `EmailAddressNamePart`

**Comment by ploeh** [comment]
`EmailAddressLocalPart` sounds good :+1: 

Thank you for investigating :smile:

**Comment by dlongest** [comment]
Unless someone else is already doing it, I'd love to work on this one and the related #349 although I'll do them separately. I'm inclined to use the 2nd approach suggested by @ploeh with a typed request for the email local part instead of string.

**Comment by ploeh** [comment]
As far as I know, no-one else is working on this, so please go ahead :+1: 

That 2nd approach is also my preferred solution.

**Comment by moodmosaic** [comment]
In case it might helps, [`UriScheme`](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/UriScheme.cs) works in a similar way when creating a `Uri`:

```csharp
var fixture = new Fixture();
fixture.Inject(new UriScheme("ftp"));
var uri = fixture.CreateAnonymous<Uri>(); 
// Prints -> ftp://bsdf6546-1df4-5d56-c7e9-1456dd226bd4/
```

Probably the implementation for `EmailAddressLocalPart` could be similar to `UriScheme`'s.
