### ISSUE TITLE
MailAddressGenerator should use context to resolve domain name

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#349]
As described in [this comment](https://github.com/AutoFixture/AutoFixture/pull/340#issuecomment-71556125), `MailAddressGenerator` should delegate the creation of the domain name part of an email address to the `ISpecimenContext`.

The generated domain names should by default be one of the domain names "example.com", "example.net", or "example.org", so that accidental collisions with real resources on the internet can be avoided. These domain names are reserved for such purposes.

**Comment by ploeh** [comment]
The implementation of this feature would be an enhancement of #340.

**Comment by tiesmaster** [comment]
I'm interested in picking up this issue. Is this still wanted?

As for the naming of the class, should I follow the same pattern as #348, and name it `EmailAddressDomainPart` (that's how the RFC talks about it)? Or follow the naming of the referenced comment, use `DomainName`, so it might be used in other places where you need a domain name?

**Comment by ploeh** [comment]
@tiesmaster, you are welcome to contribute this feature :smile: 

Good question regarding the name. I'd lean slightly towards `DomainName`, because it'd also be useful for other purposes, such as WWW domain names. By default we should only use `example.org` etc. but calling the class `DomainName` leaves it open to also serve up names such as `www.example.org`. That might seem like a slightly odd part of an email address, but as far as I know, `foo@www.example.org` is still a valid email address.

I'm open for counter-arguments, though :smile:

**Comment by tiesmaster** [comment]
Ok, good to know ;)

`DomainName` sounds like the most appropriate then, I'll take that.
