### ISSUE TITLE
AutoConfiguredNSubstituteCustomization infinite enumeration on IReadOnlyList property

### ISSUE THREAD

**Issue by MichaelLogutov** [AutoFixture/AutoFixture#350]
This test fails with timeout because Items property will infinitely generate new items.
The problem seems to not appear when using IList<> or IEnumeration<>.

    [TestClass]
    public class Tests
    {
        public class Data
        {
            public IReadOnlyList<string> Items { get; set; }
        }

        [TestMethod, Timeout (500)]
        public void Test ()
        {
            // arrange
            var fixture = new Fixture ();
            fixture.Customize (new AutoConfiguredNSubstituteCustomization ());

            var sut = fixture.Create<Data> ();

            // act
            var result = sut.Items.Count (x => true);

            // assert
            Assert.AreEqual (0, result);
        }
    }

**Comment by mrinaldi** [comment]
The problem here is that ``AutoConfiguredNSubstituteCustomization`` sets up ``MoveNext()`` to always return the same value and AutoFixture ends up creating the anonymous boolean as true, that means it doesn't matter how many times ``MoveNext()`` is called, it always returns true and continues to enumerate the collection.

The reason it doesn't happen with ``IList<>`` or ``IEnumerable<>`` is because AutoFixture relays those types to their concrete types counterpart.

Since AutoFixture 3 is built against .NET 4.0, and ``IReadOnlyList<>`` is only available in .NET 4.5, we cannot create a default relay for ``IReadOnlyList<>`` in AutoFixture's code base

What you can do, though, is create a customization in your code base that relays ``IReadOnlyList<>`` to ``List<>`` or some other concrete type, just like it has been done for ``IReadOnlyCollection<>`` in v4 branch of AutoFixture.

Just make sure you add this customization before the ``AutoConfiguredNSubstituteCustomization``.
Also note that now the collection has 3 items created by AutoFixture, which is the default behavior for ``IList<>`` and ``IEnumerable<>``.

```C#
public class ReadOnlyListCustomization : ICustomization
{
	public void Customize(IFixture fixture)
	{
		fixture.ResidueCollectors.Add(new ReadOnlyListRelay());
	}
}

public class ReadOnlyListRelay : ISpecimenBuilder
{
	public object Create(object request, ISpecimenContext context)
	{
		if (context == null)
			throw new ArgumentNullException("context");

		var t = request as Type;
		if (t == null)
			return new NoSpecimen(request);

		var typeArguments = t.GetGenericArguments();
		if (typeArguments.Length != 1 ||
			typeof(IReadOnlyList<>) != t.GetGenericTypeDefinition())
			return new NoSpecimen(request);

		return context.Resolve(
			typeof(List<>).MakeGenericType(typeArguments));
	}
}

public class Tests
{
	public class Data
	{
		public IReadOnlyList<string> Items { get; set; }
	}


	[Fact]
	public void Test()
	{
		// arrange
		var fixture = new Fixture();
		fixture.Customize(new ReadOnlyListCustomization());
		fixture.Customize(new AutoConfiguredNSubstituteCustomization());

		var sut = fixture.Create<Data>();

		// act
		var result = sut.Items.Count(x => true);

		// assert
		Assert.Equal(3, result);
	}
}
```

**Comment by ploeh** [comment]
Thank you, @mrinaldi, for that very detailed explanation :+1: 

As described here, the *v4* branch already contains support for `IReadOnlyList<T>`, but I don't see how we could address that in AutoFixture 3.

Given those constraints, and the above workaround, can we then close this issue?

**Comment by MichaelLogutov** [comment]
Yeah, I'll use that workaround until stable v4 is pushed to nuget.
Thanks!

**Comment by MichaelLogutov** [comment]
Btw, can't AutoFixture just make all any IEnumerable.MoveNext run max 3 times? Because I'm sure that classes implementing IEnumerable manually will face the same issue and writing custom relay on every one of them is a bit tedious.

**Comment by ploeh** [comment]
> Btw, can't AutoFixture just make all any IEnumerable.MoveNext run max 3 times?

It [does that already for well-known collections](https://github.com/AutoFixture/AutoFixture/wiki/Version-History#various-collections-are-filled-by-default). Apart from `IReadOnlyCollection<T>`, are you experiencing problems with other collection types?

**Comment by MichaelLogutov** [comment]
Well, correct me if I'm wrong, but the problem was that autofixture makes any IEnumerable infinite by overriding return of MoveNext to true and returning not null IEnumerable.Current.
So if someone implements IEnumerable manually (just like IReadOnlyList do) it will facing the same infinite issue. No?

**Comment by ploeh** [comment]
Have you tried?

**Comment by MichaelLogutov** [comment]
Just tested it - got the same error (infinite enumeration):

        public interface IMyList<out T> : IEnumerable<T>
        {
        }

        public class Data
        {
            public IMyList<string> Items { get; set; }
        }


        [TestMethod, Timeout (500)]
        public void Test ()
        {
            // arrange
            var fixture = new Fixture ();
            fixture.Customize (new AutoConfiguredNSubstituteCustomization ());


            var sut = fixture.Create<Data> ();


            // act
            var result = sut.Items.Count (x => true);


            // assert
            Assert.AreEqual (0, result);
        }

**Comment by ploeh** [comment]
Yes, but `IMylist<T>` is your custom interface...

**Comment by MichaelLogutov** [comment]
Abstract class behaves the same. Basically - when autofixture applies nsubstitute customization automatically to property which implements IEnumerable this property became infinite enumeration.
Is there a way for such properties by default enumerate maximum 3 times (like CreateMany)?

**Comment by ploeh** [comment]
This might be worth looking into, but I don't know if it's possible with NSubstitute...

**Comment by adamchester** [comment]
It sounds like auto-mocking the `MoveNext` method so it always returns `true` causes a special kind of common pain.

Surely, we could even manually change any mock we created to return true->true->false?
