### ISSUE TITLE
ConstructorInitializedMemberAssertion does not require initialization

### ISSUE THREAD

**Issue by cocogorilla** [AutoFixture/AutoFixture#355]
If no constructor is found with a parameter matching the property name, the assertion passes.

Is this the intended behavior?  I was surprised, I definitely expected the assertion to require at least 1 constructor containing the fuzzy matched property name.

**Comment by adamchester** [comment]
That is the intended behaviour for writable properties and fields.

Does issue #131 help explain this behaviour?

**Comment by cocogorilla** [comment]
That makes perfect sense... and the main thing is it works as expected for a readonly property.  Thanks for clearing that up.
