### ISSUE TITLE
InfiniteDataAttribute

### ISSUE THREAD

**Issue by alexfoxgill** [AutoFixture/AutoFixture#357]
As requested by @moodmosaic in [this PR](https://github.com/AutoFixture/AutoFixture/pull/356/files#r25580306).

This attribute is intended for use in conjunction with `CompositeDataAttribute`:

``` CSharp
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)
public class InfiniteDataAttribute : DataAttribute
{
    private readonly DataAttribute _decorated;

    public InfiniteDataAttribute(DataAttribute decorated)
    {
        _decorated = decorated;
    }

    public override IEnumerable<object[]> GetData(MethodInfo methodUnderTest, Type[] parameterTypes)
    {
        while (true)
        {
            foreach (var dataSet in _decorated.GetData(methodUnderTest, parameterTypes))
                yield return dataSet;
        }
    }
}
```

The idea is that you wrap an `AutoDataAttribute` with an `InfiniteDataAttribute` so that it can provide AutoData for any number of iterations of a, xUnit Theory. This allows AutoData to be used with xUnit's `PropertyDataAttribute`, which currently it can't (see #354 and #356):

``` CSharp
public class PropertyAutoDataAttribute : CompositeDataAttribute
{
    public PropertyAutoDataAttribute(string propertyName)
        : base(new PropertyDataAttribute(propertyName),
               new InfiniteDataAttribute(new AutoDataAttribute(new Fixture())))
   {
   }
}
```

**Comment by ploeh** [comment]
Why is it called *Infinite?*

**Comment by alexfoxgill** [comment]
Well, it generates an infinite sequence! Alternatively, `RepeatDataAttribute` would also describe it well, given that it repeats?

**Comment by ploeh** [comment]
Ah, right, I didn't notice the `while(true)`...

`RepeatDataAttribute` may be a slightly better name, in that I think it better communicates what actually goes on.

**Comment by alexfoxgill** [comment]
That works for me. Would it be beneficial to provide the attribute with an optional parameter `int? repetitions`? I'm trying to think of other cases where this might be useful.

**Comment by ploeh** [comment]
Before we do a ton of work on this feature... Do we know how it's going to work in xUnit.net 2?

AFAIK, there's going to be breaking changes in xUnit.net 2, so perhaps we should think twice before we put a lot of work into this...

**Comment by alexfoxgill** [comment]
That's a valid point.

xUnit v2's [DataAttribute](https://github.com/xunit/xunit/blob/b2c6201025f71ede57c0e9cc1f0ad31ee828dbfb/src/xunit.core/Sdk/DataAttribute.cs) changes the type signature of the `GetData` method. They have removed the array of type parameters which was the second argument to the function. I assume this is because this information is easily accessible from the `MethodInfo` parameter, so the second argument was redundant.

So, it shouldn't be troublesome to migrate, and given that the existing attributes (Composite, Auto, InlineAuto) must be migrated anyway, I would suggest that this could simply be added to the list when the time comes. It might be nice to offer it as compatible with xUnit v1, as I guess many people won't be migrating right away.

**Comment by zvirja** [comment]
@alexfoxgill If you don't mind, I'm closing this issue for now. This feature looks very ad-hoc and it's purpose is not clear. The unit tests you write should be stable enough to not fail depending on the auto-generated data. If you would like to perform exhaustive check, it's probably to use [FsCheck](https://fscheck.github.io/FsCheck/) or similar tools which was designed for such purpose.

This issue existed for 2 years and during this time nobody else asked about it, which makes me confident that it doesn't cover a _common_ usage scenario. Given that it's very easy to implement this feature in your own project, let's postpone this feature for now. If later we see that it's high-demand, we can always re-open the issue.

Alex, please let me know if you have concerns.
