### ISSUE TITLE
New Instance of fixture is creating the same value

### ISSUE THREAD

**Issue by sbrockway** [AutoFixture/AutoFixture#360]
I have noticed that when I repeatedly create a new instance of fixture and ask it to create a value for me, I always get the same value back.  Whereas creating a single instance and reusing it creates new values.
For bool the value is always true for new instances.  Where as with a single instance the value always alternates.
Is this expected behavior?
I create a new instance of fixture in my test setup with the idea that I would get a fresh instance for each test, but this behavior is less than ideal.
Also, shouldn't the bool generation be more "random" than alternation?
Thanks.  Excellent tool by the way!

			var fixture = new Fixture();
			var runCount = 10;
			Console.WriteLine("Same instance bool");
			for (int i = 0; i < runCount; i++)
			{
				Console.WriteLine(fixture.Create<bool>());
			}
			Console.WriteLine("New Instance bool");
			for (int i = 0; i < runCount; i++)
			{
				// always the same (true)
				Console.WriteLine(new Fixture().Create<bool>());
			}
			Console.WriteLine("Same Instance Ints");
			for (int i = 0; i < runCount; i++)
			{
				Console.WriteLine(fixture.Create<int>());
			}
			Console.WriteLine("New Instance Ints");
			for (int i = 0; i < runCount; i++)
			{
				// always the same
				Console.WriteLine(new Fixture().Create<int>());
			}

**Comment by dcastro** [comment]
The behavior is by design. The boolean generator always returns true first, then false, the true again and so on. 

The same goes for the enum generator. The first time you ask for an instance of an enum type, you'll be given its first value. The fact that the first value also happens to be `default(EnumType)` makes this behaviour very inconvenient at times, because you can't tell whether the enum generated by autofixture was correctly assigned to a field, or whether nothing was assigned at all - the end result is the same.

**Comment by adamchester** [comment]
This is by design, but it's only a default. You can configure the fixture to use random generation. Try [RandomBooleanSequenceCustomization](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/RandomBooleanSequenceCustomization.cs).

**Comment by ploeh** [comment]
FWIW, `bool` is just a problematic data type in the context of value generation. If there's a good default behaviour *without* disadvantages, I haven't found it yet; more details [here](https://github.com/AutoFixture/AutoFixture/issues/83#issuecomment-14762824).

As suggested by @adamchester, you can change the behaviour with `RandomBooleanSequenceCustomization`, or in other ways, even, if you want to.

Does that answer your question?

**Comment by sbrockway** [comment]
Yes, that answers the question.  Thanks guys!
