### ISSUE TITLE
CreateMany should accept zero

### ISSUE THREAD

**Issue by realbart** [AutoFixture/AutoFixture#365]
Maybe there's a better way to do this, but here's a scenario:
You want to create a collection of orders with random numbers of order lines.
This seems to be very difficult in AutoFixture. But still, here's an attempt.

It fails because it does not want to make empty collections. I need to explicitly write a case to fix this behavior. I'd almoste be better off populating the members with random data myself:

        private IEnumerable<Order> CreateOrdersWithLines(int collectionSize)
        {
            var fix = new Fixture();
            var lineCount = 0;

            for (var i = 0; i < collectionSize; i++)
            {
                var order= fix
                    .Build<Order>()
                    .With(o => o.Lines, fix.CreateMany<OrderLine>(lineCount).ToArray())
                    .Create();
                lineCount= ritCount++ % 5;
                yield return order;
            }
        }

**Comment by ploeh** [comment]
It may very well be that it's too restrictive to prohibit *0* as a `count` value... Perhaps we've been a bit overzealous here...

In *some* sense, the current behaviour makes sense, as there isn't much *'many'* about 0, but the same could be said about *1*, which we *do* accept...

@moodmosaic, @adamchester, @ecampidoglio, do you think it's reasonable to loosen the argument check slightly, allowing *0* as well, but still prohibiting negative numbers?

**Comment by moodmosaic** [comment]
IMO it makes sense to also allow *0* – I've never had to set `RepeatCount` to *1*, or *0*, but since *1* is allowed, *0* should also be allowed.

--

(Also, *I think*, it looks like a [POLA](http://en.wikipedia.org/wiki/Principle_of_least_astonishment) violation, if one can set `RepeatCount` to *1* but *can't* set it to *0*.)

**Comment by ecampidoglio** [comment]
I'd make the argument that if you need to do `CreateMany<T>(0)` why not just use `Enumerable.Empty<T>()`?

Besides, you wouldn't get any value out of using AutoFixture if all you need is an empty sequence.

**Comment by realbart** [comment]
@ecampidoglio I initially misread "Allowing  0  would be way to be liberal" :-)
I usualy hate it when somebody codes "if (x.length != 0) foreach (var y in x) DoSomething(y);"
To me, the empty collection is still a collection. So I would never expect an empty collection to behave differently than collections contining members.

Maybe my example has a more simple solution. For now, I need to write:

    private IEnumerable<Order> CreateOrderWithLines(int collectionSize)
    {
        var fix = new Fixture();
        var lineCount = 0;

        for (var i = 0; i < collectionSize; i++)
        {
            var order= fix
                .Build<Order>()
                .With(o => o.Lines, 
                    (
                        linecount == 0 
                        ? Enumerable.Empty<OrderLine>()
                        : fix.CreateMany<OrderLine>(lineCount)
                    ).ToArray())
                .Create();
            lineCount= ritCount++ % 5;
            yield return order;
        }
    }

**Comment by ploeh** [comment]
It seems like the majority of us (including me) is *for* making the change, allowing *0* as a `count` value. The change is now up for graps :smile:

**Comment by ztsmith** [comment]
CreateMany still seems to throw an exception with count of zero. The exception comes from the  FiniteSequenceRequest constructor: https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Kernel/FiniteSequenceRequest.cs

I'm happy to send a pull request for this, just wanted to make sure I wasn't missing something.

**Comment by ploeh** [comment]
Oh, dear, that should teach us to do a full repro of the reported issue, instead of just assuming that it'll work because we change things in a single place :flushed:

A PR would be welcome :+1: 

Sorry about that.

**Comment by moodmosaic** [comment]
Thank you, @ztsmith. – Good catch :+1:

**Comment by kim07** [comment]
:+1:

**Comment by ploeh** [comment]
Can we close this issue now, I wonder...?

**Comment by moodmosaic** [comment]
I think, it makes sense now to close it. @realbart do you agree?

**Comment by ploeh** [comment]
Despite two PRs *related* to this issue, none of them actually reproduce it, so we haven't seen demonstrated whether or not the original issue is resolved...

**Comment by realbart** [comment]
@moodmosaic I'm allright with closing it. Thanks for fixing it.
