### ISSUE TITLE
AutoDataAttribute not compatible with xunit 2.0.0.

### ISSUE THREAD

**Issue by jimmymain** [AutoFixture/AutoFixture#366]
Hi,

xunit 2.0.0 has been released, and some of the classes in xunit extensions have been moved.
The latest nuget package for AutoFixture.Xunit is not compatible.

**Comment by moodmosaic** [comment]
Thank you for reporting this. – You may track *AutoFixture.Xunit2* progress [here](https://github.com/AutoFixture/AutoFixture/pull/294).

**Comment by ploeh** [comment]
Perhaps we should change the .nuspec version requirements for the AutoFixture.Xunit package to explicitly be less than xunit 2.0.0, if that's possible.

**Comment by moodmosaic** [comment]
Yes, that's a very good idea.

**Comment by jimmymain** [comment]
Hi,

I have built the pull request, and can report that the tests do seem to work with one very important caveat.

The test explorer battles to report back the results of some of the tests. AutoFixture (or perhaps another component) seems to be changing the name of the test to include some of the data, for example, I get this error in the output window when running the tests.

xunit2 Test adapter sent back a result for an unknown test case. Ignoring result for 'Messages.DownstreamLoginMessageTests.TestLoginMessageOnNonWorkingDayThrowsException(date: 2016-02-27T20:21:53.2560541)'.

It would seem that the test explorer is adding the auto generated date parameter into the name of the test. This occurs when choosing run all tests in test explorer. If however I manually select every test, and then select 'run selected tests' it seems to use the correct test names. I'ts particularly noticeable with string parameters that contain GUID values. Unfortunately this means one cannot be certain that all the tests have actually passed.

I suspect therefore, that the integration is not quite 100% yet.
If you look in the test explorer after running all the tests you will notice the test names have parameter values added to them.

I am going to wait a little longer before upgrading.

**Comment by moodmosaic** [comment]
This looks like an issue related to either xUnit.net runner for Visual Studio or Visual Studio Test Explorer itself...

The `build-release` script uses the xUnit.net console runner and runs without warnings (on my machine).

**Comment by adamchester** [comment]
@jimmymain have you tried using the xunit visual studio runner (like #363)?

**Comment by jimmymain** [comment]
That's the runner I am using.
xunit.runner.visualstudio      2.0.0-rc1-build1030  Includes support for running xUnit.net v1 and v2 tests from Visual Studio 2012+.                                      

I am using the nuget package to install the runner, and using the regular visual studio test explorer. That is where I am experiencing the problem.

**Comment by TeaDrivenDev** [comment]
I agree that this looks very much like a test adapter issue.

@jimmymain You are using a pre-release version of the test runner; there have been three more release candidates plus the actual release after that. You may want to check whether the problem still occurs with the final 2.0.0 release. Generally make sure all your xUnit 2 bits are 2.0.0 **final** (but NuGet should enforce that anyway if you use the PR).

**Comment by jimmymain** [comment]
Autofixture remains incompatible with xunit 2.0.0.
Perhaps another issue needs to be created?

**Comment by ploeh** [comment]
@jimmymain, as @moodmosaic [described March 31](https://github.com/AutoFixture/AutoFixture/issues/366#issuecomment-87978249), that [issue already exists](https://github.com/AutoFixture/AutoFixture/pull/294).

**Comment by ploeh** [comment]
FWIW, @TeaDrivenDev has been so kind to create a [place-holder issue](https://github.com/AutoFixture/AutoFixture/issues/375) to track progress on this feature.
