### ISSUE TITLE
MockRelay and abstract circular dependencies

### ISSUE THREAD

**Issue by dcastro** [AutoFixture/AutoFixture#369]
Given the following abstract class with a circular dependency:

    public abstract class RecursiveAbstract
    {
        public abstract RecursiveAbstract Prop { get; set; }
    }

The following test passes as expected:

    [Fact]
    public void ResolveResursiveAbstract()
    {
        var fixture = new Fixture().Customize(new AutoConfiguredMoqCustomization());
        fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList()
            .ForEach(b => fixture.Behaviors.Remove(b));
        fixture.Behaviors.Add(new OmitOnRecursionBehavior(1));

        fixture.Create<RecursiveAbstract>();
    }

However, the following test fails:

    [Fact]
    public void ResolveMockOfResursiveAbstract()
    {
        var fixture = new Fixture().Customize(new AutoConfiguredMoqCustomization());
        fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList()
            .ForEach(b => fixture.Behaviors.Remove(b));
        fixture.Behaviors.Add(new OmitOnRecursionBehavior(1));

        fixture.Create<Mock<RecursiveAbstract>>();
    }

```
Ploeh.AutoFixture.ObjectCreationExceptionAutoFixture was unable to create an instance from Ploeh.AutoFixture.AutoMoq.UnitTest.QuickTest+RecursiveAbstract, most likely because it has no public constructor, is an abstract or non-public type.
```

(Note: at the moment, the user can work around the issue by using `Mock.Get(fixture.Create<RecursiveAbstract>())` instead)

To find out where the problem was, I followed the request path and found this:
```
SeededRequest(typeof(Mock<RecursiveAbstract>), null)
 -> typeof(Mock<RecursiveAbstract>)
 -> PropertyInfo "Prop"
 -> SeededRequest(PropertyInfo "Prop", "Prop")
 -> typeof(RecursiveAbstract)
 -> typeof(Mock<RecursiveAbstract>)
```

That last request, is made by [MockRelay (line 83)](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoMoq/MockRelay.cs#L83)

```csharp
public object Create(object request, ISpecimenContext context)
{
    //...
    var t = request as Type;
    //...

    var m = MockRelay.ResolveMock(t, context);
    if (m == null)
        return new NoSpecimen(request);

    return m.Object;
}

private static Mock ResolveMock(Type t, ISpecimenContext context)
{
    var mockType = typeof(Mock<>).MakeGenericType(t);
    return context.Resolve(mockType) as Mock;
}
```

At this point, `OmitOnRecursionBehavior` intercepts this request and returns a `OmitSpecimen`.
The last line of `MockRelay.ResolveMock` will then attempt to cast `OmitSpecimen` to `Mock`, which will fail. Consequently, `MockRelay.Create` will return `new NoSpecimen(request)`.

This `NoSpecimen` is then caught by [`TerminatingWithPathSpecimenBuilder`](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Kernel/TerminatingWithPathSpecimenBuilder.cs#L86), which throws a `ObjectCreationException`.

To fix this, `MockRelay` must first check whether the value returned by `context.Resolve(mockType)` is a `OmitSpecimen` - if so, return it immediately. Only then should it try to cast the value to `Mock`.

I'll be submitting a PR to address this issue soon.

**Comment by ploeh** [comment]
As always, an exemplary bug report :+1:

**Comment by dcastro** [comment]
Thanks! :smile:

I think this bug raises an important issue: there are a few places in the framework where `null` and `OmitSpecimen` are simply not accounted for, and therefore treated as invalid specimens. [I'm guilty of this myself](https://github.com/AutoFixture/AutoFixture/pull/336#discussion_r23168674)!

In the past, it wasn't [deemed an issue](https://github.com/AutoFixture/AutoFixture/pull/336#discussion_r23496711), but perhaps the time has come to address this. 

If you're willing have these fixed now, I can come up with a list of places where `null` and `OmitSpecimen` are not properly validated and then fix them.

**Comment by ploeh** [comment]
It probably would be a good idea to fix these mistakes one at a time.

Yesterday, I was actually thinking about this, and the most likely places where this may have an impact could be some of the other Auto-Mocking Container Glue Libraries, which may have the same issue as this one... I haven't investigated, but it's conceivable.

**Comment by dcastro** [comment]
Are you suggesting we sweep the auto-mocking libraries first, and then move onto other libraries (as in, one library at a time)? Sorry, I'm not quite sure what you meant by "fix these mistakes one at a time".

**Comment by ploeh** [comment]
What I meant was this:

As we [previously discussed](https://github.com/AutoFixture/AutoFixture/pull/336#discussion_r23496711), it doesn't seem to be an issue in any other places, so couldn't we just change the behaviour one class at a time?

It's a potential defect waiting to happen, as you demonstrated here, so I agree that it may be a good idea to change the incorrect implementations, but are these changes breaking changes? I don't think they are, so we can gradually correct one class at a time.

Am I answering the wrong question?

**Comment by dcastro** [comment]
What I still don't understand about the "one at a time" bit (and I'm pretty sure this is me being dense) is whether we should fix a) a class at a time, *if and when* bugs such as this are reported or b) fix them all *now*, but in granular PRs, one PR for each class.

**Comment by ploeh** [comment]
Sorry if I was being vague. I meant "fix them [...] *now*, but in granular PRs, one PR for each class".

**Comment by dcastro** [comment]
Thank you for clarifying - sometimes I just need things spelled out to me :sweat: I'll start by looking into #395
