### ISSUE TITLE
Make EnumeratorRelay a default residue collector

### ISSUE THREAD

**Issue by dcastro** [AutoFixture/AutoFixture#374]
Should the `EnumeratorRelay` be added to the [default collection of residue collectors](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Fixture.cs#L116)?

I was planning on addressing the same issue as @mrinaldi did on PR #351, but for AutoMoq. I was going to simply add this line to both `AutoMoqCustomization` and `AutoConfiguredMoqCustomization`:

    fixture.ResidueCollectors.Add(new EnumeratorRelay());

But then it hit me: why not make it part of the default collection? It's just as important as the existing  `EnumerableRelay`. It's a cross-cutting concern, it's not tied to any specific mocking framework, or even mocking at all, and it would solve this issue for all the mocking glue libraries, including AutoFoq and AutoRhinoMock.

**Comment by ploeh** [comment]
Yes, that sounds like a good idea. Great observation :+1:

**Comment by ploeh** [comment]
Resolved in AutoFixture 3.26.0.
