### ISSUE TITLE
xUnit v2 coordination and progress

### ISSUE THREAD

**Issue by TeaDrivenDev** [AutoFixture/AutoFixture#375]
As adding support for xUnit.net v2 is going to consist of a good number of individual pull requests, and there may be the odd question to discuss for which there is no specific pull request (yet), I'm setting up this issue to track the current progress and discussion.

The list of planned steps/pull requests is as follows (**bold = currently open**):
- [x] Switch to xUnit v2 MSBuild runner
- [x] Create solution for xUnit v2 glue library
- [x] Install xUnit v2 NuGet packages
- [x] Add CustomizeAttribute
- [x] Add AutoDataAttribute 
- [x] Add dependency constraints tests and building the xUnit v2 glue library NuGet package to the build process
- [x] Add FrozenAttribute
- [x] Add GreedyAttribute, ModestAttribute and NoAutoPropertiesAttribute
- [x] Add FavorArraysAttribute, FavorEnumerablesAttribute and FavorListsAttribute
- [x] Add CompositeDataAttribute
- [x] Add InlineAutoDataAttribute and scenario tests

**Comment by ploeh** [comment]
:+1:

**Comment by TeaDrivenDev** [comment]
The first question I have is this:

When integrating the new projects into the build process (to allow for verifying correct compilation and running the tests), I would currently also enable creation of the NuGet package. However, this may not be ideal with respect to releasing other things in the mean time, because for at least a few days, the full build would create an incomplete xUnit v2 package.

Should I regard creating the NuGet package as a final step after all the "content" has been added?

**Comment by ploeh** [comment]
> Should I regard creating the NuGet package as a final step after all the "content" has been added?

I think it would make sense to wait a bit with defining the *AutoFixture.Xunit2* NuGet package until something can go into it.

It doesn't have to be a feature complete port of *AutoFixture.Xunit* before that can happen, but at the very least I think it needs to have the `AutoDataAttribute`. Then we could pretty much rev from there, couldn't we?

**Comment by moodmosaic** [comment]
>Then we could pretty much rev from there, couldn't we?

Agreed.

And after that we could have the `CompositeDataAttribute` and so on.

**Comment by ploeh** [comment]
The next-most important feature, after `AutoDataAttribute` itself, is, IMO, `FrozenAttribute`. Judging by blog posts, the new Pluralsight course, etc. that's what everybody uses, including yours truly.

**Comment by TeaDrivenDev** [comment]
If you'd like to build it up that way, that certainly makes sense. Are there more prioritizations you'd like to make? (Most things are not dependent on each other, so I guess we're pretty free in defining the order.)

**Comment by ploeh** [comment]
*My* priority is like this:

1. `[AutoData]`
2. `[Frozen]` (which means that first, we need `CustomizeAttribute`, IIRC)
3. `[InlineAutoData]` (which means that first, we need `CompositeDataAttribute`)
4. `[Modest]` and `[Greedy]`

From there, the other features are so exotic that I don't think the ordering matters.

**Comment by TeaDrivenDev** [comment]
Good. I have reordered the list to signify this tentative order of adding features.

**Comment by moodmosaic** [comment]
Yeap, the priority proposed by @ploeh is fine! :smiley:

**Comment by TeaDrivenDev** [comment]
I have streamlined the rest of the plan a little; I don't think we need that many individual pull requests that each only add a single short attribute class and a similarly short test file, do we?

I have also moved `CompositeDataAttribute` and `InlineAutoDataAttribute` to the end of the list. While those are among the more important features, they are the only ones that cannot remain entirely unchanged and I'm still having some issues with.

**Comment by moodmosaic** [comment]
@TeaDrivenDev Nice!

FWIW [`CompositeDataAttribute` currently uses the `Zip` and `Select`](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture.xUnit.net/CompositeDataAttribute.cs#L77-L80) functions that @alexfoxgill added a couple of weeks back.

(Just to be sure you're not struggling with my old procedural implementation of `CompositeDataAttribute`.) :wink:

**Comment by TeaDrivenDev** [comment]
That's actually the problem I'm having - the old implementation worked right away, but with the new one I get arrays nested one level too deep in one or two tests. I'll have a look at it again, and if I can't figure it out, I'll send a pull request not for merging but for solving the problem. ;-)

**Comment by TeaDrivenDev** [comment]
So, I think we are done here, and this can be closed. Thanks @ploeh and @moodmosaic for your review and guidance, and @alexfoxgill for catching that one small thing that eluded us all.

**Comment by ploeh** [comment]
Fabulous :birthday: :cocktail:

**Comment by moodmosaic** [comment]
Great work! :bowtie:
