### ISSUE TITLE
incorrect test names when using autodata and xunit.testrunner.visualstudio

### ISSUE THREAD

**Issue by jimmymain** [AutoFixture/AutoFixture#392]
Hi,

I have updated to xunit 2 - thanks for all the work on this, it's great.
I am still having trouble with `autodata`, and `xunit.testrunner.visualstudio`.

Given a test like this:
```
        [Theory, AutoData]
        public void TestLastCommittedDsMessageDictionary(int x, int y)
        {
        {
```

In the visual studio test explorer the test is listed with its **name** containing an x and y value.
LastCommittedMessageTests.TestLastCommittedDsMessageDictionary(x: 30, y: 194)

Because `autodata` changes the test values on each test run, the test name doesn't match up with the name in test explorer.

I get this error message in the test output window. The value for x and y have changed, and therefore the test is not recognized as the same one that just executed.
```
Test adapter sent back a result for an unknown test case. Ignoring result for 
'LastCommittedMessageTests.TestLastCommittedDsMessageDictionary(x: 109, y: 97)'.
```

As you can see the **30 and 194** changed in the next test execution to **109 and 97**.
The test explorer doesn't match up the test.

**Comment by moodmosaic** [comment]
Thank you for reporting this. This looks more like an issue related to the xUnit.net Test Runner for VS.

**Comment by adamchester** [comment]
I have observed this behaviour too. I wonder if @bradwilson would like to comment?

**Comment by moodmosaic** [comment]
(Always wondering *...why just don't use the [TestDrive.Net add-in](http://www.testdriven.net/)*.) :smiley:

**Comment by ploeh** [comment]
How does it work with xUnit.net 1.x?

**Comment by bradwilson** [comment]
So, let's talk about pre-discovery.

xUnit.net v1 with theories never pre-discovered the theory data. There was only a single runnable "test case" which ran all the data at once and reported multiple results for that test case.

xUnit.net v2 supports data pre-discovery. This means you will generally see an individual test case for each row of theory data, and you can run them individually. When using a runner like Visual Studio, these pre-discovered test cases can be run individually. However, when you choose "Run All", Visual Studio does not give you back the list the list of test cases, so it forces you to rediscover them.

The pre-discovery feature is intended for data which is (a) fast to discover, and (b) stable. Things like `InlineData` and `MemberData` usually fall into this bucket; data providers that pull data from expensive sources (like a SQL server) or randomly generate data (like `AutoData`) do not. The data discoverer for `AutoData`, therefore, should turn off pre-discovery. There is a method on [`IDataDiscoverer`](https://github.com/xunit/xunit/blob/3631e67cc6cccf28b23333661019733baeb80254/src/xunit.core/Sdk/IDataDiscoverer.cs) which indicates whether the discoverer wants to participate in pre-discovery. You should always be returning false for any data sets which are either (a) expensive and/or (b) unstable. (I realized while writing this that the XML doc comments only mention part (a) and not part (b), so I'll update that now.)

**Comment by ploeh** [comment]
@bradwilson Thank you for explaining that :+1: 

> The data discoverer for AutoData, therefore, should turn off pre-discovery.

As far as I understand what you're writing, we'd need to implement `IDataDiscoverer` somewhere. Should we just add an implementation of that interface to the *AutoFixture.Xunit2* library? Will it be picked up by convention, or should it be registered somewhere?

**Comment by bradwilson** [comment]
Right, implement `IDataDiscoverer`, and then decorate the data attribute with `[DataDiscoverer(...)]`. Example: [`InlineDataDiscovererAttribute`](https://github.com/xunit/xunit/blob/9464b84ab32959da8b5b16fa25541aa89a8dd6b6/src/xunit.core/InlineDataAttribute.cs#L12), [`InlineDataDiscoverer`](https://github.com/xunit/xunit/blob/9464b84ab32959da8b5b16fa25541aa89a8dd6b6/src/xunit.core/Sdk/InlineDataDiscoverer.cs)

[`DataDiscoverer`](https://github.com/xunit/xunit/blob/9464b84ab32959da8b5b16fa25541aa89a8dd6b6/src/xunit.core/Sdk/DataDiscoverer.cs) has both methods as virtual; since this is the default behavior you're already using, you could use it as a base class and just override `SupportsDiscoveryEnumeration`.

**Comment by ploeh** [comment]
@bradwilson, thank you, it's all clear now :+1: 

Converting this issue to a feature that's up for grabs for anyone wanting to take it :smile:

**Comment by adamchester** [comment]
I'll see if I can tackle this now :smile:
