### ISSUE TITLE
AutoConfiguredNSubstituteCustomization throws ObjectCreationException when it can't populate a mock's property/method return value

### ISSUE THREAD

**Issue by alexfoxgill** [AutoFixture/AutoFixture#394]
One of my interfaces exposes an `Expression<Func<...>>` as a method return value. When using `AutoConfiguredNSubstituteCustomization` to generate a mock of this interface, AutoFixture is unable to create an instance. That's fine, I don't need it to create an instance as I can do this myself, but what I would like it to do is **ignore** the method, rather than receive an ObjectCreationException. Perhaps [this method](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoNSubstitute/NSubstituteVirtualMethodsCommand.cs#L185-L198) could swallow the exception?

**Comment by dcastro** [comment]
I don't think the fixture should silently ignore the fact that it failed to setup a method... 
Would injecting a hand crafted `Expression<Func<...>>` solve your problem?

```csharp
fixture.Inject<Expression<Func<int>>>(() => 5);
fixture.Create<MyInterface>():
```

**Comment by alexfoxgill** [comment]
I'm using the customization in an xUnit theory, and then immediately setting the expression in the test setup. I suppose I could include a customization that sets all `Expression<Func<...>>` to a standard value, but I'd rather be able to specify that it doesn't get set at all. I understand that you'd not want to do this in all cases, but I'd like the option to do it when it makes sense for me.

I tried adding a custom `SpecimenBuilder` to omit expressions:

```CSharp
public class OmitExpressionsSpecimenBuilder : ISpecimenBuilder
{
    public object Create(object request, ISpecimenContext context)
    {
        var t = request as Type;
        if (t == null || !t.IsGenericType)
            return new NoSpecimen();

        var genericType = t.GetGenericTypeDefinition();
        if (genericType != typeof (Expression<>))
            return new NoSpecimen();

        return new OmitSpecimen();
    }
}
```

However, this resulted in an `InvalidCastException`:

> Unable to cast object of type 'Ploeh.AutoFixture.Kernel.OmitSpecimen' to type 'System.Linq.Expressions.Expression`1...

Do you think the SpecimenBuilder should work?

**Comment by dcastro** [comment]
I think it should, and I think the exception you're getting may be related to issue #369

**Comment by alexfoxgill** [comment]
Yes I think you're right - how funny that you found an equivalent bug just last week :) in that case I'll close this issue and use an OmitSpecimen in future
