### ISSUE TITLE
System.OverflowException : Value was either too large or too small for a Decimal.

### ISSUE THREAD

**Issue by taylorc** [AutoFixture/AutoFixture#4]
With a model similar like 

```
public class Product {

    [HiddenInput(DisplayValue=false)]
    public int Id { get; set; }

    [Required(ErrorMessage = "Please enter a product name")]
    public string Name { get; set; }

    [Required(ErrorMessage = "Please enter a description")]
    [DataType(DataType.MultilineText)]
    public string Description { get; set; }

    [Required]
    [Range(0.01, double.MaxValue, ErrorMessage = "Please enter a positive price")] 
    public decimal Price { get; set; }

    [Required(ErrorMessage = "Please specify a category")]
    public string Category { get; set; }

    public string ImageName { get; set; }

    [HiddenInput(DisplayValue = false)]
    public string ImageMimeType { get; set; }
}
```

and in my test
     _fixture = new Fixture().Customize(new MultipleCustomization());
     _fixture.CreateAnonymous<'Product'>();

When the CreateAnonymous<'Product'>() code is run. I get a System.OverflowException : Value was either too large or too small for a Decimal. 

Trying to workout whether it's a bug or user error.

Sorry had to add the '' in to get the generic type to show up.

**Comment by tdwright-itg** [comment]
Hi @ploeh. First off, love Autofixture - thanks for your work!

I'm experiencing the same error as @taylorc, but am working with a very complex object structure. Is there any way to find out which field is the culprit?

The stack trace mentions the create method of your `RangeAttributeRelay` class - am I correct to infer that this implies my issue will be similar to @taylorc?

Any help would be greatly appreciated!

Tom

**Comment by zvirja** [comment]
@tdwright-itg Could you please fire a new issue and provide a code sample with stack trace?
This one was closed long time ago - it's better to let it have a rest 😉

**Comment by tdwright-itg** [comment]
Haha! No problem. Will do.
