### ISSUE TITLE
AutoConfiguredNSubstituteCustomization cannot set up override using Arg matching

### ISSUE THREAD

**Issue by alexfoxgill** [AutoFixture/AutoFixture#405]
Substitutes created with the fixture using `AutoConfiguredNSubstituteCustomization` cannot subsequently be overridden using NSubstitute's `Arg` matching facility.

The following five test cases are all variations of the theme

### Test Case 1: Pass
This test already exists in the project [here](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoNSubstituteUnitTest/AutoConfiguredFixtureIntegrationTest.cs#L282). It sets up a substitute, calls a method, then mocks the method and calls it again to check that the returned value is the same as the mock. So far, so good!

```CSharp
[Fact]
public void SetupCallsOverrideValueFromFixture()
{
    var fixture = new Fixture().Customize(new AutoConfiguredNSubstituteCustomization());
    var substitute = fixture.Create<IInterfaceWithMethod>();
    var anonymousString = fixture.Create<string>();
    var result1 = substitute.Method(anonymousString);

    var expected = fixture.Create<string>();
    substitute.Method(anonymousString).Returns(expected);

    var result2 = substitute.Method(anonymousString);

    Assert.NotEqual(result1, result2);
    Assert.Equal(expected, result2);
}
```

### Test Case 2: Pass
This is the same as the original test case, but *without* the initial call to the substitute's method. It still passes.

```CSharp
[Fact]
public void SetupCallsOverrideValueFromFixture2()
{
    var fixture = new Fixture().Customize(new AutoConfiguredNSubstituteCustomization());
    var substitute = fixture.Create<IInterfaceWithMethod>();
    var anonymousString = fixture.Create<string>();
    //var result1 = substitute.Method(anonymousString);

    var expected = fixture.Create<string>();
    substitute.Method(anonymousString).Returns(expected);

    var result2 = substitute.Method(anonymousString);

    //Assert.NotEqual(result1, result2);
    Assert.Equal(expected, result2);
}
```

### Test Case 3: Fail
The above test case passes, but when we use NSubstitute's `Arg.Any<>` matching parameter to mock the method return, it *doesn't* return the expected result

```CSharp
[Fact]
public void SetupCallsOverrideValueFromFixture3()
{
    var fixture = new Fixture().Customize(new AutoConfiguredNSubstituteCustomization());
    var substitute = fixture.Create<IInterfaceWithMethod>();
    var anonymousString = fixture.Create<string>();
    //var result1 = substitute.Method(anonymousString);

    var expected = fixture.Create<string>();
    substitute.Method(Arg.Any<string>()).Returns(expected);

    var result2 = substitute.Method(anonymousString);

    //Assert.NotEqual(result1, result2);
    Assert.Equal(expected, result2);
}
```

### Test Case 4: Fail
It's a similar story for the `Arg.Is<>` parameter matcher.

```CSharp
[Fact]
public void SetupCallsOverrideValueFromFixture4()
{
    var fixture = new Fixture().Customize(new AutoConfiguredNSubstituteCustomization());
    var substitute = fixture.Create<IInterfaceWithMethod>();
    var anonymousString = fixture.Create<string>();
    //var result1 = substitute.Method(anonymousString);

    var expected = fixture.Create<string>();
    substitute.Method(Arg.Is<string>(_ => true)).Returns(expected);

    var result2 = substitute.Method(anonymousString);

    //Assert.NotEqual(result1, result2);
    Assert.Equal(expected, result2);
}
```

### Test Case 5: Pass
This is where it gets interesting. By uncommenting the first call to `substitute.Method`, we can use the `Arg.Any<>` matcher to return the expected value. It's not clear what's going on behind the scenes in NSubstitute here, but my guess is that calling the method somehow clears it for future stubbing.

```CSharp
[Fact]
public void SetupCallsOverrideValueFromFixture5()
{
    var fixture = new Fixture().Customize(new AutoConfiguredNSubstituteCustomization());
    var substitute = fixture.Create<IInterfaceWithMethod>();
    var anonymousString = fixture.Create<string>();
    var result1 = substitute.Method(anonymousString);

    var expected = fixture.Create<string>();
    substitute.Method(Arg.Any<string>()).Returns(expected);

    var result2 = substitute.Method(anonymousString);

    Assert.NotEqual(result1, result2);
    Assert.Equal(expected, result2);
}
```

I hope that I explained the problem clearly! I took a look at the `AutoConfiguredNSubstituteCustomization` but I don't have any knowledge of the NSubstitue codebase so it was quite difficult to understand what was going on at a glance. Hopefully if I get some time I'll do some more in-depth reading.

**Comment by jrnail23** [comment]
Try using `AutoNSubstituteCustomization` along with it, but add it before `AutoConfiguredNSubstituteCustomization`:

```csharp
var fixture = new Fixture()
    .Customize(new AutoNSubstituteCustomization())
    .Customize(new AutoConfiguredNSubstituteCustomization());
```

**Comment by alexfoxgill** [comment]
Well, that seemed to work - is this the intended usage, or just a workaround?

**Comment by jrnail23** [comment]
I can't speak to the intended usage, but I just happened to run into the same issue yesterday, and it worked for me.  I don't think I'd call it a workaround in the "hack" sense -- it's just how those two customizations work WRT their use of residue collectors and the order in which types are resolved.
It did catch me by surprise a little, though.

**Comment by ploeh** [comment]
FWIW, I don't think that's the intended usage. Perhaps @mrinaldi or @dcastro have some insights into the matter.

**Comment by mrinaldi** [comment]
This is definitely not the intended usage and although it works in these scenarios, it will break others.

I've taken a look into this issue. It seems to have been broken since the change to support OmitSpecimen.
What happens is that when you use the argument matchers (``Arg.Any()`` and ``Arg.Is()``), NSubstitute assumes you are setting up a call and it will not call the already setup callbacks at all. Thus, when you call the method, AutoConfiguredNSubstitute will be called for the first time, overriding the already setup value.

I need more time to investigate further this issue and see what can be done to resolve it.

BTW, the best workaround is to make a call to the method using the same parameters you are using in the exercise/act phase before you setup the method using the argument matchers, just like @alexfoxgill does in Test Case 5.

**Comment by alexfoxgill** [comment]
@mrinaldi can you recommend a workaround for the case where I don't have a reference to the parameter that will be passed?
