### ISSUE TITLE
RandomNumericSequenceGenerator.Create throws ArgumentOutOfRangeException when limits are not ascending

### ISSUE THREAD

**Issue by Pvlerick** [AutoFixture/AutoFixture#408]
Simple repro:

```C#
[Fact]
public void ConstructorShouldThrow()
{
    var fixture = new Fixture();
    fixture.Customizations.Add(new RandomNumericSequenceGenerator(8, 3));

    fixture.Create<int>();
}
```

This is probably a bug as line 162 of [RandomNumericSequenceGenerator](https://github.com/AutoFixture/AutoFixture/blob/20b91b313daba05fd51714323ad0575e4f25d8c9/Src/AutoFixture/RandomNumericSequenceGenerator.cs) `this.random.Next((int)this.lower, (int)this.upper)` will throw an `ArgumentOutOfRangeException` when lower > upper.

The constructor documentation is a bit ambiguous; it states "A sequence of integers beginning with two positive or negative number optionally followed by a series of greater numbers." which doesn't say enough about the relation between the two first (second has to be equal or greater then the first). Actually the only constraint is that each number is >= than the previous.

I found this while investigating on #407.

I will send a PR.

**Comment by moodmosaic** [comment]
Good catch :+1: – Thank you for reporting this!
