### ISSUE TITLE
NumericSequenceGenerator internally uses Int32 as counter

### ISSUE THREAD

**Issue by Pvlerick** [AutoFixture/AutoFixture#410]
[NumericSequenceGenerator.cs](https://github.com/AutoFixture/AutoFixture/blob/20b91b313daba05fd51714323ad0575e4f25d8c9/Src/AutoFixture/NumericSequenceGenerator.cs) internally uses an Int32 for the value it keeps increasing and returning.

Wouldn't it be more appropriate to use an Int64/long so that when a long is requested there is a chance that it actually returns something that is in that space? For the moment it will never be a long with a value higher than Int32.MaxValue.

This might be more of a question, as they might be a good reason for it - and admittedly this generator would have to be hammered quit a bit before reaching Int32.MaxValue since it starts from 0 :-)

I found this while investigating on #407

**Comment by moodmosaic** [comment]
Thank you for reporting this. AFAICT, `NumericSequenceGenerator` shouldn't relate to #407, isn't it?

**Comment by Pvlerick** [comment]
I stumbled upon it while investigating and trying [this](https://github.com/AutoFixture/AutoFixture/issues/407#issuecomment-108200933).

But it is not strictly related.

**Comment by moodmosaic** [comment]
@Pvlerick should we close this now that #412 is merged? :smiley:

**Comment by Pvlerick** [comment]
Right on!
