### ISSUE TITLE
The 255th number returned by RandomNumericSequenceGenerator is always 255.

### ISSUE THREAD

**Issue by Pvlerick** [AutoFixture/AutoFixture#413]
I found something else while investigating #407

```C#
[Fact]
public void The255thDrawIsAlways255()
{
    // Fixture setup
    var dummyContext = new DelegatingSpecimenContext();
    var sut = new RandomNumericSequenceGenerator(1, 255);
    // Exercise system
    var result = Enumerable
        .Range(0, 256)
        .Select(_ => sut.Create(typeof(long), dummyContext))
        .Cast<long>()
        .ToList();
    // Verify outcome
    Assert.Equal(255, result[254]);
    // Teardown
}
```

First, notice that `GetNextRandom` method in `RandomNumericSequenceGenerator` uses `this.random.Next((int)this.lower, (int)this.upper)`, the upper bound in Random.Next being exclusive - the first 254 will be drawn between 1 and 254.

Next, in the `EvaluateRange` method, notice that the count check is done on `this.upper - this.lower`.

```C#
private void EvaluateRange()
{
    if (this.count == (this.upper - this.lower))
    {
        this.count = 0;
        this.CreateRange();
    }

    this.count++;
}
```

When comes the 255th draw, the `count` is 254 and upper = 255 and lower = 1, so the `if` is entered, and `count` is reset and the `CreateRange` method is called.

```C#
private void CreateRange()
{
    var remaining = this.limits.Where(x => x > this.upper - 1).ToArray();
    if (remaining.Any() && this.numbers.Any())
    {
        this.lower = this.upper;
        this.upper = remaining.Min() + 1;
    }
    else
    {
        this.lower = limits[0];
        this.upper = limits[1];
    }

    this.numbers.Clear();
}
```

The `remaining` variable will hold only one element: 255 (since it's bigger than `upper` (255) - 1) and `numbers` has 254 elements, so the `if` is entered.
In there, `lower` is set to `upper` (255) and upper is set to the minimum in `remaining` + 1 (256).

Next call to Random.Next will be with 255 and 256, so it'll always be 255.

I think this only happens with the initial lower and upper limits, but I have to check: I will investiage more when time permits. It seems it was discussed in #148 but I didn't have time to read the full discussion yet.

**Comment by Pvlerick** [comment]
After reading #148, I can that this issue was raised in the past but that no decision was taken on the upper limit being inclusive or exclusive.

However, the current behaviour is not consistent with the "ideal" algorithm described [here](https://github.com/AutoFixture/AutoFixture/issues/407#issuecomment-108552683).

**Comment by moodmosaic** [comment]
Thank you for reporting this!

Here's some QA that might help addressing this issue.

**Does it make the algorithm more predictable?**

I think it does. Should we care?

**Does it result into test code that is less robust?**

I think it doesn't.

**Is it a bug, the fact that the 255th number is always the same.**

Probably yes, although the guarantee is about the uniqueness, not the exact position. However if the 255th number is always the same, then it's a bug.

**Comment by Pvlerick** [comment]
As explained in #148, this can actually be extrapolated to

```C#
[Theory]
[InlineData(10)]
[InlineData(42)]
[InlineData(255)]
[InlineData(14865)]
public void TheUpperLimitThDrawIsAlwaysUpperLimit(int upper)
{
    // Fixture setup
    var dummyContext = new DelegatingSpecimenContext();
    var sut = new RandomNumericSequenceGenerator(1, upper);
    // Exercise system
    var result = Enumerable
        .Range(0, upper + 1)
        .Select(_ => sut.Create(typeof(long), dummyContext))
        .Cast<long>()
        .ToList();
    // Verify outcome
    Assert.Equal(upper, result[upper - 1]);
    // Teardown
}
```

__Should we care?__
I'm not sure. I guess nobody is using AutoFixture as their random number generator for cryptography related stuff :smile: 

I think it's a bug according to the specs

> Creates a sequence of random, unique, numbers starting at 1.

Since it can be predicted, it is not random.

I think it's a fun problem to think about, but fixing it is probably not going to make a difference, I believe.

**Comment by moodmosaic** [comment]
Agreed :smiley:

**Comment by ploeh** [comment]
Very thorough analysis, @Pvlerick :+1: I agree that this is a bug; I also think the point is well made that it may not be of the highest priority in terms of the main use case of AutoFixture. Still, it would be best to address it.
