### ISSUE TITLE
CreateAnonymousWithDoubleDateTimePropertiesWillAssignDifferentDates in FixtureTest behaves erraticaly

### ISSUE THREAD

**Issue by Pvlerick** [AutoFixture/AutoFixture#414]
While inspecting/merging #412, it became apparent that the [CreateAnonymousWithDoubleDateTimePropertiesWillAssignDifferentDates](https://github.com/AutoFixture/AutoFixture/blob/2aea953f6c4e532b3021579fb1f87605aa15e390/Src/AutoFixtureUnitTest/FixtureTest.cs#L1014) test is [erratic](http://xunitpatterns.com/Erratic%20Test.html)

The test creates a [`DoublePropertyHolder`](https://github.com/AutoFixture/AutoFixture/blob/2aea953f6c4e532b3021579fb1f87605aa15e390/Src/TestTypeFoundation/DoublePropertyHolder.cs) that hold two date and then checks that the dates of the two DateTime are different.

By default, Fixture uses the default constructor of [RandomDateTimeSequenceGenerator](https://github.com/AutoFixture/AutoFixture/blob/2aea953f6c4e532b3021579fb1f87605aa15e390/Src/AutoFixture/RandomDateTimeSequenceGenerator.cs#L35) that uses [Now -/+ 2 years](https://github.com/AutoFixture/AutoFixture/blob/2aea953f6c4e532b3021579fb1f87605aa15e390/Src/AutoFixture/RandomDateTimeSequenceGenerator.cs#L22) as limits, which in turn creates a [RandomNumericSequenceGenerator](https://github.com/AutoFixture/AutoFixture/blob/2aea953f6c4e532b3021579fb1f87605aa15e390/Src/AutoFixture/RandomNumericSequenceGenerator.cs#L47) with the ticks of [the upper and lower as limits](https://github.com/AutoFixture/AutoFixture/blob/2aea953f6c4e532b3021579fb1f87605aa15e390/Src/AutoFixture/RandomDateTimeSequenceGenerator.cs#L42).

My calculations are the following:
- One day is 864 000 000 000 ticks
- Four years is 1 262 304 000 000 000 = (365 * 4 + 1) * 864 000 000 000 -- the +1 being for the leap year

So, when drawing a random long from RandomNumericSequenceGenerator, we have __~1 262 304 000 000 000__ values to draw from, but since every __864 000 000 000__ will give us the same date, we have __1/1461__ chance to draw two ticks that are in the same range. It makes sense since there are 1461 days in four years.

I am not 100% sure of my calculations, but the following fails as often as it does not:

```C#
[Fact]
public void Test()
{
    var sut = new Fixture();
    for (int i = 0; i < 1461; i++)
    {
        var result = sut.Create<DoublePropertyHolder<DateTime, DateTime>>();
        Assert.NotEqual<DateTime>(result.Property1.Date, result.Property2.Date);
    }
}
```

I would be tempted to simply remove the test itself, since it basically is testing that we get numbers from RandomNumericSequenceGenerator.

**Comment by moodmosaic** [comment]
Thank you for reporting this :+1: This looks like an awesome analysis!

Based on the analysis you did, removing this test can be an option...

Thinking out loud, another option would be to change it, e.g. by creating a couple of `DateTime` instances and making sure that, at least, some of them are different.

**Comment by adamchester** [comment]
If we think of tests as documentation, is it really true that we expect/guarantee the `Date` part of the `DateTime` instances to be different? I'm not sure that's a valid guarantee we should make.

**Comment by moodmosaic** [comment]
@adamchester That makes it even more clear, that this test has to be either *fixed* or removed, isn't it?

**Comment by Pvlerick** [comment]
I tend to agree with @adamchester 

I didn't design this, but it seems a stretch to assume that two randomly generated DateTime will have a different date.

In the same vein, since it is generate from [ticks](https://msdn.microsoft.com/en-us/library/system.datetime.ticks(v=vs.110).aspx)

> A single tick represents one hundred nanoseconds or one ten-millionth of a second. There are 10,000 ticks in a millisecond, or 10 million ticks in a second.

Event comparing them to the millisecond wouldn't be enough, they would have to be compared to the ticks.

I think comparing the two DateTime themselves would work since they'll have different Ticks, no?

**Comment by adamchester** [comment]
how would we recommend users generate unique dates? Let's say we removed this test, it's possible that somebody was relying on it. What do we suggest they do instead?

**Comment by Pvlerick** [comment]
Then another generator is needed I am afraid.

RandomDateTimeSequenceGenerator will generate unique DateTime object since not the same tick will be used twice. Relying on part of that DateTime to be unique (in this case, year month and day) isn't a good idea nor guaranteed by that generator.

**Comment by adamchester** [comment]
Yeah, I think we should probably recommend they don't use `DateTime` at all if they expect their dates to be unique. Modelling the domain in that way doesn't reveal the fact that only the `Date` part is important or unique.

**Comment by adamchester** [comment]
This SO post by @ploeh is the closest I've found so far: http://stackoverflow.com/a/28633780/672329

**Comment by ploeh** [comment]
If you look at the Git log, you'll see that this test was last changed in the summer of 2011 (in 24109f1dc46534486325a8efe5e247bef7e037ad). Back then, `DateTime` values weren't generated by `RandomDateTimeSequenceGenerator`, but by `DateTimeGenerator` (a class that's still around). Back then, the test was correct.

There are three ways forward that I can identify

- Change the test so that it only compares `DateTime` instances, and not their `Date` properties.
- Change the test by first adding `DateTimeGenerator` to the `Fixture` instance.
- Both of the above.

**Comment by Pvlerick** [comment]
Looking at [CurrentDateTimeGenerator](https://github.com/AutoFixture/AutoFixture/blob/2aea953f6c4e532b3021579fb1f87605aa15e390/Src/AutoFixture/CurrentDateTimeGenerator.cs) ([DateTimeGenerator](https://github.com/AutoFixture/AutoFixture/blob/2aea953f6c4e532b3021579fb1f87605aa15e390/Src/AutoFixture/DateTimeGenerator.cs) is marked as deprecated), it seems to me that the test would still fail since it returns DateTime.Now - the two Dates will be identical.

At the time, [DateTimeGenerator](https://github.com/AutoFixture/AutoFixture/blob/24109f1dc46534486325a8efe5e247bef7e037ad/Src/AutoFixture/DateTimeGenerator.cs) was behaving differently: [it was adding one day between each call](https://github.com/AutoFixture/AutoFixture/blob/24109f1dc46534486325a8efe5e247bef7e037ad/Src/AutoFixture/DateTimeGenerator.cs#L30).

So I believe that leaves only option 1, which I think would make the test consistent with the current specification.

**Comment by ploeh** [comment]
Oh, we changed the behaviour of an existing class back then; that wasn't very [OCP](https://en.wikipedia.org/wiki/Open/closed_principle) of us :flushed: 

In that case I agree that the first of the options I outlined seems to be the most correct remedy.
