### ISSUE TITLE
Undefined behavior of FrozenAttribute combined with construction attributes like [Greedy], [Modest], [Favor?], etc.

### ISSUE THREAD

**Issue by olegsych** [AutoFixture/AutoFixture#420]
This topic was discussed in the previously closed thread #132. I'd like to reopen it in hope of discovering a solution. Here is the gist of it.

The CLR does not guarantee the order of attributes in assembly metadata. Because of that, combining the `FrozenAttribute` with construction attributes, like `GreedyAttribute` and `FavorListsAttribute`, produces undefined results. With the current implementation, one of the following two tests will always fail.

``` C#
using Ploeh.AutoFixture.Xunit2;
using Xunit;

public class Subject
{
    public Subject() { }
    public Subject(int greedy) { this.IsGreedy = true; }
    public bool IsGreedy { get; private set; }
    public override string ToString() { return "Subject " + this.GetHashCode().ToString(); }
}

public class UnitTest1
{
    [Theory, AutoData]
    public void FrozenAndGreedy([Frozen, Greedy] Subject p1, Subject p2)
    {
        Assert.Same(p1, p2);
        Assert.True(p1.IsGreedy);
    }

    [Theory, AutoData]
    public void GreedyAndFrozen([Greedy, Frozen] Subject p1, Subject p2)
    {
        Assert.Same(p1, p2);
        Assert.True(p1.IsGreedy);
    }
}
```

This behavior is a trap for those without deep understanding of both CLR and AutoFixture because "freezing" and "construction" are conceptually independent operations and combining two attributes like `[Frozen]` and `[Greedy]` feels natural. However, with the current implementation, one should _never_ apply these attributes to the same parameter at the risk of previously working tests starting to produce unpredictable results. I suspect that people will only learn about this problem after using AutoFixture for a while and accumulating a fair number of tests. By that time fixing the problem in the user code may be costly and they may have pulled out a few hairs trying to understand why the same test fails in different environments or starts failing in the same environment without obvious reasons.

**Comment by olegsych** [comment]
The undefined ordering of attribute metadata by the CLR probably cannot be fixed by AutoFixture :smile:. But I'm hoping that the current implementation of the `FreezingCustomization` used by the `[Frozen]` attribute implementations could be changed to solve this problem. 

[Today](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/FreezingCustomization.cs), it proactively creates the specimen at the `Fixture.Customize` time and stores in in a `FixedBuilder` inserted in the beginning of the `Fixture.Customizations` list. Since the `ConstructorCustomization` used by the `[Greedy]` and other construction attributes also inserts a builder in the beginning of the list, whichever attribute happens to be placed last by the CLR wins because its customization will end up on top of the list.

What if the `FreezingCustomization` is changed no longer create the specimen and rely on a behavior (a.k.a. `ISpecimenBuilderTransformation`) to capture it instead? Here is very rough sketch of what it might look like: 

```C#
public class FreezingCustomization : ICustomization
{
    public void Customize(IFixture fixture)
    {
        fixture.Behaviors.Add(new FreezingBehavior(this.targetType));
    }
}

public class FreezingBehavior : ISpecimenBuilderTransformation
{
    private readonly Type targetType;
    public ISpecimenBuilder Transform(ISpecimenBuilder builder)
    {
        return new FreezingBuilder(builder, this.targetType);
    }
}

public class FreezingBuilder : ISpecimenBuilder
{
    private readonly Type targetType;
    private readonly ISpecimenBuilder nextBuilder
    private object specimen;
    public object Create(object request, ISpecimenContext context)
    {
        if (request == this.targetType && this.specimen != null)
            return this.specimen;
        object specimen = this.nextBuilder.Create(request, context);
        if (this.targetType.IsAssignableFrom(specimen))
            this.specimen = specimen;
        return specimen;
    }
}
```

If I understand correctly, this would defer creation of the specimen from the `Fixture.Customize` time, when not all construction customizations have been added to the fixture yet, to a later `Fixture.Create` time, when the specimen is actually needed and all customizations had a chance to modify the fixture.

Thoughts?

**Comment by ploeh** [comment]
This might be a good idea.

The whole *Freeze* story in AutoFixture could do with an overhaul, and this is probably the best way to approach it.

There's no master plan behind the current Freeze implementations. I originally created the feature because I noticed that I kept using a Create/Inject combo, so I simply created a method that made that combination 'official'. Back then I struggled producing a good name, but finally settled on `Freeze`.

Only later did I realise that this feature was a rediscovery of the *Singleton lifestyle* (as described in my [DI book](http://amzn.to/12p90MG)).

As you point out, the only difference is that Freeze tends to eagerly create the value, whereas a proper implementation of the *Singleton lifestyle* would memoize the value upon first request.

I wouldn't mind going in that direction, but can't predict if it will produce breaking changes. It's worth a try, though.

**Comment by jrnail23** [comment]
I've started using my own composite attributes to give me control over these sorts of ordering issues.

Also, @ploeh, as I previously mentioned in #70, defining a way to do what Autofac calls "instance per lifetime scope" might be desireable, rather than only working with Singleton.

**Comment by sergeyshushlyapin** [comment]
It looks like I found pretty simple solution to the problem described by @olegsych (unless I'm missing something):
>The CLR does not guarantee the order of attributes in assembly metadata. Because of that, combining the FrozenAttribute with construction attributes, like GreedyAttribute and FavorListsAttribute, produces undefined results.

There is the `CustomizeFixture` method in the `AutoDataAttribute` class (if we talk about xUnit) which iterates through _all_ the parameter customizations and apply them one by one. That is a good place to tweak the attributes order and apply the _freezing_ customization when necessary.

I implemented it for xUnit2. Please let me know if you think that is the right way to go.

**Comment by sergeyshushlyapin** [comment]
@ploeh, in the meantime, could you please take a look on the suggested fix. There are two scenarios when the freezing customization is applied at a wrong time:

1. Unpredictable attributes order in CLR. It's **unstable** but appeared on the **same** specimen creation level, in our case [Customizations](https://github.com/AutoFixture/AutoFixture/wiki/Internal-Architecture#customizations).
- Inappropriate time to *freeze* a specimen.  It is **stable** and appears on **different** levels, e.g. Customizations (Freezing) and [Residue Collectors](https://github.com/AutoFixture/AutoFixture/wiki/Internal-Architecture#residue-collectors) (Moq, Substitute).

The fix tries to address the first one (according to the original issue subject).
