### ISSUE TITLE
Strong name sign the NUnit2 assemblies

### ISSUE THREAD

**Issue by mgasca** [AutoFixture/AutoFixture#423]
All other AutoFixture assemblies that I have used are strong name signed, but the NUnit2 ones are not.  This makes the assemblies unusable as-is in scenarios where the product/test assemblies are themselves strong name signed.  

To support using the NUnit2 assemblies in these scenarios I would like to request strong naming them along with the others.

**Comment by ploeh** [comment]
I don't know the reason that the NUnit2 assemblies aren't signed; could it be that we forgot?

IIRC, at least one AutoFixture assembly is unsigned: AutoFixture.AutoFoq. The reason for that is that Foq itself isn't signed.

It may be the case that there's a similar reason AutoFixture.NUnit2 isn't signed, but I find it more probable that we forgot to do it.

**Comment by ploeh** [comment]
Resolved in [AutoFixture.NUnit2 3.32.2](https://www.nuget.org/packages/AutoFixture.NUnit2/3.32.2) (f3b3dc8b3f6a4df53e77f8872735da3c085808c5).
