### ISSUE TITLE
fixture.Create fails to create a class with CulutreInfo property

### ISSUE THREAD

**Issue by hazzik** [AutoFixture/AutoFixture#427]
Culture is not supported.
Parameter name: name
namec923fee7-0d29-4ad3-b3f4-a54c9c9a40c2 is an invalid culture identifier.

**Comment by adamchester** [comment]
This seems like nice enhancement to support, creating culture infos.

@hazzik how would you expect it to work, by default? Create a random culture?

**Comment by hazzik** [comment]
I think either valid random or current culture.

**Comment by cvbarros** [comment]
I got around this problem by having a specific CultureInfoSpecimenBuilder
as follows:

public class CultureInfoSpecimenBuilder : ISpecimenBuilder
    {
        private readonly IRequestSpecification _specification;

        public CultureInfoSpecimenBuilder()
        {
            _specification = new ExactTypeSpecification(typeof
(CultureInfo));
        }

        public object Create(object request, ISpecimenContext context)
        {
            if (!_specification.IsSatisfiedBy(request))
                return new NoSpecimen(request);

            return Thread.CurrentThread.CurrentUICulture;
        }
    }

Hope it helps. Maybe it could be reused internally by AutoFixture.


2015-07-27 6:33 GMT-03:00 Alexander Zaytsev <notifications@github.com>:

**Comment by cvbarros** [comment]
I got around this problem by having a specific CultureInfoSpecimenBuilder
as follows:

```C#
public class CultureInfoSpecimenBuilder : ISpecimenBuilder
{
	private readonly IRequestSpecification _specification;

	public CultureInfoSpecimenBuilder()
	{
		_specification = new ExactTypeSpecification(typeof (CultureInfo));
	}

	public object Create(object request, ISpecimenContext context)
	{
		if (!_specification.IsSatisfiedBy(request))
			return new NoSpecimen(request);

		return Thread.CurrentThread.CurrentUICulture;
	}
}
```
Then use it to customize the `IFixture`: `fixture.Customizations.Add(new CultureInfoSpecimenBuilder());`
Hope it helps. Maybe it could be reused internally by AutoFixture.

**Comment by ploeh** [comment]
@cvbarros, couldn't you just do the following?

```C#
fixture.Customize(() => Thread.CurrentThread.CurrentUICulture);
```

BTW, IIRC, `CurrentUICulture` is almost never the correct value to use; `CurrentCulture` would probably be more appropriate.

**Comment by ploeh** [comment]
Culture is one of those nasty aspects that cause tests to run nicely for years, until someone comes by and runs them on a different culture. The simplest example may be parsing a decimal:

```F#
> Decimal.Parse("1.234", CultureInfo "da-DK");;
val it : decimal = 1234M
> Decimal.Parse("1.234", CultureInfo "en-US");;
val it : decimal = 1.234M
```

Given this, I don't think picking a *random* `CultureInfo` would be a good idea.

Using `Thread.CurrentCulture` probably wouldn't make things worse, as this is already the Ambient Context whenever culture isn't explicitly stated, but in the interest of keeping tests deterministic, I think [`CultureInfo.InvariantCulture`](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.invariantculture.aspx) would be more appropriate.

**Comment by cvbarros** [comment]
@ploeh I'm not sure if it's a version problem(using 3.16.5.0). I couldn't apply the exact suggestion, but this has worked:

```C#
fixture.Customize<CultureInfo>(
	ob => ob
		.FromFactory(() => CultureInfo.InvariantCulture)
		.OmitAutoProperties()
	);
```

Anyways, for me it was better to use the `CultureInfoSpecimenBuilder`. It just seemed easier to reuse in my case.

**Comment by ploeh** [comment]
@cvbarros, sorry, I wrote the above code snippet directly here without checking :flushed: 

I think it should be the following, but I haven't tried to compile that either:

```C#
fixture.Register(() => Thread.CurrentThread.CurrentUICulture);
```

**Comment by cvbarros** [comment]
Thanks @ploeh . I'd like to tackle this issue, if possible. I was thinking about creating a `InvariantCultureGenerator` and adding it to the `DefaultPrimitiveBuilders.GetEnumerator()`  method. What do you think about this approach? This would be my first contribution.

**Comment by ploeh** [comment]
That ought to work :+1:

**Comment by bjorn-ali-goransson** [comment]
FWIW, here's my take on a pseudo-random CultureInfo specimen builder


    public class CultureInfoSpecimenBuilder : ISpecimenBuilder
    {
        public List<CultureInfo> Cultures = CultureInfo.GetCultures(CultureTypes.AllCultures).Select(c => c.TwoLetterISOLanguageName).Distinct().Select(name => new CultureInfo(name)).ToList();
        public Random Random = new Random();

        public object Create(object request, ISpecimenContext context)
        {
            if (request is Type && (Type)request == typeof(CultureInfo))
            {
                return Cultures[Random.Next(0, Cultures.Count)];
            }

            if (request is SeededRequest && ((SeededRequest)request).Request is Type && (Type)((SeededRequest)request).Request == typeof(CultureInfo))
            {
                return Cultures[Random.Next(0, Cultures.Count)];
            }

            return new NoSpecimen();
        }
    }
