### ISSUE TITLE
AutoDataAttribute causes an InvalidOperationException

### ISSUE THREAD

**Issue by ferbraz89** [AutoFixture/AutoFixture#436]
I'm experiencing problems with a simple use of AutoData. AutoDataAttribute seems to cause or lead to an InvalidOperationException. Does anyone knows how to fix this problem? Is the AutoFixture's support for xUnit.net problematic?

I've tried several times to use the AutoData attribute, included in the extension, and always receive an exception of type InvalidOperationException.
Next I attach a link to a solution that tries to reproduce the problem: https://github.com/ferbraz89/UnitTestProjectWithAutofixtureAndXunit 

My best guess is that (maybe) the maintainer of the library needs to update his dependencies. Just to get noticed, I'm not the only one who has experienced issues (see Colin Bowern's comment on http://blog.ploeh.dk/2010/10/08/AutoDataTheorieswithAutoFixture/).

**Comment by moodmosaic** [comment]
As it looks like, you're trying to use xUnit.net 2 with AutoFixture.Xunit instead of *AutoFixture.Xunit2*.

You may *first* install [AutoFixture.Xunit2](https://www.nuget.org/packages/AutoFixture.Xunit2) via NuGet, which also installs the appropriate version of xUnit.net 2. Then you may install additional xUnit.net 2 packages, if you need them.

**Comment by sergeyshushlyapin** [comment]
Have you tried `Ploeh.AutoFixture.Xunit2`?

**Comment by ferbraz89** [comment]
Wow. I cannot believe I missed that. NuGet didn't show me an AutoFixture.Xunit2 available for install in first place, I searched wrong. My fault.  
However, ReSharper now says that the test using AutoData is inconclusive, and the Test Explorer can't  even find it. It seems to be related to visualstudio. I don't know.

**Comment by ploeh** [comment]
Does it work with other test runners (especially [xunit.runner.console](https://www.nuget.org/packages/xunit.runner.console))?

**Comment by ferbraz89** [comment]
Don't worry Mark, It works now. It was a version conflict between dependencies. Thanks a lot to Nikos and Sergey. You guys are genius. I'm really sorry to have wasted your time.
Thanks again !
