### ISSUE TITLE
Templating and References

### ISSUE THREAD

**Issue by Krizzzn** [AutoFixture/AutoFixture#438]
I'm trying to create 2 different complex objects based on the same template. My goal is to write a unit test, that makes sure that only specific properties can be updated by a function.

The problem is that Autofixture seems to create References instead of new objects. Here's a sample:
````
var template = _fixture.Build<Foo>()
                      .With(m => m.Id, 100)
                      .With(m => m.Prop2, "123")
                      .Without(m => m.FooContent)
                      .Create();

_fixture.Register<Foo>(() => template);

var subject= _fixture.Create<Foo>();
var expected = _fixture.Create<Foo>();

subject.Prop3 = 300;

if (expected.Prop3 == 300)
            throw new Exception("BOOM");
````

As AutoFixture user I would expect to receive a real object instead of references onto the my given template. 
Am I doing something wrong, or doesn't AutoFixture support this behaviour?

Edit: After giving it a second thought I guess this isn't easy. The main problem will be the deep copy, Still is there a way I could achieve this with Autofixture?

**Comment by ploeh** [comment]
> I would expect to receive a real object instead of references onto the my given template.

Why?

Let's try to take AutoFixture out of the picture:

```C#
var template = new Foo { Id = 100, Prop2 = "123" };

var sublect = template;
var expected = template;

subject.Prop3 = 300;
```

In this case, what would you say the value of `expected.Prop3` is?

**Comment by Krizzzn** [comment]
300. 
My point is that I would expect that AF gives me a new object on a Create<> call instead of a reference to my template. 
How it is currently implemented the Register<> call works only for structs. 

Please don't get my wrong - i really like AutoFixture. It saves a lot of time. I just wanted to bring this issue to your attention/ ask if there's a way to supply templates to AF that result in new Objects. Maybe I'm using it wrong.

**Comment by moodmosaic** [comment]
>As AutoFixture user I would expect to receive a real object instead of references onto the my given template.

No, it would be a POLA violation if AutoFixture didn't behave this way, since you are specifying *explicitly* that your object should be created in a particular way:

```
_fixture.Register<Foo>(() => template);
```

That is, you are specifying that, for all `Foo`, you need the `template` instance back.

**Comment by Krizzzn** [comment]
Point taken. 
Is there another way to make AF always return an object that has the same values set for consecutive calls to Create<>? Best without having to set up every property in advance. 
If not would that be a use-case for AF?

Please feel free to close this issue if you don't see such requirement...

**Comment by ploeh** [comment]
Does `Customize` do what you want to do?

```C#
fixture.Customize<Foo>(c => c
    .With(m => m.Id, 100)
    .With(m => m.Prop2, "123")
    .Without(m => m.FooContent));
```

**Comment by Krizzzn** [comment]
`Customize` is not the thing I'm looking for. When I've to call it for every property on my model I'd opt for writing less code by instantiating a new object with `new`.

My goal was to create a spec for a repository that has an `Update` method. The spec was supposed to make sure that the repository is only able to update a predefined set of properties. The model is expected to grow in the number of properties and I didn't want to go back to edit that test every time I add a new property. 

My Idea was to have AF create a template of my model. The template is then provided to AF to generate clones of exactly that setup. But I guess this is an edge case for which AF was never meant (maybe its even a stupid thing to do). 
Now I'm using serialization to create clones of my template.

Thank you for all your feedback. If you like you can close this issue.

**Comment by ploeh** [comment]
> a predefined set of properties

Where is this set predefined?

(I'm going to close the issue, because I don't think it belongs in the realm of AutoFixture, but feel free to keep the discussion going if you'd like.)
