### ISSUE TITLE
CultureInfo still doesn't work with non-customized Fixture instance

### ISSUE THREAD

**Issue by tiesmaster** [AutoFixture/AutoFixture#441]
I was happy to see the addition of the `InvariantCultureGenerator`, as a result of #427. I just upgrade one of our projects to the latest version, but unfortunately it throws.

I though it had something to do with my unit test project (it's also using `AutoConfiguredMoqCustomization`), but it can be reproduced with the following unit test, in a new project:

````csharp
        [Fact]
        public void CreateWithUsualPublicEntryPointCrashes()
        {
            var fixture = new Fixture();
            fixture.Create<CultureInfo>();
        }
````

Am I doing something wrong, perhaps?

[Full stacktrace](https://gist.github.com/tiesmaster/d7f6c27c7fdee58af033)

**Comment by ploeh** [comment]
Thank you for making me aware of that. It's quite an embarrassing oversight on my part, but it should now be fixed in [AutoFixture 3.34.2](https://www.nuget.org/packages/AutoFixture/3.34.2).

**Comment by tiesmaster** [comment]
Cool! I was already looking at the "composition root" in [Fixture.cs:63](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Fixture.cs#L63), how to fix that, but I didn't completely understood how that works. Do you have that documented somewhere, or a blogpost about how that works?

Thanks for the quick fix, btw :+1:

**Comment by ploeh** [comment]
Documentation is always the weak part, but there's the high-level architecture document that describes some of it: https://github.com/AutoFixture/AutoFixture/wiki/Internal-Architecture

HTH
