### ISSUE TITLE
Latest version of Frozen attribute no longer works with mocked instances

### ISSUE THREAD

**Issue by jchapuis** [AutoFixture/AutoFixture#447]
Somehow the latest version of the Frozen attribute (in 3.36.0 release), which features the new policy enumeration, no longer seems to work when freezing mocked interfaces.

For instance, for a `MyTheory([Frozen] Mock<IRepository> repository, SomeSut sut)`, with `SomeSut` constructor accepting `IRepository` in parameter, a new mocked instance will be created.

**Comment by ploeh** [comment]
Thank you for reporting this. That's certainly not the intent, but I haven't had time to investigate yet. I'm quite hung up the next couple of days, but if @ecampidoglio hasn't had time or inclination to look into it before, I'll get to it as soon as possible.

**Comment by ecampidoglio** [comment]
Thank you for reporting the issue. I'm on it.

**Comment by ecampidoglio** [comment]
Fixed in #448.

**Comment by ploeh** [comment]
Thank you, @ecampidoglio :+1:
