### ISSUE TITLE
Invalid cast from Int32 to DateTime

### ISSUE THREAD

**Issue by adriaanp** [AutoFixture/AutoFixture#452]
I'm getting this exception when calling Create. What is the best way to debug this to see which property this is crashing on? I've tried logging to a file but the stream just ends and never at the same place.

Any direction to try debug this would be appreciated.

**Comment by ploeh** [comment]
You should be able to troubleshoot using TracingBehavor:

```C#
fixture.Behaviors.Add(new TracingBehavior());
```

Depending on your context, you might need to be aware of this: http://stackoverflow.com/q/18602462/126014

**Comment by adriaanp** [comment]
Thanks this helped identifying the problem. We are using a custom DataAnnotation that inherits from RangeAttribute which is causing this problem for us.

Is there a way to tell AutoFixture not to look at DataAnnotation attributes?

**Comment by moodmosaic** [comment]
There are 2 options:
 * Remove support for *all* Data Annotation attributes
 * Remove support for a specific Data Annotation attribute

**Remove support for all Data Annotation attributes**

```csharp
var fixture = new Fixture().Customize(
    new NoDataAnnotationsCustomization());
```

**Remove support for a specific Data Annotation attribute**

Extrapolating from [NoDataAnnotationsCustomization](https://github.com/AutoFixture/AutoFixture/blob/f452f729e22c8c53f7e80833a342a84671e0edaa/Src/AutoFixture/NoDataAnnotationsCustomization.cs#L38-L42), it's possible to do this:

```csharp
fixture
    .Customizations
    .Where(c => c.GetType() == typeof(RangeAttributeRelay))
    .ToList()
    .ForEach(c => fixture.Customizations.Remove(c));
```

* RangeAttributeRelay corresponds to RangeAttribute
* StringLengthAttributeRelay corresponds to StringLengthAttribute
* RegularExpressionAttributeRelay corresponds to RegularExpressionAttribute

**Comment by ploeh** [comment]
Could a third option be to add a custom `ISpecimenBuilder` for the custom attribute?

**Comment by moodmosaic** [comment]
Yes, indeed. Though I'm not sure how different it would be from [the built-in one](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/DataAnnotations/RangeAttributeRelay.cs) that handles this particular attribute.

**Comment by ploeh** [comment]
We don't know, since we don't know how customised the derived attribute is.

@adriaanp, is there anything else we can do to help you?

**Comment by adriaanp** [comment]
Thanks we found a solution writing our own custom ISpecimenBuilder. :+1:

**Comment by ploeh** [comment]
@adriaanp, can we close the issue, then?
