### ISSUE TITLE
Creating nested generic interfaces

### ISSUE THREAD

**Issue by SeanFarrow** [AutoFixture/AutoFixture#454]
Hi,

In one of my tests I have a need to create a nested generic interface.
I can do this with NSubstitute as follows:
Substitute.For<ICommandHandler<ICommand>>();
When trying to do this with AutoFixture as follows:
Fixture.Create<ICommandHandler<ICommand>>();
I get the following exception: 
Riskscoper.Server.Core.Mediator.Tests.Commands.CommandExecuter.WhenAListOfCommandHandlersIsPassedInToTheConstructor (TestFixtureSetUp):
SetUp : Ploeh.AutoFixture.ObjectCreationException : AutoFixture was unable to create an instance from Riskscoper.Server.Core.Mediator.Contracts.Commands.ICommandHandler`1[Riskscoper.Server.Core.Mediator.Contracts.Commands.ICommand], most likely because it has no public constructor, is an abstract or non-public type.

Request path:
	  Riskscoper.Server.Core.Mediator.Contracts.Commands.ICommandHandler`1[Riskscoper.Server.Core.Mediator.Contracts.Commands.ICommand]
Could the ability to mock multiple generic interfaces be added, or does this already exist?
Any help appreciated.
Kind regards
Sean.

**Comment by ploeh** [comment]
Thank you for writing. At a glance, I don't think this error message has anything to do with nested generics, but simply the fact that AutoFixture is being asked to create an instance of an interface.

You can use one of the [Auto-Mocking Container](http://blog.ploeh.dk/2013/03/11/auto-mocking-container) Glue Libraries for AutoFixture to handle interfaces and abstract base classes - e.g. [AutoFixture.AutoMoq](http://blog.ploeh.dk/2010/08/19/AutoFixtureasanauto-mockingcontainer). You can find a [full list of AutoFixture packages on the front page of the repo](https://github.com/AutoFixture/AutoFixture#downloads).

**Comment by SeanFarrow** [comment]
Hi,

Thant worked a treat, feel free to close this.
Cheers
Sean.

**Comment by ploeh** [comment]
This seems to be a FAQ, so I've opened #455 in order to make the error message more helpful.
