### ISSUE TITLE
Make some InlineAutoDataAttribute constructor overloads protected

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#458]
`InlineAutoDataAttribute` has a constructor overload that takes an `AutoDataAttribute` as an argument.

As #457 implicitly points out, there's no way to use this constructor overload when using the `[InlineAutoData]` attribute to annotate tests.

This constructor overload only exists to enable a derived class to supply a custom, derived instance of `AutoDataAttribute`, thereby customizing the behaviour of the derived attribute. Since this constructor overload only exists to enable inheritance, we should consider changing its accessibility level to `protected`.

This is a breaking change, so can only be done in AutoFixture 4.

Note that this ought to be done for both *AutoFixture.Xunit* and *AutoFixture.Xunit2*.

**Comment by moodmosaic** [comment]
I'm going to take a look at this, and (hopefully) open a Pull Request over the next couple of days.

**Comment by moodmosaic** [comment]
I think we can now close this, since #462 is merged.

**Comment by ploeh** [comment]
Addressed by 5ac109164aa212c5963d620d3a4a166ebbe1096f
