### ISSUE TITLE
Test failure in AutoFixture.xUnit.net2 in Visual Studio

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#459]
When I open *AutoFixture.xUnit.net2.sln* in Visual Studio 2015 and attempt to run all tests with [TestDriven.Net](http://testdriven.net), I get this result:

```
------ Test started: Assembly: Ploeh.AutoFixture.Xunit2.dll ------

Test '' failed: File not found: C:\Users\mark\Documents\ploeh\AutoFixture\Src\AutoFixture.xUnit.net2\bin\Debug\xunit.execution.desktop.dll
Parameter name: assemblyFileName
	System.ArgumentException: File not found: C:\Users\mark\Documents\ploeh\AutoFixture\Src\AutoFixture.xUnit.net2\bin\Debug\xunit.execution.desktop.dll
	Parameter name: assemblyFileName
	at Guard.FileExists(String argName, String fileName)
	at Xunit.Xunit2Discoverer..ctor(ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink)
	at Xunit.Runner.TdNet.TdNetRunnerHelper..ctor(Assembly assembly, ITestListener testListener)
	at Xunit.Runner.TdNet.TdNetRunner.CreateHelper(ITestListener testListener, Assembly assembly)
	at Xunit.Runner.TdNet.TdNetRunner.RunAssembly(ITestListener testListener, Assembly assembly)
	at TestDriven.TestRunner.AdaptorTestRunner.Run(ITestListener testListener, ITraceListener traceListener, String assemblyPath, String testPath)
	at TestDriven.TestRunner.ThreadTestRunner.Runner.Run()

0 passed, 1 failed, 0 skipped, took 0,44 seconds (xUnit.net 2.0.0 build 2929).

------ Test started: Assembly: Ploeh.AutoFixture.Xunit2.UnitTest.dll ------
134 passed, 0 failed, 0 skipped, took 3,46 seconds (xUnit.net 2.0.0 build 2929).

------ Test started: Assembly: Ploeh.AutoFixtureUnitTest.dll ------
3691 passed, 0 failed, 0 skipped, took 12,02 seconds (xUnit.net 1.9.2 build 1705).

========== Total Tests: 3825 passed, 1 failed, 0 skipped, took 16,17 seconds ==========
```

The `build-release-sh` script runs without error, so it seems to be a Visual Studio-specific issue. It may also be present in other solutions, but I've yet to try. This seems to have been present at least since 7ab27e6dcbf4ee49a2a67cb0e4c0adb7e7fa5720, but I haven't attempted to trace it further back than that.

**Comment by adamchester** [comment]
So TestDriven.NET is attempting to discover tests in `Ploeh.AutoFixture.Xunit2.dll` which does not actually contain any tests we want to run. Could it be a bug in TestDriven.NET? Is not finding any tests really a test failure?

**Comment by ploeh** [comment]
That may be the case, but I'm quite sure it hasn't always done that. I'll try to ask Jamie Cansdale.

**Comment by moodmosaic** [comment]
That's strange, indeed... I also get the same result on my machine.

**Comment by tiesmaster** [comment]
I don't know if this is still an issue, but found the cause of this, at least.

It appears that xunit pulls in the `xunit.execution.desktop.dll` by a separate msbuild script, and loads it on demand. That's [present](https://github.com/AutoFixture/AutoFixture/blob/65f0d0010833b11c9f4312ab2c367dd271b0318c/Src/AutoFixture.xUnit.net2.UnitTest/AutoFixture.xUnit.net2.UnitTest.csproj#L3) in the unit test project, but missing from the other project. If you add that line, the error goes away.

I'm guessing that it was removed from the main project, when it was created. It might be that the expectation was there, that it would end up in the NuGet package that gets created out of this, and it was removed, just to be sure.

I could put [this commit](https://github.com/tiesmaster/AutoFixture/commit/5fb0d78267a00308b6e5cfbf077b32cb45bb99f2) in a PR, to fix it. I've verified that it doesn't get added to the NuGet package.

**Comment by moodmosaic** [comment]
:+1: I think that's the way to go. Thank you very much for investigating this!

**Comment by moodmosaic** [comment]
Sure, it'd be great with a Pull Request :smiley:

**Comment by bradwilson** [comment]
For a little bit of the why: https://github.com/AutoFixture/AutoFixture/pull/495#issuecomment-166767288
