### ISSUE TITLE
Add non-generic Create(Type) method

### ISSUE THREAD

**Issue by dotnetjunkie** [AutoFixture/AutoFixture#473]
I (ab)use Autofixture to generate documentation examples for a Web API. The messages (commands and queries) that Autofixture will create for me are serialized to JSON and become part of the documentation. This works really really well, and it takes a few lines of code, compared to the hundreds of lines of ugly code that the VS template for Web API generates in its /HelpPage area (yuck).

Currently I use the following code to achieve this:

``` c#
private static readonly MethodInfo CreateMethodInfo =
    GetMethod(() => SpecimenFactory.Create<int>(new Fixture()))
    .GetGenericMethodDefinition();

public static object Create(Type type)
{
    var fixture = new Fixture();
    int index = 1;
    fixture.Register(() => "sample text " + index++);

    return CreateMethodInfo.MakeGenericMethod(type).Invoke(null, new object[] { fixture });
}

private static MethodInfo GetMethod(Expression<Func<int>> methodCall) => 
    ((MethodCallExpression)methodCall.Body).Method;
```

Since I don't know the exact message at compile time, I can't call Autofixture's `Fixture.Create<T>()` method. As the above code shows, the way I currently solved this is by invoking this generic `Create<T>` method using reflection.

Is there a simpler way to do achieve my goal, and if not, could a non-generic `Create(Type)` method be added to the library?

**Comment by moodmosaic** [comment]
Would [this](http://stackoverflow.com/a/16547379/467754) solution work?

```c#
var specimen = new SpecimenContext(fixture).Resolve(type);
```

**Comment by dotnetjunkie** [comment]
Cool! That does the trick! Thanks.
