### ISSUE TITLE
AutoMoqCustomization and c# 6.0 autoproperties with initializers

### ISSUE THREAD

**Issue by flodpanter** [AutoFixture/AutoFixture#478]
Hi there. I am wondering what the correct behaviour should be in the below case. I expect the test to succeed, but this may not be the opinion of the Autofixture authors? 

     [TestMethod]
        public void Autofixture_and_autoproperties()
        {
            //ARRANGE
            //sut
            var f = new Fixture().Customize(new AutoMoqCustomization());

            //ACT
            var sut = f.Freeze<Animal>();
            //ASSERT
            sut.Name.Should().Be("Spot");
        }

        public class Animal
        {
            public string Name { get; set; } = "Spot";
        }

**Comment by ploeh** [comment]
The behaviour is correct; I expect the above test to fail.

While `Animal.Name` has a default value, it also has a writeable setter. Without AutoFixture, you can easily create an instance with a different name:

```C#
var sut = new Animal { Name = "Perry" };
```

In that case, `sut.Name` would *not* be "Spot", but "Perry".

By default, AutoFixture populates public writeable properties when it creates objects, which explains why `sut.Name` is *not* "Spot".

You can switch off this feature for an entire `Fixture` like this:

```C#
fixture.OmitAutoProperties = true;
```

or, you can do it as a one-off action:

```C#
var sut = fixture.Build<Animal>().OmitAutoProperties().Create();
```

Does this answer your question?

**Comment by flodpanter** [comment]
Thanks for the answer and the suggestions. It makes sense. :+1:
