### ISSUE TITLE
Invalid cast exception after installing 3.37.2

### ISSUE THREAD

**Issue by voroninp** [AutoFixture/AutoFixture#485]
Here is the stack trace:

>Test method Wumte.Server.Distribution.Core.UnitTests.InfoSec.InfoSecDistributionDbAccessorTest.GetTerminalsInfo_CorrectQueryLogic threw exception: 
>System.InvalidCastException: Invalid cast from 'System.DateTime' to 'System.Nullable`1[[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'.
>
>    at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
>   at System.DateTime.System.IConvertible.ToType(Type type, IFormatProvider provider)
>   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
>   at Ploeh.AutoFixture.Kernel.BindingCommand`2.ConvertIfAppropriate(Object candidate, Type targetType)
>   at Ploeh.AutoFixture.Kernel.BindingCommand`2.Execute(Object specimen, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.FilteringSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Dsl.NodeComposer`1.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Dsl.CompositeNodeComposer`1.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
>   at Ploeh.AutoFixture.Kernel.SeedIgnoringRelay.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.FilteringSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Dsl.NodeComposer`1.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Dsl.CompositeNodeComposer`1.Create(Object request, ISpecimenContext context)
>   at Ploeh.AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
>   at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context, T seed)
>   at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context)
>   at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenBuilder builder)
>   at Ploeh.AutoFixture.SpecimenFactory.Create[T](IPostprocessComposer`1 composer)
>   at Wumte.Server.UnitTest.Library.EntitiesTestHelper.Create[TEntity]()

Here is the tool method where fixture is used:

```c#
private static TEntity Create<TEntity>() where TEntity : HistoryEntityBase
{
	var dateFrom = Fixture.Create<DateTime>().Date;
	var dateTo = dateFrom.AddDays(Fixture.Create<int>());

	return Fixture.Build<TEntity>()
		.With(e => e.DateFrom, dateFrom)
		.With(e => e.DateTo, dateTo)
		.Create();
}
```

`DateTime? HistoryEntityBase.DateTo` is actually nullable.

Before installing new version everything worked fine.

Changing from `var dateTo = dateFrom.AddDays(Fixture.Create<int>());` to `DateTime? dateTo = dateFrom.AddDays(Fixture.Create<int>());` does not help.

**Comment by ploeh** [comment]
I just today pushed out version 3.37.2, and it contains support for implicit conversions. Have you tried to use that?

**Comment by voroninp** [comment]
Pardon me, Mark.
I corrected the title. The version is 3.37.2 =(

**Comment by voroninp** [comment]
Yes, corrected the title =)

**Comment by voroninp** [comment]
Sure, it's better to memoize all reflection related operations and sometimes even create and compile expressions.

```c#
private static Delegate GetConversionFunction(Type sourceType, Type destinationType)
{
	Requires.NotNull(sourceType, "sourceType");
	Requires.NotNull(destinationType, "destinationType");

	var conversionOperator =
		sourceType.GetMethods(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy)
			.Where(
				method => (method.Name == "op_Explicit" || method.Name == "op_Implicit")
						  && method.ReturnType == destinationType)
			.OrderBy(method => sourceType.MinDistanceFrom(method.DeclaringType))
			.FirstOrDefault();

	var lambdaType = typeof (Func<,>).MakeGenericType(typeof (object), destinationType);
	LambdaExpression conversionExpression;
	Delegate conversionFunction;

	if (conversionOperator == null)
	{
		var convertible = typeof (IConvertible);
		if (convertible.IsAssignableFrom(sourceType))
		{
			var conversionMethod = convertible.GetMethod("ToType");

			var instance = Expression.Parameter(typeof (object), "source");
			var typeValue = Expression.Constant(destinationType);
			var formatterValue = Expression.Constant(CultureInfo.InvariantCulture);

			conversionExpression = Expression.Lambda(
				lambdaType,
				Expression.Convert(
					Expression.Call(
						Expression.Convert(instance, convertible),
						conversionMethod, typeValue, formatterValue),
					destinationType),
				instance);

			conversionFunction = conversionExpression.Compile();

			return conversionFunction;
		}

		throw new InvalidOperationException(
			"Cannot convert type '{0}' to type '{1}'.".FormattedInvariant(
				sourceType.AssemblyQualifiedName,
				destinationType.AssemblyQualifiedName));
	}

	var param = Expression.Parameter(typeof (object), "source");
	conversionExpression = Expression.Lambda(
		lambdaType, Expression.Call(conversionOperator, Expression.Convert(param, sourceType)), param);
	conversionFunction = conversionExpression.Compile();

	return conversionFunction;
}
```

**Comment by voroninp** [comment]
Thanks for the fix.
