### ISSUE TITLE
Modify build scripts to allow the use of C# 6.0 features

### ISSUE THREAD

**Issue by Pvlerick** [AutoFixture/AutoFixture#500]
As mentioned in PR #499, the current build scripts do not allow for C# 6.0 features, while VS 2015 and the build server are perfectly happy with them.

This does not happen when building with a more recent version of msbuild (such as the one that ships with VS 2015 in "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe")

Side note: with the new msbuild, 4 warnings are produced
``warning MSB3884: Could not find rule set file "AutoFixture.NUnit2.ruleset``
``warning MSB3884: Could not find rule set file "AutoFixture.NUnit2.ruleset``
``warning MSB3884: Could not find rule set file "AutoFixture.xUnit.net.ruleset``
``warning MSB3884: Could not find rule set file "Migrated rules for AutoRhinoMock.ruleset``

**Comment by ploeh** [comment]
Thank you for bringing this to our attention.

First of all, just to make sure that I understand the current capabilities correctly, please correct me if the following is incorrect:

- AutoFixture 3 targets .NET 4.
- It's possible to use C# 6 to compile .NET 4 binaries.
- To use C# 6 one must have Visual Studio 2015. Earlier versions of Visual Studio can't compile C# 6 code.

I must admit that I'm not completely sure about all of these statements, which is the reason I'm listing them.

**Comment by Pvlerick** [comment]
1 and 2 are ok.

For 3 AFAIK only Visual Studio 2015 supports C# 6.0's syntax indeed - including C# 6.0 in the code base would force everyone to move to Visual Studio 2015 (or other C# 6.0 supporting IDEs).

On a side note again, my understanding is that MSBuild can now be retrieved as a package (https://www.nuget.org/packages/MSBuild/), maybe that could be explored.

**Comment by ploeh** [comment]
For my part, I have no problem with a Visual Studio 2015 requirement, but we ought to consider the wider community.

Again, I'd like to solicit comments for or against **making Visual Studio 2015 a requirement** for working with AutoFixture, particularly, but not exclusively, from @moodmosaic, @ecampidoglio, @adamchester.

**Comment by adamchester** [comment]
:+1: to VS 2015, no reason I can think of to stick with 2013.

Also :+1: to putting those build warnings in a separate issue; I get them too. We might also need to upgrade the sln files to be all 2015 format, for consistency. In the past, appveyor used this to help decide on msbuild version but that may not be necessary now.

**Comment by ecampidoglio** [comment]
I think the syntactic sugar brought by C# 6 is _sweet_ enough to make it worthwhile. So :+1: to that.

Regarding the build on Appveyor, @adamchester is right; we need to update the header in the solution file for Appveyor to pick the right version of MSBuilld. Also, we'll have to switch to the _Visual Studio 2015_ environment in the build configuration, since that should have [MSBuild 14 in the `PATH`](http://help.appveyor.com/discussions/suggestions/772-use-msbuild-14-by-default).

**Comment by tiesmaster** [comment]
:+1: for upgrading to 2015 ;)

**Comment by Pvlerick** [comment]
Using the [C# Essentials](https://visualstudiogallery.msdn.microsoft.com/a4445ad0-f97c-41f9-a148-eae225dcc8a5) extension, there are 324 warnings (all of them are ``CSE0001	Consider using nameof for the parameter name``) and 669 messages (most of them being ``CSE0003	Consider using an expression-bodied member`` and ``CSE0002	Consider using a getter-only auto property``).

**Comment by ErikSchierboom** [comment]
Another :+1: for upgrading to VS 2015

**Comment by moodmosaic** [comment]
As long as the `*.sln` files can be opened in the latest version of Visual Studio *and* can be compiled in the command-line, I wouldn't bother constraining them.

At the end, the questions comes down to whether we'd care, or not, to use C# 6 features.

**Comment by ploeh** [comment]
> At the end, the question comes down to whether we'd care, or not, to use C# 6 features.

Good point.

The `nameof` operator is nice to have, but hardly a killer feature. Does C# 6 offer anything else that would make development of AutoFixture easier?

**Comment by Pvlerick** [comment]
C# 6.0 doesn't have any killer feature, only nice to have. But I like the ``nameof``, real immutable types using get only auto- properties and expression-bodied members are very nice nice additions, to point a few.

I think it's also about keeping up with the times as it's always a bit frustrating not to be able to use new language features.

**Comment by ErikSchierboom** [comment]
The argument made by @Pvlerick is also how I view it. No, there is nothing "big" in C# 6's new features, but the getter-only properties and expression-bodied members do have the potential to make code more concise and clear.

**Comment by ploeh** [comment]
While C# 6 has no killer features, it seems like it wouldn't hurt upgrading either. With this discussion, I mainly wanted to gauge the impact of making this change. A priori, I didn't know if any of the AutoFixture regulars were, for some reason, prevented from using Visual Studio 2015 - after all, this is software that actually costs money.

As I read this thread, no one has objected, so I consider this suggestion **accepted**. I'm therefore going to add the *jump in* tag, so that anyone who thinks it would be an interesting task feels welcome to take it on :smile:

**Comment by ErikSchierboom** [comment]
Hopefully, I'll be able to do submit something tomorrow.

**Comment by moodmosaic** [comment]
I'm not excited by C# 6 – it kind of reminds me the [uncanny valley](https://en.wikipedia.org/wiki/Uncanny_valley) – so I can't really hold an opinion on the upgrade. But, if you decide to do the upgrade, it's find by me as I'm already on Visual Studio 2015 :wink:

**Comment by ecampidoglio** [comment]
> it kind of reminds me the uncanny valley

That's intriguing. In which way does it remind you of that, if I may ask?

**Comment by moodmosaic** [comment]
@ecampidoglio, heres' how:

>"As non functional-first languages ape the features of functional-first ones, they're attempting to cross the uncanny valley of programming language design."

That's merely my own paraphrase and combination of [this](http://blog.ploeh.dk/2015/04/15/c-will-eventually-get-all-f-features-right/) article with [this](http://blog.codinghorror.com/avoiding-the-uncanny-valley-of-user-interface/) older one.

---

(To be clear – *I do like C#*, it's just that I'm not *excited* by C# 6.)

**Comment by ecampidoglio** [comment]
@moodmosaic Thanks for clarifying. I can see how [expression-bodied function members](https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#expression-bodied-function-members) would fit in that description.

A part from that, the theme of C# 6 seems to be more about _terseness_ than adding functional features.

**Comment by moodmosaic** [comment]
@ecampidoglio That sounds good!

**Comment by ErikSchierboom** [comment]
I am working on getting the Build-release scripts compiling the C# 6 code. I tried to use the MSBuild NuGet package, but the MSBuild.exe contained in that package does not support the /ruleset command. So perhaps we can switch over to the MSBuild NuGet package when rulesets are supported.

Furthermore, I had to switch the msbuild path from the "Windows" folder to the "Program files (x86)" version, as the Windows path's version does not support C# 6 (see [this SO question](http://stackoverflow.com/questions/32007871/how-to-upgrade-msbuild-to-c-sharp-6)).

Having changed that, I then can compile the C# 6 code. One last question: what to do with the `build-release.sh` file? It refers to `$WINDIR/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe`, so I suspect that it won't work with C# 6. To what should I change the call?

**Comment by ploeh** [comment]
> One last question: what to do with the `build-release.sh` file?

Unfortunately, that ought not to be the last question, but rather the first question. I exclusively use the shell script for my verification and publication workflows, but I do realise that I hadn't updated the CONTRIBUTING.md file to that effect. Please accept my apologies for that; it's entirely my fault.

The AutoFixture build scripts are getting somewhat long in the tooth, so the question is if we shouldn't consider migrating to something more maintainable.

In several of my other, more modern OSS projects, I use [FAKE](http://fsharp.github.io/FAKE) to manage the build, verification, and publication workflows, and that works well. As an example, [here's a build script I published a couple of days ago](https://github.com/ploeh/Numsense/blob/master/Build.fsx).

FAKE might be able to address these questions, freeing us to do more interesting things.

**Comment by ErikSchierboom** [comment]
Interestingly, FAKE has been on my list of things to check out for a while. This might be a good opportunity to do so. I'll see if I can get things working using FAKE. It might take a while though.

**Comment by ploeh** [comment]
To be clear, I don't think migrating to FAKE is going to be *trivial*; quite a lot is going on in that build script. It should be doable, though.

**Comment by ErikSchierboom** [comment]
@ploeh Should I try to exactly mimic the MSBuild features in the FAKE script? E.g., in your Numsense FAKE build script, you use git to do a clean, but in AutoFixture an MSBuild clean is done. What should I be striving for?

**Comment by ploeh** [comment]
@ErikSchierboom For that particular step, feel free to do whatever suits you best.

The reason I normally use `git clean` is because I've found that MSBuild's *clean* often doesn't do a good job of *really* cleaning up. It may just be an old scar of mine, though...

**Comment by ErikSchierboom** [comment]
@ploeh I am happily converting the MSBuild file to FAKE, which is proceeding fairly well. I was wondering if everything in the MSBuild file is really necessary. For example, the build is done through MSBuild by passing it the "rebuild" value. That MSBuild task is dependent on another task that does a "clean" MSBuild. However, this is not necessary according to [this SO answer](http://stackoverflow.com/questions/1247457/difference-between-rebuild-and-clean-build-in-visual-studio-2008), as a rebuild is in itself also a clean.

Also, there is a command do to a clean of the Debug build, but there is no command to do the Debug build itself. Should the build command be added, or the clean command be removed?

And lastly, I found the combination of the "Build", "Test", "TestOnly" and "BuildAndTestOnly" a bit confusing. Are all used?

**Comment by adamchester** [comment]
@ErikSchierboom the idea with `BuildOnly` and `TesOnly` is [hopefully explained here](https://github.com/AutoFixture/AutoFixture/pull/502). They are in use, but if you can think of a less confusing name for them, that would be good.

**Comment by ErikSchierboom** [comment]
@adamchester That clears things up. Thanks.

**Comment by ploeh** [comment]
IIRC, you can reduce most of this to my lack of faith in MSBuild's ability to actually clean out binaries and such. Perhaps it's only scars; perhaps the current versions of MSBuild and Visual Studio actually, you know, _remove_ binaries and other build artefacts under both _rebuild_ and _clean_... Older versions couldn't be trusted to do this, though, even though the _feature_ was seemingly there.

Perhaps I went a bit overboard with these, trying to ensure that the build process has a clean slate from which it can work.

This also explains why I tend to use `git clean` these days.

**Comment by ErikSchierboom** [comment]
@ploeh Do you want me to keep them? I'm fine with either option.

**Comment by ploeh** [comment]
My only concern here is that when I run `build-release.sh` I have confidence that all artefacts are created from a clean slate. This is important because it ensures that the build process is repeatable; it wouldn't be repeatable if there's a build step that depends on some residual files that are lying around on my machine, but other people don't have.

I'm sure @adamchester have opinions about the other build options, though :wink:

**Comment by ErikSchierboom** [comment]
I got things working on Windows machine! On my Mac, the build fails due to comment references not being found. I'll look into that later, You can see the progress at: https://github.com/ErikSchierboom/AutoFixture/tree/fake-build

**Comment by ErikSchierboom** [comment]
I believe now that #523 has been merged, this issue has been fixed. I just verified this by using the `nameof` operator somewhere and using the FAKE build script the build was successful.

**Comment by ploeh** [comment]
Like @ErikSchierboom, I believe this issue has now been addressed. Can we close the issue?

**Comment by ploeh** [comment]
Closing, due to lack of response.
