### ISSUE TITLE
.NET Core & Serializable Exceptions

### ISSUE THREAD

**Issue by lbargaoanu** [AutoFixture/AutoFixture#509]
In .NET exceptions need to be serializable in order to be able to cross AppDomain boundaries. Not so in .NET Core (no AppDomains). Do AutoFixture exceptions need to be passed across AppDomains? The testing infrastructure in VS uses AppDomains, but I'm not sure whether this affects AutoFixture. The simplest option is not to serialize exceptions. Another would be to solve it at compile time. Or at runtime with a shim.

**Comment by ploeh** [comment]
> Do AutoFixture exceptions need to be passed across AppDomains?

We don't know. AutoFixture is a library. What people do with it is beyond our control. They *may* be using it in such a way that exceptions need to be serialised across AppDomains.

IIRC, the only way that affects the implementation of Exceptions is that they are adorned with the `[Serializable]` attribute, and that they have an extra protected constructor overload. Is that an impediment when it comes to .NET Core?

**Comment by lbargaoanu** [comment]
There is no default binary serialization in .NET Core. So if the code is to remain unchanged we need to provide some replacement types just to compile.

**Comment by ploeh** [comment]
Does that mean that the `[Serializable]` attribute doesn't exist?

Just trying to understand...

**Comment by lbargaoanu** [comment]
Yes. And the types passed in the serialization constructor.

**Comment by ploeh** [comment]
I see. Thank you for explaining that.

Changing the existing AutoFixture types by removing the offending code would be a breaking change, so isn't something we can do in AutoFixture 3.

In AutoFixture 4, we *could* make that breaking change, but would that be appropriate?

I haven't seen if the .NET team has issued any guidance on this question, but it'd be interesting to read if they have.

Assuming that 'normal' .NET will be around for a while yet, wouldn't it still be appropriate to release a version of AutoFixture that targets the 'old' framework? If so, wouldn't it still be appropriate that Exceptions are serializable?

If so, I don't see any other option than conditional compilation, but that may only be my lack of imagination speaking...

**Comment by lbargaoanu** [comment]
I'm sure most custom exception types out there are not serializable and they get away with it :) But strictly speaking, yes, they should be serializable. We can solve it with conditional compilation. We can also add a reference only in the .NET Core configuration to a library containing the placeholder types. Partial classes and conditional compilation could be simple enough I believe.

**Comment by ploeh** [comment]
OK. What should we do with this issue?

Is it a work item? Or did we arrive at an answer, so that we ought to close the issue?

I'd like to prevent the issue list from growing too big, so I prefer to only keep issues open if there's a way they can be closed by deliberate action.

**Comment by lbargaoanu** [comment]
We'll consider it a question. When I have the PR ready we can talk there :)

**Comment by ploeh** [comment]
FTR, I find it perfectly fine to ask questions like this, as a new issue :+1: 

As long as we can close them quickly *or* convert them to actionable work items, I think the more public discussions we can have, the better.

In other words: please ask again if you have other questions.

**Comment by lbargaoanu** [comment]
Some further research.
https://github.com/dotnet/roslyn/issues/3528
https://github.com/aspnet/EntityFramework/search?utf8=%E2%9C%93&q=exception+in%3Apath&type=Code
https://github.com/dotnet/roslyn/blob/db9c4edd46ebd93c862c2479c1bac5d85818ec89/src/Scripting/Core/CompilationErrorException.cs
