### ISSUE TITLE
GetMemberType?

### ISSUE THREAD

**Issue by Michael-DST** [AutoFixture/AutoFixture#520]
I just upgraded to 4.2.0 and I am seeing an extension method that I was using "GetMemberType( MemberInfo )" is now missing and is my build is breaking as a result of it (the sads).  I did a quick search on this and didn't see anything.  Of course, I am not a very good searcher and am generally lazy so I am posting here now. :)  Is there a reason why this was removed instead of deprecated with a message on how to reconcile?

**Comment by ploeh** [comment]
4.2.0? Really? The most recent version of AutoFixture is 3.39.0...

The extension method `GetMemberType` doesn't ring a bell... Where was it defined (what was the name of the class that held this extension method)? In which version of AutoFixture did you last see it?

**Comment by Michael-DST** [comment]
Ugh!!  How freaking embarrassing.  I had just gotten done attending an AutoFixture StackOverflow post (or was in the middle of doing that) and was also thinking "why don't you deprecate it like AutoFixture does?"  This was meant for [AutoMapper](https://github.com/AutoMapper/AutoMapper).  Oh, the shame.

![](https://i.imgflip.com/y93up.jpg)

**Comment by ploeh** [comment]
No worries :smile: The names _are_ quite similar!
