### ISSUE TITLE
AutoFixture.AutoMoq does not work with newer versions of Moq without manually changing the project.lock.son file

### ISSUE THREAD

**Issue by davidpeden3** [AutoFixture/AutoFixture#541]
This problem is super easy to reproduce:

1. Create a new `class library (package)` in visual studio 2015
2. Edit the `project.json` to depend on `AutoFixture`, `AutoFixture.AutoMoq`, and `Moq` like this:

```
{
	"version": "1.0.0-*",
	"description": "autofixturetest Class Library",
	"authors": [ "dpeden" ],
	"tags": [ "" ],
	"projectUrl": "",
	"licenseUrl": "",
	"dependencies": {
		"AutoFixture": "3.40.0",
		"AutoFixture.AutoMoq": "3.40.0",
		"Moq": "4.2.1510.2205"
	},
	"frameworks": {
		"net46": { }
	}
}
```

You will get the following error:

<img width="967" alt="moq" src="https://cloud.githubusercontent.com/assets/1190710/13578831/e752fb3a-e45f-11e5-9838-ff957ea7760d.png">

You can manually work around the error by following this guidance:

http://stackoverflow.com/a/34579963/607701

Which is clearly less than desirable.

If you remove the explicit `Moq` dependency or if you explicitly reference the same version of the dependency of `Moq` that `AutoFixture.AutoMoq` depends on, you do not get the dependency resolution error.

This problem is not associated with ASP.NET MVC as originally speculated in the comments of the linked SO post but may be related to `dnu build/restore` and how it generates the `project.lock.json` file.

**Comment by dcastro** [comment]
Looks like this should be a matter of fixing the capitalization in the [nuspec file](https://github.com/AutoFixture/AutoFixture/blob/master/Nuget/Ploeh.AutoFixture.AutoMoq.nuspec).

**Comment by davidpeden3** [comment]
I looked for that and didn't find it. Thanks for linking the file. I have submitted a pull request to correct the casing.

**Comment by ploeh** [comment]
Does [AutoFixture 3.40.1](https://www.nuget.org/packages/AutoFixture/3.40.1) resolve this issue?

**Comment by davidpeden3** [comment]
It does, indeed. Thank you for getting the package pushed so quickly.

**Comment by sm-g** [comment]
I got "Moq, Version=4.1.1308.2120, Culture=neutral, PublicKeyToken=69f491c39445e920" FileLoadException after use AutoMoq in VS2017 in regular, `<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>` project.

```
<PackageReference Include="AutoFixture.AutoMoq">
      <Version>3.50.7</Version>
    </PackageReference>
    <PackageReference Include="AutoFixture.NUnit3">
      <Version>3.50.7</Version>
    </PackageReference>
    <PackageReference Include="Moq">
      <Version>4.7.99</Version>
    </PackageReference>
    <PackageReference Include="NUnit">
      <Version>3.8.1</Version>
    </PackageReference>
```

**Comment by zvirja** [comment]
@sm-g Could you please create a separate issue for that? Also please provide me with a sample project (zip and attach) where I can reproduce the issue. This will simplify the investigation process.

Thank you in advance.
