### ISSUE TITLE
`IPostprocessComposer.With`, perhaps, should allow me to read properties from the object being created.

### ISSUE THREAD

**Issue by JoshMcCullough** [AutoFixture/AutoFixture#545]
E.g.:

```
fixture.Customize<MyThing>(c => c
    .With(o => o.End, o => o.Start.AddDays(2)));
```

So, this is adding the following member to the interface:

```
IPostprocessComposer<T> With<TProperty>(Expression<Func<T, TProperty>> propertyPicker, Expression<Func<T, TProperty>> valuePicker);
```

Then, I can look at other properties on the object to determine what my current property should be set to. This is assuming that auto-property-filling happens before manual-property-filling.

**Comment by ploeh** [comment]
Thank you for your interest in AutoFixture. As explained in #544, I don't want to add more members to the fluent DSL, so I'm going to close this suggestion.
