### ISSUE TITLE
Put unit tests naming convention in Wiki

### ISSUE THREAD

**Issue by amirkarimi** [AutoFixture/AutoFixture#55]
AutoFixture has a very nice naming convention for its unit test methods. It can be a naming convention reference for unit test classes and methods for other projects as well.

Please describe about this convention in Wiki.

**Comment by moodmosaic** [comment]
I don't think that this can be described on the wiki... However, most of the unit tests are formatted with [this rule of thumb](http://blog.ploeh.dk/2013/06/24/a-heuristic-for-formatting-code-according-to-the-aaa-pattern/).
