### ISSUE TITLE
CompositeDataAttribute in AutoFixture.NUnit3

### ISSUE THREAD

**Issue by lewis-elliott** [AutoFixture/AutoFixture#595]
What happened to CompositeDataAttribute? Has it been replaced with something else?

**Comment by moodmosaic** [comment]
CompositeDataAttribute has not been implemented yet in AutoFixture.NUnit3, even though there's #589 by @hackle which adds support for *InlineAutoDataAttribute*.

**Comment by moodmosaic** [comment]
Thank you for reporting this :+1:

Since NUnit3 support is tracked by #522, I think we can close this one. Feel free to comment in #522, reopen this one, or even open a new issue.
