### ISSUE TITLE
AutoFixture.AutoRhinoMocks mocking virtual methods on concrete classes.

### ISSUE THREAD

**Issue by lewis-elliott** [AutoFixture/AutoFixture#601]
Is this supported out the box with AutoRhinoMockCustomization?

**Comment by ploeh** [comment]
IIRC, `AutoRhinoMockCustomization` doesn't create dynamic Test Doubles for concrete classes. [`AutoMoqCustomization` doesn't](http://blog.ploeh.dk/2010/08/25/ChangingthebehaviorofAutoFixtureauto-mockingwithMoq), and all the AutoFixture [auto-mocking containers](http://blog.ploeh.dk/2013/03/11/auto-mocking-container) tend to have the same overall underlying design philosophy.

**Comment by lewis-elliott** [comment]
Thanks for the reply. That makes sense. Moqs syntax of Mock<T> makes it much easier to pass mocks of concrete types with virtual methods into your tests as parameters. Unfortunately I think you have to use MockRepository.Create in RhinoMocks which you can't pass in, so I'll look for another way around this.

**Comment by ploeh** [comment]
Is there anything regarding this isse that we can do?
