### ISSUE TITLE
MockBehaviors using AutoFixture.AutoMoq

### ISSUE THREAD

**Issue by jdarsie** [AutoFixture/AutoFixture#607]
Hi. Quick question.

Using Moq, I can specify MockBehaviors like this:

`var mock = new Mock<IDependency>(MockBehavior.Strict);`

Is it possible to freeze a strict mock using AutoFixture.AutoMoq?

`var mock = m_fixture.Freeze<Mock<IDependency>>();`

I could not figure out how to do it. Is it implemented? What extension point should I use if I have to do it myself?

First time commenting on this project. Let me know if this question needs to go somewhere else.

Thanks

**Comment by jdarsie** [comment]
Found this SO question online: http://stackoverflow.com/questions/34055672/how-can-i-make-automoqcustomization-use-strict-mockbehavior

**Comment by ploeh** [comment]
Does that answer your question, then?

**Comment by jdarsie** [comment]
I am going through your article right now: http://blog.ploeh.dk/2013/10/23/mocks-for-commands-stubs-for-queries/

**Comment by ploeh** [comment]
> Do you remember if anybody pushed those new implementations for IMethodQuery and ICustomization?

Which implementations?

**Comment by jdarsie** [comment]
> you should be able to create a new class that implements IMethodQuery by using MockConstructorQuery as a starting point.

> you'll also need to create a custom ICustomization that does almost exactly the same as

**Comment by jdarsie** [comment]
Sorry, still learning how to use this

**Comment by ploeh** [comment]
These are not part of the AutoFixture code base.

**Comment by jdarsie** [comment]
Well, that's all then :)

**Comment by ploeh** [comment]
Do you need help with anything else?

**Comment by jdarsie** [comment]
Nevermind, thx.
