### ISSUE TITLE
AutoFixture doesn't work well with the recent version of Resharper (2016.1)

### ISSUE THREAD

**Issue by Zvirja** [AutoFixture/AutoFixture#614]
In the recent version of Resharper (2016.1), the test runner becomes crazy if I use AutoFixture.
Consider the following source code:
```csharp
  public class Tests
  {
    [Theory, AutoData]
    public void TheoryTest(string data)
    {
    }

    [Theory, InlineAutoData("Test")]
    public void TheoryTest2(string data, string data2)
    {
    }

    [Theory, InlineAutoData("Test")]
    public void TheoryTest3(string data)
    {
    }


    [Theory, InlineData("Test")]
    public void TheoryTest4(string data)
    {
    }
  }
```

If we run tests in Resharper, we'll get the following output:
![image](https://cloud.githubusercontent.com/assets/1074182/14851375/30ea5eb4-0c88-11e6-98f4-6dbadc8b8dd6.png)

It's expected behavior. However, let's re-run the tests again:
![image](https://cloud.githubusercontent.com/assets/1074182/14851384/3cfb1d6a-0c88-11e6-85c1-c6c628af4380.png)

Each time you re-run tests, the number of trash tests increases, including the Total number of tests.

If AutoFixture is not used, or our theory don't consume auto generated data - everything is fine.

I'm not sure whether this is AutoFixture, xUnit or Resharper issue (or intersection of some of them), therefore decided to raise it here. If you discover that it's actually not AutoFixture issue - probably it makes sense that somebody who knows AutoFixture internals will register appropriate issue for guilty - I'll be unable to provide them with relevant (which includes their area only) scenario.

Thank you!

**Comment by Zvirja** [comment]
I played more with this issue and found that it's actually Resharper (or xUnit) issue. I was able to reproduce it without using the AutoFixture libraries.

I've decided to report this issue to ReSharper: [https://youtrack.jetbrains.com/issue/RSRP-458569](https://youtrack.jetbrains.com/issue/RSRP-458569).

**Comment by ploeh** [comment]
Thank you for investigating. Since it's the case that it looks like a ReSharper issue, I'm going to close this one.
