### ISSUE TITLE
ElementsBuilder throwing an InvalidCastException

### ISSUE THREAD

**Issue by dcastro** [AutoFixture/AutoFixture#618]
**Repro**:

```cs
new ElementsBuilder<string>("a", "b", "c").Create<string>();
````

**Expected result:**
code should return either "a", "b", or "c"

**Actual result:**
```
System.InvalidCastException : Unable to cast object of type 'Ploeh.AutoFixture.Kernel.NoSpecimen' to type 'System.String'.

   at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context, T seed)
   at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context)
   at *MyMethod*() in *MyFilePath*:line 31
```

**Notes**

I dove into the source code and it seems that new `new ElementsBuilder<string>("a", "b", "c").Create<string>()` is equivalent to:

```cs
new SpecimenContext(new ElementsBuilder<string>("a", "b", "c")).Resolve(new SeededRequest(typeof(string), default(string)))
```

Looking at the implementation of [`ElementsBuilder`][0], it seems it expects `request` to be `typeof(string)`, but it does NOT handle `SeededRequest`. Is this by design? Is my expectation incorrect or is this a bug?

As a final note, this works as expected:

    new ElementsBuilder<string>("a", "b", "c").Create(typeof (string), null as SpecimenContext)

**Background**

My goal was create a generator that randomly returns one of a fixed set of strings.
I could then use this generator to set a property of an object to be one of those strings, like so:

```cs
private class DocumentTypeCustomization : ICustomization
{
    private readonly Generator<string> _docTypes;

    public DocumentTypeCustomization(params string[] docTypes)
    {
        _docTypes = new Generator<string>(new ElementsBuilder<string>(docTypes));
    }

    public void Customize(IFixture fixture)
    {
        fixture.Customize<Document>(c => 
            c.With(d => d.DocType, _docTypes.First()));
    }
}
```

Perhaps there is a workaround i can use in the mean time? Or maybe there's an even easier way that I missed?

Thanks

 [0]: https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/ElementsBuilder.cs

**Comment by ploeh** [comment]
This is perfectly normal behaviour, since 'leaf' `ISpecimenBuilder` objects aren't intended to be invoked directly. You could successfully argue that this is a design flaw, and I'm not even going to attempt to defend this.

Most other `ISpecimenBuilder` implementations behave the same way, though, so it's consistent with the rest of AutoFixture. Examples include `DomainNameGenerator`, `EnumGenerator`, and `Int32SequenceGenerator`.

For your particular scenario, I think you could compose `ElementsBuilder<T>` with an appropriate `IRequestSpecification`. Something like:

```C#
new FilteringSpecimenBuilder(
    new ElementsBuilder<string>(docTypes),
    new PropertySpecification(
        typeof(string),
        "DocType"));
```

I haven't tried to compile it or run it, so you'll probably need to tweak it a bit to get it working.

If that idea doesn't seem to work at all, please write again.

**Comment by dcastro** [comment]
Yes, I remembered right after posting this that specimen builders don't handle seeded requests - they're unwrapped by the `SeedIgnoringRelay` and then re-resolved :)

The code you posted makes sense and it should work IMO, but I can't get it to work, maybe I'm doing something wrong. Here's what I have:

```cs
public class Doc
{
    public string DocType { get; set; }
}

var docTypes = new[] {"a", "b"};

var fixture = new Fixture();
fixture.Customizations.Add(new FilteringSpecimenBuilder(
    new ElementsBuilder<string>(docTypes),
    new PropertySpecification(
        typeof (string),
        "DocType")));

var doc = fixture.Create<Doc>();

Assert.Contains(doc.DocType, docTypes);
```

**Comment by dcastro** [comment]
The problem seems to be on line 54 of `ElementsBuilder`.

```cs
if (!typeof(T).Equals(request))
    return new NoSpecimen();
```

`request` is an instance of `PropertyInfo` (whose `Name` is `DocType` and whose `PropertyType` is `string`), so the equality check fails.

**Comment by ploeh** [comment]
The easiest workaround is probably to define a new `ISpecimenBuilder`, then:

```C#
public class DocTypePropertyBuilder : ISpecimenBuilder
{
    private readonly ISpecimenBuilder factory;

    public DocTypePropertyBuilder(params string[] elements)
    {
        this.factory = new ElementsBuilder<string>(elements);
    }

    public object Create(object request, ISpecimenContext context)
    {
        var pi = request as PropertyInfo;
        if (pi == null ||
            pi.PropertyType != typeof(string) ||
            pi.Name != "DocType")
            return new NoSpecimen();

        return this.factory.Create(pi.PropertyType, context);
    }
}
```

The following test passes:

```C#
var docTypes = new[] { "a", "b" };

var fixture = new Fixture();
fixture.Customizations.Add(new DocTypePropertyBuilder(docTypes));

var doc = fixture.Create<Doc>();

Assert.Contains(doc.DocType, docTypes);
```

**Comment by dcastro** [comment]
That works, thank you!

I  changed your code a little bit to use a `PropertySpecification` instead, as suggested earlier:

```csharp
public class DocTypePropertyBuilder : ISpecimenBuilder
{
    private readonly ISpecimenBuilder factory;
    private readonly IRequestSpecification spec =
        new PropertySpecification(typeof (string),"DocType");

    public DocTypePropertyBuilder(params string[] elements)
    {
        this.factory = new ElementsBuilder<string>(elements);
    }

    public object Create(object request, ISpecimenContext context)
    {
        if (!spec.IsSatisfiedBy(request))
            return new NoSpecimen();

        var pi = (PropertyInfo) request;
        return this.factory.Create(pi.PropertyType, context);
    }
}
```
