### ISSUE TITLE
Support FakeItEasy 2

### ISSUE THREAD

**Issue by mattiasnordqvist** [AutoFixture/AutoFixture#628]
FakeItEasy 2 is out. Any plans on supporting it?

**Comment by ploeh** [comment]
No _plans_, but we do take pull requests :wink:

**Comment by ploeh** [comment]
I've added the [_jump-in tag_](https://nikcodes.com/2013/05/10/new-contributor-jump-in), because I think this might be a good task to take on, even of one isn't familiar with the AutoFixture code base.

Not that I think the task is going to be trivial or small, but because, as far as I understand the changes in FakeItEasy 2, a new _AutoFixture.AutoFakeItEasy2_ Glue Library would be a 95% copy of _AutoFixture.AutoFakeItEasy_.

**Comment by moodmosaic** [comment]
>a new _AutoFixture.AutoFakeItEasy2_ Glue Library would be a 95% copy of _AutoFixture.AutoFakeItEasy_.

Agreed. — As @adamralph wrote in #617, _AutoFixture.AutoFakeItEasy_ contains (at least) [two lines of code that are incompatible with FakeItEasy 2.0](https://github.com/AutoFixture/AutoFixture/pull/617#issue-152857988).

**Comment by adamralph** [comment]
Does that mean you intend to create a new package rather than bump the version of the current one?

**Comment by ploeh** [comment]
That's the usual strategy here. This enables people who are not ready to make the change to stay on the old version for a while.

We still have a Glue Library for xUnit 1.x as well.

**Comment by moodmosaic** [comment]
@adamralph Yes, that's also what we've been doing with the xUnit.net and NUnit Glue Libaries.

**Comment by adamralph** [comment]
OK, fair enough. It's a reasonable strategy.

**Comment by caloggins** [comment]
I created a fork, updated to FakeItEasy 2.1.0, and fixed the failing code. What's the next step I should take? Make a pull request?

**Comment by ploeh** [comment]
You could :smile:

**Comment by ploeh** [comment]
With the release of [AutoFixture.AutoFakeItEasy2 3.48.0](https://www.nuget.org/packages/AutoFixture.AutoFakeItEasy2/3.48.0) I think we can close this issue(?)

**Comment by adamralph** [comment]
On behalf of the [FakeItEasy owners](https://github.com/orgs/FakeItEasy/teams/owners), thank you to everyone who made this happen!

/cc @blairconrad @thomaslevesque

**Comment by TeaDrivenDev** [comment]
@ploeh I think so; it's a bit confusing when coming from up-for-grabs.net or the like. ;-)
