### ISSUE TITLE
AutoConfiguredNSubstituteCustomization could randomly fail due to Task inlining

### ISSUE THREAD

**Issue by Zvirja** [AutoFixture/AutoFixture#630]
__Steps to reproduce:__

- Create interface with non-void method.
- Create interface with method that results interface from point 1:

```csharp
public interface IInterfaceWithMethod
{
    string Method(string s);
}

public interface IInterfaceWithMethodSource
{
    IInterfaceWithMethod Get();
}
```

- Resolve `IInterfaceWithMethodSource` and later call the `Get()` method to get `IInterfaceWithMethod` instance:
```csharp
var fixture = new Fixture().Customize(new AutoConfiguredNSubstituteCustomization());
var interfaceSource = fixture.Create<IInterfaceWithMethodSource>();
var instance = interfaceSource.Get();
```

__Result:__

Sometimes code fails with the following exception:
```
NSubstitute.Exceptions.CouldNotSetReturnException

Could not find a call to return from.
Make sure you called Returns() after calling your substitute (for example: mySub.SomeMethod().Returns(value)).
If you substituted for a class rather than an interface, check that the call to your substitute was on a virtual/abstract member.
Return values cannot be configured for non-virtual/non-abstract members.

   at NSubstitute.Core.SubstitutionContext.LastCallShouldReturn(IReturn value, MatchArgs matchArgs)
```

Issue happens because code that creates `IInterfaceWithMethod` mock (when you call the `IInterfaceWithMethodSource.Get()` method) could be executed on the same thread. As result, mock creation will corrupt the current NSubstitute state and it will be unable to setup result later.

Technically, it happens because [this code](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoNSubstitute/NSubstituteVirtualMethodsCommand.cs#L207) is not always executed on a new thread. It could happen that task is inlined on the current thread. See this [stackoverflow discusstion](http://stackoverflow.com/questions/12245935/is-task-factory-startnew-guaranteed-to-use-another-thread-than-the-calling-thr).

**Comment by Zvirja** [comment]
Hi guys,

Likely, that is not a proper question here, but could you please review the bug and PR? This is rather a critical issue for my solution, because when I run my tests under dotCover, almost 30 tests becomes red and I cannot measure code coverage properly. Therefore, it could be great if this fix could be merged and published to NuGet, so I could update assembly.

If you have any questions or notes regarding the bug/PR - let me know.

**Comment by ploeh** [comment]
Sorry, I didn't realise that it was urgent; I don't think I've seen an AutoFixture issue that was urgent before... :flushed:

**Comment by Zvirja** [comment]
Thanks for update.
It never happened until I started to use dotCover. Now it happens for each time I measure coverage - while issue looks minor, it lefts no ways to measure the coverage correctly.

Well, AutoFixture is still awesome, this is just NSubstitute integration that causes issues :)
