### ISSUE TITLE
Symbols problem

### ISSUE THREAD

**Issue by apobekiaris** [AutoFixture/AutoFixture#632]
Do the symbols work ok for you? I clean my symbols cache and see the new pdb loaded in the modules window. However when at runtime I try to step in for example in Fixture.Create the file SpecimentFactory.cs is open but I am wrong positioned.but at design time r# symbol browsing works fine.

**Comment by ploeh** [comment]
I can't say; I never use that feature... :flushed: If someone else has information (works/doesn't work) to share, please add it here.

**Comment by ploeh** [comment]
Closing, due to inactivity. Please re-open if there's anything we can _do_.
