### ISSUE TITLE
RandomBooleanSequenceGenerator is biased towards `false`

### ISSUE THREAD

**Issue by dcastro** [AutoFixture/AutoFixture#633]
I was playing around with `RandomBooleanSequenceCustomization` when I noticed that, more often that not, I was getting a `false` value. Roughly 66% of the time.

So I looked into it, and it turns out that the customization defers to its [generator counterpart (`RandomBooleanSequenceGenerator`)][0], which in turn defers to `RandomNumericSequenceGenerator`. Here are the relevant bits:

```cs
this.randomBooleanNumbers =
    new RandomNumericSequenceGenerator(0, 2);
```

```cs
private bool GenerateBoolean(ISpecimenContext context)
{
    return (int)this.randomBooleanNumbers.Create(typeof(int), context) == 0;
}
```

The problem seems to be that the upper bound passed to `RandomNumericSequenceGenerator` (2) is inclusive, not exclusive. Which means we'll either get 0, 1 or 2. And because 0 is translated to `true`, and 1 and 2 to `false`, the random boolean generator ends up being biased towards `false`.

I don't think this was the intended behavior. Am I correct in assuming this is a bug?

 [0]: https://github.com/AutoFixture/AutoFixture/blob/98d7b4d00ba05e406796e32b560b5975f1f9af78/Src/AutoFixture/RandomBooleanSequenceGenerator.cs

**Comment by ploeh** [comment]
Sounds like a bug to me :flushed:

**Comment by dcastro** [comment]
In that case, and if there are no objections, I'll go ahead and submit a PR.

The only question I have is: how would one go about writing a *reliable* regression test for this? In my experience, testing randomness is no easy task.

**Comment by ploeh** [comment]
Testing isn't the _only_ way to prevent errors and regressions. We also review changes, keeping an eye out for errors that unit tests can't easily point out. 

If someone else has a better suggestion, I'm open to learn, but otherwise, I'd be inclined to accept a pull request with a fix for this, even if that pull request adds no new tests.
