### ISSUE TITLE
Passive Customization Attributes are ignored when used in combination with [Frozen]

### ISSUE THREAD

**Issue by sergeyshushlyapin** [AutoFixture/AutoFixture#637]
If a test method parameter is decorated with both `[Substitute]` and `[Frozen]` attributes, a concrete instance is created instead of a substitute. The following test fails:

``` csharp
[Theory, AutoNSubstituteData]
public void FreezeConcreteTypeSubstitute([Frozen, Substitute] ConcreteType ct1, ConcreteType ct2)
{
    Assert.Same(ct1, ct2);
    Assert.True(ct1.GetType().BaseType == typeof(ConcreteType)); // fails
    // A real instance is created instead of a mock.
}
```

The issue has been addressed in PR #627 but it was agreed that the solution is sub-optimal. To be implemented in a new PR.

**Comment by ploeh** [comment]
@sergeyshushlyapin, while I haven't added the [jump in](https://nikcodes.com/2013/05/10/new-contributor-jump-in) label to this issue, you're still more than welcome to attempt to address it. You seem to be on top of things :+1:

**Comment by sergeyshushlyapin** [comment]
The issue is not about the `[Substitute]` attribute only. It's about all the [Passive Attributes](http://blog.ploeh.dk/2014/06/13/passive-attributes/) that require corresponding *relays* to create specimens (e.g. [StringLengthAttributeRelay](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/DataAnnotations/StringLengthAttributeRelay.cs)):

```csharp
[Theory, AutoData]
public void StringLengthConstraintWorksWithoutFrozen([StringLength(3)]string str)
{
    Assert.True(str.Length == 3); // pass
}

[Theory, AutoData]
public void StringLengthConstraintFailsWithFrozen([Frozen][StringLength(3)]string str)
{
    Assert.True(str.Length == 3); // fails
}
```

The underlying reason is in the wrong assumption that in order to create a specimen only *type* is required. In the Glue Libraries specimens can be defined by types and *Customization Attributes*.

The [FreezeOnMatchCustomization](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/FreezeOnMatchCustomization.cs#L103) resolves specimens using type only which causes the issue:
```csharp
var specimen = context.Resolve(this.TargetType);
```

**Comment by Zvirja** [comment]
Just a hint: as a potential way to fix this issue is to create a custom `ICustomAttributeProvider` implementation and resolve it. That implementation should hide one attribute that we already processed. However, that could lead to large refactoring for existing code..

**Comment by zvirja** [comment]
Will be fixed in v4.
