### ISSUE TITLE
[Question] Simple tests without comments vs respecring existing code style

### ISSUE THREAD

**Issue by sergeyshushlyapin** [AutoFixture/AutoFixture#638]
I noticed the @ploeh's article [A heuristic for formatting code according to the AAA pattern](http://blog.ploeh.dk/2013/06/24/a-heuristic-for-formatting-code-according-to-the-aaa-pattern/) when I  knew *something is wrong* with my tests. Excellent article. I stopped using the redundant AAA comments and I'm pretty happy about that now! ;)

In the same time, similar comments are still widely used in the AutoFixture [code base](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixtureUnitTest/FixtureTest.cs#L71) including the [new](https://github.com/AutoFixture/AutoFixture/pull/629/commits/df61e113aeba25d091cf3d4dd389ec519551800e#diff-e04f88c155fefc61f37deb262ae23a32R5146) code. I realize that it's done in [respect](https://github.com/AutoFixture/AutoFixture/blob/master/CONTRIBUTING.md#pull-requests) of the existing styles, but I have a feeling that it might be OK to stop doing that in order to improve the readability.

I definitely do not summon to stop respecting all the other code styles, of course no. I'm talking about the comments only. I'll accept any answer for this particular product. Just want to be in sync with the current policy.

Thanks.

**Comment by ploeh** [comment]
I'd be OK if you adopt the above-mentioned heuristic. The AutoFixture code base is getting old, and in it you can find more than one coding style. There have been many contributors, and I think it's fine that the code base reflects that.

The most important quality of a code base, to me, is that it's easy to understand.

**Comment by sergeyshushlyapin** [comment]
Great, thanks :)
