### ISSUE TITLE
Receiving a circular reference exception when using insufficient factory method

### ISSUE THREAD

**Issue by sergeyshushlyapin** [AutoFixture/AutoFixture#643]
Consider the following type with a **private** constructor and a static *factory* method :
```csharp
public class TypeWithPseudoFactoryMethod
{
    private TypeWithPseudoFactoryMethod() { }

    public static TypeWithPseudoFactoryMethod DoSomething(
        TypeWithPseudoFactoryMethod argument)
    {
        return new TypeWithPseudoFactoryMethod();
    }
}
```

Creating an instance of this type leads to a circular dependency because the `DoSomething` method requires a parameter of the type it suppose to create:

```
...
AutoFixture was unable to create an instance of type Ploeh.AutoFixture.Kernel.SeededRequest   
because the traversed object graph contains a circular reference.
...
	Path:
		Ploeh.TestTypeFoundation.TypeWithPseudoFactoryMethod argument --> 
		Ploeh.TestTypeFoundation.TypeWithPseudoFactoryMethod --> 
		Ploeh.TestTypeFoundation.TypeWithPseudoFactoryMethod

```

This method is definitely not suitable for creating specimens so it must not be used as a factory method.  The default object creation exception is much informative and easy to deal with (if there are no other valid factory methods):

```
AutoFixture was unable to create an instance from  
Ploeh.TestTypeFoundation.TypeWithPseudoFactoryMethod,  
most likely because it has no public constructor, is an abstract or non-public type.
```

**Comment by moodmosaic** [comment]
Thank you for reporting this. – Isn't the current behavior more precise though? :neutral_face:

Factory Methods are supported using a heuristic, and if there's something *wrong* with the requested type, a *specific* exception ought to be thrown – instead of throwing a general one (as proposed here).

**Comment by sergeyshushlyapin** [comment]
The current behaviour is pretty precise in describing *why* AF was unable to create a specimen. My intention was to *avoid* such situations completely when it's clear than the call **will not succeed**. This gives a chance to other *builders* to create the specimen.

I tried to describe the scenario in details in the [PR](https://github.com/AutoFixture/AutoFixture/pull/644#discussion_r66198748).

**Comment by moodmosaic** [comment]
>This gives a chance to other builders to create the specimen.

I'm not 100% sure if that's the case, but it looks like #644 leaves the campground cleaner, indicating that the current behavior is buggy.

**Comment by ploeh** [comment]
Is there any case where the above class design is appropriate? If so, what is it?

**Comment by sergeyshushlyapin** [comment]
The real example I faced is the `System.IO.Stream` class that contains method `Synchronized` which receives and returns a *stream*. I'm not saying it's appropriate, it just exists and it takes a while to figure out why AF cannot create a specimen of this type.

**Comment by ploeh** [comment]
That's an unusual design. Could there be a reason the BCL team decided to design it like that, instead of like the following?

```
public Stream Synchronized()
```

I'm asking because I'd be disinclined to suggest that the BCL team missed such a low-hanging opportunity for a more object-oriented design, but I can't come up with a reason myself :flushed:
