### ISSUE TITLE
SemanticComparison not matching Nullable value against value where names match

### ISSUE THREAD

**Issue by haymansfield** [AutoFixture/AutoFixture#650]
Hi,

I am attempting to use SemanticComparison to create a proxy with the following properties:

Source
        public DateTime StartTime { get; set; }
        public DateTime? EndTime { get; set; }
Destination
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }

I use <source>.AsSource().OfLikeness<dest>().CreateProxy();

EndTime propagates correctly but StartTime does not.

Is this the expected behaviour?

**Comment by haymansfield** [comment]
In either case, is there a workaround?

**Comment by moodmosaic** [comment]
How do the class constructor(s) look like?

**Comment by haymansfield** [comment]
The destination has no defined constructor.
The source has a default constructor which initializes a list.

**Comment by haymansfield** [comment]
Here is a test case:


    [Test]
    public void SemTest()
    {
        var source = fixture.Create<Source>();
        var dest = source.AsSource().OfLikeness<Destination>().CreateProxy();
    }

    public class Source
    {
        public DateTime StartTime { get; set; }

        public DateTime? EndTime { get; set; }
    }

    public class Destination
    {
        public DateTime? StartTime { get; set; }

        public DateTime? EndTime { get; set; }
    }

**Comment by moodmosaic** [comment]
This is bug in the `CreateProxy` method. Thank you for catching and reporting this! :+1: 

---

The following tests demonstrate the bug:

```c#
[Fact]
public void SourceAndDestinationAreSemanticallyEqual()
{
    var source =
        new Fixture().Create<Source>();
    var destinatation =
        new Destination
        {
            StartTime = source.StartTime,
            EndTime   = source.EndTime
        };
    source.AsSource().OfLikeness<Destination>()
        .ShouldEqual(destinatation); // Passes.
}

[Fact]
public void SourceAndProxiedDestinationAreSemanticallyEqual()
{
    var source =
        new Fixture().Create<Source>();
    var destinatation =
        new Destination
        {
            StartTime = source.StartTime,
            EndTime  = source.EndTime
        };
    Assert.True(source
        .AsSource()
        .OfLikeness<Destination>()
        .CreateProxy()
        .Equals(destinatation)); // Fails.
}
```

`Source.StartTime` is of type `DateTime`, while `Destination.StartTime` is of type `Nullable<DateTime>`, so it looks like `CreateProxy` matches on the exact type instead, but it probably shouldn't.

**Comment by ploeh** [comment]
I [still think we should deprecate the class](https://github.com/AutoFixture/AutoFixture/issues/406#issuecomment-104753427) - or even the entire SemanticComparison library...

**Comment by haymansfield** [comment]
I'm happy to stop attempting to use it but I came to it as a useful companion to AutoFixture as it allows me to confirm the values on a fixture generated object have not been modified by a method under test.

I initially looked at Likeness but that is not sufficient as it keeps a reference to the original object.

Can you suggest a solution to this problem?

One solution that comes to mind would be to allow Autofixture to create a pair of identical objects, one for input, one for comparisons. You could then build your likeness against the comparison object.

**Comment by moodmosaic** [comment]
>Can you suggest a solution to this problem?

Don't use `CreateProxy` in this case, at least until this bug is fixed. Instead, use `Likeness` directly:

```c#
[Fact]
public void SourceAndDestinationAreSemanticallyEqual()
{
    var source =
        new Fixture().Create<Source>();
    var destinatation =
        new Destination
        {
            StartTime = source.StartTime,
            EndTime   = source.EndTime
        };
    source.AsSource().OfLikeness<Destination>()
        .ShouldEqual(destinatation); // Passes.
}
```

**Comment by zvirja** [comment]
@moodmosaic Could you please clarify which exact action is required here? If we need to  obsolete/remove something, we can do that in v4..

**Comment by moodmosaic** [comment]
IIRC, the idea was to deprecate the Likeness class(es)... There's also a bug in the Common Intermediate Language we produce through the ProxyGenerator, hence [that](https://github.com/AutoFixture/AutoFixture/issues/650#issuecomment-226473093) comment of mine.

Perhaps there should be a *post*-v4 list with such items?

**Comment by zvirja** [comment]
@moodmosaic Sure, we can handle it after. The only concern for my side what if some breaking changes are required by this issue. If not - let's release that after v4 :relaxed:

**Comment by zvirja** [comment]
This issue has been migrated here: https://github.com/AutoFixture/SemanticComparison/issues/1
