### ISSUE TITLE
SemanticComparison.ruleset is missing

### ISSUE THREAD

**Issue by moodmosaic** [AutoFixture/AutoFixture#651]
I've just noticed that the `SemanticComparison.ruleset` file is missing, after getting the latest from `master` and doing a `git clean -dxf`:

![image](https://cloud.githubusercontent.com/assets/287532/16106013/208239e2-3399-11e6-870c-ec4ca8d0ac4a.png)

**Comment by ploeh** [comment]
Let's remove it from the project file, then.

**Comment by rahulpnath** [comment]
@ploeh Should this not be closed?

**Comment by moodmosaic** [comment]
This should definitely be closed. Good catch @rahulpnath :+1:
