### ISSUE TITLE
NSubstitute - AutoConfigured properties are resolved via Type requests

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#653]
**Bug:** When NSubstitute integration resolves value for mock's property, it performs `Type` request rather than `PropertyInfo` request. Because of that some features (like `[Frozen(Matching.PropertyName)]` xUnit attribute) doesn't work properly for substitutes.

Consider the following example (pretty verbose though):

``` csharp
  public class NSubstituteIntegrationTest
  {
    [Fact]
    public void InterfacePropertyShouldBeResolvedCorrectly()
    {
      var fixture = new Fixture();
      fixture.Customize(new AutoConfiguredNSubstituteCustomization());

      //For each Data Property request return etalon
      var expectedData = fixture.Create<string>();
      fixture.Customizations.Insert(0,
        new FilteringSpecimenBuilder(
          new FixedBuilder(expectedData),
          new PropertySpecification(typeof(string), "Data")));


      var classValue = fixture.Create<TestClass>();
      var ifValue = fixture.Create<ITestInterface>();

      //assert
      Assert.NotSame(expectedData, classValue.OtherData);
      Assert.NotSame(expectedData, ifValue.OtherData);

      Assert.Same(expectedData, classValue.Data);
      Assert.Same(expectedData, ifValue.Data); //___this assertion fails___
    }

    public interface ITestInterface
    {
      string Data { get; }
      string OtherData { get; }
    }

    public class TestClass
    {
      public string Data { get; set; }
      public string OtherData { get; set; }
    }
  }
```

A few things to clarify before fixing:  
1. Please confirm that `PropertyInfo` request should be fired to resolve `ITestInterface.Data` property value. I'm not 100% confident that `PropertyInfo` are purposed for this kind of situations (while this looks obvious, though).
2. @mrinaldi I've noticed that you fired [another PR](https://github.com/nsubstitute/NSubstitute/pull/234) which supposes that current integration could be heavily refactored. How do you feel, does it make sense to fix current integration or it's better to wait till "large refactoring"? If you feel that that direction could take a lot of time - I could fix issue for current integration.

**Comment by mrinaldi** [comment]
Indeed, the current integration will be heavily refactored.
However, since we're having a discussion on the changes yet, I'm not sure how long it'll take to have everything in place to refactor the integration.

So, I wouldn't invest time to change the current integration, but since I'm not the one facing the bug, it's up to you. If you feel you need this badly, go for it.

Let me know if I can help you with anything.

**Comment by Zvirja** [comment]
Thanks for the answer.
So far I didn't need that exact functionality, just noticed the bug. If I find it important for me - I'll try to fix it. Hope the mentioned PR will be merged somewhere in future :)

**Comment by zvirja** [comment]
Fixed in v4. The `PropertyInfo` requests are issued for the Properties.
