### ISSUE TITLE
Static properties should be excluded when using the ConstructorInitializedMemberAssertion

### ISSUE THREAD

**Issue by Martin-Bohring** [AutoFixture/AutoFixture#656]
Currently the naming convention used by the **ConstructorInitializedMemberAssertion** is also applied to static fields and properties.

Most of the time those are either initialized inline or initialized by a class constructor.
Therefore I think those should be excluded when selecting the properties and fields to be asserted.

I might have overlooked something, but I consulted the code base and have found no way to avoid the situation.

For value types it is not uncommon to provide a null value. For example think about [string.Empty](https://msdn.microsoft.com/en-us/library/system.string.empty(v=vs.110).aspx).

Doing that for custom value types causes the ConstructorInitializedMemberAssertion to assume the field or property is initialized by an instance constructor.

Probably the **GetPublicPropertiesAndFields** method within the **ConstructorInitializedMemberAssertion** class needs to ignore static fields and properties.

**Comment by Martin-Bohring** [comment]
Having a second look I see the following:

```c#
        private static IEnumerable<MemberInfo> GetPublicPropertiesAndFields(Type t)
        {
            return t.GetMembers(BindingFlags.Instance | BindingFlags.Public)
                .Where(m => m.MemberType.HasFlag(MemberTypes.Field) || m.MemberType.HasFlag(MemberTypes.Property));
        }
```
Now I am really confused: It only looks for instance members, but somehow it still pukes on static fields and properties :astonished:

**Comment by Martin-Bohring** [comment]
Sorry for having 3 comments in a row, but I think the problem is within the **IsMemberThatRequiresConstructorInitialization** method. It should ignore static properties and fields.

If there is interest, then I can come up with a repro PR.

**Comment by adamchester** [comment]
@Martin-Bohring thanks for reporting this!

Are you able to give a snippet of code that fails to behave the way you expect?

**Comment by Martin-Bohring** [comment]
Here a simple repo

```c#
class AutoFixtureIdiomsProblem
    {
        public static readonly AutoFixtureIdiomsProblem TheProblem = new AutoFixtureIdiomsProblem(0);

        public AutoFixtureIdiomsProblem(int someValue)
        {
            SomeValue = someValue;
        }

        public int SomeValue { get; private set; }
    }

    public sealed class AutoFixtureIdiomsProblemTests
    {
        public void ShouldInitializeFieldsAndProperties()
        {
            var fixture = new Fixture();

            var intializeFieldsAndPropertiesAssertion = new ConstructorInitializedMemberAssertion(fixture);

            intializeFieldsAndPropertiesAssertion.Verify(typeof(AutoFixtureIdiomsProblem));

        }
    }
```

Don't be fooled by the lack of test attributes. I am using Fixie as test framework and the tests are picked up by convention. 

The test fails with the following exception:

Result StackTrace:	
No constructors with an argument that matches the read-only field 'TheProblem' were found
   at Ploeh.AutoFixture.Idioms.ConstructorInitializedMemberAssertion.Verify(FieldInfo fieldInfo)
   at Ploeh.AutoFixture.Idioms.IdiomaticAssertion.Verify(FieldInfo[] fieldInfos)
   at Ploeh.AutoFixture.Idioms.IdiomaticAssertion.Verify(Type type)
   at Media.Domain.Tests.AutoFixtureIdiomsProblemTests.ShouldInitializeFieldsAndProperties() in C:\Users\MBO\Documents\GitHub\fixieSpec\Samples\Media.Domain.Tests\AutoFixtureIdiomsProblem.cs:line 26
Result Message:	Ploeh.AutoFixture.Idioms.ConstructorInitializedMemberException

 So it is clearly the **TheProblem** field when things go wrong. Remove the field an all is well

**Comment by adamchester** [comment]
I see, this certainly looks like a bug, do you intend to submit a PR to fix?

**Comment by Martin-Bohring** [comment]
**@adamchester**
I skimmed the code base and feel confident to sbmit a PR. By I think there are more places like that. I will start with the problem at hand,
