### ISSUE TITLE
Question: Any reason CompositeSpecimenBuilder.ComposeIfMultiple is internal?

### ISSUE THREAD

**Issue by Zvirja** [AutoFixture/AutoFixture#657]
The `CompositeSpecimenBuilder.ComposeIfMultiple()` helper method is marked as `internal` ([source code](https://github.com/AutoFixture/AutoFixture/blob/98d7b4d00ba05e406796e32b560b5975f1f9af78/Src/AutoFixture/Kernel/CompositeSpecimenBuilder.cs#L104).

This method is pretty useful if you are creating your custom behavior. Is there any good reason why it's marked as internal? If not - I'd prefer to make it public via PR.

Thanks.

**Comment by ploeh** [comment]
This method is `internal` because the only purpose it serves is to make AutoFixture's internal object graph a bit prettier. I don't consider that an essential part of what AutoFixture does in order to provide value, so I didn't want to have to support it.

Most 'user code' ought not need this method, because I don't expect 'user code' to build complex subgraphs for AutoFixture. In the rare case where someone might need to do something like that, it's 4 lines of code, which can be easily reproduced.

**Comment by Zvirja** [comment]
Ok, I see, there are two reasons: you don't want to support it and method implementation is straightforward.

Well, I feel fine with approach to create a similar method in my code - no issues with that. The only thing which is still confusing me is that making this method `internal` creates API incompleteness.

AF provides API to add custom behaviors. However, _each_ time you create custom behavior, you will need to implement this method as well. That's because `fixture.Behaviors.Add()` method expects that you pass instance of the `ISpecimenBuilderNode`. Regular `ISpecimenBuilderNode.Compose()` method implementation is following:

```csharp
ISpecimenBuilderNode Compose(IEnumerable<ISpecimenBuilder> builders)
{
    var innerBuilder = CompositeSpecimenBuilder.ComposeIfMultiple(builders);
    return new This_Type(innerBuilder);
}
```

Likely, you will always need to reduce array of builders to single builder. I've checked most of Compose() method implementation and found that _all_ them use `CompositeSpecimenBuilder.ComposeIfMultiple()` method.

If any time you need to create custom behavior you must re-implement the same internal method, that looks like API is incomplete and method should be public - to avoid the same work.

If you still feel that this is not a strong reason to make this method public - feel free to close this question :)

I'm a novice to AF, so let me know if I overlooked something.

**Comment by ploeh** [comment]
Yes, most internal code in AutoFixture uses `ComposeIfMultiple`, but they don't _have_ to. They only do that to make the internal object graph prettier, which was mainly a concern for me when I originally developed the current engine - it was a bit easier to look at the graph in a debugger that way.

Whether or not you use `ComposeIfMultiple` doesn't change the _behaviour_ of AutoFixture, so custom implementers don't have to use that method. The behaviour of `new CompositeSpecimenBuilder(builder)` is identical to the behaviour of `builder`.

**Comment by Zvirja** [comment]
Thank you for the wide explanation. I overlooked that we can simply create `CompositeSpecimenBuilder` even if it contains single nested builder - no need to reduce it. Due to some reasons (likely, because I read the examples too much) I thought that there are no other ways :)

Therefore, indeed presence of the `ComposeIfMultiple` method is not such critical as I thought before.

Question can be closed.
