### ISSUE TITLE
OmitAutoProperties does not work with AutoConfiguredMoqCustomization.

### ISSUE THREAD

**Issue by bj0** [AutoFixture/AutoFixture#662]
I have to use `OmitAutoProperties` on a fixture to prevent a 3rd party library object from receiving string data in a format it can't handle.  This always worked fine using `AutoMoqCustomization`, but I switched to `AutoConfiguredMoqCustomization` because I needed to create frozen mock interface objects that would be used in nested references.  This part worked fine, but properties on that interface are filled with AutoProperty data (instead of default values) even if `OmitAutoProperties` is true.

I'm testing it using the following code in LinqPad:

```
void Main()
{

    var fixture1 = new Fixture().Customize(new AutoMoqCustomization());
    var fixture2 = new Fixture().Customize(new AutoConfiguredMoqCustomization());
    fixture1.OmitAutoProperties = true;
    fixture2.OmitAutoProperties = true;

    var iprops1 = fixture1.Freeze<IProps>();
    var iprops2 = fixture2.Freeze<IProps>();

    fixture1.Create<IProps>().Name.Dump(); // null 
    fixture2.Create<IProps>().Name.Dump(); // filled

    fixture1.Create<IClass>().Props.Name.Dump(); // null
    fixture2.Create<IClass>().Props.Name.Dump(); // filled

    fixture1.Build<TestProps>().OmitAutoProperties().Create().Props.Name.Dump(); // null
    fixture2.Build<TestProps>().OmitAutoProperties().Create().Props.Name.Dump(); // filled

    fixture1.Create<IClass>().Props.Equals(ip1).Dump(); // false
    fixture2.Create<IClass>().Props.Equals(ip2).Dump(); // true (this is what i need)
}

// Define other methods and classes here

public interface IProps
{
    string Name { get; }

    int X { get; }
    float Y { get;}
}

public interface IClass
{
    IProps Props { get;}
}

public class TestProps
{
    public IProps Props { get; set;}

    public TestProps(IProps props) { this.Props = props;}
}
```

**Comment by zvirja** [comment]
@bj0 Sorry for the belated reply. 

This issue has been created long time ago. Are you still interested in the answer?😄Just found this one and want to understand whether it makes sense to spend time on it 😉

**Comment by bj0** [comment]
Well, someone might find it useful, but I'm currently not working on any C# projects so I don't have anything to test it on.

**Comment by zvirja** [comment]
It seems nobody else faced the problem described above since it was created. Let's close it for now and get back to it only if you or somebody else still need an answer.

Thanks for raising it.
