### ISSUE TITLE
Examine type of created FakeItEasy Fakes instead of using IHideObjectMembers

### ISSUE THREAD

**Issue by blairconrad** [AutoFixture/AutoFixture#663]
From my https://github.com/AutoFixture/AutoFixture/pull/617#issuecomment-229425417

I think using `IHideObjectMembers` to tell if a Fake were created properly is not the best idea, because
1. `IHideObjectMembers` changed namespaces between FakeItEasy 1.x and 2.0, keeping AutoFakeItEasy from working with FakeItEasy 2.x, and
2. just because something implements `IHideObjectMembers` doesn't mean it's a Fake.

I propose comparing the resolved object's type against `Fake<T>`. It should be a more robust solution, and would even allow for us to remove the upper bound on the FakeItEasy nuget dependency (and as a side effect, obviate the need for AutoFakeItEasy2).

I've spiked the change in AutoFakeItEasy only. It seems to work, and allows me to upgrade to a FakeItEasy 2.2.0 dependency. I'll submit a PR for discussion.

**Comment by ploeh** [comment]
I'm not sure I'm endowed with sufficient insight to evaluate this. @adamralph, what do you think?

**Comment by blairconrad** [comment]
@ploeh, @moodmosaic, I'm sure the change is functionally sound but am always happy to hear what @adamralph thinks. Of course @thomaslevesque may also have some insight.
However, the important question for the AutoFixture owners would be whether or not you'd want to continue with AutoFakeItEasy2. This change makes it redundant, but there's always the tricky question of removing things from a project. Taking away AutoFakeItEasy2 could be considered a breaking change and I was wondering if you'd want to do that. Making the change in both packages is, of course, also an option, but it increases the maintenance work in the future.

**Comment by adamralph** [comment]
The proposal seems sound to me. I agree that checking for an implementation of `IHideObjectMembers` is a very brittle test.

Has AutoFakeItEasy2 already been released?

**Comment by blairconrad** [comment]
@adamralph, thanks for the chime in.

Regarding the status of the AutoFakeItEasy2 release:

* [NuGet package](https://www.nuget.org/packages/AutoFixture.AutoFakeItEasy2)
* [Twitter announcement](https://twitter.com/ploeh/status/747889675042496513) (which you retweeted :wink:)

**Comment by adamralph** [comment]
Thanks for refilling my sieve-like memory :smile: 

Indeed, AutoFakeItEasy2 would be made redundant by lifting the upper bound restriction on AutoFakeItEasy. I guess it could be de-listed, and/or made into a meta-package which depends on AutoFakeItEasy, with "please uninstall me" in it's description.

**Comment by blairconrad** [comment]
>  "please uninstall me" in its description.

HA! Love it.

**Comment by moodmosaic** [comment]
I'd rather prefer to take the extra maintenance overhead and keep the *AutoFixture.AutoFakeItEasy2* package as-is, instead of possibly having to confuse its consumers. :confused:

**Comment by moodmosaic** [comment]
@blairconrad, great find! 👍

I really wish I knew it when writing the *AutoFixture.AutoFakeItEasy* Glue Library 😳

**Comment by blairconrad** [comment]
@moodmosaic, thanks for the update. I will amend my PR accordingly.

**Comment by blairconrad** [comment]
Oh. Even though AutoFakeItEasy2 will survive, I'd be inclined to remove the upper bound on the AutoFakeItEasy package's FakeItEasy dependency. Is that suitable?

**Comment by moodmosaic** [comment]
>I'd be inclined to remove the upper bound on the AutoFakeItEasy package's FakeItEasy dependency

In order to do that, we'd have to first change AutoFixture.AutoFakeItEasy in order to use [that mighty extension method](https://github.com/AutoFixture/AutoFixture/pull/617#issuecomment-229425417).

**Comment by zvirja** [comment]
@blairconrad @moodmosaic Do I see it properly that we could close this issue because [it has been already fixed](https://github.com/Zvirja/AutoFixture/commit/897b68879ea5bd3238bf27607d99cb7421d47dc7)?

**Comment by blairconrad** [comment]
@zvirja, @moodmosaic
Since #664 and #671 have been merged. I think this issue can be closed. I didn't understand why it wasn't back in the day. It seemed to me that the then-owners were waiting until a package was released, maybe.
