### ISSUE TITLE
Add more details to "traversed object graph contains a circular reference" error

### ISSUE THREAD

**Issue by MNF** [AutoFixture/AutoFixture#667]
When using AutoFixture, I've got the following exception :

> Ploeh.AutoFixture.ObjectCreationException: AutoFixture was unable to create an instance of type System.Reflection.RuntimePropertyInfo
> because the traversed object graph contains a circular reference. Information about the circular path follows below. This is the correct behavior when a Fixture is equipped with a ThrowingRecursionBehavior, which is the default. This ensures that you are being made aware of circular references in your code. Your first reaction should be to redesign your API in order to get rid of all circular references. However, if this is not possible (most likely because parts or all of the API is delivered by a third party), you can replace this default behavior with a different behavior: on the Fixture instance, remove the ThrowingRecursionBehavior from Fixture.Behaviors, and instead add an instance of OmitOnRecursionBehavior.
> 

It will be good to provide URL to the help page with example, e.g. to Wiki  https://github.com/AutoFixture/AutoFixture/wiki/Examples-of-using-behaviors

**Comment by ploeh** [comment]
That's one way to do it, but how about adding the two important lines of code directly to the exception message?

I'm thinking about these statements:

```C#
fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList().ForEach(b => fixture.Behaviors.Remove(b));
fixture.Behaviors.Add(new OmitOnRecursionBehavior());//recursionDepth
```

**Comment by MNF** [comment]
Yes, it will work.
