### ISSUE TITLE
Feature: Create a string specimen with Min/MaxLength constraint

### ISSUE THREAD

**Issue by sergeyshushlyapin** [AutoFixture/AutoFixture#678]
The following two tests fail:

``` csharp
[Theory, AutoData]
public void CreateParameterWithMinLengthConstraint([MinLength(5)]string p)
{
    Assert.True(p.Length == 5); // fails; actual is 37
}

[Theory, AutoData]
public void CreateParameterWithMaxLengthConstraint([MaxLength(5)]string p)
{
    Assert.True(p.Length == 5); // fails; actual is 37
}
```

In order to make it pass two new _relays_ similar to [StringLengthAttributeRelay](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/DataAnnotations/StringLengthAttributeRelay.cs) need to be implemented.

**Important:** the [MaxLengthAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.maxlengthattribute%28v=vs.110%29.aspx) and [MinLengthAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.minlengthattribute%28v=vs.110%29.aspx) classes are available since .Net 4.5 so those AutoFixture projects that are still on .Net 4.0 have to be upgraded (that should cause no problems since 4.5 is [backward compatible](https://blogs.msdn.microsoft.com/dotnet/2011/09/26/compatibility-of-net-framework-4-5/) with 4.0).

**Comment by micheleissa** [comment]
@zvirja Could you point me to the right direction on this one. I feel I can do it and will be a good start on the real stuff :)

**Comment by zvirja** [comment]
@micheleissa I'd look at #711 and fix all the concerns we had there. The approach looked fine :wink:

**Comment by micheleissa** [comment]
Gotcha.I'll look into #711

**Comment by damian-krychowski** [comment]
@ztsmith  shouldn't the tests be rather: 

```c#
[Theory, AutoData]
public void CreateParameterWithMinLengthConstraint([MinLength(5)]string p)
{
    Assert.True(p.Length >= 5); //fails; actual is 37 - if actual is 37 than it is ok, as it is longer than 5
}

[Theory, AutoData]
public void CreateParameterWithMaxLengthConstraint([MaxLength(5)]string p)
{
    Assert.True(p.Length <= 5); // fails; actual is 37 - here something is wrong
}
```

Don't these make more sense? Asserting that length should be always equal to 5 is quite strange for me.

**Comment by zvirja** [comment]
@damian-krychowski Have you referenced a wrong guy? :wink:

**Comment by zvirja** [comment]
@damian-krychowski I do agree that we should create string of variable length, rather than of stable one.
