### ISSUE TITLE
Deprecate AutoFakeItEasy2 further in AutoFixture 4

### ISSUE THREAD

**Issue by moodmosaic** [AutoFixture/AutoFixture#686]
Now that #685 is merged, <del>what's left is to remove AutoFixture.AutoFakeItEasy2 enterily</del> we can deprecate AutoFakeItEasy2 further in AutoFixture 4.

As @ploeh [wrote](https://github.com/AutoFixture/AutoFixture/issues/686#issuecomment-236459795), we should use `[Obsolete("...", true)]` to produce a compiler error if people attempt to use it.

**Comment by ploeh** [comment]
Following the normal procedure for deprecating APIs, in AutoFixture 4 we should use `[Obsolete("...", true)]` to produce a compiler error if people attempt to use it.

Only in AutoFixture 5 can we delete the library.

**Comment by moodmosaic** [comment]
>Only in AutoFixture 5 can we delete the library.

A long way.

**Comment by moodmosaic** [comment]
FWIW, I've updated the title and comment of this issue to reflect the procedure that's [mentioned above](https://github.com/AutoFixture/AutoFixture/issues/686#issuecomment-236459795).

**Comment by zvirja** [comment]
@moodmosaic I have an idea to just to not add AutoFakeItEasy2 to the v4 version - people who use it already will just switch to the AutoFakeItEasy v4. I don't see a reason to proceed with support if this project is discontinued and is not required more.

Do you agree with such a plan? :)

**Comment by moodmosaic** [comment]
[That](https://github.com/AutoFixture/AutoFixture/issues/686#issuecomment-236459795) is the smoothest transition for the users thought. It's similar to what we discussed [here](https://github.com/AutoFixture/AutoFixture/issues/744#issuecomment-290986502).

**Comment by zvirja** [comment]
I do agree with better migration experience, but as we need to migrate each project to .NET Core type, it would require additional efforts to support this one - not just keep as is and bump the version. Also I understand why it does matter for the `Obsolete` attributes - there might be a bunch of them in the project and it will be really hard to understand what is going on. Here the situation is much simpler - there is no `AutoFixture.FakeItEasy2` compatible with `AutoFixture` v4, the whole package disappeared at once. You can simply install other package instead - it will not require you to fix the individual changes.

In any case [we decided to trim](https://github.com/AutoFixture/AutoFixture/issues/745) the `Ploeh` namespace prefix, it will not be so smooth update :) Given that we will have a Wiki page describing the major breaking changes - it's not a problem to mentioned that other package should be used instead.

However let's see what @ecampidoglio and @adamchester think about this.

**Comment by zvirja** [comment]
I've just noticed that the `AutoFixture.FakeItEasy2` package [is not published](https://www.nuget.org/packages/AutoFixture.AutoFakeItEasy2/) to the NuGet more. This means that we could safely remove it from our project - it isn't consumed by users.

@moodmosaic Do you agree with that given this fact? :relaxed:

**Comment by moodmosaic** [comment]
@zvirja, yes, I don't see why not. FWIW, here's the [discussion](https://github.com/AutoFixture/AutoFixture/pull/672) that lead to it's deprecation.

**Comment by zvirja** [comment]
@moodmosaic Given that, could we rename this issue to "Remove AutoFakeItEasy2 from v4"?

**Comment by moodmosaic** [comment]
>could we rename this issue to "Remove AutoFakeItEasy2 from v4"

That was the original title. Only in AutoFixture 5 though we can get rid of it.

In AutoFixture 4, in order to be compatible with [Sem Ver 2.0.0](http://semver.org/), we have to use the [ObsoleteAttribute](https://msdn.microsoft.com/en-us/library/system.obsoleteattribute(v=vs.110).aspx). The same is written by @ploeh [above](https://github.com/AutoFixture/AutoFixture/issues/686#issuecomment-236459795).

[Yes, it was an exception to remove it from NuGet.](https://github.com/AutoFixture/AutoFixture/pull/672#issuecomment-231524546) If I were in your shoes, I'd rather play it safe and use the ObsoleAttribute. NuGet is a delivery mechanism, [but not the only one](https://github.com/moodmosaic/fsharp-hedgehog-samples/commit/3352cb3ea628703b557d2ddd9a565d0a1caee151) 😃

**Comment by zvirja** [comment]
Done!
