### ISSUE TITLE
Cast operators shouldn't be used as factory method during specimen  construction

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#691]
AutoFixture uses public static methods to detect the factory method for object construction. However, it appears that it also detects implicit/explicit cast operators and tries to use them.

Consider the following sample:

``` csharp
    public abstract class BaseClass
    {
      public static implicit operator BaseClass(int value)
      {
        return new DefaultImpl(value);
      }
    }

    public class DefaultImpl : BaseClass
    {
      private int _value;

      public DefaultImpl(int value)
      {
        _value = value;
      }
    }
```

If you ask Fixture to create `BaseClass`, it will create `DefaultImpl` instance successfully.
That happens because of [this code](https://github.com/AutoFixture/AutoFixture/blob/a3d21c3f67e49948c18cc8bbdf9f92a820fddd89/Src/AutoFixture/Kernel/FactoryMethodQuery.cs#L43) - operators are returned as static methods.

Is that expected behavior? I'd say that no, because that is very tricky and unclear behavior. In my opinion, cast operator should not be used as a way to construct instance. Moreover, if that is an explicit cast operator.

**Comment by zvirja** [comment]
@AutoFixture/core Guys, if you have a free time - could you please examine this issue and confirm that it's a bug? I'm about to mark it as a bug and fix 😉

**Comment by moodmosaic** [comment]
I've never thought about this when adding support for Static Factory Methods. Interesting.

What's wrong with leaving it the way it currently is though?

After all, we might be actually doing the right thing, specially in these situations where one has to [deal with primitive obsession](https://lostechies.com/jimmybogard/2007/12/03/dealing-with-primitive-obsession/).

**Comment by zvirja** [comment]
Initially I observed that issue using the [System.IO.Abstractions](https://github.com/tathamoddie/System.IO.Abstractions) library. If you check [FileInfoBase.cs](https://github.com/tathamoddie/System.IO.Abstractions/blob/master/System.IO.Abstractions/FileInfoBase.cs) implementation you will notice the following:
```csharp
public static implicit operator FileInfoBase(FileInfo fileInfo)
{
	return new FileInfoWrapper(fileInfo);
}
```

They provide a way to cast a real `FileInfo` into the abstractions wrapper. It might be useful if you would like to pass object from legacy code into the other code written on the abstractions.

Now consider the following test:
```csharp
[Theory, AutoConfiguredNSubstituteData]
public void SomeTest(FileInfoBase fileInfo)
{
   ...
}
```
Given that `FileInfoBase` is an abstract class, I'd expect that a NSubstitute stub will be created. However, I see the a failed test, because AF uses the conversion method and tries to create a real `FileInfo` instance:
```
System.IO.FileNotFoundException
Could not find file 'fileName134b0f07-0200-417a-81fd-70470c8e1500'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
```

Here I'd consider the existing behavior as buggy and definitely the helper conversion method should not be considered as a factory method 😞

Of course, there is a workaround - add the `[Substitute]` attribute. However, if `FileInfoBase` is required somewhere deeply inside the graph - it will not help.
----
After considering your example, I still have doubts whether it's OK to use the conversion methods. For the sample with "primitive obsession" I'd expect that such classes have a public constructor (or even the default empty one) and/or the settable properties. Therefore, AutoFixture will be capable to create such objects anyway. However, if public constructor and a factory methods are missing and the only way is the conversion method - is that fine in such cases to use those conversion methods? Likely, author wanted to prohibit the activation and it's better to explicitly configure AF how to activate such objects..

It could happen that I'm missing some scenario when it's absolutely fine to have construction available via conversion methods only, so let's fine such a sample 😉

@moodmosaic What do you think now? 😏

**Comment by moodmosaic** [comment]
I think, what I'm trying to say might make more sense by quoting the following 😃 

"AutoFixture was originally build as a tool for Test-Driven Development (TDD), and TDD is all about **feedback**. In the spirit of [GOOS](http://amzn.to/VI81bP), you should **listen to your tests**. If the tests are hard to write, you should consider your API design. **AutoFixture tends to amplify that sort of feedback** [..]" -- https://stackoverflow.com/a/22688857/467754

Based on the that, I'm still not convinced that we should change AutoFixture because `FileInfoBase` returns `FileInfoWrapper` and that `FileInfoWrapper` isn't setup with reasonable [local defaults](https://stackoverflow.com/a/6739953/467754)...

**Comment by zvirja** [comment]
> FileInfoWrapper isn't setup with reasonable local defaults...

Well, it's definitely not a good local default because it fail my unit tests because of a non-existing file 😄

Let's consider this issue from another perspective. As I mentioned above, we have situation when a class:
- doesn't have public constructor
- doesn't have a factory method
- has conversion method only

This class doesn't look friendly for the direct construction as all the usual creation ways are closed. The only way it leaves is to use the conversion method. While it works, it doesn't seem obvious that this is a right way and it should be used by default. I'd vote to have explicitness in such situations. 

For me, the question is not whether conversion is the right construction method in general. Rather, it is "should the conversion be used to construct objects _when any other way is missing_?" Do you see a practical use-case when you want to might want to use conversion method for the class without other construction ways? 😕

**Comment by moodmosaic** [comment]
>when a class:
>- doesn't have public constructor
>- doesn't have a factory method
>- has conversion method only
>
>This class doesn't look friendly for the direct construction as all the usual creation ways are closed. The >only way it leaves is to use the conversion method. While it works, it doesn't seem obvious that this is a >right way and it should be used by default. I'd vote to have explicitness in such situations. 

Good point. It looks like we have a bug (rather than a feature) here.

---

One way to 'fix' this is the following:

- Change the existing behavior so that it throws an exception
  - If possible, provide a very detailed message
- Add a new behavior that, once added to the Fixture instance, it *will* allow an object to be created through its explicit/implicit conversion methods
  - If possible, modify the above (hypothetical) detailed exception message to include an example of how to add this new behavior to the Fixture instance

**Comment by zvirja** [comment]
I'm not sure I got the whole idea, so please answer the following:
- Under which exact condition that exception should be thrown?
- Where exactly the exception should be thrown? Likely, the [FactoryMethodQuery](https://github.com/AutoFixture/AutoFixture/blob/a3d21c3f67e49948c18cc8bbdf9f92a820fddd89/Src/AutoFixture/Kernel/FactoryMethodQuery.cs) is not responsible for that.
- For the initial scenario I don't want any exception to be thrown. Rather, I expect that NSubstitute customization handles the request and returns mock.. Can we still make this happen within your fix?
- Do you have some particular way in mind on how to add the customization behavior? We could add smth like the [OmitAutoProperties](https://github.com/AutoFixture/AutoFixture/blob/a3d21c3f67e49948c18cc8bbdf9f92a820fddd89/Src/AutoFixture/Fixture.cs#L198) property, but I think it's too much for such a small feature.. 

---

I think it's a quite rare scenario to introduce the ability to change the AF default behavior. Therefore, I wanted to suggest a stupidly straightforward fix - change the [FactoryMethodQuery](https://github.com/AutoFixture/AutoFixture/blob/a3d21c3f67e49948c18cc8bbdf9f92a820fddd89/Src/AutoFixture/Kernel/FactoryMethodQuery.cs#L43) and add a filter to skip the conversion methods. Later when class is created, those methods will not be discovered and user will get an exception that AF doesn't know how to construct the object. If user wants to construct the particular type using its conversion method - he can add a customization for that particular type.

That might be considered as a breaking change in behavior, so we could add this fix to the `v4` branch. However, if we consider current behavior as a bug - it will be fine to fix it even for v3 :relaxed:

Do you like my way or you still want to handle this situation in a special way in the kernel (with exceptions and configuration)?

**Comment by moodmosaic** [comment]
>Do you like my way or you still want to handle this situation in a special way in the kernel (with exceptions and configuration)?

I think it's up to you 😃

>I'm not sure I got the whole idea, so please answer the following:
>- Under which exact condition that exception should be thrown?

I'm currently swamped and can't walk you through off the top of my head for what I wrote [here](https://github.com/AutoFixture/AutoFixture/issues/691#issuecomment-311319310) (for `v3`).

So if you feel like changing `FactoryMethodQuery` I'd say go for it, but then this (breaking) change can target the `v4` branch.

**Comment by zvirja** [comment]
Is fixed in v4.
