### ISSUE TITLE
Regular Expression Data Annotation breaks Create()

### ISSUE THREAD

**Issue by lesheinz** [AutoFixture/AutoFixture#692]
I recently got an error creating an Object with AutoFixture. The error was 'cannot convert type string to integer'. The property in question was an integer and I had set the RegularExpression DataAnnotation to `'\d\d:\d\d'`. 
The idea  was that the input for the property would take hours and minutes seperated by a semicolon. The value would translate (via a custom Json Converter) into an integer variable (the total minutes).

Looking back at the problem at hand it is obvious that AutoFixture tried to create a string that fits the regex and stuff it into an integer property. Which should not work of course.

The lack of a more detailed exception message did force me to debug the issue for quite some time though. Maybe some more information in the message would have prevented that from happening. I would have loved to see the property on which the creation failed and maybe event the value that was created by AutoFixture for that property.

**Comment by sergeyshushlyapin** [comment]
> The value would translate *(via a custom Json Converter)*

If you need a *custom* Json Converter to translate your value, you should [customize AutoFixture](http://megakemp.com/2013/04/16/general-purpose-customizations-with-autofixture/) first so that it's able to *use the converter*.

Though, moving [from primitive obsession to domain modelling](http://blog.ploeh.dk/2015/01/19/from-primitive-obsession-to-domain-modelling/) could be a better option.

**Comment by lesheinz** [comment]
You're absolutely right. I did solve the issue by using a better datatype for the property (Timespan). I just wanted to point out that maybe the exception handling by AutoFixture could have been better.

As to the domain modelling point:
The validation and json conversion was already a part of the model. Nevertheless thanks for linking the post ! I like the idea of wrapping validation and constraints into the datatypes themselves.

**Comment by moodmosaic** [comment]
>I just wanted to point out that maybe the exception handling by AutoFixture could have been better.

Should we discuss this on a separate issue? If so, could we close this one? :smiley:

**Comment by lesheinz** [comment]
Oh sure, no problem!
