### ISSUE TITLE
Generate IQueryable<T> specimens

### ISSUE THREAD

**Issue by sergeyshushlyapin** [AutoFixture/AutoFixture#705]
The following code throws `ObjectCreationException`:
```csharp
var fixture = new Fixture();

// Ploeh.AutoFixture.ObjectCreationException : AutoFixture was unable to create an instance from
// System.Linq.IQueryable`1[System.Object] ...
fixture.Create<IQueryable<object>>();
```

**Comment by moodmosaic** [comment]
IME, I've rarely seen `IQueryable<T>` being used outside Entity Framework. If we agree that [it's somewhat (or rather) a problematic interface](https://www.infoq.com/news/2012/03/IQueryable-api), should we consider adding support for it?

---

Wouldn't it be possible to just create an `IEnumerable<T>` and then convert it to an `IQueryable<T>`? Like so:

```c#
[Fact]
public void ConvertedEnumerableIsNotEmpty()
{
    var actual =
        new Fixture().Create<IEnumerable<object>>().AsQueryable();
    Assert.NotEmpty(actual); // Passes.
}
```

**Comment by sergeyshushlyapin** [comment]
> Wouldn't it be possible to just create an IEnumerable<T> and then convert it to an IQueryable<T>?

Yes, it's definitely possible. That is the way I used to create such kind of specimens. I just thought the test could be *a bit easier* if one wouldn't need to call the `AsQueryable()` method:
```csharp
[Theory, AutoData]
public void TestSmth(SomeSut sut, IEnumerable<> enumerable)
{
  var queryable = enumerable.AsQueryable();
  sut.DoSmthWithQueryable(queryable);
  Assert.EverythingIsOkWith(queryable);
}
```

```csharp
[Theory, AutoData]
public void TestSmth(SomeSut sut, IQueryable<> queryable)
{
  sut.DoSmthWithQueryable(queryable);
  Assert.EverythingIsOkWith(queryable);
}
```

> If we agree that it's somewhat (or rather) a problematic interface, should we consider adding support for it?

Please let me cite the project description:

> AutoFixture is an open source library for .NET designed to **minimize the 'Arrange' phase of your unit tests** in order to maximize maintainability.

Despite the interface can be considered as problematic, there are still can be some _valid_ cases where developers might need to use it (e.g. when implementing a LINQ provider). Shouldn't AutoFixture just follow it's main goal and create the requested specimens?

**Comment by moodmosaic** [comment]
My point is that there's the existing [`.AsQueryable()`](https://msdn.microsoft.com/en-us/library/bb353734.aspx), which is just 13 characters long and it's honest in what it does—converts an IEnumerable to an IQueryable.

I'm a little worried about '_adding support for IQueryable_' because [in reality there's a whole lot more](http://blog.ploeh.dk/2012/03/26/IQueryableTisTightCoupling/) than just converting an IEnumerable to an IQueryable (which is what #706 currently does)...

**Comment by sergeyshushlyapin** [comment]
Clear, thanks.
