### ISSUE TITLE
AutoFixture override value of public fields

### ISSUE THREAD

**Issue by trondd** [AutoFixture/AutoFixture#719]
See repository https://github.com/trondd/AutoFixture-issue-719.git for a description of the issue.

**Comment by trondd** [comment]
The issue is solved by changing the `Condition` field in the `Rule` class to a get-only property. The question is why AutoFixture does this to begin with.

**Comment by Zvirja** [comment]
This is default AutoFixture behavior to initialize any writable public property and field. That is done to ensure that your object graph is fully initialized (dependencies could be injected via properties in addition to constructor).
You can disable that as described in [wiki](https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#disable-autoproperties). If you are interested in code base, this behavior is implemented in [this file](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Kernel/AutoPropertiesCommand.cs).

Hope that will help you to mitigate the issue :)

**Comment by trondd** [comment]
Thanks for an excellent explanation. When I think about it it totally makes sense.
