### ISSUE TITLE
Idioms: Verify guarded constructor with failing overload throws invalid exception

### ISSUE THREAD

**Issue by sergeyshushlyapin** [AutoFixture/AutoFixture#723]
Given a type that has got all the valid null guards but cannot be instantiated due to some error in one of the constructors (invalid type casting in the first one):

```csharp
public class TypeWithNullGuardAndFailingCtorOverload
{
    public TypeWithNullGuardAndFailingCtorOverload(object arg1)
        : this(arg1, (int)new object()) // throws InvalidCastException (expected)
    {
    }

    public TypeWithNullGuardAndFailingCtorOverload(
        object arg1, object arg2)
    {
        if (arg1 == null)
            throw new ArgumentNullException();
        if (arg2 == null)
            throw new ArgumentNullException();
    }
}
```

When this type is verified by the [GuardClauseAssertion](https://github.com/AutoFixture/AutoFixture/blob/ab829640ed8e02776e4f4730d0e72ab3cc382339/Src/Idioms/GuardClauseAssertion.cs), the `Ploeh.AutoFixture.Idioms.GuardClauseException` is thrown without any reference to the real exception causing the problem:
`
An attempt was made to assign the value null to the parameter "arg1" of the method ".ctor", and no Guard Clause prevented this. Are you missing a Guard Clause?
          Method Signature: Void .ctor(System.Object)
          Parameter Type: System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, ...
`

Since the error is in the constructor overload design rather that in the guard, it's expected to see the original `InvalidCastException` only. The `GuardClauseException` should not be mentioned here at all.

**Comment by sergeyshushlyapin** [comment]
To solve this issue the following [redundant `catch` block](https://github.com/AutoFixture/AutoFixture/blob/ab829640ed8e02776e4f4730d0e72ab3cc382339/Src/Idioms/NullReferenceBehaviorExpectation.cs#L57-L60) in the `NullReferenceBehaviorExpectation` class have to be removed.

**Comment by sergeyshushlyapin** [comment]
Sorry, I was not really precise, the inner exception exists but it is not visible _immediately_ in the test output (as I stated before). In order to figure out what was wrong I had to debug the test (which is inconvenient):

![image](https://cloud.githubusercontent.com/assets/4719165/20730838/4c42432c-b690-11e6-8c51-c8c5c782c16e.png)

**Comment by zvirja** [comment]
@moodmosaic Could you please elaborate on this, so we finally close this issue? 😉

It looks is fine to me. Yep, it's a false-positive, however it looks like a pretty exotic case and `InnerException` is present, so I don't see any issue here and how that should be improved. In most cases _you don't_ want to see how exactly ctor failed if guard was missing - it's enough to simply know about issue.

**Comment by moodmosaic** [comment]
Well, the more information we can provide, the easier it can be to troubleshoot issues. If we can easily add the inner exception on the message, it'd be nice.

**Comment by zvirja** [comment]
I've just checked that and found that fixing of this particular scenario wouldn't help a lot. There are 7 more places throwing the `GuardClauseException` and we'll need to fix them all which will create a bit of mess.

I'm still not sure that the inner exception message is actually always helpful. If you missed the `null` value guard, your code will likely fail with an arbitrary exception as you haven't configured the input parameters and method/ctor logic is broken. In this case the actual exception and it's message (e.g. `NullReferenceException` or `InvalidOperationException`) might make it look like you should to fix the exception reason, but that is not true. In reality you should put the guard and no more actions are required.

The scenario described by Sergey is pretty rare and a bit exotic. I believe that for such cases the existing `InnerException` property should be enough to figure out the issue.

I really afraid that the inner exception message will be misleading and will bring more issues than benefit.

@sergeyshushlyapin @moodmosaic Could you reply to my concerns?

**Comment by moodmosaic** [comment]
>I really afraid that the inner exception message will be misleading and will bring more issues than benefit.

I doesn't necessarily have to be the *inner* exception per-se. Do we have other information we could add in the (existing) exception message?

**Comment by zvirja** [comment]
> Do we have other information we could add in the (existing) exception message?

I don't see how we could improve the existing message without adding the potentially misleading information. The scenario mentioned by Sergey is very rare and it doesn't worth it to describe it. Do you see something?

**Comment by moodmosaic** [comment]
IME, if someone reaches up to the point of reporting an issue (like @sergeyshushlyapin did), it can probably means that the issue isn't *that* rare...

I defer the decision to @sergeyshushlyapin and you. :cowboy_hat_face:

**Comment by zvirja** [comment]
> it can probably means that the issue isn't that rare

Well, who knows, but it's a good point! 👍

@sergeyshushlyapin Could you please follow-up?

**Comment by zvirja** [comment]
> I do not know if that is a valid solution, but have you tried this?

The suggested fix would lead to even more confusion as the automatically generated arguments could often lead to the failure. However that doesn't matter as long as null guard is present.

Consider the following method:
```c#
public void Method(int value, string message)
{
    if(!this._knownValues.Contain(value)) throw new ArbitraryException("Value not registered")
}
```

In this case when `message` is `null` expectation will fail with `ArbitraryException` and you might think that it's a problem. However, the problem is that you have missing guard. If you have a guard, you would never reach the line causing the `ArbitraryException`. And that is the trick - if method failed with an arbitrary exception - the reason is the guard which is missing.

Therefore, the suggested fix would bring more damage than benefit.

>  It does not matter (for me) if it's 'rare' or not.

Sure it doesn't! However, we already wrap the inner exception and it's fully available on the exception message. If you use `NCrunch` or `R#` you should see the inner exception message by default. Example of the output from R#:

```
AutoFixture.Idioms.GuardClauseException
An attempt was made to assign the value null to the parameter "arg1" of the method ".ctor", and no Guard Clause prevented this. Are you missing a Guard Clause?
Method Signature: Void .ctor(System.Object)
Parameter Type: System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Declaring Type: AutoFixturePlayground.GuardClauseTest+TypeWithNullGuardAndFailingCtorOverload, AutoFixturePlayground, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Reflected Type: AutoFixturePlayground.GuardClauseTest+TypeWithNullGuardAndFailingCtorOverload, AutoFixturePlayground, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   at AutoFixture.Idioms.NullReferenceBehaviorExpectation.Verify(IGuardClauseCommand command) in C:\projects\autofixture\Src\Idioms\NullReferenceBehaviorExpectation.cs:line 61
   at AutoFixture.Idioms.CompositeBehaviorExpectation.Verify(IGuardClauseCommand command) in C:\projects\autofixture\Src\Idioms\CompositeBehaviorExpectation.cs:line 44
   at AutoFixture.Idioms.GuardClauseAssertion.VerifyNormal(IMethod method) in C:\projects\autofixture\Src\Idioms\GuardClauseAssertion.cs:line 275
   at AutoFixture.Idioms.GuardClauseAssertion.Verify(ConstructorInfo constructorInfo) in C:\projects\autofixture\Src\Idioms\GuardClauseAssertion.cs:line 103
   at AutoFixture.Idioms.IdiomaticAssertion.Verify(ConstructorInfo[] constructorInfos) in C:\projects\autofixture\Src\Idioms\IdiomaticAssertion.cs:line 179
   at AutoFixture.Idioms.IdiomaticAssertion.Verify(Type type) in C:\projects\autofixture\Src\Idioms\IdiomaticAssertion.cs:line 96
   at AutoFixturePlayground.GuardClauseTest.TestGuard() in C:\Users\Alex\Documents\Visual Studio 2017\Projects\AutoFixturePlayground\AutoFixturePlayground\Class1.cs:line 55

System.InvalidCastException
Specified cast is not valid.
   at AutoFixture.Idioms.ReflectionExceptionUnwrappingCommand.Execute(Object value) in C:\projects\autofixture\Src\Idioms\ReflectionExceptionUnwrappingCommand.cs:line 74
   at AutoFixture.Idioms.NullReferenceBehaviorExpectation.Verify(IGuardClauseCommand command) in C:\projects\autofixture\Src\Idioms\NullReferenceBehaviorExpectation.cs:line 51
```

AutoFixture already provides all the necessary diagnostics - you simply need to scroll over the whole exception message 😉

Given that, do you see how else we could improve the situation without leading to the unnecessary confusion? I'd be really happy to improve the situation if you only could suggest how.

**Comment by sergeyshushlyapin** [comment]
> However, we already wrap the inner exception and it's fully available on the exception message. If you use NCrunch or R# you should see the inner exception message by default.

Oh, nice! Could it be that this part was missing when I reported the issue about one year ago? This exception message definitely looks good to me. thanks.

**Comment by zvirja** [comment]
>  Could it be that this part was missing when I reported the issue about one year ago?

We haven't changed the code, so I don't know 😉 Well, there is a chance that some output window simply trimmed the exception message (e.g. NCrunch exception preview).
