### ISSUE TITLE
Values provided by seeded customization algorithm get overwritten.

### ISSUE THREAD

**Issue by roarwrecker** [AutoFixture/AutoFixture#727]
I am experimenting with the Customize method using the FromSeed method. Maybe I am using the feature not like intended...
The following example does not work the way I want to. I only want to create anonymous values for the properties which have not been already set in the seed.

```CSharp
[TestMethod]
public void SeedTest()
{
	var fixture = new Fixture();
	var seed = new MyClass
	{
		MyInteger = 10
	};
	fixture.Customize<MyClass>(c =>
		c.FromSeed(s =>
		{
			if (s.MyInteger == default(int))
			{
				s.MyInteger = fixture.Create<int>();
			}
			return s;
		}));
	var result = fixture.Create(seed);
	Assert.AreEqual(10, result.MyInteger);
}

private class MyClass
{
	public int MyInteger { get; set; }
}
```

The idea of this customization is to create a generic algorithm using seeds to only assign values to the properties which have not already been set by the provided seed.

**Comment by Rudauke** [comment]
I have never used the FromSeed() method before, so I won't be discussing if it works correctly or not, but if you want to always create an object with a specified field value, you can use:

`fixture.Customize<MyClass>(x => x.With(y => y.MyInteger, seed.MyInteger));`

**Comment by zvirja** [comment]
@roarwrecker I agree with @Jankowski-J that it would be much simpler to write something like:
```csharp
fixture.Customize<MyClass>(x => x.With(y => y.MyInteger, 10));
var result = fixture.Create<MyClass>();
```
or if you need that customization for one time only:
```csharp
var result = fixture
    .Build<MyClass>()
    .With(x => x.MyInteger, 10)
    .Create();
```

Let me know whether your question is solved or your real example doesn't fit.

**Comment by roarwrecker** [comment]
Thanks for your replies.
I wanted to create a generic customization which creates anonymous values only if the property has not been set.

Never mind. It was just an experiment...
