### ISSUE TITLE
Nullable values should sometimes be null

### ISSUE THREAD

**Issue by ofirgeller** [AutoFixture/AutoFixture#731]
If I use auto fixture to create a nullable value or a complex object with nullable properties null is a valid value that should sometimes be "created". I do not know what is the correct proportions to use but if i'm using auto fixture for some kind of fuzzing/property testing this is very important.

**Comment by zvirja** [comment]
I'm not sure about that. `null` is a valid value for the reference types as well, however we never generate `null` for them. 

On other hand, currently we don't handle `Nullable<T>` on any special manner. Rather, we discover it's constructor which requires value and invoke it.

If you need such behavior, you might want to create a [customization](https://github.com/AutoFixture/AutoFixture/wiki/Internal-Architecture#customizations) that will handle `Nullable<T>` requests and generate null for them from time to time. However, it's a question whether AutoFixture is the right tool for such tasks. Probably, you want to look at the [FsCheck](https://github.com/fscheck/FsCheck).

I'd vote to not implement this. Reference @AutoFixture/core so they could add their thoughts.

**Comment by ofirgeller** [comment]
@zvirja 
Can't seem to mention @AutoFixture/core.

If you are not creating values randomly, then this is against the concept of this library, but if you are, this is asking for the range of the random values to match the range of the type.

It's true that all reference types are nullable in C#, but the difference is that they are always nullable and therefore nullable by default. If we assume null is a valid value we will need to add a way for the user of this library to specify that null is not a valid value and that is not a road I would recommend.

However with null-able values that are explicitly nullable the user has explicitly defined null as a possible value. I know this is attributing intent and that this is not a clear cut interpretation but I think in most use cases it is the correct one.

One big argument against my request would be that if we create a null value randomly in the ratio of 1 in the number of all possible values it will happen so infrequent that it will not be of any use anyway and might even appear like a bug to the user once in a blue moon. and deciding on any other ratio is too arbitrary.

So for this reason I've changed my mind and now think this is not a good idea, and that it might be enough to document the current behavior instead, thank you for your input :)

**Comment by zvirja** [comment]
Thanks for the reply :) Yes, it's indeed would might create a headache during the debug process.

Can we close the ticket or you have more questions? :wink:

**Comment by codecontemplator** [comment]
I used something like this to inject random null values for nullable types.

```csharp
public class InjectNullValuesForNullableTypesSpecimenBuilder : ISpecimenBuilder
{
    private Random random = new Random();
    private const double LikelihoodOfNull = 0.1;

    public object Create(object request, ISpecimenContext context)
    {
        if (request is Type type)
        {
            var underlyingType = Nullable.GetUnderlyingType(type);
            if (underlyingType != null)
            {
                if (random.NextDouble() < LikelihoodOfNull)
                    return null;

                return context.Resolve(underlyingType);
            }
        }

        return new NoSpecimen();
    }
}
```
