### ISSUE TITLE
System.ComponentModel.DataAnnotations stop seeding values from including property names

### ISSUE THREAD

**Issue by tomRedox** [AutoFixture/AutoFixture#733]
The presence of data annotations seems to change how the data in complex objects is seeded.

```
    using System.ComponentModel.DataAnnotations;
    public class Customer
    {
        public int ContactId { get; set; }

        [StringLength(60)]
        public string Add1 { get; set; }

        public string Add2 { get; set; }
    }
```

Using `_fixture.Create<Customer>()` to create an instance of the class above will result in a class that has values along the lines of:

ContactId = 123
Add1 = "cf89518c-f0a1-4aa8-84f0-1e323c5f95eb"
Add2 = "**Add2**2e497514-cc56-49af-8003-83211658d565"

So, the Add1 property that has a data annotation doesn't have an 'Add1' prefix where as the Add2 property with no annotation does have a prefix.

Is that expected behaviour, and if so, is there any way to get the prefix/seed automation when using data annotations?

**Comment by cvbarros** [comment]
That is indeed expected behavior, because the geneation of data
annotation-aware values must conform to the constraints imposed.

This effectively turns off the seeded part, and focus on genrating only
valid values.

You can disable this behavior by customizing the fixture with a
NoDataAnnotationsCustomization.

**Comment by tomRedox** [comment]
many thanks @cvbarros, that sorted it.  I had read some of the documentation but hadn't come across that.

For anyone else who comes across this, you can add that customisation as follows:

```
_fixture.Customize(new NoDataAnnotationsCustomization());
```
