### ISSUE TITLE
AutoFixture declarative attributes

### ISSUE THREAD

**Issue by siberianguy** [AutoFixture/AutoFixture#734]
I use AutoFixture with Fixie tests. A lot of pleasure. No attributes for tests (thanks to Fixie), no cumbersome, repetetive code for fixtures (thanks to AutoFixture). But sometimes I feel a need for a little bit of customization. Let's take this test as an example:

```
public void Should_do_something(IEnumerable<Client> clients)
{
   ...
}
```

I set up so AutoFixture automatically generates value for it. And a collection of three elements is generated. Sometimes it's not what I want (i. e. I need to test for an empty collection).

Now I know how to fix it in a imperative way by calling CreateMany but it doesn't suit this scenario. It feels like declarative approach (i. e. EmptyCollectionAttribute applied to clients argument) would work much better in this scenario. I assume some internal part of AutoFixture need to be aware of this attribute (it could be a plugin). So my question is whether there's anything like that. If not, I would be grateful for a hint which part of AutoFixture I can customize to implement this feature.

**Comment by zvirja** [comment]
Hi,

Sorry for such a delayed reply. I am not aware of such a feature out of the box, but it should be pretty simple to create such an attribute if you need it. Unfortunately, I don't have too much experience with Fixie, therefore I've written a sample for xunit. I believe it should demonstrate you an idea, so it could be easily ported to your framework.

```csharp
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
public class EmptyCollectionAttribute : CustomizeAttribute
{
	public override ICustomization GetCustomization(ParameterInfo parameter)
	{
		var paramType = parameter.ParameterType;
		if (!paramType.IsGenericType || paramType.GetGenericTypeDefinition() != typeof(IEnumerable<>))
			throw new InvalidOperationException("Invalid type");

		var emptyArray = Array.CreateInstance(paramType.GenericTypeArguments.Single(), 0);
		return new EmptyCollectionCustomization(parameter, emptyArray);
	}

	private class EmptyCollectionCustomization : ICustomization
	{
		private readonly ParameterInfo _paramToMatch;
		private readonly object _result;

		public EmptyCollectionCustomization(ParameterInfo paramToMatch, object result)
		{
			_paramToMatch = paramToMatch;
			_result = result;
		}

		public void Customize(IFixture fixture)
		{
			fixture.Customizations.Add(
				new FilteringSpecimenBuilder(
					new FixedBuilder(_result),
					new EqualRequestSpecification(_paramToMatch)));
		}
	}
}

public class EmptyCollectionAttributeTest
{
	[Theory, AutoData]
	public void GetValue(
		[EmptyCollection] IEnumerable<string> strings, 
		[EmptyCollection] IEnumerable<int> ints, 
		[EmptyCollection] IEnumerable<List<int>> lists)
	{
		Assert.Empty(strings);
		Assert.Empty(ints);
		Assert.Empty(lists);
	}
}
```

Hope that still does matter for you and will inspire you 😉

**Comment by zvirja** [comment]
Closing this one due to inactivity. @siberianguy Feel free to re-open the issue if you still have questions or suggestions.
