### ISSUE TITLE
remove dependency on xunit.extensions

### ISSUE THREAD

**Issue by jimmymain** [AutoFixture/AutoFixture#738]
xunit.extensions cannot be upgraded to version 2.0.0 because autofixture.xunit has a dependency on an older version.
since xunit.extensions is temporary migration fix, can it not be removed now?

**Comment by moodmosaic** [comment]
Could you try using AutoFixture.Xunit2 instead?

**Comment by jimmymain** [comment]
damn: I knew that... sorry for bothering you...
