### ISSUE TITLE
Should we keep our sign key secret?

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#746]
Previously @ploeh kept the signing key for all the assemblies in secret. I'd like to discuss whether it indeed makes sense.

If we check other popular testing helpers, we'll find that all them has opened public key:
1. xunit - [key is open](https://github.com/xunit/xunit/blob/master/src/signing.snk).
1. nunit - [key is open](https://github.com/nunit/nunit/blob/master/src/nunit.snk).
1. NSubstitute - [key is open](https://github.com/nsubstitute/NSubstitute/blob/master/Source/nsubstitute.snk).
1. Moq - [key is open](https://github.com/moq/moq4/blob/master/Moq.snk).
1. FakeItEasy - [key is open](https://github.com/FakeItEasy/FakeItEasy/blob/master/FakeItEasy.snk).
1. FluentAssertions - [key is open](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions.snk).

I don't see too much sense to keep AF key closed and believe we can also add it to the repository. Indeed, signing allows to prove the assembly's identity, but I don't believe we strictly require that. Our days NuGet is used to distribute packages, rather than third-party sites where the identity indeed does matter.

If we publish key to the repository, that will have a lot of benefits:
1. It will be easier to generate NuGet with signed assemblies by CI.
1. It will be easier for people to make own AutoFixture assemblies and test whether it solves particular issue. Consider the following scenario:

    1. You found some bug in AF. You download source code locally and fix it.
    2. Now you have AF assemblies with fixed bug and you want to test whether it helped.

    Here is where the issues start. If you assemblies are unsigned, you cannot simply put the modified assemblies to the local NuGet cache - project will not compile. Rather, you need to update all your projects to target to a new assembly - just for a simple test. The things become even worse when that is the core `AutoFixture` assembly, as other depending libraries (like `AutoFixture.xunit` or `AutoFixture.NSubstitute`) will need to be updated as well.

    If we ship signing key issue will be solved.
1. You don't need to store one more secret :)

As for the @ploeh, it seems he [didn't have](https://github.com/AutoFixture/AutoFixture/issues/703#issuecomment-280425693) strong reason to keep it secret.

Personally, I'd vote using both hands to open the key and simplify everybody's life.
Guys (@moodmosaic, @adamchester, @ecampidoglio, @klimisa) - what do you think about this?

**Comment by adamralph** [comment]
👍 to open the key.

**Comment by abatishchev** [comment]
Don't see any reasons not to open it. How cares? I doubt anyone does.

**Comment by cvbarros** [comment]
Open the key and keep nuget.org privileges secret.

**Comment by moodmosaic** [comment]
Although I find the topic of discussion interesting, I have no opinion. Voting neutral on that one.

**Comment by zvirja** [comment]
@ecampidoglio and @adamchester 
Could you please add your opinions here as well? 
I'm currently working on CI to have early builds for v4 and simplify the release procedure itself. I need the sign key on CI - so l need this decision.

**Comment by ecampidoglio** [comment]
I think it makes sense to open it up, especially considering the second point brought up in [this comment](https://github.com/AutoFixture/AutoFixture/issues/746#issue-218774704).
Also, these days authenticity is guaranteed by the NuGet account that publishes the package, which certainly wasn't the case during the early days of AutoFixture.

So, sure, you can go ahead and commit the keys to the repo as far as I'm concerned. 👍

**Comment by adamchester** [comment]
👍 to open it up

**Comment by zvirja** [comment]
Thanks, agreed :)
