### ISSUE TITLE
Ensure that for each nuspec file we have set upper boundary for dependencies

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#747]
We should ensure that for each dependency in our `nuspec` files the upper bound is set. For instance, if we support xunit2, we should check that our dependency is following: `[2.0, 3.0)`, rather than simple `2.0`.

That is to ensure that library will not become broken after our dependency releases a new major version.

**Comment by zvirja** [comment]
After thinking more about this I'm not sure whether the cap should be present. If we don't update the particular library in time, it will be unavailable. On other hand, people will not install the AF when compatibility wasn't explicitly tested, so it will be clear that it's not supported yet..

@AutoFixture/core Guys, what do you think about this one?

**Comment by moodmosaic** [comment]
I don't see why not 👍 

Some dependencies, however, *do* work even after releasing a major version. Take Moq as an example, where AFAICT we depend on Moq 3 but I'm pretty sure AutoFixture.AutoMoq works also with Moq 4+.

I think it's safer though to set an upper bound limit.

**Comment by zvirja** [comment]
In this case, I'd suggest us to follow the next approach:

1. Set upper limit to all the external components we use. Usually that are the testing frameworks for our glue libraries.
1. For each supported version of library (e.g. Moq 2, Moq 3) add a test project like that is done [here](https://github.com/AutoFixture/AutoFixture/pull/702). 

With such approach we will ensure that we always have tests for the particular version of dependency and if we guarantee that it works.

**Comment by moodmosaic** [comment]
`1.` is fine by me 👍 
`2.` might need maintenance  in the long run

---

I'm voting, for now, only for `1.`, I'd hold `2.` unless @AutoFixture/core has a different opinion.

**Comment by klimisa** [comment]
Agreed.  Vote for 1, hold on 2. 👍

**Comment by zvirja** [comment]
Fine, agreed with 1 👍 

@moodmosaic Could you clarify which exact maintenance dept you mean? The idea was that we create an empty project which imports all the `*.cs` files from the base test project. The only difference will be the newer package dependencies. If later you want to modify any particular test body, we'll need to modify it in a single place only.

If we don't have such tests - how can we be sure that we support each particular dependency version and it works? :worried:

**Comment by moodmosaic** [comment]
@zvirja,

>The idea was that we create an empty project which imports all the *.cs files from the base test project. The only difference will be the newer package dependencies.

This works as long as the base test project uses Semantic Versioning, and with the hope that a major version won't have breaking changes (?)

I don't think it's worth the effort... It was an ad-hoc case [the one for AutoFixture.AutoFakeItEasy2](https://github.com/AutoFixture/AutoFixture/pull/702), so perhaps we should invoke the [rule of three](https://blog.codinghorror.com/rule-of-three/) and wait.

**Comment by zvirja** [comment]
Done!
