### ISSUE TITLE
AutoFixture.NSubstitute does not work with latest version of Nsubstitute 2.0.2.0

### ISSUE THREAD

**Issue by disklosr** [AutoFixture/AutoFixture#752]
I have a project configuration with the following libraries:
- AutoFixture.NSubstitute version 3.50.2 which is documented to be working with all Nsubstitute version >= 1.5.0
- Nsubstitute version 2.0.2.0 which was release on last february

During runtime I get the following error:
```
 MESSAGE:
System.IO.FileLoadException : Could not load file or assembly 'NSubstitute, Version=1.10.0.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  ----> System.IO.FileLoadException : Could not load file or assembly 'NSubstitute, Version=1.5.0.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
+++++++++++++++++++
STACK TRACE:
at Ploeh.AutoFixture.AutoNSubstitute.SubstituteRelay.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.ResidueCollectorNode.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Fixture.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
   at ...
```

Forcing the version of NSubstitute to the one just before 2.0.2.0 (that is version 1.10.0) solved the issue.
This leads me to the conclusion that the latest version of Nsubstitute isn't compatible with your library.

**Comment by zvirja** [comment]
> AutoFixture.NSubstitute version 3.50.2 which is documented to be working with all Nsubstitute version >= 1.5.0

Well, likely that statement was written when NSubsitute 2.0 release ;-)

Nevertheless, I've just tested this approach with a regular .NET Framework library and it appeared to work. The only requirement is that you need to have [assembly binding redirect](https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx) to the NSubstitute `2.0.2.0`, as AutoFixture libraries were compiled against NSubstitute `1.5.0.0`.

Here is my code.
File with test:
```csharp
public class NSubstituteIntegrationTest
{
    [Fact]
    public void ToTest()
    {
        var fixture = new Fixture().Customize(new AutoNSubstituteCustomization());

        var test = fixture.Create<ITest>();
        Assert.NotNull(test);
    }

    public interface ITest { }
}
```

`app.config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="NSubstitute" publicKeyToken="92dd2e9066daa5ca" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.2.0" newVersion="2.0.2.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Therefore, try applying the AssemblyBindingRedirect and see whether it helps.

If that still doesn't help, clarify whether that is a NET Core project type or the NET Framework.

**Comment by zvirja** [comment]
@disklosr Did you have any luck to try installation again? I'll close this issue for now and if you still observe it - please re-open.
