### ISSUE TITLE
Dependencies strategy for .NET Core switch

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#760]
Currently AutoFixture [follows](https://github.com/AutoFixture/AutoFixture/blob/master/CONTRIBUTING.md#dependencies) a strategy when all the dependencies were included to the project in the `Packages` folder. It works well for the Full Framework because we can use the platform assemblies "for free". However, .NET Core (and .NET Standard) follows a bit different strategy and all the API you use should be installed via NuGet. As result, you have a lot of platform dependencies.

I played with migration of the AutoFixture project to .NET Core and noticed that after the NuGet restore the `Packages` folder started to take much more size.
Currently: 94MB
After switch to .NET Core: 320MB.

The delta is 226MB. The new size is 3.4 times larger.

Most of the libraries are not specific to our project somehow and, rather, are related to the `netstandard1.5` API we are going to target to.

Therefore, it's a good time to revisit our strategy and decide whether we are going to continue the approach we had before. The worst thing is that after new versions of .NET Standard might be released, they might increase all the dependency versions and our repository will blow up again.

Another thing is that after we migrate our projects to the .NET Core build system, they will target both `.NET Framework` and `.NET Standard` simultaneously. It will be impossible to keep local cache for `.NET Framework` only - build will if any dependencies are missing. Therefore, our solution should cover both targets simultaneously.

Personally, I see the following ways to follow:
### 1. Don't maintain the repository state more

The main reason why we maintained the repository cache is to be able to work without Internet immediately after checkout. We can continue to support work without Internet, however you will need to trigger a build before, so that the required packages are cached in local NuGet cache. 

Of course, this solution is not perfect and not all the cases are covered. For instance, if you have a custom branch with different dependencies, you should prefetch packages for it as well.

The benefit is that we will not blow up repository and that will simplify maintenance - given than number of packages now is much larger (about 65 system packages), it might be hard to keep track all them.

### 2. Try to change the strategy to store `nupkg` files only

We could try to investigate whether it would be possible to store `.nupkg` files only. After that when you trigger a NuGet restore, it should unpack files locally. The packed size is much smaller and takes `34.2MB` compared to `320MB`. However, we should still realize that if we update packages for a couple of time, that will add 100MB to the repository size and next git clone will take much longer.

I'm also not sure that NuGet restore will work fine without Internet even if all the necessary packages are present - that should be investigated.

### 3. Keep as is
The option is to keep everything as it is. This approach might not work well because .NET Core build system now creates special files in the `obj` directory during the NuGet restore. These files are not committed, so after you checkout the repository, build will fail even if all the required assemblies are present on file system. 

Build will pass only after you trigger the NuGet restore. There is a risk that NuGet might fail to restore packages if Internet connection is missing, even if unpacked packages are present in the `Packages` folder.

--------
If I'm missing something - add your ways to solve the issue.

Personally, I don't see problems with the first option - it's a common situation today that you should compile after the checkout.

@adamchester, @moodmosaic, @ecampidoglio looking forward to your thoughts.

**Comment by adamchester** [comment]
Option 3 is not possible to do reliably anymore.

I have not even attempted Option 2 anywhere for fear that there are so many packages, however I believe it's a scenario that both Paket and nuget can support (store nupkg files in source control and restore from that local cache). There are so few examples of this "out in the wild"for NuGet and dotnet core that I can't recommend it.

Option 1 is the only course we can take that I'm sure will work. It has my vote for that reason alone.

**Comment by moodmosaic** [comment]
Yes, from the above options, I think the 1st one might be the easiest. Voting for that one too... 😕

**Comment by zvirja** [comment]
Thanks guys! :wave:

Ok, so the majority voted to follow with the first option - don't maintain repository cache. @ecampidoglio Do you also agree to follow with Option 1, so I can proceed with .NET Core migration?

**Comment by ecampidoglio** [comment]
At this point, `nuget restore` doesn't seem to work without an Internet connection (see NuGet/Home#2623) so I think we should just go with times. Option 1 gets my vote. 👍
