### ISSUE TITLE
Implement SourceLink approach to enable simpler source code stepping

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#770]
Our current approach of distribution symbols and source code stepping possibility is to produce two NuGet packages:
- `Product.nupkg` - package with binaries only.
- `Product.symbols.nupkg` - package with binaries, pdb files and source code.

Later we upload package to the product and symbol feeds.

While this approach usually works (I wasn't able to get it working for the `3.50.2` though), there are some caveats with it. The major drawback is that it requires complex configuration of VS: an an additional Symbol Server should be added and a set of checkboxes should be enabled. I believe that most of our consumers doesn't even know about such a possibility.

Instead, I'd suggest to use the [Source Link](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/source_link.md) feature. The idea is that PDB files embed information where to look for the source code. In our case we'll point out directly to the GitHub (i.e. link for particular file will look like `https://raw.githubusercontent.com/AutoFixture/AutoFixture/{COMMIT}/Src/AutoFixture/Fixture.cs`). Later if you want to step into AutoFixture code, VS will simply grab source code from the GitHub repo. This feature is supported by VS 2017 and AFAIK is enabled by default (even if not - it's a single tick).

To embed information to the PDB files we can use the [SourceLink](https://github.com/ctaggart/SourceLink) tool. I've already tested it and it seems to work. The good news is that previously tool worked for the Portable PDBs only, however starting from VS 2017 Update 3 it [will be available](https://github.com/dotnet/roslyn/pull/18539) for the Windows PDBs as well.

Therefore, I'd suggest to change our distribution for `v4` so:
- we use the `SourceLink` tool to extend PDB files with source information.
- we extend the `Product.nupkg` package to include both binaries and PDBs. That will allow to enable source stepping for AutoFixture out of the box. While it will increase size of the package, I believe it's totally fine as we are in 2017 😄
- we still produce and upload the `Product.symbols.nupkg` package with PDB files and symbols. That should enable Source Stepping in older VS versions.

This feature is already used by [xunit](https://github.com/xunit/xunit/blob/bcea8b324628c17af340e9664fa7183820afb9e0/src/common.props#L23) and it works like a charm 👍

@AutoFixture/core Do you have any concerns regarding this? 😉

**Comment by moodmosaic** [comment]
I have no experience with SourceLink, I've rarely used PDB files also 🤠  However, this sounds good to me:

>In our case we'll point out directly to the GitHub (i.e. link for particular file will look like >`https://raw.githubusercontent.com/AutoFixture/AutoFixture/{COMMIT}/Src/AutoFixture/Fixture.cs`). >Later if you want to step into AutoFixture code, VS will simply grab source code from the GitHub repo. >This feature is supported by VS 2017 and AFAIK is enabled by default (even if not - it's a single tick).

If it doesn't cause issues to other IDEs/Debuggers/previous VS editions, I don't see why not 👍

**Comment by zvirja** [comment]
Done!
