### ISSUE TITLE
Use `dotnet pack` to generate NuGet packages

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#774]
Currently we use `nuspec` files to generate NuGet packages. That is not very convenient as we need to duplicate dependencies in both `csproj` and `nuspec` files. The `dotnet pack` solves that issue as all the package metadata is extracted from the `csproj` file only.

**Comment by moodmosaic** [comment]
That would be nice to have also in the current version (?)

**Comment by zvirja** [comment]
I'm afraid that is not possible for v3. In order to use `dotnet pack` you need to have projects of .NET Core format. I've already [done that](https://github.com/AutoFixture/AutoFixture/pull/769) in v4 branch, so we are ready to use the feature there. We don't bind v3 to a new SDK, so feature is missing here.

**Comment by zvirja** [comment]
Closed via #780
