### ISSUE TITLE
FrozenAttribute does not freeze collection of mocks

### ISSUE THREAD

**Issue by rexcfnghk** [AutoFixture/AutoFixture#778]
I have a composite class that takes a collection of `IResolver` as a dependency:

```c#
public class CompositeResolver : IResolver
{
    private readonly IEnumerable<IResolver> _resolvers;

    public CompositeResolver(IEnumerable<IResolver> resolvers)
        => _resolvers = resolvers;

    public int Calculate(int initial)
        => _resolvers.Aggregate(initial, (acc, curr) => curr.Calculate(acc));
}
```
Then I used AutoFixture, AutoFixture.AutoMoq, and AutoFixture.Xunit2 to set up a simple unit test to verify the collection of resolvers are all being called:

```c#
public class CompositeResolverTests
{
    [Theory, AutoMoqData]
    public void Calculate_CallsResolversWithExpectedCountOfTimes(
         int initial,
         [Frozen] IEnumerable<Mock<IResolver>> mockResolvers,
         CompositeResolver sut)
    {
        // Arrange
        foreach (var mock in mockResolvers)
        {
            mock.Setup(m => m.Calculate(It.IsAny<int>()).Verifiable();
        }

        // Act
        sut.Calculate(initial);

        // Assert
        Assert.All(
            mockResolvers, 
            mock => mock.Verify(r => r.Calculate(It.IsAny<int>()), Times.Once);
    }
}
```
This fails because `mockResolvers` and `sut._resolvers` are two separate collections of `IResolver`s.

Is this a bug in AutoFixture?

**Comment by zvirja** [comment]
And what if you freeze collection of entities instead:
```csharp
[Frozen] IEnumerable<IResolver> resolvers
```

In this case it should work. 

If the latter example works fine, I'd say that such behavior is expected. The `Freeze` attribute matches the exact type but  actually the `IEnumerable<Mock<IResolver>>` request is never issued, so two different collections are resolved.

Currently we have [similar issues](https://github.com/AutoFixture/AutoFixture/issues/766) when glue library helper attributes don't work if you wrap type with `Mock<>`. It looks like a feature to implement one more library with Moq specific helper attributes.

**Comment by rexcfnghk** [comment]
@zvirja Yes if I remove the Moq wrapping the test will freeze the resolver collection correctly. However, this prevents me from setting up expectations to the mock instances.

From what I understand, if my test were not requesting for a collection, it would have worked as expected (i.e. apply `FrozenAttribute` to a `Mock<IResolver>` and the dependency being a `IResolver`).

**Comment by zvirja** [comment]
You can always use `Mock.Get()` to convert instance of `T` to `Mock<T>`, so that should not be the case 😉

>From what I understand, if my test were not requesting for a collection, it would have worked as expected 

Yes, it will work. The reason is that request for `IResolver` is redirected to `Mock<IResolver>` and here your customization applies. In case you request `IEnumerable<IResolver>`, you will get a series of `Mock<IResolver>` requests, rather than `IEnumerable<Mock<IResolver>>`. If in your initial sample you frozen `Mock<IResolver>`, you would get the `_resolvers` contain N (usually 3) instances of the same frozen `IResolver`.

**Comment by rexcfnghk** [comment]
@zvirja It makes sense. However, I think it will be more intuitive if a request to `IEnumerable<Mock<IResolver>>` can also be frozen like in my example. Is `AutoMoqCustomization` the correct place to look into if I want to achieve the behaviour I wanted?

**Comment by zvirja** [comment]
> However, I think it will be more intuitive if a request to IEnumerable<Mock<IResolver>> can also be frozen like in my example. 

My position here would be the same as described [here](https://github.com/AutoFixture/AutoFixture/issues/766#issuecomment-313656029) - I don't think that it's a good idea to change the behavior for existing attributes. Rather, it might make sense to introduce new ones which will be specific to the Moq integration.

I've created an example of the `FrozenEnumerableOfMocks` attribute that could help to achieve the desired behavior.

```csharp
public class FrozenEnumerableOfMocks: CustomizeAttribute
{
    private static Type TryUnwrap(Type container, Type expected)
    {
        if(container == null) return null;

        if (container.IsGenericType && container.GetGenericTypeDefinition() == expected)
        {
            return container.GenericTypeArguments.Single();
        }

        return null;
    }

    private static Type Wrap(Type container, Type element)
    {
        return container.MakeGenericType(element);
    }

    public override ICustomization GetCustomization(ParameterInfo parameter)
    {
        var entityType = TryUnwrap(TryUnwrap(parameter.ParameterType, typeof(IEnumerable<>)), typeof(Mock<>));
        if (entityType != null)
        {
            return new FreezeEnumerableOfMocks(entityType);
        }
        
        throw new InvalidOperationException("Customization is applied to wrong type.");
    }
    
    public class FreezeEnumerableOfMocks: ICustomization
    {
        private readonly Type _elementType;

        public FreezeEnumerableOfMocks(Type elementType)
        {
            _elementType = elementType;
        }
        
        private static IEnumerable<T> SelectObjectsFromMocks<T>(IEnumerable<Mock<T>> mocks) where T : class
        {
            return mocks.Select(x => x.Object);
        }
        
        public void Customize(IFixture fixture)
        {
            // IEnumerable<Mock<T>>
            var tEnumerableOfMockOfElement = Wrap(typeof(IEnumerable<>), Wrap(typeof(Mock<>), _elementType));
            var enumerableOfMockObjects = fixture.Create(tEnumerableOfMockOfElement, new SpecimenContext(fixture));
            
            // Freeze request to IEnumerable<Mock<T>>, so always return the same result
            fixture.Customizations.Insert(
                0,
                new FilteringSpecimenBuilder(
                    new FixedBuilder(enumerableOfMockObjects),
                    new EqualRequestSpecification(tEnumerableOfMockOfElement)));                    

            // IEnumerable<T>
            var tEnumerableOfElement = Wrap(typeof(IEnumerable<>), _elementType);
            var enumerableOfObjects = GetType()
                .GetMethod(nameof(SelectObjectsFromMocks), BindingFlags.NonPublic | BindingFlags.Static)
                .MakeGenericMethod(_elementType)
                .Invoke(null, new []{ enumerableOfMockObjects});
           
            // Freeze request to IEnumerable<T>, so always return the value same objects.                   
            fixture.Customizations.Insert(
                0,
                new FilteringSpecimenBuilder(
                    new FixedBuilder(enumerableOfObjects),
                    new EqualRequestSpecification(tEnumerableOfElement)));
        }
    }
}

```

And usage:

```csharp
public class CompositeResolverTests
{
    [Theory, AutoMoqData]
    public void Calculate_CallsResolversWithExpectedCountOfTimes(
         int initial,
         [FrozenEnumerableOfMocks] IEnumerable<Mock<IResolver>> mockResolvers,
         CompositeResolver sut)
    {
        // Arrange
        foreach (var mock in mockResolvers)
        {
            mock.Setup(m => m.Calculate(It.IsAny<int>()).Verifiable();
        }

        // Act
        sut.Calculate(initial);

        // Assert
        Assert.All(
            mockResolvers, 
            mock => mock.Verify(r => r.Calculate(It.IsAny<int>()), Times.Once);
    }
}
```

Of course, my code is just a sample and it's main purpose is to demonstrate an idea. You can probably find more elegant solution and extend it to cover all your cases :)

**Comment by zvirja** [comment]
@rexcfnghk Could you please confirm that question was resolved for you? If so, could we close this issue? ☺️

**Comment by rexcfnghk** [comment]
Yes it does solve my issue. Thanks!
