### ISSUE TITLE
Repository line endings hell

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#803]
I've started to work on the SourceLink integration (#770) which is [sensitive](https://github.com/ctaggart/SourceLink/wiki/Line-Endings) to line endings and found a bit of hell in our repository. It appeared that half of the files are being committed with `CRLF` endings, while other ones with `LF`.

That should be fixed, so that all files are being stored in the repo with `LF`. Later, when you checkout files on Windows, git will automatically convert them to `CRLF` during checkout and to `LF` during the commit (unless you intentionally disabled that). That is the common practice in repositories and it's quite strange to see a mess here.

We should fix files in both the `master` and `v4` branch as we constantly merge `master` to `v4`.

@moodmosaic @adamchester @klimisa Do you have any objections regarding the fix? If not, I'll fix line endings for all the files and make direct commits with that changes. Otherwise, it will be impossible to proceed with #770.

**Comment by adamchester** [comment]
👍 From me

**Comment by moodmosaic** [comment]
👍 From me, too.

**Comment by zvirja** [comment]
Agreed! I'll try to find the right moment and will fire the commits to both branches.

**Comment by zvirja** [comment]
Fixed
