### ISSUE TITLE
Improvement string injecting and text creation

### ISSUE THREAD

**Issue by JaWiD2** [AutoFixture/AutoFixture#806]
**Hi**, recently i using AutoFixture and think that's fantastic!
I have an idea for improve default string creation, by inspiring from [this extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.DummyTextGenerator) for visual studio we can create dummy text.So code can be something like this:
```C#
var fixture = new Fixture();
fixture.InjectDummyString(vocabulary: Vocabulary.LoremIpsum, wordCount: 10);
// Or maybe
//fixture.InjectDummyString(vocabulary: Vocabulary.ChildeHarold, wordCount: 5, startWord: 5);
var dummyText = fixture.Create<string>();
```
I know we can use `fixture.Customizations.Add(new DummyTextBuilder());` or something like this but i think string data are high usage and AutoFixture native string builder (using hashing) are meaningless and ugly but in this way is more structured.
Thank you.

**Comment by zvirja** [comment]
Thank you for firing the issue and sharing your idea.

To be honest, I don't see how "Lorem Ipsum.." string is better than the Guid we currently generate. The benefit from Guid is that each string is unique and your tests have additional guards. With Lorem Ipsum strings will not be so unique, so it could lead to false positive/negative in unexpected places.
```csharp
public class Sut
{
	public Sut(string prop1, string prop2)
	{
		Prop1 = prop1;
		Prop2 = prop2;
	}

	public string Prop1 { get; }
	public string Prop2 { get; }
}


public class Tests
{
	[Fact]
	public void SutTest()
	{
		var fixture = new Fixture();
		var str1 = fixture.Create<string>();
		var str2 = fixture.Create<string>();

		var sut = new Sut(str1, str2);
		
		Assert.Equal(sut.Prop1, sut.Prop2);
	}
}
```

If your string generator produced not random enough string, the tests like above could pass, even if that is false positive.

Therefore, I'd vote to not change the current generation algorithm to not break the existing solutions and keep tests trustworthy.

@moodmosaic @adamchester Would appreciate if you could also share your opinion.

**Comment by moodmosaic** [comment]
@JaWiD2, thank you for bringing this [extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.DummyTextGenerator) to our attention 👍 

Yes, it's possible to replace each and every internal builder with a custom one, e.g. as shown [here](http://blog.ploeh.dk/2009/04/27/ReplacingAutoFixturesDefaultAlgorithms/), or using extension method(s) like the `InjectDummyString` one, as shown by @JaWiD2 proposes.

Other than that, there are no plans to integrate any of these in AutoFixture itself; the existing ones, and the various Customization APIs, have been battle tested for 7+ years.
