### ISSUE TITLE
.NET Framework support for v4

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#815]
Our current target for v4 is .NET Framework 4.5. However, this version is quite obsolete and it's support has [been abandoned](https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework) by MS more than half of the hear ago.

Given that we update vNext quite rarely, I'd suggest to re-target to the version that is being currently supported by MS. That is rather `4.5.2` or the `4.6.2`.

I have a proposal to support `4.6.2` instead of `4.5` family. In the `4.6.x` family were done some [improvements in API](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/#whats-new-in-net-2015) that would useful to us. For instance:
- Additional collections implement `IReadOnlyCollection<T>` such as `Queue<T>` and `Stack<T>`. Might be potentially useful as we use `Stack<T>` in a [few](https://github.com/AutoFixture/AutoFixture/blob/2a4396415a00fbf31e1ababececc91333fbb27cb/Src/AutoFixture/Kernel/TerminatingWithPathSpecimenBuilder.cs#L22) [places](https://github.com/AutoFixture/AutoFixture/blob/2a4396415a00fbf31e1ababececc91333fbb27cb/Src/AutoFixture/Kernel/RecursionGuard.cs#L17) and might want to refactor this to have that in a single place only.
- The `System.Globalization.CultureInfo.CurrentCulture` and `System.Globalization.CultureInfo.CurrentUICulture` properties are now read-write rather than read-only. We actually have [such switchers](https://github.com/AutoFixture/AutoFixture/blob/2b907bdd1b6217ca887400041c87128804a91d3d/Src/AutoFixtureUnitTest/UseCultureAttribute.cs#L46-L51) in our code and this would allow to eliminate them.
- The `AppContext` - the whole new world of defining the compatibility/feature switches. It might be very cool feature for some default/experimental features that we want to be able to enable/disable globally at once. The very good example is [this PR](709) when we want to have constant names for tests decorated with `AutoData` attribute. The reason is that VS runner is unable to run such tests and there clients who use VS runner. We don't want to enable such behavior by default, therefore if user wants this feature, it would need to define it's own `AutoData`-like attribute, enable the strategy there and later use his attribute all over the code. Might be not very conveniently if you already have thousands of tests.
With `AppContext` we could define a custom switch to control the default behavior, so we could enable the behavior easily. The benefit is that this is the officially suggested way to do such things.
Of course, this should be used with caution and in exceptional cases only, however the instrument might be useful.

There might be some other benefits that I'm not aware of (e.g. some NuGet dependencies that have .NET Framework limitations).

Personally, I don't see too much issues with support of `v4.6.x` branch and higher. This branch is quite old and is being actively used. Given that our library is a test lib, we will enforce target framework for the test projects only without touching the production projects.

@AutoFixture/core What do you think about this? Would you agree to target `v4.6.2` for the v4 or you have strong opinion to keep `v4.5.x`, so we should set `v4.5.2` instead?

**Comment by moodmosaic** [comment]
That's a good point, it's great that you brought it up 💯 IMO, while supporting `v4.6.2` looks tempting, perhaps we could rather pick `v.4.5.2` to allow for broader reach?

**Comment by zvirja** [comment]
It's the only point that bothers me too - about support. However it's a dark area as I don't know whether .NET 462 will be an issue for clients or whether they are fine and already use it. We update to major quite rarely and will need to work with what we have for some time. That's why I put this topic here.

Just discovered that all our friends (NUnit, xUnit, NSubstitute, Moq, FakeItEasy) support 4.5, so probably we have no choice here - we'll need to stick to that. It would be a pity if somebody need us as 4.5, but we don't support that.
After all, 4.6.2 features are not critical to us, so we could probably live some time without that..

**Comment by Kralizek** [comment]
Wouldn't be best to aim to support only .NET Standard 1.5 ?

**Comment by zvirja** [comment]
@Kralizek I see a few major reasons to support .NET 4.5 explicitly:
- We target .NET Standard 1.5 that is supportable starting .NET 4.6. Meaning, that we'll automatically abandon .NET 4.5.
- There are feature specific to desktop only and are missing on .NET Standard (e.g. serializable exceptions, [MailAddress](https://github.com/AutoFixture/AutoFixture/blob/cc12c22e47b94d232a6a3b540d791de2f6b0639e/Src/AutoFixture/MailAddressGenerator.cs#L1) type, etc).
- There might be people using VS 2012 and VS 2015. If we start to target .NET Standard only, I'm not sure they will be covered. While the framework might be compatible, I'm not sure that build SDK will handle that.

Also it doesn't cost too much to think about abandoning full framework support 😄

**Comment by zvirja** [comment]
Done! Now we target `v4.5.2`.
