### ISSUE TITLE
Albedo project - governance model change

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#821]
The `AutoFixture.Idioms` project depends on [`Albedo`](https://github.com/ploeh/Albedo) that is being currently maintained by @ploeh. Currently we are migrating our projects to support .NET Standard and it appeared that `Albedo` doesn't support that world. I've [created a PR](https://github.com/ploeh/Albedo/pull/96) to Albedo project to solve that, however Mark rejected it saying that he is no longer interested in that area, so he doesn't want to spend his time on that. Instead Mark suggested to transfer project to the AutoFixture account as apparently we are the only major consumer of that lib.

Given that this is the only way to proceed with .NET Standard support for `Idioms`, I suggest the following plan:

From @AutoFixture/core side:
1. We create one more repository under the AutoFixture account.
2. We create a copy of project (simply push all the commits).
3. We enable .NET Standard support for the lib and publish v2.0 to NuGet.

From @ploeh side:
1. Push the sign key to the `master` branch as we'll open it in any case.
2. Add `AutoFixture`, `AlexPovar` and `klimisa` as package owners (to be same as [here](https://www.nuget.org/packages/autofixture)).
3. Later change the Readme to mention that project has been transferred to another place.

Notice the following:
1. @ploeh To indicate the changed ownership we will remove the `Ploeh` namespace prefix from code. That is to align project with a decision made in #745.
1. @ploeh We'll add AutoFixture as a co-author of the package. We'll keep the current copyrights as [we haven't agreed yet](750) what to do with them.
1. @moodmosaic @adamchester @klimisa I'm ready to do this _only_ if you allow me to migrate project, add .NET Standard 2.0 support and rework the build approach _without_ a need to create PRs. No business logic will be affected by that (if it is - I'll create a PR to discuss). I'll need to significantly reorganize the project (to align it with AutoFixture one) and it will be painful to do that via PRs.

@ploeh @AutoFixture/core Do you agree with such a plan? :wink:

**Comment by moodmosaic** [comment]
Albedo―while being one of the best object-oriented C# codebases I'm aware of, a useful, and interesting open-source project―has no place in the AutoFixture organization, IMHO.

That was the reason we actually developed it under @ploeh's account. I see no reason going back on this decision.

There is a *ton* of PRs going on already, with a high frequency of changes like never before and just a few available reviewers.

---

* I'd suggest to hold off the decision until most of the [v4 milestone issues](https://github.com/AutoFixture/AutoFixture/milestone/3) are closed
* In case you decide to move forward on this, do not add me as a reviewer on the pull requests. I currently don't have more bandwidth for reviews

**Comment by zvirja** [comment]
@moodmosaic Thanks for your reply! A bit unexpected decision, but I completely understand it! Ok, let's live without .NET Core support for `Idioms` for now and decide what to do at the end of v4.

**Comment by zvirja** [comment]
I decided to follow a bit different approach - I created a standalone organization for that project: https://github.com/AlbedoOrg.  We'll transfer the project there and I'll add the .NET Standard support. I'll do that myself by applying the similar layout as we have here. Later other guys like @moodmosaic @ecampidoglio could also participate if they wish.

Currently [I'm waiting](https://github.com/ploeh/Albedo/pull/96#issuecomment-329172560) for the @ploeh actions to proceed further.

**Comment by zvirja** [comment]
We already transferred the repo, so this question should be closed. I'll add @adamchester and @moodmosaic as co-owners, as they contributed to the library in past.

**Comment by moodmosaic** [comment]
You should also add @jwChung. He did a lot of great work in Albedo.

**Comment by zvirja** [comment]
Sure, no concerns from my side. Please add him - you also have admin rights :blush:

**Comment by jwChung** [comment]
@moodmosaic Long time no see. Thank you for your kind attention. @zvirja

**Comment by moodmosaic** [comment]
@jwChung, you are welcome! I've just invited you a few hours ago.
