### ISSUE TITLE
Extract SemanticComparision to a standalone repo

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#833]
I've recently learned that previously the SemanticComparison component was a part of AutoFixture, however later it has been extracted to a standalone library. Currently the SemanticComparison library doesn't contain any references to the AutoFixture is not longer a part of the products family.

I suggest to extract this library to a standalone repository inside the AutoFixture organization. My main concern is the release management. Currently SemanticComparison have the same version as AutoFixture. In 99% we modify something inside the AutoFixture component and as result we constantly release new versions of SemanticComparison _without_ any changes.

If we extract it to a standalone repo, component will have its own lifecycle. I'll copy all the build scripts layout there, so release procedure will be exactly as it's now - tags for public releases. Nothing will change to the SemanticComparison users except a fact that they will not see updates noise without changes.

@moodmosaic @adamchester @ecampidoglio Your thoughts?

**Comment by moodmosaic** [comment]
I don't know... Why not just leave it as-is?

...Perhaps I'm saying this because I tend to keep existing stuff the way they are―to preserve history, and because usually my time is limited―so I'll leave this change up to you, then.

**Comment by zvirja** [comment]
> I don't know... Why not just leave it as-is?

The main reason for me is to not release new versions of the product when nothing changes. There might be people who use `SemanticComparison` library and don't use `AutoFixture`. It might be weird for them to see new versions when actually nothing changes in the component for years. Of course, we have the same situation for all the AutoFixture products family, however there _there is a risk_ that changes are incompatible (e.g. new API released and used), while here products are totally separated.

> so I'll leave this change up to you, then.

By other words, if I have free time for this in future, you are fine. Have I got it right? 😉

**Comment by moodmosaic** [comment]
Yes, you did 😉

**Comment by zvirja** [comment]
Done! Welcome a new repo within the AutoFixture organization: https://github.com/AutoFixture/SemanticComparison! 🎉🌟🌟

I've used the `git filter-branch` feature, so the files history is preserved till 2010.

Will keep this issue open till I remove the SemanticComparison project completely from this repo.

**Comment by zvirja** [comment]
Done.
