### ISSUE TITLE
Add `IParameterCustomizationSource` interface to AutoFixture project

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#842]
Currently our test framework specific glue libraries (for NUnit and xUnit) have [CustomizeAttribute](https://github.com/AutoFixture/AutoFixture/blob/06ca10bf1c12c914f9c0d8218351709cbfe605ac/Src/AutoFixture.xUnit.net2/CustomizeAttribute.cs#L11) class to enable parameter specific customizations. We even have built-in attributes like `Frozen` or `Greedy` which use this extension point. This mechanism allows user to define their own attributes and works like a charm, however there are 2 major issues currently:

1. It's impossible to define such customization attributes in mock framework glue libraries (like AutoMoq).
2. If you, as a third party developer, want to provide a package with your own attributes, you need to create 4 different packages - one per each test library. That is because `CustomizeAttribute` is defined in those libraries.

I've checked this area more and found that actually the `CustomizeAttribute` has nothing specific to the test library and is the same for all 4 glue libraries. Therefore, I came up with an idea to define the `IParameterCustomizationSource` interface in the AutoFixture project. It will have the same signature as `CustomizeAttribute`:
```csharp
interface IParameterCustomizationSource
{
    ICustomization GetCustomization(ParameterInfo parameter);
}
```

Later all the test framework glue library will look for the attributes implementing this interface and apply them if needed. The `CustomizeAttribute` attributes will start to implement this interface as well.

Any other glue library will be capable of providing active parameter customizations (in contrast with passive approach, when relay builder is injected to customizations and checks whether request has particular marker attribute).

Of course, AutoFixture assembly might not seem the best place for this attribute, but we don't have a lot of choice - that is the only common library among all our glue libraries. Also we'll still have `CustomizeAttribute` classes as expected extension point - interface is for exceptional cases only when attribute is not available.

We have places that might use this feature, e.g. #766. In this case active customization (explicitly created and applied to the fixture) will work much better than a passive approach.

Also package authors will be happy as they will be able to support all test framework glue libraries via single package.

@adamchester @moodmosaic Do you have any concerns regarding this? Let me know, if see more elegant solution.

**Comment by moodmosaic** [comment]
The overall idea makes sense to me. It'll also invoke the rule of three... And while you're doing a great job mentioning the advantages of this new approach, what about the disadvantage(s)?

**Comment by zvirja** [comment]
So far I see a couple of disadvantages:

1. In fact, AutoFixture is not the best place for this interface, as it should "know nothing" about the potential glue libraries. While we introduce this interface there, the library itself will not use it - those are glue libraries, which are the main clients of this interface. Therefore, it's a bit "dirty" approach. From architectural perspective, we should create a standalone package with that single interface and later reference that package on our glue libraries. 

1. Suppose, we create "active" customization attribute in AutoMoq package, like `FrozenMock`. Later user installs the AutoMoq library. While this attribute is available to the user, he can use it only if he installs xUnit or NUnit integration libraries. What looks weird, that you should install some other package which is not directly referenced to be able to use some particular feature.

That is basically two things that are worrying me. They shows that approach is not ideal and some parts will start to indirectly know about other parts (indirectly, because there is no direct reference).

Ideally, the architecture should look like following:
- `TestFrameworksFoundation`  with `IParameterCustomizationSource` attribute. 
- xUnit/NUnit integrations, referencing `TestFrameworksFoundation`
- `AutoMoq.TestFrameworkExtensions`, referencing both `TestFrameworksFoundation` and `AutoMoq` and providing that `FrozenMock` attribute.

While ideal picture looks nicer, it's 4 more packages with tests (or even more in future) and it will be a hell to maintain all that stuff, as currently we have about 30 projects. Therefore, while the current way brings some architecture violation, it looks like a reasonable tradeoff is favor of simplicity.

@moodmosaic What do think now? :blush:

**Comment by moodmosaic** [comment]
>1. In fact, AutoFixture is not the best place for this interface, as it should "know nothing" about the potential glue libraries

This should be fine. After all, *"clients [...] own the abstract interfaces"* (Agile Principles, Patterns, and Practices, chapter 11).

>2. Suppose, we create "active" customization attribute in AutoMoq package, like FrozenMock. Later user installs the AutoMoq library.

What happens if he or she doesn't install the auto-mocking library?

---

>Ideally, the architecture should look like following:
>
>* TestFrameworksFoundation with IParameterCustomizationSource attribute.
>* xUnit/NUnit integrations, referencing TestFrameworksFoundation
>* AutoMoq.TestFrameworkExtensions, referencing both TestFrameworksFoundation and AutoMoq and providing that FrozenMock attribute.

This sounds scary. —This sounds like cyclic dependencies. Cyclic dependencies are often the indirect outcome of coupled design, and this can make the code base harder to maintain.

---

Let's see what comes out from my question on the `2.` item.

**Comment by zvirja** [comment]
> What happens if he or she doesn't install the auto-mocking library?

Nothing :wink: Those customization attributes are expected to be used in test methods, decorated with `AutoData` like attributes:
```csharp
[Theory, AutoData] 
public void SomeTest([FrozenMock] IData data) {...} 
```
If you apply this attribute somewhere else nothing will happen - literally :smiley: Those attributes provide a customizatiom - it's a _caller_ responsibility (i.e. `AutoData` attribute) to get this customization and apply it to the Fixture instance. Therefore, those attributes simply make no sense if test framework is missing. 

> This sounds like cyclic dependencies.

To be honest, I don't see any cycles here. Rather, for me it looks like a downfall graph, when each child has a dependency on the parents only. Am I missing something and you see some hidden cycles here? I'm not a big fun of this approach neither, but for me it looked as "the most right" way, so it would be quite interesting to see what I miss..

**Comment by moodmosaic** [comment]
>>This sounds like cyclic dependencies.
>
>To be honest, I don't see any cycles here. [..]

What's the purpose of adding `TestFrameworksFoundation`? What would be the alternatives?

**Comment by zvirja** [comment]
> What's the purpose of adding `TestFrameworksFoundation`?

The only purpose would be to have `IParameterCustomizationSource` definition.. So later it would be referenced if that interface is needed. But yep, it sounds like an overkill. :blush:

> Let's see what comes out from my question on the 2. item.

So, do you have any concerns after my reply on this?

**Comment by moodmosaic** [comment]
I'd suggest to avoid introducing new libraries (like the hypothetical *TestFrameworksFoundation*). Or at least reconsider this in *post-v4*.

Let's see how a PR that adds IParameterCustomizationSource  to the core namespaces looks like. 🚀

**Comment by zvirja** [comment]
Implemented.

**Comment by cecilphillip** [comment]
@zvirja any docs or samples on how this works?

**Comment by zvirja** [comment]
@cecilphillip Well, it works like any regular `CustomizeAttribute` class specific to the testing framework glue library, but instead you implement the `IParameterCustomizationSource` attribute. There is no documentation for it as it targets very specific scenarios.

Probably, it would be easier if you describe which stories you are trying to cover, so I can advice on that...
