### ISSUE TITLE
[Performance] Make fixture creation lazy in AutoData attribute

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#843]
# Problem 

Recently I analyzed the issue #831 and discovered that `AutoData` attribute might be constructed multiple times by the test engine during the test discovery and invocation. Not all the constructed instances are later used by the test engine to obtain the argument values (e.g. for xUnit [we disable](https://github.com/AutoFixture/AutoFixture/blob/d7187bb16d7adadff7e1d73e143b604c291a4990/Src/AutoFixture.xUnit.net2/AutoDataAttribute.cs#L15) test discovery), therefore part of the constructed fixture instances are never used.

Recently I profiled the fixture customization performance (see e.g. #818) and found that customization might be quite expensive if we have a lot of tests. Therefore, if we could omit fixture construction when fixture is not needed, that would be awesome.

I tired to test this approach on my real solution with 2k xUnit tests and found that NCrunch tests discovery time decreased from ~4.5 sec to ~2.2 sec. For NUnit benefit might be even larger, as I found that attribute might be constructed 3 times (in #818 there were reported even larger numbers).

# Solution
I see a few ways to solve this issue. All of them makes the Fixture creation deferred, so it's created only if required.

## 1. Add a constructor overload to take a factory method
In this case `AutoData` attribute will have the following constructor:
```csharp
public AutoDataAttribute(Func<IFixture> factory) {} 
```

If you wish to customize the fixture, the code will look like following:
```csharp
class MyData : AutoDataAttribute
{
  public MyData(): base(() => 
       new Fixture()
           .Customize(new AutoMoqCusomization()) 
  { }
} 
```

Or more complex scenario if you have some arbitrary tweaks:
```csharp
class MyData : AutoDataAttribute
{
  public MyData(): base(() =>
    {
      var fixture = new Fixture()
           .Customize(new AutoMoqCusomization());
      fixture.Inject(new CustomType());

      return fixture;
    }) 
  { } 
} 
```

At the first glance it might look ugly, but actually it's almost same what we have now - we also need to pass a customized fixture instance to the `base`  constructor. The only difference will be that you'll need to pass a lambda instead of a value.

## 2. Add a virtual factory method
I like less this idea, but to avoid a mess in constructor we might add a factory method that creates the fixture instance. Later, if you need to customize the fixture, you will need to override it:
```csharp
public class MyData : AutoDataAttribute
{
  protected override IFixture OnCreateFixture()
  {
    var fixture = new Fixture()
         .Customize(new AutoMoqCusomization());
    fixture.Inject(new CustomType());

    return fixture;
  } 
} 
```
The issue is that this way is less obvious as customers will need to somehow know that such a method exists.

-------

@adamchester @moodmosaic Do you have any concerns regarding the suggested change? It brings a significant boost to the discovery time, which is important for tools like NCrunch. Also, which way do you like better? If you see a cooler way than the ones suggested above - please share it :wink:

**Comment by moodmosaic** [comment]
I don't see why not. Although I can't remember people complaining about the performance...

The first option looks nice, but it'd be good to keep the existing constructor(s) as well, otherwise it'll be hard(er) for those upgrading to AutoFixture v4. (Not every AutoFixture user follows those GitHub issues.)

**Comment by zvirja** [comment]
> but it'd be good to keep the existing constructor(s) as well

Sure, I'll keep them obsoleted and explain in the message that the overload with a lambda should be used as it offers a better performance.

**Comment by moodmosaic** [comment]
OK, and perhaps we should include the performance comparison results in the git commit message? Just to be in/sane enough!

**Comment by zvirja** [comment]
Done! Implemented in v4
