### ISSUE TITLE
Reserve 'AutoFixture' package prefix on the NuGet

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#863]
Currently NuGet has ability to reserve package prefix, so only owner could push packages with such a prefix (see [xunit](https://www.nuget.org/packages/xunit/) as an example). That will allow to avoid situations when third party packages are being published with identity close the original one, so clients might be unsure who published them.

Consider the [AutoFixture.NUnit3.PatchedName](https://www.nuget.org/packages/AutoFixture.NUnit3.PatchedName) package as an example. You might think that this package is published by AutoFixture, but that isn't so. Therefore, to avoid confusion, we should prevent possibility to push such packages. People will still be capable of pushing their libraries, however they will be forced to use the different naming.

**Comment by zvirja** [comment]
@ploeh As far as I got it, I'll need a verified account on Nuget to proceed on this direction. Would it be possible for you to share the credentials for the AutoFixture NuGet account? I'll later try to make it verified and perform NuGet name prefix reservation.

**Comment by ploeh** [comment]
Sorry, I don't own the _AutoFixture_ NuGet account, and I don't know what the credentials are...

I'm not sure, but it _could_ be that it was created by @ecampidoglio...

**Comment by zvirja** [comment]
@ecampidoglio Could you please take a look?

**Comment by ecampidoglio** [comment]
@zvirja I'll DM you the credentials for the AutoFixture account.

**Comment by zvirja** [comment]
@ecampidoglio Thank you - the credentials have been transferred.

@onovotny @diverdan92 We would like to proceed with package prefix id reservation for the `AutoFixture` prefix as described [here](https://blog.nuget.org/20170417/Package-identity-and-trust.html). While I found the instruction, I wasn't able to find the starting point (neither on nuget.org or github) - email/place where I can issue the request. Could you please advise on this? I do imagine that procedure is following:
- Verify NuGet account ownership - the [AutoFixture](https://www.nuget.org/profiles/AutoFixture) account in our case.
- Reserve the `AutoFixture*` prefix, so that only `AutoFixture` account could push.

Thank you very much!

**Comment by zvirja** [comment]
Just send the reservation request as that is described here: https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation. I'm waiting for the reply.

**Comment by zvirja** [comment]
OK. I got the MS mail firewall denial 😖 [Am waiting for the further clarifications](https://github.com/NuGet/Home/issues/5307#issuecomment-336151729) now...

**Comment by zvirja** [comment]
Done! Now our packages have the "Verified" mark 😊
![image](https://user-images.githubusercontent.com/1074182/31667019-de2aae50-b356-11e7-8580-70cef7209c72.png)

Also the `AutoFixture.*` package prefix is reserved, so only `AutoFixture`, `phoeh` and `AlexPovar` accounts could create packages with that prefix.

There is also an option to open some prefix for the community, so people could create their own extensions for the AutoFixture. I came up with `AutoFixture.Community.*` mask. That will allow our clients to create their own extensions for the AutoFixture, while it will be clear that those packages are not owned by the AutoFixture.

@moodmosaic @adamchester Do you have any concerns regarding the `AutoFixture.Community.*` package name prefix opened for anybody for push? If not - I'll proceed with a request to NuGet team.

----
@frblondin You have pushed a set of packages with very confusing names:
- [AutoFixture.NUnit3.PatchedName](https://www.nuget.org/packages/AutoFixture.NUnit3.PatchedName/)
- [AutoFixture.MSTest2](https://www.nuget.org/packages/AutoFixture.MSTest2/)

From the package name it might look like those products are being developed and supported by the AutoFixture, but that isn't so. You also used our logo for those packages which makes the situation even more confusing 😕

We need to decide how to proceed with those packages.
- `AutoFixture.NUnit3.PatchedName` - This feature is already a part of the AutoFixture. The v4 (which will be released in upcoming week or two) will contain stable name out-of-the-box, so this package is no longer required. Could you please unlist the package from NuGet, so it's invisible for the search? People who already installed the package _will be still able_ to restore the package.

- `AutoFixture.MSTest2` - Here the situation is even worse as you in fact "stole" the name. If we decide to support MSTest2 in future, we will be unable to publish to NuGet as this name is already reserved. Therefore, I'd like to ask you about the following (and would highly appreciate if you agree):
    - Unlist all the `AutoFixture.MSTest2` packages.
    - Pass the ownership of the `AutoFixture.MSTest2` package to the `AutoFixture` NuGet account. If later we decide to support this package, we'll be able to push it.
    - If you indeed would like to publish your own package for MSTest support, please rename package to `AutoFixture.Community.MSTest2` and re-publish it. This name will clearly indicate that product isn't maintained by the AutoFixture and is community-driven instead.

Thomas, do you agree with such a plan? If you see more feasible options - please advice 😉

**Comment by frblondin** [comment]
Good news!

As per your questions:
* `AutoFixture.NUnit3.PatchedName`: we still need it for the lazy initialization of the fixture. This last part will be delivered in v4 in a week or so and my team still need to be able to create projects and get this package easily from nuget. this `AutoFixture.NUnit3.PatchedName` NuGet package is there for a year so I guess it can remain visible one more week?
* `AutoFixture.MSTest2`: I temporarily tested MSTest2 but I'm not using it any longer.
   * Unlist all the AutoFixture.MSTest2 packages.
_Done_
   * Pass the ownership of the AutoFixture.MSTest2 package to the AutoFixture NuGet account. If later we decide to support this package, we'll be able to push it.
_I sent you an ownership proposal in NuGet.org_
   * If you indeed would like to publish your own package for MSTest support, please rename package to AutoFixture.Community.MSTest2 and re-publish it. This name will clearly indicate that product isn't maintained by the AutoFixture and is community-driven instead.
_Not planning to use it anymore_

Thanks

**Comment by zvirja** [comment]
> This `AutoFixture.NUnit3.PatchedName` NuGet package is there for a year so I guess it can remain visible one more week?

Sure, no worries 😉 Just wanted to align our actions and ensure that we fix that somewhere in future. If you still need to perform _the new installations_ - it's a good reason to keep that till the release.

> I sent you an ownership proposal in NuGet.org

Thanks a lot for that! I've just accepted the ownership request so AutoFixture is an owner now.

**Comment by frblondin** [comment]
> I sent you an ownership proposal in NuGet.org
>> Thanks a lot for that! I've just accepted the ownership request so AutoFixture is an owner now.

... and I just removed myself as an owner.

**Comment by zvirja** [comment]
> ... and I just removed myself as an owner.

Great. Now we can be sure that you will not accidentally remove the ownership in future 😄

----
@moodmosaic @adamchester Looking forward to your confirmation on [this](https://github.com/AutoFixture/AutoFixture/issues/863#issuecomment-337234427) to proceed further.

**Comment by zvirja** [comment]
I decided to proceed further and NuGet team has already opened the `AutoFixture.Community.*` namespace prefix to everyone. That should simplify things as now the ownership will be clear.

@moodmosaic @adamchester Let me know if you have any concerns regarding the naming.

Closing this one as no more actions are required here.

**Comment by moodmosaic** [comment]
>@moodmosaic @adamchester Do you have any concerns regarding the `AutoFixture.Community.*` package name prefix opened for anybody for push? If not - I'll proceed with a request to NuGet team.

Sounds actually like a decent idea 👍
