### ISSUE TITLE
v4 release

### ISSUE THREAD

**Issue by ebbeflarup** [AutoFixture/AutoFixture#890]
Quick question, wasn't todays merge of the AutoFixture v4 branch supposed to submit new NuGet packages or is that intentionally left for later?
I see in the build that the version number didn't change.

**Comment by zvirja** [comment]
@ebbeflarup Thanks for following us 😉 Commits to the master are not supposed to trigger new releases. Rather, we need to create a tag to start the release process. I'm going to do that soon, so you'll see a published package 😉

**Comment by zvirja** [comment]
JFYI: [I released](https://twitter.com/AutoFixture/status/920623108863741953) v4 rc1 to the NuGet now 😉

**Comment by Kralizek** [comment]
@zvirja any timeline for the RTM? (I know, I'm greedy)

**Comment by zvirja** [comment]
@Kralizek Do you have any issues using RC? :wink:

**Comment by Kralizek** [comment]
@zvirja not at all. But I want to update our internal packages to use the v4 and `dotnet pack` gives a nasty warning about using preview packages into non-preview ones :P

My internal package used to be a metapackage with
* NUnit
* AutoFixture
* Moq

But I will change it so that it also includes AutoMoq and AutoFixture.NUnit3 and a definition of `[AutoMoqInlineData]` attribute.

**Comment by zvirja** [comment]
Now I see it, thanks. Well, I'm going to release RTM after we finish all the issues [in the scope](https://github.com/AutoFixture/AutoFixture/milestone/4). Probably, it will take a couple of weeks.

**Comment by kmorcinek** [comment]
@zvirja just to ensure I understand correctly: I can safely update to 4.0 RC cause what is left are only couple bugs. And if this bugs don't influence me (they don't), nothing will be broken between RC and final version?

**Comment by zvirja** [comment]
@kmorcinek Basically yes, that's why how I see that as well. The only minor breaking change is related to #905, but it's unlikely that you will observe it. Even if so, it's a trivial one to fix.
