### ISSUE TITLE
EmptyStringBehaviorExpectation/WhitespaceOnlyStringBehaviorExpectation

### ISSUE THREAD

**Issue by DixonDs** [AutoFixture/AutoFixture#896]
I think it would be a valuable addition for GuardClauseAssertion as it is a quite common case to have guards for empty/whitespace-only strings. What do you think?

**Comment by zvirja** [comment]
Well, I haven't worked with Idioms too much, howevery my position is that as long as those expectations are pluggable and are disabled by default (so we don't introduce the breaking changes), I don't mind to have them as a part of the lib.

Let's see what @adamchester and @moodmosaic think about that - they worked longer on that lib.

**Comment by moodmosaic** [comment]
I pretty much share @ploeh's [IsNullOrWhiteSpace trap](http://blog.ploeh.dk/2014/11/18/the-isnullorwhitespace-trap/) thoughts, and it'd be very skeptical adding this.

(Scroll down in that article where it says *Problems with IsNullOrWhiteSpace*.)

**Comment by DixonDs** [comment]
@moodmosaic Well, the article discusses incorrect usages of `IsNullOrWhiteSpace` which is fine. But it doesn't mean there are no correct usages of `IsNullOrWhiteSpace` as a guard clause (even though I use it rarely myself). And then we still have `IsNullOrEmpty` used much more often in practice as a guard clause than `IsNullOrWhiteSpace`, do you think we can add `EmptyStringBehaviorExpectation` at least? If we don't make it default expectation, it is up to library users to decide if they want to use it or not
