### ISSUE TITLE
Rename "Jump in" tag to "good first issue"

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#914]
Currently we have the `jump in` tag for the good-to-start issues. Recently GitHub team introduced the `good first issue` label for such issues and documented it everywhere:
- https://help.github.com/articles/about-labels/#using-default-labels
- https://help.github.com/articles/finding-open-source-projects-on-github/#searching-using-labels

Therefore, I suggest to rename the tag and set it to a default color. We'll follow the convention so new members will be able to recognize this tag much easier.

@moodmosaic @adamchester Any objections?

**Comment by moodmosaic** [comment]
👍 Sounds good

**Comment by zvirja** [comment]
Done.

**Comment by zvirja** [comment]
Fire a PR on this site:
https://github.com/up-for-grabs/up-for-grabs.net

**Comment by zvirja** [comment]
Done. Fired: https://github.com/up-for-grabs/up-for-grabs.net/pull/812
