### ISSUE TITLE
Private field naming convention

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#915]
In this issue I'd like to align the private field name convention in our project.

I've found that in one places we prefix private fields with underscore, while in other we don't. That is a pretty confusing and we should align the single styling for this project.

Usually, I prefer to start private fields with the underscore character:
```c#
private class SomeClass
{
    private readonly int _someValue;

    public SomeClass(int value)
    {
        this._someValue = value;
    }
}
```

However I would be fine if we agree to live without them (like most of the code is written in kernel) as we enforce the `this` keyword (so it's clear that it's the field):
```c#
private class SomeClass
{
    private readonly int someValue;

    public SomeClass(int value)
    {
        this.someValue = value;
    }
}
```

@moodmosaic @adamchester Do you have any opinion regarding the naming convention? I'm fine with whatever we follow - the only wish is to have a consistency.

**Comment by moodmosaic** [comment]
That's the current style which we should probably keep and make consistent everywhere:

```c#
private class SomeClass
{
    private readonly int someValue;

    public SomeClass(int value)
    {
        this.someValue = value;
    }
}
```

I know that all ReSharper users don't like it. Do you, @zvirja?

**Comment by zvirja** [comment]
Well, I indeed like underscores 😊 However, I'm perfectly fine to not put them - I'm already following this convention at a few projects where code styles are out of my control. As long as `this` keyword is used, that doesn't lead to any confusion.

The only wish I have is to configure the R# appropriately, so it doesn't highlight each field in our solution 😄

@moodmosaic That means you vote to proceed without underscores, don't you?

**Comment by DixonDs** [comment]
@zvirja 
>The only wish I have is to configure the R# appropriately, so it doesn't highlight each field in our solution

Probably, in this case, it makes sense to include the shared R# settings file into the repository in order to make it easier to new contributors using R#

**Comment by zvirja** [comment]
> Probably, in this case, it makes sense to include the shared R# settings file into the repository

Yep, [we already have them](https://github.com/AutoFixture/AutoFixture/blob/master/Src/All.sln.DotSettings). However, you should open the `All.sln` solution to pick them up. I didn't want to duplicate this file 10 times for each solution we have 😕

**Comment by moodmosaic** [comment]
>@moodmosaic That means you vote to proceed without underscores, don't you?

Well, basically, yes, unless it bothers you _so much_ that makes you totally unproductive; in this case, feel free to change it everywhere. 😃 

---

`this` is much more powerful than `_` technically speaking. I think, `_` is a remnant from the old days, where we used to prefix instance fields with `_` or `m_`, static fields with `s_` and constant fields with `c_`.

(In C/C++, things can be more scary with `sz_` etc.)

---

I have a feeling that [Maxim Shafirov](https://www.jetbrains.com/company/people/) and co., who invented ReSharper had related background and so they put it in ReSharper; then they kept it for historical reasons or something(?)

**Comment by zvirja** [comment]
> Well, basically, yes, unless it bothers you so much 

Well, in that case agreed to live without them 🎉

> `this` is much more powerful than `_` technically speaking.

Yep. Just to feel my pain - on my primary work project we follow a convention _to not put_ neither `_` nor `this` keyword. Feel the confusion I see every day when it's totally unclear whether you access a field or a local variable; a Property or a Static Class with same name 😢 We even had bugs because of the latter.

> then they kept it for historical reasons or something(?)

Yep, likely. I'm currently [maintaining a plugin for R#](https://github.com/zvirja/ReSharperHelpers) and therefore I work with R# code base a lot. It was quite surprising, but internally they follow a convention to prefix fields with `my` - like `myManager`, `myRepository`. Therefore, even R# team doesn't follow their own rules 😄

**Comment by moodmosaic** [comment]
>It was quite surprising, but internally they follow a convention to prefix fields with `my` - like `myManager`, `myRepository`.

Sounds like they're coming from VB? 😉 

---

**Comment by zvirja** [comment]
Well, I don't believe in that :) However, who knows.. :smirk:
