### ISSUE TITLE
Issues with AutoMoq and mocking a fluent request builder

### ISSUE THREAD

**Issue by mbcrawfo** [AutoFixture/AutoFixture#921]
I'm testing an extension method that has the following call to the MS Graph API at its core.  I've noted on each line the type returned by that call.

    var groupPage = await service.Me // IUserRequestBuilder
        .GetMemberGroups(true)       // IDirectoryObjectGetMemberGroupsRequestBuilder
        .Request()                   // IDirectoryObjectGetMemberGroupsRequest
        .PostAsync()                 // Task<IDirectoryObjectGetMemberGroupsCollectionPage>
        .ConfigureAwait(false);

I expected to be able to write a test like below, letting AutoMoq build out the request builder chain and only requiring me to set the return value of the result property of interest.  However, this test fails with an exception when attempting to generate `IDirectoryObjectGetMemberGroupsCollectionPage` during the call to `PostAsync()`.  In order for the test to work, I need to pull in all the objects in the builder chain *except* for the last one, manually create it, and manually link up the chain of methods.

    // expected test
    [Test]
    [AutoMoqData]
    public async Task GetUserGroupsAsync_ReadsGroupsFromGraphApi_WhenClaimsOverageIsPresent(
        IGraphServiceClient service,
        [Frozen] Mock<IDirectoryObjectGetMemberGroupsCollectionPage> pageMock,
        ClaimsIdentity identity,
        List<string> expected)
    {
        // arrange
        pageMock.SetupGet(x => x.CurrentPage).Returns(expected);
        identity.AddClaim(new Claim("_claim_names", @"{""groups"": ""x""}"));

        // act
        var actual = await service.GetUserGroupsAsync(identity);

        // assert
        Assert.That(actual, Is.EquivalentTo(expected));
    }

    // expected test throws (while executing the service.Me... call above):
    Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: System.Threading.Tasks.Task`1[[Microsoft.Graph.IDirectoryObjectGetMemberGroupsCollectionPage, Microsoft.Graph, Version=1.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].
    Could not find a parameterless constructor.
       at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyInstance(Type proxyType, List`1 proxyArguments, Type classToProxy, Object[] constructorArguments)
       at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
       at Moq.Mock`1.<InitializeInstance>b__0()
       at Moq.Mock`1.OnGetObject()
       at Moq.MockDefaultValueProvider.ProvideDefault(MethodInfo member)
       at Moq.Interceptor.Intercept(ICallContext invocation)
       at Castle.DynamicProxy.AbstractInvocation.Proceed()
       at Castle.Proxies.IDirectoryObjectGetMemberGroupsRequestProxy.PostAsync()
       at MyLibrary.Extensions.GraphServiceClientExtensions.<GetUserGroupsAsync>d__1.MoveNext() in C:\Projects\MyLibrary\MyLibrary\Extensions\GraphServiceClientExtensions.cs:line 36

    // actual test required:
    [Test]
    [AutoMoqData]
    public async Task GetUserGroupsAsync_ReadsGroupsFromGraphApi_WhenClaimsOverageIsPresent(
        Mock<IGraphServiceClient> serviceMock,
        [Frozen] Mock<IUserRequestBuilder> urbMock,
        [Frozen] Mock<IDirectoryObjectGetMemberGroupsRequestBuilder> grbMock,
        [Frozen] Mock<IDirectoryObjectGetMemberGroupsRequest> grMock,
        ClaimsIdentity identity,
        List<string> expected)
    {
        // arrange
        var pageMock = new Mock<IDirectoryObjectGetMemberGroupsCollectionPage>();

        serviceMock.SetupGet(x => x.Me).Returns(urbMock.Object);
        urbMock.Setup(x => x.GetMemberGroups(true)).Returns(grbMock.Object);
        grbMock.Setup(x => x.Request(null)).Returns(grMock.Object);
        grMock.Setup(x => x.PostAsync()).Returns(Task.FromResult(pageMock.Object));
        pageMock.SetupGet(x => x.CurrentPage).Returns(expected);
        identity.AddClaim(new Claim("_claim_names", @"{""groups"": ""x""}"));

        // act
        var actual = await serviceMock.Object.GetUserGroupsAsync(identity);

        // assert
        Assert.That(actual, Is.EquivalentTo(expected));
    }

The versions of the libraries involved are:

    AutoFixture{,.AutoMoq,.NUnit3} = 3.51
    Moq = 4.1.1308
    NUnit3 = 3.8.1

**Comment by zvirja** [comment]
Thanks for reporting the issue!

In order to simply the investigation, could you please provide me with with all the type definitions as well? It would be awesome to have a code snippet that could be copied to VS and run there without a need to define anything. I'm not familiar with MS Graph API and your domain too much, so it isn't that simple for me to understand the scenario easily 😅

**Comment by mbcrawfo** [comment]
So interestingly both Moq and NUnit have been updated in the past week (to v4.7.145 and v3.9.0 respectively), and the behavior has changed.  Now there is no problem with creating the mocks, but the simpler version of the test gets a NRE when accessing the `CurrentPage` property, implying to me that maybe the frozen attribute isn't working as expected?

Here's a full repro.  The only thing you need besides the previously mentioned packages is Microsoft.Graph.

    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.Graph;
    using Moq;
    using NUnit.Framework;
    using Ploeh.AutoFixture;
    using Ploeh.AutoFixture.AutoMoq;
    using Ploeh.AutoFixture.NUnit3;
    
    namespace AutoFixtureTest
    {
        public static class GraphServiceClientExtensions
        {
            public static async Task<List<string>> GetUserGroupsAsync(this IGraphServiceClient service)
            {
                var page = await service.Me
                    .GetMemberGroups(true)
                    .Request()
                    .PostAsync()
                    .ConfigureAwait(false);
    
                return page.CurrentPage.ToList();
            }
        }
    
        public class AutoMoqDataAttribute : AutoDataAttribute
        {
            public AutoMoqDataAttribute()
                : base(CreateFixture())
            {
            }
    
            private static IFixture CreateFixture()
            {
                var fixture = new Fixture();
                fixture.Customize(new AutoMoqCustomization());
                fixture.Behaviors
                    .OfType<ThrowingRecursionBehavior>()
                    .ToList()
                    .ForEach(b => fixture.Behaviors.Remove(b));
                fixture.Behaviors.Add(new OmitOnRecursionBehavior());
    
                return fixture;
            }
        }
    
        [TestFixture]
        public class Tests
        {
            [Test, AutoMoqData]
            public async Task Throws_NullReferenceException(
                IGraphServiceClient service,
                [Frozen] Mock<IDirectoryObjectGetMemberGroupsCollectionPage> pageMock,
                List<string> expected)
            {
                // arrange
                pageMock.SetupGet(x => x.CurrentPage).Returns(expected);
    
                // act
                var actual = await service.GetUserGroupsAsync();
    
                // assert
                Assert.That(actual, Is.EquivalentTo(expected));
            }
            
            [Test, AutoMoqData]
            public async Task WorksAsExpected(
                Mock<IGraphServiceClient> serviceMock,
                [Frozen] Mock<IUserRequestBuilder> urbMock,
                [Frozen] Mock<IDirectoryObjectGetMemberGroupsRequestBuilder> grbMock,
                [Frozen] Mock<IDirectoryObjectGetMemberGroupsRequest> grMock,
                List<string> expected)
            {
                // arrange
                var pageMock = new Mock<IDirectoryObjectGetMemberGroupsCollectionPage>();
    
                serviceMock.SetupGet(x => x.Me).Returns(urbMock.Object);
                urbMock.Setup(x => x.GetMemberGroups(true)).Returns(grbMock.Object);
                grbMock.Setup(x => x.Request(null)).Returns(grMock.Object);
                grMock.Setup(x => x.PostAsync()).Returns(Task.FromResult(pageMock.Object));
                pageMock.SetupGet(x => x.CurrentPage).Returns(expected);
    
                // act
                var actual = await serviceMock.Object.GetUserGroupsAsync();
    
                // assert
                Assert.That(actual, Is.EquivalentTo(expected));
            }
        }
    }

**Comment by mbcrawfo** [comment]
I've noticed this in a couple of other places today.  Here's a generalized example that has nothing to do with the Microsoft library.  It definitely looks like the frozen attribute isn't working correctly on some of these mocks - if you debug the test the `Mock<IBar>` passed as the parameter and the one retrieved in the method are different instances.

    using Moq;
    using NUnit.Framework;
    using Ploeh.AutoFixture;
    using Ploeh.AutoFixture.AutoMoq;
    using Ploeh.AutoFixture.NUnit3;
    
    namespace AutoFixtureTest
    {
        public interface IFoo
        {
            IBar GetBar();
        }
    
        public interface IBar
        {
            string Property { get; }
        }
    
        public class Baz
        {
            private readonly IFoo _foo;
    
            public Baz(IFoo foo)
            {
                _foo = foo;
            }
    
            public string Test()
            {
                var bar = _foo.GetBar();
                return bar.Property;
            }
        }
    
        public class AutoMoqDataAttribute : AutoDataAttribute
        {
            public AutoMoqDataAttribute()
                : base(CreateFixture())
            {
            }
    
            private static IFixture CreateFixture()
            {
                var fixture = new Fixture();
                fixture.Customize(new AutoMoqCustomization());
    
                return fixture;
            }
        }
    
        [TestFixture]
        public class Tests
        {
            [Test, AutoMoqData]
            public void Property_DoesNotReturnMockedValue(
                [Frozen] Mock<IBar> barMock,
                string expected,
                Baz sut)
            {
                // arrange
                barMock.SetupGet(x => x.Property).Returns(expected);
    
                // act
                var actual = sut.Test();
    
                // assert
                Assert.That(actual, Is.EqualTo(expected));
            }
        }
    }

**Comment by zvirja** [comment]
Sorry for the belated reply - was a bit busy.

I've reviewed your samples and at the first glance it looks like the issue is that you use the wrong AutoMoq customization.

The `AutoFixture.AutoMoq` package (BTW NSubstitute integration as well) is shipped with `AutoMoqCustomization` and `AutoConfiguredMoqCustomization`. The first one which you currently use, simply creates mocks without configuring them. The latter configures all the non-generic methods and properties to return auto-generated value. Please see [here](https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#auto-configured-mocks) for more information.

After I started to use the `AutoConfiguredMoqCustomization` in your latest sample, test passed. Honestly, I haven't tested your first sample, but I have a feeling that it's basically about the same 😊

Could you please test the `AutoConfiguredMoqCustomization` and let me know whether it now works as you expect?

Thanks.

**Comment by mbcrawfo** [comment]
Thanks!  I know I have read that wiki page and blog post before, but I guess the distinction wasn't clear to me and I must not have needed to the auto configured behavior until now.

I think what caused confusion for me is that `AutoMoqCustomization` *does* configure the mock, but it doesn't use the fixture for the configuration.  Here are a few tests that demonstrate the difference between the default behavior of a mock, and the behavior of one created by `AutoMoqCustomization`:

    [Test]
    public void DefaultMoqBehavior()
    {
        var fooMock = new Mock<IFoo>();
        
        var bar = fooMock.Object.GetBar();
        
        Assert.That(bar, Is.Null);
    }
    
    [Test, AutoMoqData]
    public void AutoMoqBehavior(
        Mock<IFoo> fooMock)
    {
        var bar = fooMock.Object.GetBar();
        
        Assert.That(bar, Is.Null);  // fails
    }

I have a feeling that this is WAI, and if that's true I suggest an updating the sample result section to say something like:

> A mocked instance of a type assignable from IInterface.  Properties and methods that return mockable types have mocked instances configured automatically.  However, these mocks are not generated using using the `IFixture` instance (see below for that behavior).

**Comment by zvirja** [comment]
>  I know I have read that wiki page and blog post before, but I guess the distinction wasn't clear to me and I must not have needed to the auto configured behavior until now.

No worries, I'm glad that my advise helped 😉

>  I suggest an updating the sample result section to say something like:

That behavior depends purely on the Moq implementation detail, which could change from version to version (in theory). Given that it's out of our control, probably it's better to rephrase that in a more general way.

In any case, you have a write access to our wiki, so feel free to put that disclaimer somewhere 😃
