### ISSUE TITLE
Support for IReadOnlyList and similar in v4

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#924]
For some reason I thought that IReadOnlyList<T> was going to be supported out-of-the-box in v4.

I understand that the relay shown in #730 couldn't be added because of the support for .NET Framework 4.5. But since we are moving into a .NET Standard, maybe we could consider to include it somehow?

I see two options:
* in the main assembly, via compiler if (after all, the .NET Framework version has the email generator)
* by creating a .NET Standard-only package with all these commodities

**Comment by zvirja** [comment]
Actually, the `IReadOnlyList<>` [is supported](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlylist-1?view=netframework-4.5) by .NET 4.5 which we currently target in v4. Also this interface is available in .NET Standard version we target. Therefore, I believe that _technically_ nothing stops us from adding that support to the AutoFixture 😉

Given that we already support `IReadOnlyCollection<>`, I don't see an issue with `IReadOnlyList<>` support - it's a part of BCL and is probably used not so rarely.

**Comment by Kralizek** [comment]
Do you mind me trying to work on a PR?

**Comment by zvirja** [comment]
I'd suggest you to postpone this a bit. I don't a like a current way how we introduce such and similar features and would like to enhance that a bit.

After that we could proceed with a new way.

**Comment by Kralizek** [comment]
Sure!

**Comment by zvirja** [comment]
Done. Fire a PR if you wish now 😉

**Comment by Kralizek** [comment]
@zvirja I will work on it during the weekend!
