### ISSUE TITLE
Use Fare package for regular expression generation

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#938]
@moodmosaic I've noticed that you have extracted Xeger to a separate NuGet package: https://github.com/moodmosaic/Fare.

In AutoFixture we have a copy of that project. Does it make sense to actually depend on your package rather than have a copy-paste inside our code?

However, in order to achieve that we need you to add .NET Standard support and probably sign the assembly, as it we are signed. I saw that you are [reluctant](https://github.com/moodmosaic/Fare/issues/25) to sign it, however we could probably trigger Fare 2.0, so that change is not so breaking.. Also we could cheat a bit and sign everything targeting .NET Framework v4.5+ 😊

**Comment by moodmosaic** [comment]
>Does it make sense to actually depend on your package rather than have a copy-paste inside our code?

[Fare](https://github.com/moodmosaic/Fare) should be the same to what we have inside AutoFixture, plus some minor changes here and there based on feedback I got from its users.

If you wish, you can take a dependency on it, and delete the appropriate files from AutoFixture. Once you do that, **AutoFixture will depend on Fare**, instead of having no other dependencies.

I don't think we should worry about anything, as I no longer work actively in Fare, but if that makes you feel safer, I can add you as a collaborator.

If you lean towards taking Fare as a dependency, you'd have to do what it takes (support .NET Standard, etc.) as I'm currently busy with other stuff and don't have the bandwidth to make changes there.

**Comment by zvirja** [comment]
> AutoFixture will depend on Fare, instead of having no other dependencies.

Well, that is not the case - we already have dependencies for the .NET Standard framework. [See v4](https://www.nuget.org/packages/AutoFixture/4.0.0-rc1).

Today AutoFixture is distributed as a NuGet package, so it doesn't provide us with any benefits to not have external dependencies. That's why I don't think we should worry about that and it's not a goal to not depend on anything.

> If you lean towards taking Fare as a dependency, you'd have to do what it takes

Got it 😉 I'm not sure I also have much free time for this now, but will see whether I have it in future.

---

Ideally I prefer to depend on other packages rather than keep code inside out project. In this particular case I understand that _real_ benefits are not so great, except the more clear code organization. So if you don't mind, let's keep this as a potential improvement, but do not prioritize it.

**Comment by moodmosaic** [comment]
>Today AutoFixture is distributed as a NuGet package, so it doesn't provide us with any benefits to not have external dependencies.

Yes, the .NET Standard version depends on `NETStandard.Library` and `System.ComponentModel.Annotations`. That's fine, as these packages are part of the .NET itself, and they were inside the BCL previously.

However, I'd strongly suggest to *avoid* taking on dependencies on other packages, (say, `Foo`) as we don't have control on what their authors are doing.

Now, `Fare` can be an exception, as it was created *for* AutoFixture, and it's maintained by people who are also involved with AutoFixture.

**Comment by zvirja** [comment]
Got your point. Well, totally makes sense. I believe that's always the rule that you should depend on third-party products only if that provides large benefit. Otherwise, dept of support might make that non-profitable. I felt that already for our glue libraries, where we should follow up each their release to ensure we support it.

**Comment by moodmosaic** [comment]
I don't really mind what we do outside the core AutoFixture package (e.g. in the Glue Libraries). But for the core package, I'd really like to depend on as less stuff as possible, preferably 0 packages other than those maintained by us (and Microsoft, for .NET Standard).

**Comment by zvirja** [comment]
Closed via #972
