### ISSUE TITLE
How do I customize creation of a collection (and its nested properties)?

### ISSUE THREAD

**Issue by tlycken** [AutoFixture/AutoFixture#942]
I have a need for customizing creation of a collection, with quite complicated relationships between the objects within it, and I can't figure out how to do it correctly.

For the sake of this issue, let's assume I'm working on a todo app. It has `Items` and `SubItems`, and the items have a week number indicating when they should be done:

    public class Item {
        public string Name { get; set; }
        public int Week { get; set; }
        public ICollection<SubItem> SubItems { get; set; }
    }

    public class SubItem {
        public string Name { get; set; }
        public Item Parent { get; set; }
    }

Now, because this is what data usually looks like in the actual application, I want to create a collection of `Item`s that has the following properties:

    * There are items that have the same name, but different weeks
    * There are items that have the same week but different name
    * There are sub-items that have the same name, but different parents

In order to do this, I've created a `TodoItemSpecimenBuilder : ISpecimenBuilder` which starts its `Create` method like this:

```csharp
var type = (request as PropertyInfo)?.PropertyType ?? request as Type;
if (type == null || !typeof(IEnumerable<Item>).IsAssignableFrom(type))
{
    return new NoSpecimen();
}

// build up the actual collection
return BuildActualCollection();
```

However, when I run tests with this specimen builder included in my context, I get lots (maybe 20 or 30) hits on the `return` statement before I enter even my setup code, and the first time I try to actually `CreateMany<Item>()`, it blows up with a cast exception because it can't cast `OmitSpecimen` to `Item`.

What am I doing wrong here?

**Comment by tlycken** [comment]
Realized StackOverflow might be a better forum for this, so cross-posted there: https://stackoverflow.com/questions/47512841/specimenbuilder-for-a-collection

**Comment by tlycken** [comment]
For reference, there is now an MCVE here: https://github.com/tlycken/MCVE_AutoFixtureCollectionSpecimenBuilder

**Comment by zvirja** [comment]
Closing this one as @ploeh has already helped you on SO. Thanks Mark 😉
