### ISSUE TITLE
Graph composition inside Fixture.cs

### ISSUE THREAD

**Issue by moodmosaic** [AutoFixture/AutoFixture#944]
Perhaps that would allow us to get rid of this pesky comment:

https://github.com/AutoFixture/AutoFixture/blob/d576fdc25ed88a35f874f9ef128b678c72752991/Src/AutoFixture/Fixture.cs#L128

**Comment by zvirja** [comment]
@moodmosaic Is your concern related to the data annotations, or to the whole approach we have for the pre-registered builders? Originally I thought that it's about annotations, but just spotted the header and became non-sure.. 😟

**Comment by moodmosaic** [comment]
It should be possible, or at least _ought_ to be possible to somehow 'pack' builders together into reusable blocks. So this way we should have a 'pack' of builders related to data annotations.

I don't know, or I don't remember, if this is possible in AutoFixture.
