### ISSUE TITLE
Rename xUnit related projects (and directory) to match NuGet package name

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#946]
Currently xUnit related projects are named as following:

- AutoFixture.xUnit.net
- AutoFixture.xUnit.net.UnitTest
- AutoFixture.xUnit.net2
- AutoFixture.xUnit.net2.UnitTest

This `.net` suffix in project name is very confusing, given that actual NuGet package name are:

- AutoFixture.xUnit
- AutoFixture.xUnit2

To make it less confusing, I wish to rename projects (and project folder) to match the NuGet ID and default namespaces:

- AutoFixture.xUnit
- AutoFixture.xUnit.UnitTest
- AutoFixture.xUnit2
- AutoFixture.xUnit2.UnitTest

That will not affect the git history, as git will gracefully handle that file move.

@moodmosaic Do you have any objections regarding that change?

**Comment by moodmosaic** [comment]
But the name is actually *xUnit.net* so it's like the NuGet Package names are the candidates for renaming.

*xUnit* is a broad term, used in [the bible](http://xunitpatterns.com/).

**Comment by zvirja** [comment]
Well, yes, the official name of the product is indeed "xUnit.net". However, the shorter "xUnit" name is also used very broadly:
- NuGet: [xunit](https://www.nuget.org/packages/xunit)
- Twitter: [xunit](https://twitter.com/xunit)
- GitHub: [xunit](https://github.com/xunit/xunit)

The top 3 results for xUnit in Google are for xUnit.net:
![image](https://user-images.githubusercontent.com/1074182/33727150-e69d2742-db7f-11e7-9b4c-fb36ef22ff07.png)

While the original xUnit term was used to [refer](https://en.wikipedia.org/wiki/XUnit) to a family of testing frameworks, currently in .NET world the "xUnit" name is a very famous alias for the "xUnit.net" and I believe is recognized by everybody. Probably, we should blame xUnit team for picking up the confusing name, however that's what we have.

I believe that it will be clear that "AutoFixture.xUnit" project is about integration with "xUnit.net" test framework, rather than about something general about xUnit test frameworks family.

I do also understand that we have different background. Definitely, Mark and you (and other maintainers which are not currently active) read a lot of canonical materials related to the unit testing and for you such "xUnit" term usage might look like a sin. However, from the practical perspective I find the "AutoFixture.xUnit.net2" name very clumsy and believe that the ".net" suffix doesn't carry any value.

My wish is to have a consistency. Currently NuGet package is named "AutoFixture.xUnit" and it's weird to have project named differently. I want to align those names as other project names match their package ID. If later we decide to rename package to "AutoFixture.xUnit.net" (which likely will not happen as that brings no value), we could easily rename the project back.

**Comment by moodmosaic** [comment]
I don't know... I wouldn't really bother changing those... However―if you really feel so―go ahead, rename them 😃 After all, we'll be more consistent this way (after the renaming).
