### ISSUE TITLE
Randomly choose from pre-defined list

### ISSUE THREAD

**Issue by amir734jj** [AutoFixture/AutoFixture#951]
I am wondering in C# AutoFixure, is there a way to randomly choose from the pre-defined list? for example, so when I use `fixture.Create` or `fixture.CreateMany`, it randomly selects an object from the pre-defined list. I did not find anything similar from documentation and searching stackoverflow so I am not sure it is even possible.

[Documentation link][1]

  [1]: https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet

**Comment by zvirja** [comment]
Closed via https://stackoverflow.com/questions/47761145/autofixure-randomly-choose-from-predefined-list
