### ISSUE TITLE
Modifying Fixture.Behaviors

### ISSUE THREAD

**Issue by peheje** [AutoFixture/AutoFixture#978]
Trying to fill an object with circular dependencies gives this nice error:

`AutoFixture.ObjectCreationExceptionWithPath: 'AutoFixture was unable to create an instance of type AutoFixture.Kernel.SeededRequest because the traversed object graph contains a circular reference. Information about the circular path follows below. This is the correct behavior when a Fixture is equipped with a ThrowingRecursionBehavior, which is the default. This ensures that you are being made aware of circular references in your code. Your first reaction should be to redesign your API in order to get rid of all circular references. However, if this is not possible (most likely because parts or all of the API is delivered by a third party), you can replace this default behavior with a different behavior: on the Fixture instance, remove the ThrowingRecursionBehavior from Fixture.Behaviors, and instead add an instance of OmitOnRecursionBehavior:`

```
fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList()
    .ForEach(b => fixture.Behaviors.Remove(b));
fixture.Behaviors.Add(new OmitOnRecursionBehavior());
```

However Fixture.Behaviors is an **IList** and therefore fixture.Behaviors.IsReadOnly could be true and should be checked. Shouldn't it just be a **List** instead?

More info here:
https://msdn.microsoft.com/en-us/library/0cfatk9t(v=vs.110).aspx
https://stackoverflow.com/questions/400135/listt-or-ilistt

**Comment by zvirja** [comment]
@peheje Thanks for the report. Did I get it clear and your concern is purely about the exception message and not the real case you have?

If so, probably, we have the message like that because we know that it should not be read-only. We have a set of other fixture properties of `IList<>` type (like `Customizations`, `ResidueCollectors`) and if we start to assume in our samples that it could be read-only, it will pollute our samples a lot without bringing any real value - currently they could never be read-only.

Does that answer your question, or I missed something? If so, please describe what exactly I missed 😉

**Comment by zvirja** [comment]
> Shouldn't it just be a List instead?

Just noticed that part. Well, in fact we are not using the `List` under the hood. We implement the `IList` interface manually, as types are not the real collections - [they are adapters](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/SpecimenBuilderNodeAdapterCollection.cs). Therefore, it's unlikely that we can change the type of properties even if we decided that it's better :pensive:

**Comment by peheje** [comment]
Thank you for the detailed response. Yes indeed my question was about the modifiable IList. I still think it's better to encourage checking for read only before trying to modify but granted I am probably nitpicking here. 

But very cool took I like it a lot.

**Comment by zvirja** [comment]
> I still think it's better to encourage checking for read only before trying to modify 

Well in this particular case it will be redundant as we have no plans to make it readonly. In any case, you shouldn't worry too much about it - if collection becomes read-only, your tests will fail with exception and you'll quickly find out what is going wrong 😉
