### ISSUE TITLE
Autofixture.Xunit issue with .net framework 4.6.2

### ISSUE THREAD

**Issue by github-arjunan** [AutoFixture/AutoFixture#989]
Hi, I have been using sitecore fakedb for unit tests. I have installed latest release of Sitecore.FakeDb.AutoFixture and Install-Package xunit. when i try to install AutoFixture.Xunit2 I'm getting below issues.

Attempting to gather dependency information for package 'AutoFixture.Xunit2.4.1.0' with respect to project 'Tests', targeting '.NETFramework,Version=v4.6.2'
Gathering dependency information took 1.45 sec
Attempting to resolve dependencies for package 'AutoFixture.Xunit2.4.1.0' with DependencyBehavior 'Lowest'
Install-Package : Unable to resolve dependencies.
At line:1 char:1
+ Install-Package AutoFixture.Xunit2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by zvirja** [comment]
As far as I can see the [`Sitecore.FakeDb.AutoFixture`](https://www.nuget.org/packages/Sitecore.FakeDb.AutoFixture/) is not compatible with `AutoFixture 4`:
```
Dependencies:
AutoFixture (>= 3.0.0 && < 4.0.0)
Sitecore.FakeDb (>= 1.7.2)
```

Therefore, either use AutoFixture 3.x, or ask @sergeyshushlyapin to update the library 😉

**Comment by zvirja** [comment]
Closing this as no actions are required from out side.
