### ISSUE TITLE
Specify desired amount of items when configuring a customization

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#990]
Hi,

I'm trying to test a piece of code that is sensible to the amount of items in a given set. Unluckily, I really can't avoid passing proper data to activate a specific path.

I would normally use `CreateMany<T>(int)` to specify the amount of items I need, but the set is in a property of a container object (btw, I am addicted to the new relay for `IReadOnlyList<T>`) like

```csharp
public class ContactIdList
{
    [JsonProperty("vids")]
    public IReadOnlyList<long> ContactIds { get; set; }

    [JsonProperty("vidOffset")]
    public long? Offset { get; set; }

    [JsonProperty("hasMore")]
    public bool HasMore { get; set; }
}
```` 

What I would suggest is to offer a way to specify the amount of items needed to be generated when customizing a type.

Ideally, something like this

```csharp
var list = fixture.Build<ContactIdList>()
                  .With(p => p.HasMore, false)
                  .Without(p => p.Offset)
                  .WithMany(p => p.ContactIds, 16)
                  .Create();
```

The parameters should be something like `(Expression<Func<T, IEnumerable<TProperty>> propertyPicker, int count)` but I'm honestly torn between naming it `WithMany<TProperty>` and adding another overload of `With<TProperty>`.

Obviously, I'm aware that I can create the list before and use `With<TProperty>(Expression<Func<T, TProperty> propertyPicker, TProperty value)` to pass the list.

**Comment by zvirja** [comment]
Thanks for raising the scenario.

I do understand the scenario you have, however I don't like too much the suggested way to fix it. The scenario looks very specific to extend API for it.

Instead, it's much better to implement it as a part of the #708. If we add the `With()` method overload taking the factory method, so it can be solved like this:
```c#
fixture.Customize<ClassToCustomize>(c =>
    c.With(x => x.Values, () => fixture.CreateMany<int>(25).ToList())
);
```

This solution is way more generic as behavior is not limited to collections only.

@moodmosaic I'd be really happy to implement #708 as it's a real enabler for more specific scenario. Therefore, if you accept such a PR, I could implement it 😉

**Comment by Kralizek** [comment]
@zvirja would it be ok to pass the fixture instance as argument to the factory method? That would allow us to write generator functions that don't depend on the captured context.

**Comment by zvirja** [comment]
@Kralizek Yep, probably, that's definitely a good idea! But I need to investigate what exact type of parameter should be present (i.e. `ISpecimenBuilder` or `ISpecimenContext` or any arbitrary type).

Let's see @moodmosaic opinion first before we proceed further.

**Comment by moodmosaic** [comment]
@zvirja, I was skeptical in #708 because it was the only scenario we were aware of. Now there's another one too, so, perhaps now it's time to *consider* adding it [this](https://github.com/AutoFixture/AutoFixture/issues/708#issuecomment-321508595) extension method to the AutoFixture itself. 😉 👍

**Comment by zvirja** [comment]
Unfortunately, it will be impossible to implement that via an extension method - as you can see, it doesn't work with `Configure<>()` method. Therefore, the only way is to extend the [`IPostprocessComposer`](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Dsl/IPostprocessComposer.cs) interface. That basically makes almost no difference in the code - implementation is pretty straightforward, that's why I am ready to do this.

**Comment by moodmosaic** [comment]
Sounds reasonable, as long as the newly added method does not mutate any input arguments, so that it doesn't violates [command-query separation](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation). (See also [this](https://stackoverflow.com/a/48673138/467754).)

**Comment by zvirja** [comment]
Agreed 😉 
Converting this to a potential feature.

**Comment by Kralizek** [comment]
I know that what I'm saying is advocating a 5.0 but maybe the fixed value should be a special case of the delegate.

So the delegate gets added in the interface and the fixed value becomes an extension.

Slightly related: do you mark a method as obsolete if you remove it from the interface and move it to an extension method? You are changing the interface at type level but compiling code will continue compiling...

**Comment by zvirja** [comment]
@Kralizek That's a great idea from the API unification point of view. It probably makes sense to do that in the upcoming major releases.

So far I'd be happy to proceed with yet another overload of the `With()` method (so we have 3 overloads), so we don't introduce the breaking changes.

**Comment by Kralizek** [comment]
Maybe add the `Obsolete` attribute to the existing overloads? Or it's too early?

**Comment by zvirja** [comment]
> Maybe add the Obsolete attribute to the existing overloads? Or it's too early?

I'd say that for now it doesn't make a lot of sense to do that - we cannot provide an alternative in a usable way.

I'm closing this issue in favor of re-opened #708 which describes the intention better.

**Comment by m0a0k0s** [comment]
This approach doesn't work with read-only properties and ReadonlyCollectionPropertiesBehavior
