### ISSUE TITLE
Support for ILookup<,>

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#991]
We recently added built-in support for `IReadOnlyList<>` (#941), `IReadOnlyDictionary<,>` (#980) and `ISet<>` (#983).

The one left out is `ILookup<,>`.

Unluckily this is a tricky one because there is only one implementation ([Lookup<TKey, TValue>](https://msdn.microsoft.com/en-us/library/bb460184%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) and this one has no public constructor.

I have a working customization for a closed generic form but I wonder if it can be reimplemented so that it works for open generics and then can be added to the default registration.

`fixture.Customize<ILookup<string, int>>(c => c.FromFactory((IDictionary<string, IEnumerable<int>> input) => input.SelectMany(i => i.Value, (item, value) => new { key = item.Key, value }).ToLookup(k => k.key, v => v.value)));`

**Comment by Kralizek** [comment]
maybe @zvirja knows an awesomely clean way of doing it?

**Comment by zvirja** [comment]
And than's again for raising the issue 🙇 

Honestly, I'm a bit reluctant of adding this type to the core library. While `ILookup` interface is a part of BCL and standard libraries, for me it looks a bit non-trivial collection. Therefore, it might be totally fine that it's not generated out of the box. After all, AutoFixture isn't supposed to support each type in BCL we have.. 😕

As for the customization implementation, it's might be like following:
```c#
public class LookupBuilder: ISpecimenBuilder
{
    public object Create(object request, ISpecimenContext context)
    {
        if (request is Type typeRequest 
            && typeRequest.IsGenericType
            && typeRequest.GetGenericTypeDefinition() == typeof(ILookup<,>))
        {
            var args = typeRequest.GetGenericArguments();
            return this.GetType()
                .GetMethod(nameof(GenerateTypedLookup), BindingFlags.Static | BindingFlags.NonPublic)
                .MakeGenericMethod(args)
                .Invoke(null, new object[] { context });
        }

        return new NoSpecimen();
    }

    private static ILookup<TKey, TValue> GenerateTypedLookup<TKey, TValue>(ISpecimenContext context)
    {
        return context.CreateMany<KeyValuePair<TKey, IEnumerable<TValue>>>()
            // Make sequence flat to later generate lookup from it.
            .SelectMany(kv => kv.Value.Select(v => new KeyValuePair<TKey, TValue>(kv.Key, v)))
            .ToLookup(kv => kv.Key, kv => kv.Value);
    }
}
```

And usage:
```c#
var fixture = new Fixture();
fixture.Customizations.Add(new LookupBuilder());

fixture.Create<ILookup<int, string>>();
```

I'd suggest to hold on this feature and see whether there are more requests for it. If they are, we could make another decision.

@moodmosaic You are invited to share your opinion as well 😉 Probably, that's me who used this interface rarely and it appears to be a common one.

**Comment by moodmosaic** [comment]
I think I would just go with an ad-hoc customization for it... After all, you *do* need custom, ad-hoc, stuff when working with AutoFixture.

*Not* that I wouldn't like this to be inside AutoFixture, it's just that there's a fair amount of work to be done in order to include it (tests, façade tests, maintenance).

I've used AutoFixture for years in some fairly sized codebases and I've never seen `ILookup<K, V>` so perhaps it's not so *common* interface?

**Comment by zvirja** [comment]
@moodmosaic Thanks for your thoughts, they confirmed my initial intention 😃 

@Kralizek Given that there is a relatively simple way to enable this feature in your solution, would you be fine if we close this issue for now? If later there are more requests for it, we could re-open it again.

**Comment by Kralizek** [comment]
@zvirja so far you don't cancel the LookupBuilder above until I have time to copy it, no problem. We are just seeing somewhere else that a feature might not appear needed at the current time but might be needed later on.

**Comment by zvirja** [comment]
Well, it's impossible to remove issues from GitHub. Even after I close it, you can still find it using the Search and use the code sample above.

Therefore, you will have ages to copy the sample above 😄
