### ISSUE TITLE
Missing architecture diagram

### ISSUE THREAD

**Issue by blairconrad** [AutoFixture/AutoFixture#992]
In [Fixture high-level layout](https://github.com/AutoFixture/AutoFixture/wiki/Internal-Architecture#fixture-high-level-layout) in the "Internal Architecture" wiki page, there's a broken link to the diagram that is the key to understanding the architecture.

I downloaded the old codeplex site archive and believe that the image is 

![a63b3e77-c140-4029-8835-8017cbf4ae09](https://user-images.githubusercontent.com/3275797/36981873-4cdf1256-205c-11e8-8877-1b0775d022f6.png).

I'll add it to the page now, but it may be desirable to move the image to a permanent, better-named location, such as an "Assets" directory in the repo. If there's interest, I can submit a PR.

**Comment by zvirja** [comment]
@blairconrad Good catch! 👍 Many thanks for reviewing the CodePlex archive and finding that picture!

I think for now it's good how you did that. I've already started to work on the doc site for the AutoFixture (however I'm approaching a bit slower than I'd like to 😖), so I'll put the picture there. It will be committed to the repo, so will be preserved.

Really cool that you spent your time looking for the picture - really appreciate! 🙇

**Comment by zvirja** [comment]
Closing this for now as decided that no actions are required.
Later I'll take the picture from the closed issue.

Thanks again!

**Comment by blairconrad** [comment]
A pleasure. Happy documenting!
