### ISSUE TITLE
System.Net.Mail support in netstandard2.0 and netcoreapp2.0

### ISSUE THREAD

**Issue by skermajo** [AutoFixture/AutoFixture#993]
Hi

It looks like System.Net.Mail is back in `netstandard2.0` and `netcoreapp2.0`. It would be great if the `MailAddress` generator could be included when targeting either platform. At the moment it looks like the `SYSTEM_NET_MAIL` conditional is [excluding it on both platforms](https://github.com/AutoFixture/AutoFixture/blob/dc7bd5ff68a146fb6027e09d6be82050e84ca620/Src/Common.props#L26) as it wasn't available prior to 2.0.

`System.Net.Mail` inclusion in 2.0 is documented here: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md

**Comment by zvirja** [comment]
@skermajo Thanks for letting us know! I've just checked that and indeed, it seems that `Mail` is already there in netstandard 2.0.

Converting this to a potential feature.
