### ISSUE TITLE
.NET Standard support in AutoFoq

### ISSUE THREAD

**Issue by baltie** [AutoFixture/AutoFixture#994]
AutoFixture now has support for .NET Standard, but AutoFoq requires .NET Framework. AutoFoq should also have support .NET Standard.

**Comment by zvirja** [comment]
As far as I can see, [`Foq`](https://www.nuget.org/packages/foq) still doesn't support .NET Standard. Therefore, we cannot provide support as well.

Let me know if I'm mistaken and overlooked something.

**Comment by baltie** [comment]
No, it was me overlooking something. You're quite right. I'll postpone my question till Foq (hopefully) supports .NET Standard. :)

**Comment by tommyja** [comment]
Foq supports netstandard now

**Comment by baltie** [comment]
@tommyja You should probably create a new issue. I'm not using autofoq in my current project.
