### ISSUE TITLE
GuardClauseAssertion fails to verify guard for constructor with parameters

### ISSUE THREAD

**Issue by ymorozov** [AutoFixture/AutoFixture#995]
I've just migrated one of my projects from Autofixture 3.50.1 to 4.1.0 and looks like GuardClauseAssertion is not working anymore. Here is the example of the test that was passing in previous version but fails in current:
        
```c#
[Theory, AutoData]
public void ProtectsInputParametersFromNulls(GuardClauseAssertion assertion)
{
    assertion.Verify(typeof(TestClassWithGuards));
}

public class TestClassWithGuards
{
    public TestClassWithGuards(string parameter1)
    {
        if (parameter1 == null)
        {
            throw new ArgumentNullException();
        }
    }
}
```

It fails with following exception:

> AutoFixture.Idioms.GuardClauseException: An attempt was made to assign the value null to the parameter "parameter1" of the method ".ctor", and no Guard Clause prevented this. Are you missing a Guard Clause?

**Comment by zvirja** [comment]
Yep, that's the change we added in v4 (see #258). Now we also verify that `ParameterName` in the thrown exception matches the verified parameter name - so we can be sure that the proper guard clause is present. In the example you shown above, you don't pass the parameter name to the thrown exception, which is violating the exception throwing usage. You should fix the clause as following:
```c#
    public TestClassWithGuards(string parameter1)
    {
        if (parameter1 == null)
        {
            throw new ArgumentNullException(nameof(parameter1);
        }
    }
```

I agree that message is a bit confusing and might be improved, however the behavior is valid.

**Comment by zvirja** [comment]
Closing this one as no actions seems to be required. Please re-open the issue if needed.
