### ISSUE TITLE
Drop support for older FakeItEasy versions

### ISSUE THREAD

**Issue by blairconrad** [AutoFixture/AutoFixture#996]
Suggested by @zvirja in https://github.com/AutoFixture/AutoFixture/pull/986#discussion_r173122352.
Assumes that #986 is merged.

Supporting very old versions of FakeItEasy increases development and maintenance costs, and complicates the code quite a bit. If we dropped support for older FIE's, we could simplify the codebase as follows:

* Change minimum supported to 1.7.4257.42
    * Can remove the `CAN_FAKE_DELEGATES` compiler constant - all versions of FakeItEasy after this can fake delegates
    * Can remove `AutoFakeItEasyCustomization.AssertFakeItEasyCanFakeDelegates`
* Change minimum supported to 2.0.0
    * Can remove `AutoFakeItEasyUnitTest`
    * `FakeItEasyMethodQuery.FakeMethod<T>.Invoke` can be  drastically simplified, becoming `return new Fake<T>(b => b.WithArgumentsForConstructor(parameters));`, as it used to be
    * Can remove `FakeObjectCall.cs` bridge class, as it exists only to paper over differences between pre-2.0.0 and 2.0.0+ call representations. Usages can be replaced with `FakeItEasy.Core.IFakeObjectCall`, or `FakeItEasy.Core.IInterceptedFakeObjectCall` if necessary.
* Change minimum supported to 3.0.0
    * Can remove `AutoFakeItEasy.FakeItEasy2UnitTest` (or `AutoFakeItEasy.FakeItEasy3UnitTest` if restricting to FIE 4.0.0+, etc.)

Benefits are cumulative, of course.

**Comment by zvirja** [comment]
@blairconrad Thanks for the detailed explanation. I've added that to v5 scope. I have no clue when we are going to start that work, however hope one day we'll apply those changes 😅

**Comment by blairconrad** [comment]
Given #1155, it may be a good time to at least reconsider this issue. Dropping some older FakeItEasys may afford an opportunity to simplify the AutoFakeItEasy. If there's interest, I would be happy to take this on, given guidance about the lowest FakeItEasy you'd like to support.

**Comment by mattiasnordqvist** [comment]
How about adding support for fakeiteasy 8?

**Comment by blairconrad** [comment]
@mattiasnordqvist, I'm not a maintainer, but I think that would be best raised as a separate issue.

**Comment by aivascu** [comment]
closed in #1438
